### ISSUE TITLE
1.0.0  is missing from releases

### ISSUE THREAD

**Issue by AndKe** [node-red/node-red-nodes#1001]
I see 1.0.0 in node-red, thank you for that , but on github there is no release of 1.0.0 - nor any changelog that would be in the releases.

**Comment by knolleary** [comment]
This repository contains many nodes that are all published individually to npm

What node are you reporting this against?

**Comment by AndKe** [comment]
I just went back to add this information, it's about node-red-node-timeswitch

**Comment by UTSAV18** [comment]
I can work on this issue please assign

**Comment by dceejay** [comment]
What is the actual issue here ? so far not seen any detailed description of any error or how to recreate.
