### ISSUE TITLE
Failure handling polar day or polar night

### ISSUE THREAD

**Issue by AndKe** [node-red/node-red-nodes#1002]
### Which node are you reporting an issue on?
node-red-node-timeswitch

### What are the steps to
try this config with today's date:

![Screenshot from 2023-05-26 23-43-54](https://github.com/node-red/node-red-nodes/assets/1468842/a16bebf1-15f6-4e6c-a3e2-dff0294335ab)

### What happens?
there is no output from the node, no "0" or "1"

### What do you expect to happen?
I would expect an output, static "sun is up" until the fall when the polar day is over.

as-is a flow cannot determine if the lights have to be on, or off (in the case being polar night or day.) - there is no output from the node, so it "does nothing"

This bug is most likely caused by the function not finding sunrise & sunset time for this part of the year. (the sun is never above/below the threshold.)

### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2 
- [ ] node.js version:  (3.0.2 docker image/idk where to find this info)
- [ ] npm version: (3.0.2 docker image/idk where to find this info)
- [ ] Platform/OS: RaspberryPi (Linux)
- [ ] Browser: Vivaldi

**Comment by dceejay** [comment]
fixed in version 1.1

**Comment by AndKe** [comment]
@dceejay thank you that was fast!
When configured to be "on" from sunrise to sunset - I would expect to see "0" (off) during the polar day, and "1" during polar night.
Today - version1.1 , configured for on from "sunrise to sunset" returns "1"
is this by design ? should I expect it to be "0" during the winter?

**Comment by dceejay** [comment]
Ah good point - needs a bit more thought. the fix isn't honouring what the on/off says correctly.

**Comment by dceejay** [comment]
the node should now report 1 for on and 0 for off - so if set for on at sunset and on at sunrise then it should be off all "summer" at high latitudes.

**Comment by AndKe** [comment]
@dceejay nice ! , Thank you. I assume it's also on for whole polar night days.
I also like the way you wrote quoted "summer" at high latitudes, this tells me you have some insight into the crappy weather here - this is  the current forecast:
![image](https://github.com/node-red/node-red-nodes/assets/1468842/1add618d-5c0b-41b4-b8de-b4f03de456e2)

**Comment by AndKe** [comment]
@dceejay - I updated to 1.1.1   - and it's still "on until sunrise" which it claims is at 01:59

Also, I've made another instance that is further north, and oddly, the sunrise estimate is exactly the same time.
Is there a way of producing the result for a given date/time (for testing purposes)? (other than the actual date/time?)

```
[
    {
        "id": "51eb8f57f98e80a1",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 4",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 1140,
        "y": 640,
        "wires": []
    },
    {
        "id": "737cd11787c6e68f",
        "type": "timeswitch",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "mytopic": "",
        "lat": "80",
        "lon": "18",
        "starttime": "5000",
        "endtime": "6000",
        "timezone": "Europe/Oslo",
        "duskoff": "0",
        "dawnoff": "0",
        "sun": true,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "jan": true,
        "feb": true,
        "mar": true,
        "apr": true,
        "may": true,
        "jun": true,
        "jul": true,
        "aug": true,
        "sep": true,
        "oct": true,
        "nov": true,
        "dec": true,
        "x": 960,
        "y": 640,
        "wires": [
            [
                "51eb8f57f98e80a1"
            ]
        ]
    },
    {
        "id": "45083525311b0db2",
        "type": "timeswitch",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "mytopic": "",
        "lat": "69.6",
        "lon": "18.9",
        "starttime": "5000",
        "endtime": "6000",
        "timezone": "Europe/Oslo",
        "duskoff": "0",
        "dawnoff": "0",
        "sun": true,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "jan": true,
        "feb": true,
        "mar": true,
        "apr": true,
        "may": true,
        "jun": true,
        "jul": true,
        "aug": true,
        "sep": true,
        "oct": true,
        "nov": true,
        "dec": true,
        "x": 960,
        "y": 740,
        "wires": [
            [
                "b48f64250e389bfe"
            ]
        ]
    },
    {
        "id": "b48f64250e389bfe",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 5",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 1140,
        "y": 740,
        "wires": []
    }
]
```

**Comment by dceejay** [comment]
You have configured it to be on at sunrise until sunset - 
<img width="457" alt="image" src="https://github.com/node-red/node-red-nodes/assets/5375409/95add0bb-bd53-4bdc-be92-5aadfac2cf63">
so it will produce 1 (on) all day... the until time is a slight distraction - as that is midnight GMT when the next day starts (in GMT)... so it will be on all "day" - at that point (which should be 23:59:59 under the covers) then it will go "off" but back on again at the next sunrise (0:0:0) (ie one sec later). As the timer only checks once per minute it should never go off.

**Comment by AndKe** [comment]
ouch, this is embarrassing, I swapped sunrise/sunset.
Thank you.
