### ISSUE TITLE
Arduino node not listing all serial ports

### ISSUE THREAD

**Issue by fsamir** [node-red/node-red-nodes#101]
The ArduinoFirmata.list() method  is filtering ports based on the following regex:
```

/usb|acm|com\d+/i
`````
On my mac, when I pair a Arduino Firmata via Bluetooth the port is called /dev/tty.<device name> which gets filtered out.

**Comment by dceejay** [comment]
This is in the Arduino Frimata npm  https://www.npmjs.com/package/arduino-firmata
Please raise the issue against that project. Thanks
