### ISSUE TITLE
blink1: pink is not a valid colour

### ISSUE THREAD

**Issue by netcompsys** [node-red/node-red-nodes#102]
I believe the colour should be amber, see code

kevin

**Comment by knolleary** [comment]
Hi, can you give a bit more context? Is this related to a node-red node?

**Comment by netcompsys** [comment]
Sorry, I had thought I had posted an issue against the node-red-node-blink1

kevin

**Comment by knolleary** [comment]
Ah right, yes this the right place. This issue tracker covers all of the nodes in the node-red-nodes repository, of which the blink1 node is one of many.

Just saw you're mailing list post as well.

Can you elaborate on 'see code' - what code should we be looking at?

**Comment by netcompsys** [comment]
I was just having a nose here
https://github.com/node-red/node-red-nodes/blob/master/hardware/blink1/77-blink1.js


var colors = {"red":"#FF0000","green":"#00FF00","blue":"#0000FF","cyan":"#00FFFF","white":"#FFFFFF","warmwhite":"#FDF5E6",
                             "purple":"#800080","magenta":"#FF00FF","yellow":"#FFFF00","amber":"#FFD200","orange":"#FFA500","black":"#000000"}

No idea which are the valid cheerlights colours but the code is unlikely to respond to poink I think

kevin

**Comment by netcompsys** [comment]
From my experience I suggest that there are more steps required to get this working on a Raspberry pi  than just the simple install instructions given

kevin

**Comment by knolleary** [comment]
Sorry, can you spell out exactly what problem you are seeing?

"pink" is not mentioned in that list of colours. Do you think it should be?

**Comment by netcompsys** [comment]
Testin an attached Blink1 connected to a USB port on an RPi 2 running node Node Red 0.10.4

Using this flow

[{"id":"3d0cfcd0.c2f304","type":"blink1","fade":"0","name":"","x":563,"y":324,"z":"f17a9170.0e857","wires":[]},{"id":"c597035a.3a69","type":"inject","name":"","topic":"","payload":"red","payloadType":"string","repeat":"","crontab":"","once":false,"x":179,"y":184,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"41ad8e87.be527","type":"inject","name":"","topic":"","payload":"blue","payloadType":"string","repeat":"","crontab":"","once":false,"x":180,"y":246,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"bcb26743.434d98","type":"inject","name":"","topic":"","payload":"green","payloadType":"string","repeat":"","crontab":"","once":false,"x":179,"y":217,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"d28d5ae1.2d72a8","type":"inject","name":"","topic":"","payload":"cyan","payloadType":"string","repeat":"","crontab":"","once":false,"x":178,"y":278,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"3a7f1089.c580f","type":"inject","name":"","topic":"","payload":"magenta","payloadType":"string","repeat":"","crontab":"","once":false,"x":179,"y":310,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"167f0b75.e980f5","type":"inject","name":"","topic":"","payload":"yellow","payloadType":"string","repeat":"","crontab":"","once":false,"x":176,"y":342,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"74aa8c51.8b5574","type":"inject","name":"","topic":"","payload":"orange","payloadType":"string","repeat":"","crontab":"","once":false,"x":175,"y":373,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"a33c23af.5cc3e","type":"inject","name":"","topic":"","payload":"pink","payloadType":"string","repeat":"","crontab":"","once":false,"x":175,"y":406,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"abe061ee.541fa","type":"inject","name":"","topic":"","payload":"purple","payloadType":"string","repeat":"","crontab":"","once":false,"x":173,"y":438,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"47281ebf.b8d7e","type":"inject","name":"","topic":"","payload":"white","payloadType":"string","repeat":"","crontab":"","once":false,"x":174,"y":468,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"b2794395.4d86c","type":"inject","name":"","topic":"","payload":"warmwhite","payloadType":"string","repeat":"","crontab":"","once":false,"x":181,"y":499,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"d9919975.266e68","type":"inject","name":"","topic":"Off","payload":"#000000","payloadType":"string","repeat":"","crontab":"","once":false,"x":179,"y":120,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]},{"id":"5367e71c.ac9818","type":"inject","name":"","topic":"","payload":"black","payloadType":"string","repeat":"","crontab":"","once":false,"x":169,"y":82,"z":"f17a9170.0e857","wires":[["3d0cfcd0.c2f304"]]}]

when i select pink as the colour to inject to the blink1 I get the following debug message

Blink1 : invalid msg : pink

kevin

**Comment by netcompsys** [comment]
If you look at git hub it says
Usage

Sends the msg.payload to a Thingm Blink(1) LED device. The payload can be any of the following:

a three part csv string of r,g,b - e.g. red is 255,0,0
a hex colour #rrggbb - e.g. green is #00FF00
a @cheerlights colour name - e.g. blue

The @cheerlights colours are - red, amber, green, blue, cyan, magenta, yellow, orange, pink, purple, white, warmwhite, black

and npm similarly

Usage
Sends the msg.payload to a Thingm Blink(1) LED device. The payload can be any of the following:

a three part csv string of r,g,b - e.g. red is 255,0,0
a hex colour #rrggbb - e.g. green is #00FF00
a @cheerlights colour name - e.g. blue
The @cheerlights colours are - red, amber, green, blue, cyan, magenta, yellow, orange, pink, purple, white, warmwhite, black

kevin

**Comment by knolleary** [comment]
So there is a mismatch between the documentation for the node, and what has been implemented. Yes, that is a bug that needs fixing.

Thanks for reporting.

Nick

**Comment by netcompsys** [comment]
See here as well
http://www.cheerlights.com/control-cheerlights

CheerLight Colors and Commands:

red
green
blue
cyan
white
warmwhite
purple
magenta
yellow
orange
pink (Added December 2013)
oldlace (Added January 2014 - same color as warmwhite, but it is now a standard HTML color name)

kevin
