### ISSUE TITLE
Email settings in settings.js not working with 2.0.1

### ISSUE THREAD

**Issue by grawsom** [node-red/node-red-nodes#1020]
### Which node are you reporting an issue on?
node-red-node-email

### What are the steps to reproduce?
Update or install to v. 2.0.1.
Setting for email in NR setting.js 
`email: {
	user: 'something@gmail.com',
	pass: 'password'
	},`

### What happens?
Not working anymore, get 2 errors.
When deploying debug log shows
`No e-mail userid set`
`No e-mail password set`

When trying to send debug log shows
`Error: Missing credentials for "PLAIN"`

### What do you expect to happen?
Did run fine with 1.14.0
So I want it to be working as before. 😉

### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 16.20.1
- [ ] npm version: 8.19.4
- [ ] Platform/OS: RPI / Windows
- [ ] Browser: EDGE

**Comment by dceejay** [comment]
Major version changes include breaking changes. This is one of those. We no longer accept credentials in the plain in the settings file. This will not be "fixed". 
You can use environment variables instead if required.

**Comment by grawsom** [comment]
Thank's
Then I have some work ahead to do. 😉
