### ISSUE TITLE
Unable to uninstall node-red-mysql-r2@^1.3.0

### ISSUE THREAD

**Issue by BUMPRW** [node-red/node-red-nodes#1023]
### Which node are you reporting an issue on?

node-red-mysql-r2@^1.3.0

### What are the steps to reproduce?

Installed per instructions [at](https://flows.nodered.org/node/node-red-mysql-r2)

### What happens?

 it didn't work per those instructions nor did it say "mysql-r2" it just said "mysql"

### What do you expect to happen?

since it didn't work I attempted: "npm uninstall mysql", didn't work; then, npm recommended other variations didn't work and I finally manually deleted the files.  If you follow that with "npm audit fix" or "npm audit fix --force", then the module reinstalls.  if you completely delete node-red and reinstall node-red the module reinstalls.  I've manually deleted it and the dependencies, but now my tree is messed up and I can't conduct an audit, additionally rpm security is flagging faults which has never happened before.

### Please tell us about your environment:

- [ ] Node-RED version: latest
- [ ] node.js version:latest
- [ ] npm version:latest
- [ ] Platform/OS:MAC OS 13.5
- [ ] Browser: Safari

**Comment by knolleary** [comment]
Hi @BUMPRW 

That node is not one we maintain.

If you follow the GitHub link from its page on flows.nodered.org it will take you to it's GitHub repository where you can report your issue.

You may need to provide some more details.

> it didn't work per those instructions nor did it say "mysql-r2" it just said "mysql"

What exactly do you mean? Where did it say that? What command did you run exactly and where did you run it?

> since it didn't work I attempted: "npm uninstall mysql", didn't work

Did you try using the proper module name? `npm uninstall node-red-mysql-r2` - assuming that is actually the module you installed originally?

Why did you run audit fix and why did you run it with the force flag? That is very likely to have installed incompatible module versions.

Assuming you were doing all of this in your `.node-red` directory, you should have a `.node-red/package.json` that lists the modules you want to have installed. If that is correct, then you may need to delete `.node-red/node_modules` and `.node-red/package-lock.json` then run `npn install` in the `.node-red` directory to get things reinstalled cleanly.

But ultimately, this isn't a module we maintain. So you may want to seek further help in the Node-RED forums.
