### ISSUE TITLE
Is node-red-nodes a better alternative to node-red-bluemix-nodes?

### ISSUE THREAD

**Issue by ozomer** [node-red/node-red-nodes#103]
Hi, this is not really an "issue", but I noticed that the packages here overlap with the [node-red-bluemix-nodes](https://github.com/node-red/node-red-bluemix-nodes) package.
I'm working on a new project on Bluemix using node-red, and I was wondering whether I should use the node-red-nodes packages instead of node-red-bluemix-nodes (the default choice in the Bluemix Node-RED starter boilerplate).
It seems the packages here are maintained better and by more people. They don't support the auto-completion of VCAP services (mongodb, mqlight, etc.), but this is a minor issue for me (copy-pasting the credentials is easy).

I noticed that all the people that contributed to node-red-bluemix-nodes also contributed to this project, so I am not starting an "ego war" :).

Thanks!
@knolleary @anna2130 @hindessm 

P.S. Awesome Project!

**Comment by knolleary** [comment]
Hi @ozomer ,
for general questions, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red).

As you identify, node-red-bluemix-nodes are nodes that have been written specifically for the Bluemix environment, to work with some of the services that are available, such as the Watson services.

node-red-nodes is where we maintain our non-core nodes. There is not a single npm package that contains all of the nodes - they are published individually to npm. They contain a mix of software services as well as hardware specific ones that make no sense in Bluemix.

The mongodb/mqlight nodes are near-identical - we apply fixes to them both in parallel. The bluemix variants have the advantage of being aware of the VCAP services etc - so you are not better off change those.

You can search for additional node packages to add to you application [here](http://flows.nodered.org).

Nick
