### ISSUE TITLE
Traceability of a product using node red

### ISSUE THREAD

**Issue by Avrilanderson** [node-red/node-red-nodes#1033]
Hello,
I am new to Node red and I have a project that has to do with traceability of products using node red. I was wondering, which hardware is the easiest to use to label a product, which later on would be easy to program on node red? RFID-CHIPS? And thank you in advance.

**Comment by dceejay** [comment]
Hi - we prefer to use the [discourse forum](https://discourse.nodered.org/) for general questions, as there are many more people there with much wider experience of applications. The issues section is for actual bug reports on the core code. I don't know enough about your area to be able to advise though RFID is a well known technology for product tracing, as are bar codes.
