### ISSUE TITLE
node-red-node-sqlite - DB filename doesn't support underscore

### ISSUE THREAD

**Issue by baxerus** [node-red/node-red-nodes#1038]
### Which node are you reporting an issue on?
`node-red-node-sqlite`

### What are the steps to reproduce?
1. Configure a new database with an underscore in the name (I tried `/data/sqlite/dwd_mosmix`)
2. Try a `CREATE TABLE` statement
3. Nothing happens
4. Change filename to something without underscore (I changed to `/data/sqlite/dwd-mosmix`)
5. Retry step 2
6. File gets created. Everything is working fine

### What happens?
Nothing. No file appearing in the filesystem

### What do you expect to happen?
Also file names with underscore do work.
But even **more important** help the user understand and prevent the issue!
By either a check on the input field that prevent not allowed chars (if there is a reason for this) or at least by throwing an error on the failed `CREATE` statement (other non-functional commands also show errors in the debug log)

### Please tell us about your environment:

- [x] Node-RED version: v3.1.0
- [ ] node.js version: ?
- [ ] npm version: ?
- [x] Platform/OS: Docker container from hub.docker.com `nodered/node-red@sha256:cf9749f31fdaee0a87a27aebf97ef6c051e1b6e77f021806f876055ae8d0b4c8`
- [x] Browser: Chrome

**Comment by dceejay** [comment]
This is working fine for me not using docker - so I guess it must be something to do with you docker file mount and/or permissions.

<img width="899" alt="image" src="https://github.com/node-red/node-red-nodes/assets/5375409/a269dfde-92e3-47ef-804e-1bb0a379a0fb">

**Comment by baxerus** [comment]
I tried again and now I also can not reproduce the issue (I could before opening this issue. Opening issues is to much effort to not retrying multiple times before).

I'm sorry and closing this issue.
