### ISSUE TITLE
Arduino-Node lost connection

### ISSUE THREAD

**Issue by daUser** [node-red/node-red-nodes#1039]
### Which node are you reporting an issue on?
Arduino-board ( hidden node )
Arduino in

### What are the steps to reproduce?
Node-Red in Docker
Start with Arduino Nano with StandardFirmata.
Deploy a Flow with a Arduino in Node

### What happens?
The status of the Arduino input is correctly read initially but stops updating after a short period. In the Docker logfile, there is the line "[error] [arduino-board:d7663aaf.47194] Arduino serial port closed," and in the Node-Red Debug tab, there is no message.

### What do you expect to happen?
I expect the Arduino in Node to reliably report status changes on the Arduino input.

### Please tell us about your environment:
NodeRed Version: 3.1.1 in Docker Container on Armbian 23.11.1 Bookworm with Linux 6.1.63-current-x86

**Comment by dceejay** [comment]
Which version of serialport node are you using ? there was an update recently to pull in latest underlying library and binaries.

**Comment by daUser** [comment]
Hello,

thank you for the tip, it pointed me in the right direction. I'm not using the serialport node; it's already included in the arduino-node. The update you mentioned has also been applied to the arduino-node – the first one in 5(?) years! With that update, it's working now. I could have thought of checking for updates for the nodes myself.

Thanks a lot!

**Comment by dceejay** [comment]
Yes - I did update both... well I had to re-implement some of the arduino node code with the node code - but yes should be much more maintainable for me now.
