### ISSUE TITLE
XMPP - cannot receive chats, using both input and output in the same flow

### ISSUE THREAD

**Issue by jotadepicas** [node-red/node-red-nodes#104]
Hi,
I've implemented a Gtalk Bot using node-red, and I think I've stumbled upon a bug. 
If I use both xmpp input **AND** xmpp output nodes, I cannot receive chat messages.

After many hours of debugging (but hey, that's what we do, right? :P), I found that for some strange reason, the "chat" event, is captured by the EventEmitter of the **OUTPUT** node (rather than the input node).

Could it be that, because using both input and output nodes, the second node "steals" the connection somehow, thus capturing the chat events? Or some other nasty side-effect like that?

For now, I've locally patched 92-xmpp.js with an **ugly fix**, registering the "chat" listener on the output node, which doesn't make much sense, but works. Since the output node needs to know the id of the input node to re-route the message to it, I've saved in a global variable so I can retrieve it later (I know... :S).

The patch consists of adding this to the function that created the input node:

```javascript
    function XmppInNode(n) {
        // here we save the node id globally 
        // as the 'inputId' variable to retrieve it later
        RED.nodes.inputId = n.id;
```

And using that id in the creation of the output node to register the listener for the 'chat' event:

```javascript
    function XmppOutNode(n) {
    ....
        xmpp.on('chat', function(from, message) {
            // here we get the input node, using the previously saved node id
            var gtalkInputNode = RED.nodes.getNode(RED.nodes.inputId);
        
            var msg = { topic:from, payload:message };
            gtalkInputNode.send([msg,null]);
    });
```

Doest any of this make sense to you? Thanks!

**Comment by dceejay** [comment]
Hi - thanks for the report - will investigate... You're right, it makes no sense - as they shouldn't be shared and should be able to have their own event handlers...

**Comment by blackbeared** [comment]
@jotadepicas  Thank you very very much bro, you make my day. I appreciate your work.
