### ISSUE TITLE
PiGPIOd Feature request: set `host` dynamically

### ISSUE THREAD

**Issue by coconup** [node-red/node-red-nodes#1040]
### Which node are you reporting an issue on?

[PiGPIOd](https://github.com/node-red/node-red-nodes/tree/master/hardware/pigpiod/)

### What happens?

Currently, `host` is a static string in PiGPIOd nodes that does not accept any templated expression (e.g. `{{msg.host}}`).

### What do you expect to happen?

I would like to be able to dynamically set `host`, since I have a lot of nodes in my `flows.json` and hardcoding a hostname in all of them seems dumb (in case that value ever changes or if I need to port flows to a different environment).

### Please tell us about your environment:

- [ ] Node-RED version: 3.1.3
- [ ] node.js version: 21.4
- [ ] Platform/OS: arm64/ RPi OS bullseye

**Comment by dceejay** [comment]
You can instead use an environment variable set out side of Node-RED - see the docs - https://nodered.org/docs/user-guide/environment-variables

**Comment by coconup** [comment]
> You can instead use an environment variable set outside of Node-RED - see the docs - https://nodered.org/docs/user-guide/environment-variables

Even better, thank you!
