### ISSUE TITLE
bbb-analogue-in not working

### ISSUE THREAD

**Issue by maxwellhadley** [node-red/node-red-nodes#105]
There is a line missing in **145-BBB-hardware.js** which prevents the bbb-analogue-in node from working with either bonescript or octalbonescript, as `this._pin` is never created. Insert after line **60**:

    this._pin = adjustName(this.pin);               // Adjusted for Octal if necessary

**Comment by maxwellhadley** [comment]
Oops!

That fix is not correct - the call to adjustName() should follow the line:

    this.pin = n.pin;                               // The Beaglebone Black pin identifying string

which is line 60 in my freshly npm-install-ed copy of the file. You appear to have added an extra try/catch block around the library loads in the github version which has put things out of whack, as it hasn’t been published yet

**Comment by dceejay** [comment]
oops - re-fixed and re-published.
