### ISSUE TITLE
EMAIL (node-red-node-email) , If msg.to is defined msg.paiload is ignored

### ISSUE THREAD

**Issue by cayetano** [node-red/node-red-nodes#1053]
### Which node are you reporting an issue on?
node-red-node-email  v2.2.0
### What are the steps to reproduce?
set msg.payload as html text
set msg.to as recipient of email
### What happens?
Receive an email with an attached file "ATT0001.json" with 0 length

### What do you expect to happen?
Receive an email tith msg.payload as body of email

### Please tell us about your environment:

- [ x] Node-RED version:3.1.3
- [ x] node.js version: 16.20.2
- [ ] npm version:
- [ x] Platform/OS:docker
- [ x] Browser: any

**Comment by cayetano** [comment]
if you set "To:" field mai is send correctly, without change payoad.

**Comment by hardillb** [comment]
I can't reproduce this at the moment. I'm setting `msg.payload`, `msg.topic` and `msg.to` with a inject node and it's working fine.

```
[
    {
        "id": "e9fa79edf8cdb7b5",
        "type": "inject",
        "z": "3dc62ba4fd8f5f9a",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            },
            {
                "p": "to",
                "v": "ben@example.com",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "Test",
        "payload": "<html><body><h1>HelloWorld</h1></body></html>",
        "payloadType": "str",
        "x": 210,
        "y": 140,
        "wires": [
            [
                "750c7e71df3458a0"
            ]
        ]
    },
    {
        "id": "750c7e71df3458a0",
        "type": "e-mail",
        "z": "3dc62ba4fd8f5f9a",
        "server": "mail.example.com",
        "port": "587",
        "authtype": "BASIC",
        "saslformat": false,
        "token": "",
        "secure": false,
        "tls": true,
        "name": "",
        "dname": "Test",
        "x": 470,
        "y": 140,
        "wires": []
    }
]
```

Can you please provide an example flow.

**Comment by cayetano** [comment]
I've already solved the poltergueist.

In a previous step, an http-request was made.
The value of msg.headers, generater by http-request, interferes with the sending of the email, causing the error.

Please close the ticket and excuse me.
