### ISSUE TITLE
node-red-node-email: authentication: none broken

### ISSUE THREAD

**Issue by SynoUser-NL** [node-red/node-red-nodes#1055]
### Which node are you reporting an issue on?
node-red-node-email

### What are the steps to reproduce?
authentication: none

### What happens?
There is a big red triangle on the node after updating to v2.2.0.
Emails are not being sent.

### What do you expect to happen?
Authentication: none just connects to an (internal network) email server.
This is now broken for me on 5 nodered instances!

**Comment by hardillb** [comment]
Can you select the email node and then from the menu select export -> copy to clipboard and past the output here. Please obfuscate any hostnames if needed, but do not remove any fields.

Also do you know what version of the email node you upgraded from?

Starting from a fresh flow and importing the node is not showing this problem so I suspect it is a problem with upgrading and a field that is present that shouldn't be.

**Comment by SynoUser-NL** [comment]
Here is the node export:
[{"id":"6de0122bf9424b50","type":"e-mail","z":"8f72b637b6278dea","g":"8e3d673035b68d3a","server":"192.168.xx.yy","port":"25","authtype":"NONE","saslformat":false,"token":"","secure":false,"tls":false,"name":"e@mail.com","dname":"Email","x":2250,"y":460,"wires":[]}]

Previous version: sorry, not sure. I've updated all instances before I noticed the problem.

When I restart the NR instance (in this case from Home Assistant) the email nodes appear fine (i..e.: no red triangle). However when I open them and click Done the triangle appears., also if nothing has changed. When clicking Cancel after opening they remain the same state as before.

**Comment by hardillb** [comment]
OK, I have a fix for you, will still need to work out why.

- Open the config
- Change the auth type to XOAuth2
- In the token field enter any value
- Change the auth type back to None

Deploy

I know why it's complaining, just don't no how to fix it long term just yet.

@dceejay this is because token is typed input now I think which automatically validates and an upgrade won't have the default value.

**Comment by hardillb** [comment]
@dceejay `oneditprepare` might have to set the default if no value is set

**Comment by SynoUser-NL** [comment]
Fix worked, and V2.2.1 works without a problem.
Thank you for fixing it quickly! :)
