### ISSUE TITLE
How can I disable the creation process?

### ISSUE THREAD

**Issue by xufei56789** [node-red/node-red-nodes#1058]
![905296406](https://github.com/node-red/node-red-nodes/assets/22664500/9d14d923-46fc-4e5a-a5b7-9b80140a6de4)

**Comment by hardillb** [comment]
As mentioned in the issue template, please use the Node-RED forum to ask questions.

It really is not clear what you are asking here, but assuming you want to prevent the creation of multiple flow tabs, this is not possible.

**Comment by Steve-Mcl** [comment]
As explained by @hardillb above, this is not a feature.  If you desire this feature, please use the node-red forum to open a discussion in the feature requests category. 

Additionally, this is the wrong repository for Node-RED core functionality (this repository is for additional node-red nodes)

Closing as https://github.com/node-red/node-red-nodes/labels/wontfix
