### ISSUE TITLE
Get datetime when qwery a date column

### ISSUE THREAD

**Issue by ThomasAndreini** [node-red/node-red-nodes#1059]
### Which node are you reporting an issue on?
mysql
### What are the steps to reproduce?
read a column in date format
### What happens?
get datetime in that format 2024-03-30T00:00:00.000Z
### What do you expect to happen?
get only date like 2024-03-30
### Please tell us about your environment:

- [x] Node-RED version: 3.1.8
- [x] node.js version: 18
- [x] npm version:
- [x] Platform/OS: docker
- [x] Browser: Chrome

**Comment by ThomasAndreini** [comment]
If I try with to qwery with a client DbVisualizer i get the correct format

**Comment by dceejay** [comment]
Answer provided via the forum - https://discourse.nodered.org/t/mysql-node-returns-time-and-date-from-columns-set-as-date/86885/2
