### ISSUE TITLE
sqlite - if database does not exist, server crashes

### ISSUE THREAD

**Issue by jotadepicas** [node-red/node-red-nodes#106]
Hi,
if you configure an sqlite node, pointing to a database that doest not exist, the following error occurs, resulting in a server crash.

    /usr/local/lib/node_modules/node-red/node_modules/node-red-node-sqlite/sqlite.js:37
                node.tick = setTimeout(doConnect, reconnect);
                                       ^
    ReferenceError: doConnect is not defined
        at Database.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/node-red-node-sqlite/sqlite.js:37:40)
    at Database.emit (events.js:95:17)

Moreover, since the server has crashed, it won't start up again unless the path to the database is fixed by manually editing the flow file in the filesystem.

thanks!
-Juan

**Comment by dceejay** [comment]
Hi Juan

Indeed it wasn't re-calling itself to retry the connection. Now fixed. Thanks.
