### ISSUE TITLE
Issue with node-red-node-serialport and serial control Node: “TypeError: newline.substr is not a function” when Using Fixed Length Split Configuration 

### ISSUE THREAD

**Issue by khalilddkhili** [node-red/node-red-nodes#1070]
### Which node are you reporting an issue on?

  I encountered an error with the node-red-node-serialport module while using the serial control node to open and close communication with a product. 
### What are the steps to reproduce?
1)  Initial Configuration

I configured the COM port as shown in the image above with the following settings:
![image](https://github.com/node-red/node-red-nodes/assets/99320819/6a1c027a-a815-409c-a93d-908d9365f619)
Split input after a timeout of 200ms
Sequence
Close COM port (close com - works correctly)
Open COM port (open com - works correctly)
Send serial commands using the serial request node (send serial commands - works correctly)
Close COM port (close com - works correctly)
Open COM port (open com - works correctly)
2) Problem with New Configuration
When I used the following configuration:

Split input into fixed lengths of 30000 chars
![image](https://github.com/node-red/node-red-nodes/assets/99320819/4239ca89-5000-41b3-b79a-4c01b0180ac2)
and repeated the same steps, I encountered an error at step 5:

Close COM port (close com - works correctly)
Open COM port (open com - works correctly)
Send serial commands using the serial request node (send serial commands - works correctly)
Close COM port (close com - works correctly)
Open COM port (open com - error: "TypeError: newline.substr is not a function")

Lien Node-RED Forum : https://discourse.nodered.org/t/issue-with-node-red-node-serialport-and-serial-control-node-typeerror-newline-substr-is-not-a-function-when-using-fixed-length-split-configuration/88601
 
### What happens?
 error: "TypeError: newline.substr is not a function"
### What do you expect to happen?
Close COM port (close com - works correctly)
Open COM port (open com - works correctly)
Send serial commands using the serial request node (send serial commands - works correctly)
Close COM port (close com - works correctly)
Open COM port (open com - works correctly)
Send serial commands using the serial request node (send serial commands - works correctly)
Close COM port (close com - works correctly)

- [ ] Node-RED version: 3.1.3
- [ ] node.js version:v18.12.1
- [ ] npm version:8.19.2
- [ ] Platform/OS: windows 10
- [ ] Browser: Microsoft Edge

**Comment by hardillb** [comment]
What version of the node-red-node-serialport are you using?

**Comment by khalilddkhili** [comment]
node-red-node-serialpor v2.0.2

**Comment by dceejay** [comment]
pushed a fix to 2.0.3
