### ISSUE TITLE
PiLCD: Startup warning "Raspberry Pi specific node set inactive"

### ISSUE THREAD

**Issue by Kristian-240623** [node-red/node-red-nodes#1073]
about project: node-red-node-pilcd
[https://flows.nodered.org/node/node-red-node-pilcd](https://flows.nodered.org/node/node-red-node-pilcd)

I am using a Raspberry Pi. When i use the node rpi-lcd, it has a gray rectangle and the text "not available". 
Sending text has no effect.
I verified the hardware function with a Python script.
(See details in discussion: [https://discourse.nodered.org/t/problem-how-to-debug-pi-lcd/88886](https://discourse.nodered.org/t/problem-how-to-debug-pi-lcd/88886))
A catch node in node-red doesn't report an error.
A normal GPIO read node seems to work.

The startup log says:
23 Jun 20:14:19 - [info] Node-RED version: v3.1.9
23 Jun 20:14:19 - [info] Node.js  version: v18.19.0
23 Jun 20:14:19 - [info] Linux 6.6.28+rpt-rpi-v8 arm64 LE
23 Jun 20:14:21 - [info] Loading palette nodes
23 Jun 20:14:21 - [debug] Module: node-red-node-pi-gpio 2.0.6 /home/ks/.node-red/node_modules/node-red-node-pi-gpio
23 Jun 20:14:21 - [debug] Module: node-red-node-pilcd 0.3.1 /home/ks/.node-red/node_modules/node-red-node-pilcd
23 Jun 20:14:21 - [debug] Module: nrlint 1.2.0 /home/ks/.node-red/node_modules/nrlint
**23 Jun 20:14:23 - [warn] rpi-lcd : Raspberry Pi specific node set inactive**
23 Jun 20:14:23 - [info] Settings file  : /home/ks/.node-red/settings.js
23 Jun 20:14:23 - [info] Context store  : 'default' [module=memory]
23 Jun 20:14:23 - [info] User directory : /home/ks/.node-red
23 Jun 20:14:23 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Jun 20:14:23 - [info] Flows file     : /home/ks/.node-red/flows.json
23 Jun 20:14:23 - [info] Creating new flow file
23 Jun 20:14:23 - [debug] loaded flow revision: 4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945
(...)

My environment:
- RPi.GPIO Library: Version 0.7.1
- Platform: Raspberry Pi 4 B 4 GB, Raspbian 12
- Node-RED version: 3.1.9
- node.js version: 18.19.0
- npm version: 9.2.0
- Browser: Firefox (latest)

**Comment by hardillb** [comment]
What version of python is installed on the machine?

**Comment by Kristian-240623** [comment]
Hi, 
Python Version: 3.11.2
```
cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Revision	: c03114
Serial		: 100000005c35cc5a
Model		: Raspberry Pi 4 Model B Rev 1.4
```

thanks,
Kristian

**Comment by Kristian-240623** [comment]
I have tested if tehre is a difference between 64 bit and 32 bit. Loaded an actual Raspbian 32 bit, made apt-get update & apt-get upgrade, installed node-red from this location [https://nodered.org/docs/getting-started/raspberrypi](https://nodered.org/docs/getting-started/raspberrypi), installed module rpi-lcd, and get exactly the same warning (however in german)
**[warn] rpi-lcd : Raspberry Pi specific node set inactive**

**Comment by Kristian-240623** [comment]
I tested different Raspbians. As you said (in the forum thread/ see first post), it is a matter of 64 or 32 bit.
Raspberry Pi 4 users seem to need attention, because not every "32 bit" is really 32 bit. I read somthing about this, but i lost it (and it is very late). What works for me, is the "legacy 32 bit" version. Not the other two versions. See Screenshot.

![grafik](https://github.com/node-red/node-red-nodes/assets/173719222/05ea9176-b46c-4432-8e9d-364fa4fcd5d4)

**Comment by hardillb** [comment]
OK, the test that is failing is this line

https://github.com/node-red/node-red-nodes/blob/305327faaa650c2cee9e428ecf4e45d972de7d7b/hardware/PiLcd/pilcd.js#L13

Which just checks for BCM being somewhere in the `/proc/cpuinfo` output and if it's not there then it says you are not running on a Pi.

It may also need another update like https://github.com/node-red/node-red-nodes/pull/1024
