### ISSUE TITLE
Email using long password and Authentication as TLS

### ISSUE THREAD

**Issue by RudolfTheRedNode** [node-red/node-red-nodes#1077]
We got some requirement. Can we use Authentication TLS and a long long password?

Best regards,
Red-Node

**Comment by hardillb** [comment]
Please use the Node-RED forums or the Node-RED Slack (both linked to from the bottom of the Node-RED [homepage](https://nodered.org/) to ask questions.

It's not clear from your question what exactly you are asking here.

- You can enable TLS when connecting to the mail server
- The email nodes do not support TLS Client Certificate authentication
- I'm not aware of any limitation on password length.


If you require TLS Client Certificate authentication then we would happily look at a Pull Request to add such a feature.
