### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by heytheww** [node-red/node-red-nodes#1084]
I am reporting a possible problem with node creation. This problem seems to be an issue, but it is actually a work oversight. I did not find any relevant experience reference before solving this problem (maybe I did not find it by chance), so I recorded it for reference.

Node-red is a mature workflow specification. I use this specification to create some custom nodes for my team to use. So, how should I debug a node after writing it? One way is through unit testing. My idea is to add it to the core node directory (node-red), so that it can be easily debugged using vs code.

When verifying my idea, in order to avoid the impact of node code writing errors, I directly used the 64-mysql node source code of the node-red-nodes project

### Which node are you reporting an issue on?
68-mysql from node-red-nodes

### What are the steps to reproduce?
Place the `68-mysql.html` and `68-mysql.js` files into `[my workplace]/node-red/packages/node_modules/@node-red/nodes/core/storage/`

### What happens?
http://127.0.0.1:1880/nodes => response:
```json
{
        "id": "node-red/mysql",
        "name": "mysql",
        "types": [
            "MySQLdatabase",
            "mysql"
        ],
        "enabled": true,
        "local": false,
        "user": false,
        "module": "node-red",
        "err": {
            "code": "MODULE_NOT_FOUND",
            "requireStack": [
                "[my workplace]\\node-red\\packages\\node_modules\\@node-red\\nodes\\core\\storage\\68-mysql.js",
                "[my workplace]\\node-red\\packages\\node_modules\\@node-red\\registry\\lib\\loader.js",
                "[my workplace]\\node-red\\packages\\node_modules\\@node-red\\registry\\lib\\index.js",
                "[my workplace]\\node-red\\packages\\node_modules\\@node-red\\runtime\\lib\\nodes\\index.js",
                "[my workplace]\\node-red\\packages\\node_modules\\@node-red\\runtime\\lib\\index.js",
                "[my workplace]\\node-red\\packages\\node_modules\\node-red\\lib\\red.js",
                "[my workplace]\\node-red\\packages\\node_modules\\node-red\\red.js"
            ]
        },
        "version": "4.0.3"
    }
```

### What do you expect to happen?
mysql nodes are like core nodes

### Please tell us about your environment:

- [x] Node-RED version: 4.0.3
- [x] node.js version: v20.17.0
- [x] npm version: 10.8.2
- [x] Platform/OS: win11 22H2
- [x] Browser: Chrome 128.0

### How to solve the problem 
when you see the debug console, you can see:

26 Sep 09:55:28 - [warn] [node-red/mysql] Error: Cannot find module 'mysql2'

So, we can solve the problem by installing mysql2 using npm
```bash
npm install mysql2
```
Therefore, pay more attention to the console information

**Comment by heytheww** [comment]
如果你想要你的节点正常显示，别忘了补充locales in `[my workplace]/node-red/packages/node_modules/@node-red/nodes/locales`

**Comment by dceejay** [comment]
For future reference that's not how to install nodes for development work... 
you should clone the complete package / project into a clean development directory - then in your working Node-RED instance working directory (eg ~/.node-red) run `npm install <path to your dev project>` 
This will install the node - and install any dependencies correctly - and you can then edit the js and html - stop and restart Node-RED and things will be linked correctly.
