### ISSUE TITLE
Problem with Node-red on RPi2 connect multiple Ti SensorTags

### ISSUE THREAD

**Issue by LuckyTiger** [node-red/node-red-nodes#109]
Environment:
Board: Raspberry Pi 2(Running RASPBIAN)
Bluetooth Adapter: ORICO BTA-403
BLE device: Ti SensorTag CC2541
![image](https://cloud.githubusercontent.com/assets/9037302/6861425/dd1c0882-d470-11e4-8f1b-4fcd03cd6429.png)
the first SensorTag works fine.
but the SensorTag2 does not work.(no sign of the Adapter)
they have different UUIDs.
I just want to ask How can i speak with multiple SensorTags?

**Comment by LuckyTiger** [comment]
![2015-03-27 11 02 59](https://cloud.githubusercontent.com/assets/9037302/6861457/830a9092-d471-11e4-9d9f-932853a270f4.png)

**Comment by hardillb** [comment]
I've been on holiday and I've leant my 2 sensorTags to somebody. When I get them back I'll try and find some time to have a look at this.

**Comment by hardillb** [comment]
Having had a bit of a play with the underlying library, it seams it will only bind to one tag at a time.

**Comment by vielmetti** [comment]
The underlying library is node-sensortag and noble and bluez (on Linux), and @sandeepmistry should know more.

**Comment by dceejay** [comment]
Closing for now as not much we can do about it - apart from hassle upstream.

**Comment by sandeepmistry** [comment]
[```SensorTag.discover```](https://github.com/node-red/node-red-nodes/blob/master/hardware/sensorTag/79-sensorTag.js#L44) only discovers a single SensorTag

The new unpublished ```1.0.0``` release includes a ```SensorTag.discoverAll``` and ```SensorTag.discoverByUuid``` API.

**Comment by hardillb** [comment]
@sandeepmistry I'm using the head code, but I still can't get it to connect to more than one tag at once. I'll open an issue against node-sensortag with the sample code I've been trying

**Comment by vielmetti** [comment]
The relevant upstream issue is https://github.com/sandeepmistry/node-sensortag/issues/37 if you're following along.

**Comment by vielmetti** [comment]
It might make sense @dceejay to split out node-red-node-sensortag as its own repo and npm - I know that's the long term plan for all of these nodes, but there's a fair bit of dependencies to sort through and the cleaner packaging would let us tweak things faster.

**Comment by dceejay** [comment]
Ed, Thanks but no. I'd prefer to keep them in one repo for now - they are already individually published to npm so installing them for non-developers is no problem. (and developers only need the pre-reqs for the nodes they are interested in.)

**Comment by dceejay** [comment]
Reopened - as per vielmetti comment in #107 (now closed)

**Comment by dceejay** [comment]
A 3rd party node https://github.com/ibm-iot/node-red-contrib-sensortag supports multiple tags.
So we will probably deprecate this version over time.
Use that as an alternative if you need multiple tags.
Will close this if no-one objects...

**Comment by vielmetti** [comment]
Super! Glad to see this, looking forward to trying it out.
