### ISSUE TITLE
Long restart times when connecting to ActiveMQ Stomp connector

### ISSUE THREAD

**Issue by mfeblowitz** [node-red/node-red-nodes#112]
This is a follow-on from issue #587 on node-red/node-red for details, mostly due to an initial misdiagnosis of the delayed restart problem.

The issue is that when any flow with a stomp node is connected to activemq, via the stomp connector, I see a guaranteed 2 minute pause in a re-deploy after a change. 

The manifestation is that there is a message from node-red about "Stopping flows", a 2-minute wait, another "Stopping flows" followed immediately by "Stopped flows", "Starting flows", and "Started flows".

I've put in several probes. I see that the DISCONNECT is being sent from stomp-client/lib/client.js and it appears that message is being received by activemq (indicated as an increase in the count of enqueued advisory messages, seen on the activemq console).  From the look of it, the callbacks in the stomp nodes are not being exercised, likely due to the lack of a call-back to stomp-client from activemq.  

So the problem appears  to be in the response back from activemq, from the stomp connector.

One thing I couldn't determine is where the 2 minute delay comes from. It's not from the setTimeout calls in the stomp nodes: they are only 15 second delays and, more important, that code is not getting executed.

Finally, it was suggested that, as a short-term workaround, I just call the disconnect and not wait for a callback. It would seem that this might result in some problems down the road. 

Any suggestions?

Thanks, 
Mark

**Comment by dceejay** [comment]
Hi Mark,

is there any further activity in the ActiveMQ log at the 2 minutes time ? Or are we just tidying up at that point ? - I guess a compromise would be to add a 5 sec setTimeout at "our" side and then call done(); so the far end gets a chance to do the right thing but we don't wait unnecessarily long.

**Comment by knolleary** [comment]
We could... but would be good to understand the underlying cause first. Wouldn't want to hack around a genuine bug in someone's code, or a misuse of the code on our part, without dealing with it properly.

Looking at the [stomp-client code](https://github.com/easternbloc/node-stomp-client/blob/master/lib/client.js#L147), it appears to be waiting for the stream to end before it will call the callback we provided. @mfeblowitz is that line (within the on-end handler) somewhere you've put a probe in to see if it gets called? If it isn't being called, that suggests the connection is being held open by someone, which takes 2 mins before the stream timesout and it unravels.

**Comment by dceejay** [comment]
looking more at that client code - it doesn't actually seem to emit disconnected as an event - you can only pass the callback into the disconnect call... 
@mfeblowitz can you try replacing line 95 in 18-stomp.js with
    node.client.disconnect(function() { done; });

**Comment by mfeblowitz** [comment]
Um. Not sure I understand the difference between a callback with "done()" and no callback at all.
Should there instead be something in the callback to trigger a local completion step?

**Comment by dceejay** [comment]
I was expecting the stomp-client to fire a "disconnected" event as it seems to fire a lot of other events.... so the current code sets up a listener for a "disconnected" event. But in fact the stomp client never creates a disconnected event. However - you it does let you call client.disconnect with a function you want it to call when it completes the disconnect. Did you try the code above ?

**Comment by mfeblowitz** [comment]
Yes. And it does work, in that there's no 2-minute wait. What I'm still wondering is how this can actually induce a wait on the calling end, as there's nothing on the calling side waiting for the callback.

**Comment by dceejay** [comment]
Well - we ask them to disconnect - and then they do so and we never get the event (as there isn't one) so we wait - I think Nick may have an override timeout in there somewhere so that eventually it stops. - which must be the 2 minutes. (unless it is just a TCP timeout - that then triggers an error at our end).

but as it fixes it - I'll push that as a fix... will be tonight.

**Comment by knolleary** [comment]
We don't (yet) have a timeout of our own... must be the TCP timeout.

**Comment by mfeblowitz** [comment]
Ok - as long as there's no need to wait for the stomp connector to ack, that's probably ok.
BTW - it'll be on the "on close" for both in and out.

Thx

**Comment by dceejay** [comment]
The stomp client itself is waiting for the stream bed so is doing the right thing, so hopefully we should be OK now. Yes it will apply to both close findings.

**Comment by dceejay** [comment]
Fix pushed - 18c866b4908cbaa80da265238afd7f907bcc6532
