### ISSUE TITLE
dweetio node should send payload value only

### ISSUE THREAD

**Issue by mattbrailsford** [node-red/node-red-nodes#122]
Currently, the dweetio node sends the payload wrapped in a { payload: XXX } object. There should be a way to send a value without the payload object.

**Comment by dceejay** [comment]
Matt,
the dweetio API only allows the sending of objects... - so raw values have to be wrapped in something to make it an object.... - we chose "payload" .... if a node-red dweetio input node receives an object called payload then it does "do the right thing" and unpacks it back to a raw value.

Closing this as would need them to change their API to allow sending raw data.

**Comment by mattbrailsford** [comment]
But there should be an option to say "I'll make my own object so don't wrap
it in a payload object". I have another system connecting at the other end
for which it expects the dweet contents to be a specific format, if I want
to connect it to node-red, I now have to explicitly handle the payload
object and unwrap it, which isn't ideal.

**Comment by dceejay** [comment]
Whoa... you are so right..  now checks if it's an object and if so leaves it alone... otherwise wraps it in {payload:...   

republished (so leaving closed)

**Comment by mattbrailsford** [comment]
Perfect! :)
