### ISSUE TITLE
Typo in SensorTag node

### ISSUE THREAD

**Issue by hardillb** [node-red/node-red-nodes#124]
Came in via email from Stephan Stadler

       if (node.stag.type === "cc2560") { // should be cc2650
            if (node.luxometer) {
                node.stag.enableLuxometer(function() {});
                node.stag.notifyLuxometer(function() {});
            } else {
                node.stag.unnotifyLuxometer(function() {});
                node.stag.disableLuxometer(function() {});
            }
        }

**Comment by dceejay** [comment]
ok - thanks for spotting this Stephan.
