### ISSUE TITLE
piface - inputs should match board

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-nodes#128]
The outputs in the node are labeled 0-7 and match what is on the board. The inputs on the board are input 0-7 but the piface node uses switch 1-4 and inputs 5-8. 

Shouldn't the inputs in the node be switch 0-3 and inputs 4-7 to be consistant?

**Comment by dceejay** [comment]
The switches on the board are labeled s1 to s4 so would seem to be OK... ?

http://www.piface.org.uk/assets/piface_digital/PiFaceBoard.png

**Comment by dceejay** [comment]
Whereas the the outputs are labeled led0 to led7.. So we are consistent with the silk screen on the board... Even if not entirely logical.

**Comment by juggledad** [comment]
On my PiFace digital 2 the silk screen shows s3 s2 s1 and s0...ahh don't you love pcb board revisions

**Comment by juggledad** [comment]
My board - with S0-S3 - has '(c) OpenLX SP Ltd 2014' just above the silk screened 'element14'  onteh switches side of the board.

Online I found a image of one with s1-s4 that has '(c) OpenLX SP Ltd 2013', so it looks like they have changed the silk screen labels.

**Comment by dceejay** [comment]
Oh joy,...
I wonder if there is any way to tell them apart via sw ?

**Comment by juggledad** [comment]
Don't know, they both say 'PiFace Digital 3.0' on the back and (sigh) I think I fried mine trying to get a PIR to work with it. Now I wish I had kept up with my electronics from 40 years ago....

**Comment by dceejay** [comment]
Closing as there is no way we can tell these boards apart via software. 
Have added a note to the readme and info pages to point out they are labelled differently.
