### ISSUE TITLE
mongodb dependency needs to be 1.4.29 or later for MongoDB 3.0.x

### ISSUE THREAD

**Issue by mblackstock** [node-red/node-red-nodes#133]
Using the mongodb node, authentication errors occur otherwise when 3.0.x database is configured with  db authentication.  Tested against mongolab sandbox running mongo 3.0.6

**Comment by knolleary** [comment]
Fixed and republished to npm as 0.0.3

**Comment by kmoughon** [comment]
FYI for anyone else having problems, I had to update to an even later version, 2.1.4, to get it to connect to Mongo 3.2 with authentication. Mongo docs point to version 2.1.x+ as necessary for nodejs to work with Mongo 3.2+. 
pi@raspberrypi:/ $ sudo npm list -g mongodb
/usr/lib
âââ mongodb@2.1.4
âââ¬ node-red-node-mongodb@0.0.4
  âââ mongodb@2.1.4
