### ISSUE TITLE
blink1

### ISSUE THREAD

**Issue by glynhudson** [node-red/node-red-nodes#135]
Install error:

$ npm install node-red-node-blink1

npm WARN deprecated node-hid@0.4.1: bad semver, NANv2 change means we shoudl be v0.5.0, NANv1 is 0.4.0

 node-hid@0.4.1 install /home/pi/.node-red/node_modules/node-red-node-blink1/node_modules/node-blink1/node_modules/node-hid
> node-gyp rebuild

**Comment by knolleary** [comment]
What version of node are you using?

**Comment by dceejay** [comment]
I suspect this is relevant...

https://github.com/node-hid/node-hid/issues/115

**Comment by glynhudson** [comment]
The issue seemed to affect V0.10.26 I was using on my Ubuntu 14.04 64-bit
desktop, using V0.12.7 on Raspberry Pi I have not noticed the issue.

On 17 October 2015 at 11:13, Dave Conway-Jones <notifications@github.com>
wrote:

> I suspect this is relevant...
>
> node-hid/node-hid#115 <https://github.com/node-hid/node-hid/issues/115>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-red/node-red-nodes/issues/135#issuecomment-148901772>
> .
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by dceejay** [comment]
Closing this now as upstream have fixed their issue.
