### ISSUE TITLE
support node-serialport  2.0.x 

### ISSUE THREAD

**Issue by xmlking** [node-red/node-red-nodes#139]
please upgrade node-serialport  to 2.0.x  be compatible with Node 4.0

**Comment by dceejay** [comment]
we are looking at this issue. Upgrading will break lots of existing users as it requires gcc 4.8 that is not installed by default on many systems.

**Comment by sleepingscorpion** [comment]
Could you provide an unofficial build/zip for 4.7+ (im on 4.9.2 on raspbian jessie) as a stop-gap solution - its a show stopper for some us, as reading serial port e.g. /dev/ttyAMA0 etc is all we need to plug and play in node-red. Thanks...

**Comment by dceejay** [comment]
How much of a show stopper ? Do you really need to be running Node.js 4.x ? The serialport nodes work fine on v0.10 and v0.12 (and come pre-installed on the apt-get nodered version on Jessie)

**Comment by xmlking** [comment]
Node.js 4+ helps us to write js code with generators , promises , async/await , arrow fictions and all ES6 syntax . Today we can run node 4 apps on raspberry pi. Only thing that preventing us to move forward is nodered

**Comment by dceejay** [comment]
We have a fix in test at the moment - works on Node 4.2.3 (LTS).
Coming soon...

**Comment by xmlking** [comment]
Thanks a lot :)

**Comment by dceejay** [comment]
Ok - - new version of node-red-node-serialport pushed....
Now using serialport v2.0.x and so should now work OK with node.js v4.x etc...
If on earlier versions then make sure npm is at least v2... and gcc >=4.6

    sudo npm i -g npm@2.x

should do the necessary if in doubt.
