### ISSUE TITLE
emoncms - would be nice if input could also be dictionnaries

### ISSUE THREAD

**Issue by arthurlutz** [node-red/node-red-nodes#147]
Am using the csv transform that gives me a payload that looks a bit like this : 

```
 "payload": {"indicator1": 4, "indicator2": 3, "indicator3": 0, "indicator4": 2 }
```

It would be nice to feed that directly to the emoncms output node. Am new to node-red so there is probably of doing the transform to 

```
"payload": "indicator1:4,indicator2:3,indcator3:0,indicator4:2"
```

How does one debug the error that I'm getting when sending wrong data to emoncms ? 
```
TypeError: undefined is not a function
```

**Comment by dceejay** [comment]
Hi, 
I have just updated the emoncms node to now also accept simple objects (no idea why it didn't before :-)
so yes you should now be able to feed that csv transformed msg.payload in directly.
