### ISSUE TITLE
Serial Port errors

### ISSUE THREAD

**Issue by scargill** [node-red/node-red-nodes#148]
Sorry if this is not new.

I'm using Node-Red on a Raspberry Pi2. I'm driving a Nextion display at 115kbd.  Serial works just fine - BUT -  I get serial errors whenever I make any changes to my flows.

Error: Serialport /dev/ttyAMA0 not open.

Over and over and over - then eventually after a short while the error messages seem to stop.. and all is well. but I get occasional resets of Node-Red and I'm trying to get rid of all errors so I can find the source.  I'm guessing these issues are due to either timing when Node-Red is restarted or updated (with the DEPLOY button) or the port staying open when you start making edits. I don't really understand the underlying reason or how to stop this..

Can anyone enlghten - I can't be the only person getting this issue...

Pete.

**Comment by dceejay** [comment]
Hi Pete,

I'm struggling to re-create this - If I have a device sending me data on /dev/ttyAMA0 (the serial port on the  GPIO header) - I can re-deploy as many times as I like on my Pi without issue (so far) - and data keeps on arriving ok.  What version of Node-RED and node.js are you using ? Anything else I can do to provoke it ?

**Comment by scargill** [comment]
Will respond in full when not at airport:-)

**Comment by dceejay** [comment]
no rush - have a good flight !

**Comment by scargill** [comment]
So my job when I get home is to find out why both Node Red installations 
reset at least once a day. It isnt the Pi as Webmin says they are staying 
up. The only recent changes I can think of are serial for Nextion displays 
and Blynk nodes for Blynk. Somehow I have to narrow this down.

**Comment by dceejay** [comment]
Hi Peter  - any update on this ? Is it really a serialport issue ?

**Comment by scargill** [comment]
Hi, sorry Dave… so my current situation… I’ve brought everything up to date – Node-Red, Blynk, serial etc… as far as I can tell NEITHER of the two installations is failing now other than BLYNK.  Certainly the daily reboot has GONE.   I need more time due to resets for upgrades etc to be definitive on this but I think I’m safe in saying that on two separate, independent installations in 2 countries – they are both rock solid for now.

 

I do occasionally get non-critical messages on power up about the serial port – it may be I’ve not totally disabled it’s Pi use (some debug purpose) as this only happens when starting Node-Red up.

 

I’ll give you more information soon. As for Blynk we have a problem – there is the Blynk designer on one side and the Blynk server people on the other – where does the problem lie? I have an inject node keepin the server alive – I’ve only tonight installed the latest update to the Blynk node so it will be 24-hours+ before I can say that is 100%.

 

I won’t drop this – I’ll keep checking and report back – for me it is essential  that I make these setups 100% reliable as I intend to spend 6 months with one installation and 6 months with the other- thousands of miles apart :)

**Comment by dceejay** [comment]
Peter, I'm going to close this for now. Feel free to re-open if it re-appears as a serialport node issue.
