### ISSUE TITLE
Ledborg cheerlights colours

### ISSUE THREAD

**Issue by DrLucyRogers** [node-red/node-red-nodes#149]
Hi,

On the info tab of the ledborg node it lists warmwhite (but not oldlace)  - on the cheerlights page http://cheerlights.com/cheerlights-api/ it prefers warmwhite. (Both work on the ledborg node)

Also on the ledborg info it lists amber, which isn't listed on cheerlights (but it works - it is the same as orange).

Hopefully I have put this in the right place this time??

Cheers Lucy

**Comment by dceejay** [comment]
Hi Lucy,

So what is the issue ? It should list them ? It shouldn't list them ?

We added amber as "everyone" apart from cheerlights wants to do a traffic light of red, amber, green :-)

**Comment by DrLucyRogers** [comment]
Ah, I see, yes amber makes sense now.

I suggest list oldlace as well - maybe as oldlace (warmwhite) - I only used the ones listed in the info so was missing out on some tweets.

Not hugely important, but may save some queries later.
