### ISSUE TITLE
Serialport does not successfully compile, +15 compile errors

### ISSUE THREAD

**Issue by jwcrawley** [node-red/node-red-nodes#153]
Multiple compile issues. 
Running nodejs 5.2.0

http://pastebin.com/pHek7VDy

**Comment by dceejay** [comment]
This should be fixed by #139. We have a fix in test at the moment - works on Node 4.2.3 (LTS).

**Comment by jwcrawley** [comment]
That is awesome to hear. I'd also be willing to test any experimental packages on my dev system, if you'd like.

Again, thank you.

**Comment by dceejay** [comment]
Closing as a duplicate of #139
