### ISSUE TITLE
When node-red-node-physical-web node-red-node-sensortag is not working

### ISSUE THREAD

**Issue by beeva-marianmoldovan** [node-red/node-red-nodes#154]
When both modules installed:
+ node-red-node-physical-web 
+ node-red-node-sensortag

Running the sensortag module throws after connected:
```
[info] Started flows
[info] [sensorTag:sensorTag] connected b0b448bf3506
noble: unknown peripheral b0b448bf3506 connected!
```

After removing **node-red-node-physical-web** everything works fine.

Tested in Ubuntu 10.04 with 3.16.0-031600-generic and Raspbian Wheezy (7) with 3.18.11-v7+ on a Raspberry Pi 2 B

**Comment by knolleary** [comment]
I suspect this is a limitation of the underlying noble module - you can't access the bluetooth hardware in two different modes at the same time.

**Comment by beeva-marianmoldovan** [comment]
I was not using both modules, in fact the eddystone module it's on other flow in the workspace and works

**Comment by knolleary** [comment]
Umm, you say you're not using both modules, but then say you are using the eddystone module in one flow and hit an error when you tried to used the sensor tag node - which sounds like both modules being used? Or have I misunderstood?

**Comment by hardillb** [comment]
Tabs are all part of the same flow, so if you have both nodes on the canvas on any tab then they will both be loaded, even if you don't have them wired up to anything else

**Comment by beeva-marianmoldovan** [comment]
node-red-node-physical-web != node-red-contrib-eddystone, but that's in a more complex flow. Made the tests in a clean environment.

The one that breaks it all it's the node-red-node-physical-web.

**Comment by dceejay** [comment]
Is this still a problem. There have been quite a few updates to the node-red-node-physicalweb node recently. Though they do both use the noble library  so it may still conflict.

**Comment by farrrell504** [comment]
still a problem.... has there been a fix?

**Comment by dceejay** [comment]
none apart from the advice to not load both nodes at once. (Or even install them both at once).

**Comment by nanohex** [comment]
I have the same problem and all i did was load the sensor tag node and debug output. 

7 Aug 02:41:56 - [info] [sensorTag:11f2487b.ee0db8] found sensor tag: b0b448b98e83
7 Aug 02:41:56 - [info] [sensorTag:11f2487b.ee0db8] connected to sensor tag: b0b448b98e83
noble: unknown peripheral b0b448b98e83 connected!
