### ISSUE TITLE
blink(1) not being found on redeploy

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#160]
node-red-node-blink1

If you have a flow with a blink1 node, and you (full) redeploy, it says 
Blink1 : device not found
and 
[error] [blink1:8957ac25.616fd] Blink1 : device not found

If you stop and start node-red, however, it finds it and works fine.

So it just seems to be on a redeploy that it "disappears". Unplugging and replugging the blink(1) solves it, or restarting node-RED.

**Comment by dceejay** [comment]
What platform / OS ?
If linux - did you add this also when setting up the blink1 ? https://github.com/todbot/blink1/blob/master/linux/51-blink1.rules

**Comment by andysc** [comment]
Ubuntu Linux on my laptop
and yes, I've got the udev rules in place.

**Comment by dceejay** [comment]
which versions of node.js, Node-RED, node-red-node-blink1 (npm ls | grep blink) ?

**Comment by andysc** [comment]
2 Jan 23:02:56 - [info] Node-RED version: v0.12.4
2 Jan 23:02:56 - [info] Node.js  version: v0.10.37

node-red-node-blink1@0.0.11 
└─┬ node-blink1@0.2.2

hope that helps :)
Andy

**Comment by dceejay** [comment]
I've now retested on Linux, and it's still working for me...
with either partial or full deploy...
NR 0.12.4
Node 0.10.41

**Comment by dceejay** [comment]
Turned out user had multiple copies of the node installed... and an old version was being used... removed duplicate and all ok.
