### ISSUE TITLE
Ping - or not

### ISSUE THREAD

**Issue by scargill** [node-red/node-red-nodes#161]
Hi

I just installed the PING node on a new Pi2 Node-Red installation - which is clearly working Node-Red as it is talking to my Windows PC.... but.. .ping doesn't work..  So this is a new JESSIE installation with nothing more than NPN/NODE-RED installed..

I put the ping node onto the screen - joined it to a debug - set to 10 seconds - and I get "false" coming out no matter what I put in.. I've tried www.google.com, http://www.google.com, www.bbc.co.uk etc - makes no difference.

Any thoughts?

**Comment by dceejay** [comment]
For some reason the Pi guys seem to have let ping be a root command... I'll ask them what's up.
to reset it you can

    sudo setcap cap_net_raw=ep /bin/ping
    sudo setcap cap_net_raw=ep /bin/ping6

There are several references to it on various fora - https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=129242

**Comment by scargill** [comment]
That works a treat Dave – but will it survive a reboot?

**Comment by dceejay** [comment]
Yes
