### ISSUE TITLE
Wemo : adding port option

### ISSUE THREAD

**Issue by benoitjadinon** [node-red/node-red-nodes#162]
hi, using the wemo node, I kept getting a ECONNREFUSED error.
but I've tried connecting to my wemos using (https://www.npmjs.com/package/belkin-wemo-command-line-tools)[belkin-wemo-command-line-tools] and it worked. then I noticed at the end of that page, they talked about port 49153, I tried forcing that port and it worked. 
the default hardcoded value in the current wemo node impl is 49154, I'm guessing it changes from one device version to the other. anyhow, I forked and added a port option, tried it and the node worked as supposed. I'll create a pull request.

**Comment by hardillb** [comment]
The port number changes over time, not just with software updates.

I am just about to publish a new set of WeMo nodes that use UPNP to look up the devices by name on the network at regular intervals to track when the ports move (or the IP addresses in a constrained DHCP world). I'll try and get the new code out at the weekend

**Comment by benoitjadinon** [comment]
that's even better ! thanks for that
