### ISSUE TITLE
Enhance node-red-node-rbe with more checks ...

### ISSUE THREAD

**Issue by Apollon77** [node-red/node-red-nodes#167]
Hey,

the RBE Node is great, but why not enhance it to have a full set of "Checks" depending of last and current value?!
I thought of:
- new value is equal to old
- new value is not-equal to old (exists)
- new value is >,<, >=, <= old value (interpreted as number)
- maybe add option to automatically convert values to numbers for some comparisms (or els how it is needed to do?)

Then it would be the perfect filter to have data flows active with the special data changes

**Comment by dceejay** [comment]
Hi
usually we prefer general discussions of enhancements to be on the mailing list. But as it happens :-)... As part of the 0.13 release (soon)... the switch node is getting a big enhancement. This already does do > <  != etc... but not against previous value... One of the enhancements will be to allow previous value. So this should now cover the basic RBE cases more completely.

The RBE node itself does do this across multiple msg.topics simultaneously - and also does the change by more than... (deadband mode) - both of which the switch node won't do (at least not  in 0.13) - so it still has a place for now.

**Comment by Apollon77** [comment]
Graet, will await the 0.13 and test then :-)

**Comment by dceejay** [comment]
great timing to ask the question ;-) thanks

**Comment by Apollon77** [comment]
I alsway try to help ;-)

already checked the commit in node-red github ... maybe I patch my local version manually to test it ...

**Comment by knolleary** [comment]
You won't be able to patch just the node as it depends on new capabilities provided by the editor. 0.13 will be released in the next couple of days.

**Comment by Apollon77** [comment]
good to know ;-))
