### ISSUE TITLE
URL support

### ISSUE THREAD

**Issue by elyobelyob** [node-red/node-red-nodes#169]
How easy would it be to add in URL support? I'd like to send a link with my message. Thanks.

**Comment by dceejay** [comment]
Sorry - could you explain some more ? URL support to what ? which node is this relating to ?

**Comment by elyobelyob** [comment]
Apologies. To the prowl node.

**Comment by dceejay** [comment]
Hi - pushed an update that add the URL field either to the edit dialogue or you can set using msg.url

**Comment by elyobelyob** [comment]
Amazing, thanks.

On Sun, Jan 24, 2016 at 6:35 PM, Dave Conway-Jones <notifications@github.com

**Comment by elyobelyob** [comment]
Hi, I'm having some issues and receiving an error "null calls to Prowl api during current hour."

**Comment by elyobelyob** [comment]
[{"id":"373fe860.c8c018","type":"function","z":"7f199bed.80e664","name":"Set filename","func":"//msg.filename = \"/var/www/html/images/\"+Date.now()+\".jpg\";\nvar date = new Date();\nvar month = (date.getMonth()+1) > 9 ? (date.getMonth()+1) : \"0\" + (date.getMonth()+1);\nvar day = (date.getDate()+1) > 9 ? (date.getDate()+1) : \"0\" + (date.getDate()+1);\nvar hours = (date.getHours()) > 9 ? (date.getHours()) : \"0\" + (date.getHours());\nvar minutes = (date.getMinutes()) > 9 ? (date.getMinutes()) : \"0\" + (date.getMinutes());\nvar seconds = (date.getSeconds()) > 9 ? (date.getSeconds()) : \"0\" + (date.getSeconds());\n\nvar dateString = \n    date.getFullYear() +\n    month + \n    day + \"-\" +\n    hours + \n    minutes +\n    seconds;\nmsg.filename = \"/var/www/html/images/\"+dateString+\".jpg\";\nmsg.url = \"http://mydomain.com/images/\"+dateString+\".jpg\";\nreturn msg;","outputs":1,"noerr":0,"x":764,"y":963,"wires":[["ba67b1e.f45985"]]},{"id":"ba67b1e.f45985","type":"prowl","z":"7f199bed.80e664","title":"","priority":0,"url":"","name":"","x":939.5,"y":951,"wires":[]},{"id":"7487e263.8b781c","type":"inject","z":"7f199bed.80e664","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":568.5,"y":971,"wires":[["373fe860.c8c018"]]}]

**Comment by elyobelyob** [comment]
Hmm, that example works. But my main flow isn't. Strange. And if I move that prowl call from the example into the main flow, it stops. Hmm.
