### ISSUE TITLE
timeswitch only sends 0

### ISSUE THREAD

**Issue by gordonthree** [node-red/node-red-nodes#176]
Very simple flow, 1 timeswitch node, 1 debug node. Timeswitch ON set to dusk -90 min, OFF set to 23:00

Status says the switch is on, but all it's sending is 0. Click the manual trigger button, get a 0. 

Here's the export 
[{"id":"f83ca823.07c358","type":"timeswitch","z":"ea68222d.1597e","name":"","mytopic":"","lat":"44.26524","lon":"-86.30247","starttime":"6000","endtime":"1380","duskoff":"-90","dawnoff":"0","sun":true,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true,"x":200,"y":440,"wires":[["211eb4e1.dee14c"]]},{"id":"211eb4e1.dee14c","type":"debug","z":"ea68222d.1597e","name":"","active":true,"console":"false","complete":"false","x":450,"y":440,"wires":[]}]

**Comment by dceejay** [comment]
Thanks, 
I'll wait til dusk tonight and try it :-)
What does the node status say ? (under the node itself)  usually something like "off until..." - does that look right  or wrong also ?

**Comment by gordonthree** [comment]
The time status under the node reads correctly for on at dusk, etc

Just getting a payload: 0 regardless of on/off status.

**Comment by dceejay** [comment]
and your lat lon are approx correct ? - (It's going to be some fun timezone issue :-)

**Comment by dceejay** [comment]
ah - oops was a simple typo - fix being pushed

**Comment by gordonthree** [comment]
fantastic, thank you for the fast fix :)
