### ISSUE TITLE
timeswitch stays on past off time

### ISSUE THREAD

**Issue by gordonthree** [node-red/node-red-nodes#177]
Hi, sorry to bug again so soon.

I have a flow with two timeswitch nodes, one is set for ON at dawn at OFF at 09:00, the other is set for ON at dusk and off at 23:00.

When I deploy, current time is 19:14, both nodes turn ON

the raspberry pi has its timezone set correctly, but I believe the clock is set to GMT, although, it's not dawn yet in GMT, so the dawn node should still be off.... confirmed, it looks like node-red is using GMT and not local time. The two nodes status: Dawn reads "on until 9:00", Dusk reads "on until 23:00".

Tried this on two different pi, one running really old node (version 0.10 something), one running really new node (version 5 something?)

lat and lon are set for my approximate location

flow here: http://pastebin.com/DrkLN5j4

**Comment by dceejay** [comment]
OK, am offline for a few days so will look at next week.

**Comment by dceejay** [comment]
If you run in verbose mode (node-red -v) it should print out when it thinks dawn and dusk are, which may help. 
Just to confirm... The system time zone is set to the one appropriate for the lat lon ? Thanks

**Comment by gordonthree** [comment]
Strangely, leaving the node alone, once it passed midnight local time, it started working properly... the next morning it switched on at dawn and off at 9am just like programmed.

Closing this ticket, since I can't reproduce the problem now.

**Comment by dceejay** [comment]
OK- thanks - but obviously re-open if it plays up again :-)
