### ISSUE TITLE
node-red-node-discovery is crashing node-red

### ISSUE THREAD

**Issue by pastukhov** [node-red/node-red-nodes#178]
Hello!
I'm getting Uncaught Exception with node-red-node-discovery : 
```
20 Feb 15:39:35 - [info] Node-RED version: v0.13.2
20 Feb 15:39:35 - [info] Node.js  version: v4.3.1
20 Feb 15:39:35 - [info] Loading palette nodes
20 Feb 15:39:35 - [info] Dashboard up and running
20 Feb 15:39:36 - [warn] ------------------------------------------
20 Feb 15:39:36 - [warn] Failed to register 4 node types
20 Feb 15:39:36 - [warn] Run with -v for details
20 Feb 15:39:36 - [warn] ------------------------------------------
20 Feb 15:39:36 - [info] Settings file  : /home/artem/.node-red/settings.js
20 Feb 15:39:36 - [info] User directory : /home/artem/.node-red
20 Feb 15:39:36 - [info] Flows file : /home/artem/.node-red/flows_artem-desktop-bt.json
20 Feb 15:39:36 - [info] Server now running at http://127.0.0.1:1880/
20 Feb 15:39:36 - [info] Starting flows
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
20 Feb 15:39:36 - [info] You may ignore the warning about Bonjour compatability.
20 Feb 15:39:36 - [info] Started flows
20 Feb 15:39:41 - [red] Uncaught Exception:
20 Feb 15:39:41 - Error: dns service error: unknown
    at Error (native)
    at MDNSService.on_resolver_done (/home/artem/.node-red/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/artem/.node-red/node_modules/node-red-node-discovery/node_modules/mdns/lib/mdns_service.js:18:40)
```

**Comment by dceejay** [comment]
Hi, which platform/OS ? You have avahi installed OK ? And the extra prereq ? Thanks

**Comment by pastukhov** [comment]
Ubuntu 15.10. Yes i have avahi installed and it(avahi) is working well.

**Comment by dceejay** [comment]
Hi,
Any chance you can share (some of) your flow ? I have just installed 13.2 on node 4.3.1 and so far it's working for me. I am on LTS 14.04 and had upgraded Gcc to gcc5. But that would be obvious as the node would not install at all if it didn't compile.

**Comment by pastukhov** [comment]
Just discovery of _http._tcp and debug.

```[{"id":"e5c55e50.1a3aa","type":"discovery","z":"c77435c5.388bc8","name":"","topic":"","service":"_http._tcp","x":160,"y":80,"wires":[["d6fc2917.2903d8"]]},{"id":"d6fc2917.2903d8","type":"debug","z":"c77435c5.388bc8","name":"","active":true,"console":"false","complete":"false","x":330,"y":80,"wires":[]}]```

I think the problem is in my network or network settings of my PC.
I'll try to find he promblem today.

**Comment by pastukhov** [comment]
The problem is in node_mdns
Simple disovery of _http._tcp leads to the similar error
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/home/artem/.node-red/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/artem/.node-red/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/artem/.node-red/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)

```

**Comment by JonSilver** [comment]
I don't know whether it's of any help, but I had node-red crashing when using nodes that need root permissions in an instance of node-red running under an ordinary user.

**Comment by philbowles** [comment]
Has this been fixed? I'm getting exactly the same problem (red v0.16.2)

**Comment by knolleary** [comment]
What version of the node are you using?

**Comment by philbowles** [comment]
6.10.3 sorry, I should have realised that might have helped! I manually edited the flows file to remove the offending discovery node, as NODE-RED was in a "reboot" loop

**Comment by knolleary** [comment]
No, I meant what version of node-red-node-discovery are you using?

**Comment by philbowles** [comment]
Not sure of the easiest / recommended way to find that out, but it looks like 0.0.17 from the package.json file:

{
  "_args": [
    [
      {
        "raw": "node-red-node-discovery",
        "scope": null,
        "escapedName": "node-red-node-discovery",
        "name": "node-red-node-discovery",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "/home/pi"
    ]
  ],
  "_from": "node-red-node-discovery@latest",
  "_id": "node-red-node-discovery@0.0.17",
  "_inCache": true,
  "_location": "/node-red-node-discovery",
  "_nodeVersion": "6.10.2",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/node-red-node-discovery-0.0.17.tgz_1492025675743_0.7450060658156872"
  },
  "_npmUser": {
    "name": "dceejay",
    "email": "ceejay@vnet.ibm.com"
  },
  "_npmVersion": "3.10.10",
  "_phantomChildren": {},
  "_requested": {
    "raw": "node-red-node-discovery",
    "scope": null,
    "escapedName": "node-red-node-discovery",
    "name": "node-red-node-discovery",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/node-red-node-discovery/-/node-red-node-discovery-0.0.17.tgz",
  "_shasum": "e6541bf3b4c11d7cd8151b0247d50fc8202ebaa7",
  "_shrinkwrap": null,
  "_spec": "node-red-node-discovery",
  "_where": "/home/pi",
  "author": {
    "name": "Dave Conway-Jones",
    "email": "ceejay@vnet.ibm.com",
    "url": "http://nodered.org"
  },
  "dependencies": {
    "mdns": "~2.3.3"
  },
  "description": "A Node-RED node that uses Bonjour / Avahi to discover nearby services.",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "e6541bf3b4c11d7cd8151b0247d50fc8202ebaa7",
    "tarball": "https://registry.npmjs.org/node-red-node-discovery/-/node-red-node-discovery-0.0.17.tgz"
  },
  "keywords": [
    "node-red",
    "mdns",
    "avahi",
    "bonjour",
    "discovery"
  ],
  "license": "Apache-2.0",
  "maintainers": [
    {
      "name": "dceejay",
      "email": "ceejay@vnet.ibm.com"
    },
    {
      "name": "knolleary",
      "email": "nick.oleary@gmail.com"
    }
  ],
  "name": "node-red-node-discovery",
  "node-red": {
    "nodes": {
      "discovery": "mdns.js"
    }
  },
  "optionalDependencies": {},
  "readme": "node-red-node-discovery\n=======================\n\nA <a href=\"http://nodered.org\" target=\"_new\">Node-RED</a> node that uses Bonjour\n / Avahi to discover local network services such as iTunes libraries, printers, etc.\n\nNow also supports announcing new services.\n\nPrerequisites\n-------------\n\nplease read the [install instructions](https://www.npmjs.com/package/mdns) for the underlying npm.\n\nFor Debian / Ubuntu this requires installing\n\n        sudo apt-get install libavahi-compat-libdnssd-dev\n\nInstall\n-------\n\nRun the following command in your Node-RED user directory - typically `~/.node-red`\n\n        npm i node-red-node-discovery\n\nUsage\n-----\n\n### Discovery\n\nUses an implementation of mdns to provide a Bonjour / Avahi\nservice discovery capability.\n\n`msg.payload` contains the service object on both arrival and leaving.\n\n`msg.state` contains boolean true or false depending if the service has arrived (true) or gone away (false)..\n\nWithin the `msg.payload` object the most interesting things are:\n\n * msg.payload.name\n * msg.payload.interface\n * msg.payload.port\n * msg.payload.addresses\n * msg.payload.txtRecord\n\nFor a full list of official service types see [this list](http://www.dns-sd.org/ServiceTypes.html\" target=\"_new).\n\n### Announce\n\nProvides a Bonjour / Avahi / Zeroconf announcement node.\n\nIf `msg.payload` is 0 - the announcement is stopped. Any other value starts the announcement process.\n\nThe announcement can be customised by the msg if not configured in the edit panel.\n\n - `msg.service` - For a full list of official service types see <a href=\"http://www.dns-sd.org/ServiceTypes.html\" target=\"_new\">this list</a>.\n - `msg.port` - the tcp or udp port to use.\n - `msg.name` - the short description name of the service. If you use %h in the name, it will be replaced by the machine hostname.\n - `msg.txtRecord` - a set of comma separated name:value pairs\n\n### Note:\n\nWhen Node-RED starts you will get a big WARNING message about the Bonjour Compatibility layer... this is just a warning so don't worry.\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "https://github.com/node-red/node-red-nodes/tree/master/io/mdns"
  },
  "scripts": {},
  "version": "0.0.17"
}

**Comment by dceejay** [comment]
What error do you actually get - as usual it's working fine for me on Ubuntu 16.04.2 LTS... and Raspberry Pi3 on latest Raspbian

**Comment by philbowles** [comment]
31 May 11:41:34 - [red] Uncaught Exception:
31 May 11:41:34 - Error: dns service error: unknown
at Error (native)
at MDNSService.on_resolver_done (/usr/lib/node_modules/node-red-node-discovery/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
at SocketWatcher.MDNSService.self.watcher.callback (/usr/lib/node_modules/node-red-node-discovery/node_modules/mdns/lib/mdns_service.js:18:40)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.

**Comment by philbowles** [comment]
FYI: It's a raspberry 3 - Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

**Comment by philbowles** [comment]
From my "main" PC:
C:\Users\phil>ping raspberrypi.local

Pinging raspberrypi.local [192.168.1.4] with 32 bytes of data:
Reply from 192.168.1.4: bytes=32 time=6ms TTL=64
Reply from 192.168.1.4: bytes=32 time=45ms TTL=64
Reply from 192.168.1.4: bytes=32 time=6ms TTL=64
Reply from 192.168.1.4: bytes=32 time=24ms TTL=64

on pi:

pi@raspberrypi:~ $ ping raspberrypi.local
PING raspberrypi.local (192.168.1.4) 56(84) bytes of data.
64 bytes from 192.168.1.4: icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from 192.168.1.4: icmp_seq=2 ttl=64 time=0.082 ms

I'm also getting a fair amount of service txt and other info from the pi from my ESP8266 ioT things...i,e, I have a discovery announce node that sets: a service "_toiiot._tcp" with TXTs
["basename":"lapique","version":"1.1","brokerIP":"192.168.1.4","brokerport":1883"

Those details get read back when any of my remote devices reboot, e.g from a very recent (5 mins ago) debug log:
```
Listen for OTA updates on port 8266
Listening for HTTP on port 80
Promote to Layer 1
L2elevate: attempting MQTT reconnect
setupL2
**lapique(v1.01) ToiioT Controller found on raspberrypi (192.168.1.4:1880)
192.168.1.4
1883**
Promote to Layer 2
trucPublish: data payload={"B":"ESP8266_WEMOS_D1MINI","I": "BC939","F":"4M","A":"192.168.1.54","V":"4.0.2"}
trucPublish: lieu payload={"Z":"Middle Earth","P":"Test Bench","R":"0"}
trucPublish: provides payload=["Switch"]
```

The part between the asterisks is retrieved from mDNS data set up by the pi, and has been working for ages.

WHen I put in the "discover" for the service + txt that each of my devices also adds about itself, the NODE-RED debug log shows that the results actually DO get retrieved,,,but then it chokes.

Could it be something to do with the non-standard services / txt records I'm adding / retrieveing? I'm using Arduino <ESP8266mDNS.h> and:

```
  MDNS.addService("truc","tcp",WEB_PORT);
  MDNS.addServiceTxt("truc","tcp","board",ARDUINO_BOARD);   
  MDNS.addServiceTxt("truc","tcp","firmware",VERSION);
  MDNS.addServiceTxt("truc","tcp","zone",zone);
  MDNS.addServiceTxt("truc","tcp","funtion",purpose);
  MDNS.addServiceTxt("truc","tcp","restart",String(restart));    
```
Confirmation from "Bonjour Browser" runiing on Windows v7
![capture](https://cloud.githubusercontent.com/assets/27769598/26628286/c4340d14-45fd-11e7-881d-782f5ab53273.PNG)

**Comment by dceejay** [comment]
Ah - indeed could well be... the dns on_resolver_done is choking on something - seems to be getting an errorCode it doesn't know about or handle correctly.

I think  you're going to have to dig into that packages code to try and debug what's going on... I'd start in the two files mentioned in the error report.

It may also be helpful to add the following to this modules code - between line 37 and 38 of our mdns.js file add the following... (It may not help - but may catch the error rather than crash...)

        browser.on('error', function(exception) {
            node.error(exception.toString(),msg);
        });

**Comment by philbowles** [comment]
Ok thanks dcj - I will give that a try and report back. Might help me clean up my code and post some proper values too! Win-Win.

**Comment by philbowles** [comment]
Lucky I spotted the little curve-ball..." ReferenceError: msg is not defined" so I took out the ',msg' and now we get: 
```
31 May 18:10:30 - [error] [discovery:_truc._tcp] Error: dns service error: unknown
```
Which I guess doesn't adavance the cause much, but at least it's out of the reboot loop...I'm very new at node.js and node.js and I fear I'm nowhere near enough of a linux hacker to dig much deeper I'm afraid...

**Comment by dceejay** [comment]
ah - that's def better (and yes remove the ,msg - my mistake.) seems it doesn't like whatever that service is...  not sure why. It should still be able to report it's existence I would have thought...
let me have a look later.

**Comment by philbowles** [comment]
I found the code in mdns.cpp where it would be nice to see the actual value of "error_code" but I just don't have the skill / knowledge to edit and recompile it.
```
Local<Value>
buildException(DNSServiceErrorType error_code) {
    if (error_code == kDNSServiceErr_NoError) {
        return Nan::Undefined();
    }

    std::string error_str("dns service error: ");
    error_str += errorString(error_code);
    Local<String> error_msg = Nan::New(error_str.c_str()).ToLocalChecked();
    Local<Value> error_v = Exception::Error(error_msg);
    Local<Object> error = error_v->ToObject();
    Nan::Set(error, Nan::New("errorCode").ToLocalChecked(), Nan::New<Integer>(error_code));
    return error_v;
}
```

But I do have another theory...one which will require a full shutdown / restart to "flush" the mdns cache...

**Comment by philbowles** [comment]
Progress: It's something to do with mDNS cache corruption (or similar). I'm in an edit-recompile-test loop and tools such as bonjour browser show that there are sometimes several entires for the board I'm testing...It looks like it's the "fragments" of earlier tests in mDNS that are causing the problem. I say that because I changed the name of my service to something completely new that I'd never used before ("wibble" if you really want to know - don't ask) and lo and behold, everything worked perfectly - even my own code (now THERE's a rarity)

So all I need to know now is an easy way forcing mDNS to clean itself up, because the shutdown / reboot didn't seem to. Maybe some other devices were "holding on" to some state which re-polluted my two restarted machines? Any advice?

**Comment by dceejay** [comment]
well done - I think .... so net is it's now working ?
I'm not sure how to flush the cache - if indeed there even is one... - I'm surprised reboot didn't wipe it, unless indeed it was some device still sending duff data.

PS - don't worry - "It's an old trick I picked up in the Sudan!"

**Comment by philbowles** [comment]
Yeah, I'm past the point where I'm fiddling with mDNS code, so with the new service name, all is sweet - and, for the record - I LOVE node-red, I'm a true convert! It forms the beating heart of my all-singing-all-dancing home automation project. The code that talks to it is home-made replacement firmware for SONOFF devices (and my own homebrew) and the NODE-RED "wires" them all together. The hitherto problematic part is to populate a listbox so I can see easily what's online / active. Soon I will be able to move my drinks cabinet closer to Berlin, but via WiFi...Thanks for all the help etc. I do have one small request though - any chance that the discover node could be modified to fire on message receipt trigger or a periodic timer rather than just once at boot? Pretty please...

Phil

**Comment by dceejay** [comment]
hmm - not sure it makes sense as the whole point of bonjour/avahi is that it reports any changes as it sees them rather than having to poll. You could use a function to catch the initial messages and save them in an array in either the flow or global context - then update the array on any changes.

**Comment by philbowles** [comment]
I do indeed save them in a global. My problem is that the raspberry will be runing 24/7 and my devices coming and going at will - I'd need some kind of notification to keep the list updated...It may have been days since last boot and although Bonjour may well be up-to-date, my NODE-RED UI listbox won't be
