### ISSUE TITLE
Document the protocol for email output

### ISSUE THREAD

**Issue by nkolban** [node-red/node-red-nodes#180]
I was attempting to use the email output node today to my own Mail server but then realized two things:

1. I wasn't 100% sure of the protocol being used but assumed it is SMTP.
2. It isn't clear to me whether the protocol being used is SSL or simple TCP.
3. It isn't clear whether or not SSL can be enabled/disabled.

I believe that these can be addressed by documentation tinkering.

**Comment by dceejay** [comment]
Hi,
yes it's SMTP (out) and IMAP (in),
Both expect SSL
and no (currently) - is allowing non secure even sensible these days ?

and yes. Will add words to clarify.

**Comment by dceejay** [comment]
closed by 734fbe2adb6870f68e09b39a3e6f001923f98add
