### ISSUE TITLE
Firmata string support

### ISSUE THREAD

**Issue by jpmanson** [node-red/node-red-nodes#181]
I've added send and receive string support using Firmata with module node-red-node-arduino 
If interested, you can found it here:
https://github.com/jpmanson/node-red-node-arduino

**Comment by hardillb** [comment]
To contribute code please check the contribution guide (https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) and submit a CLA and then raise a pull request so we can examine the changes.

**Comment by dceejay** [comment]
please do :-) looks useful.

**Comment by jpmanson** [comment]
I've just sent the CLA...Could be polished, but it works. The feature is useful to string send/receive commands to/from Arduino, for example "START_ENGINE" or "SPEED=54", etc.

**Comment by dceejay** [comment]
what are lines 168-170 doing ? (in the .js file) ... description is not set anywhere...

**Comment by dceejay** [comment]
cla arrived ok - feel free to raise a pr (and polish it up first ;-)

**Comment by jpmanson** [comment]
These lines can be replaced:
                        var input = msg.payload;
                        if (typeof description != 'string') {
                            input = input.toString();
                        }
						
With this:
                        var bytes = new Buffer(msg.payload.toString(), "utf8");

The previous check was because if msg.payload contains a number the Buffer constructor throws an error. Forcing it with toString() solves the problem. I will replace it now and then I'll raise the PR

**Comment by dceejay** [comment]
closed by PR and dc3b220ec4032fe5966bb70026a9fa3463b01afd
