### ISSUE TITLE
sense-hat 0.8 seems to break node-red on Pi zero

### ISSUE THREAD

**Issue by broo0ose** [node-red/node-red-nodes#186]
Hi, 

every time I install the sense-hat node it fails to do anything and then node-red refuses to deploy. 
node-red also then refuses to quit with Ctrl-C on the console. 

It was working OK on earlier versions like 0.6, and the sensehat python examples work fine. 

for the record.. 
    Node-RED version: v0.13.3
    Node.js  version: v0.10.29
    Linux 4.1.18+ arm LE

thanks

Bruce

**Comment by knolleary** [comment]
Hi, that's for raising. Not tested it on a PiZero yet (and mine is in the office, so can't quickly test it right now).

There's one quick test you could do that would help; in the sensehat node install directory (guessing `/home/pi/.node-red/node_modules/node-red-node-pi-sense-hat`), can you try running: `python sensehat.py` in a terminal window. If it starts without error, then type `Y1` into the terminal window. This should turn on reporting of the environment data once a second. Hit `ctrl-c` to quit.

If there are any error messages, please share here. Other wise, I'll get the PiZero running tomorrow so I can check it here.

**Comment by broo0ose** [comment]
it works but it is very irregular, not 1 a second.

**Comment by knolleary** [comment]
Ok... you say it all worked ok with 0.6 - could you give 0.7 a go?

**Comment by broo0ose** [comment]
please excuse my ignorance. How do I install older versions.

**Comment by knolleary** [comment]
Ah, no excusing needed - my apologies for assuming you'd know. You can install specific versions using:

    npm install node-red-node-pi-sense-hat@0.0.7

It may be worth testing with 0.0.6 again as well, just to make sure it was the upgrade that broke things.

**Comment by broo0ose** [comment]
ok. it stays broken all the way back to 0.0.5 so I'm going to wipe the SD and start again. 
I'll let you know what happens, thanks for your help.

**Comment by broo0ose** [comment]
OK, it's all working now. I think it must have been some code that was in the window causing a problem each time. I had used 'while' instead of 'if' to test for the joystick state and it was enough to kill node-red.  

Thanks for your help, sorry for the false alarm.
