### ISSUE TITLE
No option to specify EU cluster

### ISSUE THREAD

**Issue by Mastergalen** [node-red/node-red-nodes#189]
There's no option to specify the cluster, meaning that at the moment you have to use the default cluster located in the US.

**Comment by knolleary** [comment]
Hi, this repository contains many nodes. Which node specifically are you raising this issue against?

**Comment by Mastergalen** [comment]
Oops, I did not realise that sorry.

It's the Pusher node: https://github.com/node-red/node-red-nodes/tree/master/social/pusher

**Comment by andersea** [comment]
Commit 2413738 fixes this.
