### ISSUE TITLE
unexpected result with rbe node

### ISSUE THREAD

**Issue by greyltc** [node-red/node-red-nodes#192]
I'm using v0.13.3 and I have a rbe (report by exception) node configured as `block if value changes by more than` `500` with the Start Value set to be `9999`.

If I send a msg.payload of 14 twice consecutively to my rbe node, I expect the first message to be dropped (since abs(9999 - 14)>500) and the second message to make it through (since abs(14-14)<500), but instead they both get dropped.

Is this a bug or is this intended behavior?

**Comment by dceejay** [comment]
same reply as before...

good question... the current behaviour is that if a value is outside the desired range it is ignored (and thus doesn't count towards the next comparison)... so the second comparison in your example is still abs(9999 -14) > 500 - so also gets ignored...
