### ISSUE TITLE
Serialport: Support more baudrates

### ISSUE THREAD

**Issue by mschm** [node-red/node-red-nodes#194]
When using the serialport node, one is bound to the most commonly supported baudrates, which are no more than 115200 bit/s. It would be nice, if higher baudrates could be selected (specifically 128000 and 256000) or if one may define any custom baudrate. As far as I can see, the limitation currently comes from the config dialog, not from the underlying serial communication module.

**Comment by dceejay** [comment]
Any particular reason why those two ? The underlying hardware has to support them of course...

**Comment by mschm** [comment]
The two mentioned baud rates came from certain devices I was dealing with. Would not consider them standard values, though saw them mentioned as standard baud rates supported by __some__ serial ports in this document: http://digital.ni.com/public.nsf/allkb/D37754FFA24F7C3F86256706005B9BE7
along with some other rates: 128000, 153600, 230400, 256000, 460800, 921600

Still, some devices may require very different rates – so I think that users should actually be able to specify them more freely. So instead of extending the standard values I'd rather propose a __custom__ option in the selection view that shows an additional text input field (along with a disclaimer saying that underlying hardware must support this?)

**Comment by philippe-gregoire** [comment]
Ah,and there's the ESP8266 boot flash rate of 76800...

**Comment by dceejay** [comment]
If you are re-flashing the ESP using Node-RED then we want to see a blog post about it !

Ok - just pushing a fix to accept "other" rates - you will need Node-RED 0.13.x to use it.

**Comment by philippe-gregoire** [comment]
Ah, well, nothing's impossible ;-)....

**Comment by mschm** [comment]
Cheers @dceejay thanks for the update :)
