### ISSUE TITLE
Sensortag Node - reconnect issue

### ISSUE THREAD

**Issue by jwende** [node-red/node-red-nodes#196]
I'm using the sensortag node on RPI3. 
NodeRed runs under sudo. It connects fine to my sesortag and all events are discovered. If I remove the battery from the sensortag and re-insert it again the tag won't reconnect.
If I stop NR it reports:
> 1 Apr 09:49:09 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
> 1 Apr 09:49:09 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069                                                                                                             a01
> 1 Apr 09:51:21 - [info] [sensorTag:sensorTag] disconnected
> ^C1 Apr 09:51:31 - [info] Stopping flows
> 1 Apr 09:51:31 - [error] [sensorTag:sensorTag] TypeError: value is out of bounds

any thoughts ?
Thanks

**Comment by hardillb** [comment]
Which version of the SensorTag do you have and are you running the standard firmware?

The first version of the tag would automatically disconnect after a certain time with the default firmware and power off. The only way to get it to reconnect was to push the button on the side to put it in discoverable mode again.

There are versions of the firmware that do not power off out there I'm told but I've never tried one

**Comment by dceejay** [comment]
I think it's more that the node doesn't go back to discovering... - attempted fix on the way...

**Comment by jwende** [comment]
It is a Sensortag V2 and it is running firmware V2. It does not disconnect automatically - so I have to press the two buttons at the same time. NR disconnects now - but it does not discover the tag again (restart required)

**Comment by jwende** [comment]
great !

**Comment by jwende** [comment]
connect/disconnect/connect works!
great - thank you

1 Apr 15:11:33 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:11:33 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:12:00 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:12:03 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:12:03 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01

**Comment by jwende** [comment]
Minor issue: log shows an increasing number of disconnect messages, I think it might be cleanup issue somewhere 

1 Apr 15:11:33 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:11:33 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:12:00 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:12:03 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:12:03 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:13:07 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:13:07 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:13:18 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:13:19 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:15:11 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:11 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:11 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:18 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:15:19 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:15:28 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:28 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:28 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:28 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:15:33 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:15:34 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01
1 Apr 15:16:50 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:16:50 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:16:50 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:16:50 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:16:50 - [info] [sensorTag:sensorTag] disconnected
1 Apr 15:17:03 - [info] [sensorTag:sensorTag] found sensor tag: 68c90b069a01
1 Apr 15:17:04 - [info] [sensorTag:sensorTag] connected to sensor tag: 68c90b069a01

**Comment by dceejay** [comment]
Don't keep disconnecting then ;-)

yeah - ok - was afraid that may happen :-(
