### ISSUE TITLE
BBB-hardware - bbb-pulse-out crashes node-RED when a USR LED pin is allocated

### ISSUE THREAD

**Issue by maxwellhadley** [node-red/node-red-nodes#198]
If a bbb-pulse-out node is deployed with one of the USR LED pins allocated to it, node-RED crashes when the flow is deployed.

`5 Apr 20:37:26 - TypeError: Cannot read property 'value' of null
  at /usr/lib/node_modules/node-red-node-beaglebone/145-BBB-hardware.js:498:33
  at onSetLEDPin (/usr/lib/node_modules/node-red-node-beaglebone/node_modules/octalbonescript/index.js:218:48)
  at onWriteMode (/usr/lib/node_modules/node-red-node-beaglebone/node_modules/octalbonescript/lib/digital.js:86:51)
  at /usr/lib/node_modules/node-red/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:95:15)
`

The crash is caused because the parameters passed to the callback by the bonescript.pinMode() function of Octalbonescript were changed at version 1.0.0:

> All callbacks now have callback(err, resp) format. The previous format was callback(resp). This is major BC break. refer WIKI for more info.

At line 498 of 145-BBB-hardware.js, the first parameter is being dereferenced when, if the call succeeded, it will be null. The test here should probably be something like `if (response === null)` to test for success. The corresponding code in bbb-discrete-out (line 418) looks OK, but all callback parameters in the code probably should be checked for similar issues.

**Comment by dceejay** [comment]
@maxwellhadley thanks for spotting.. Hopefully got them all now.
