### ISSUE TITLE
Daemon: line split on random positions

### ISSUE THREAD

**Issue by ukasiu** [node-red/node-red-nodes#202]
When listening to rtl_433 output I get json messages randomly split into pieces. Shouldn't this module use https://github.com/jahewson/node-byline instead?
![screenshot at 01-25-06](https://cloud.githubusercontent.com/assets/816363/14584208/432a8284-043b-11e6-8f45-9c4fad590525.png)

**Comment by dceejay** [comment]
The node delivers whatever turns up in it's buffer on stdin - either as a raw buffer, or string or number. How do we know that the input may contain \n characters ?  or \r\n ? or \r ?

**Comment by ukasiu** [comment]
Afaik it's a standard behavior of `gets` function in many programming
languages. For me it seems quite unusable when I get buffer scattered
randomly.

**Comment by knolleary** [comment]
@dceejay seems quite reasonable to have a mode, like on serial, that will buffer and split the output more intuitively.

**Comment by dceejay** [comment]
Yeah, I'm not saying no - just need to work what the actual mode should be... ie - should this be the behaviour of the existing strings out mode ? Or a new buffer until... mode - and should it be any char or just \n.
And indeed should this buffering up capability be part of the join node ?

**Comment by knolleary** [comment]
@dceejay we've already solved this for the TCP In node and the Serial node... it doesn't need rethinking from scratch.

**Comment by dceejay** [comment]
Hi @ukasiu 
I have added a line out mode to version 0.0.5. It buffers up and outputs whenever it receives a \n char.

**Comment by ukasiu** [comment]
@dceejay thanks :)
