### ISSUE TITLE
node-red-node-email ignores bcc field. 

### ISSUE THREAD

**Issue by gugurete** [node-red/node-red-nodes#209]
node-red-node-email ignores bcc field. 
i would suggest this change in 61-email.js

                    var sendopts = {};   // sender address
                    sendopts.from = msg.from || node.userid;
                    sendopts.to = node.name || msg.to; // comma separated list of addressees
                    sendopts.cc = msg.cc;
                    sendopts.bcc = msg.bcc;
                    sendopts.subject = msg.topic || msg.title || "Message from Node-RED"; // subject line

tried a pull request but i do not have permissions to the node-red-nodes.git

**Comment by dceejay** [comment]
Hi,

good suggestion... I will make one slight change... if the "to" name is specified in the edit dialogue (node.name) then it will ignore msg.cc and msg.bcc - ie if the user is specifying a fixed address we don't want other parameters to get set behind their back.
