### ISSUE TITLE
Sense Hat Node

### ISSUE THREAD

**Issue by vikas1369** [node-red/node-red-nodes#220]
In the description of node-red-node-pi-sense-hat-simulator on https://www.npmjs.com/package/node-red-node-pi-sense-hat-simulator

It says "This allows you to create flows that interact with a virtual Sense HAT without the actual hardware - whether you're running on a Raspberry Pi, a laptop or elsewhere.".

I have installed Node-Red on my ubuntu 14.04 system and am able to run node-red successfully on the localhost.

But when I install the sense-hat simulator node It doesn't show up. And in the list of installed nodes it shows as the extraneous node.

According to the description we can have this node whether on raspberry pi or laptop or elsewhere then why this node doesn't show up?

Thanks

**Comment by hardillb** [comment]
Please describe how you installed the node, especially which directory you were in when you ran the npm command.

Also it would be useful to see the output from Node-RED when it's starts

**Comment by vikas1369** [comment]
I followed following steps

1. $sudo apt-get install nodejs
2. $sudo apt-get install npm
3. $sudo ln -s /usr/bin/nodejs /usr/bin/node
4. $mkdir node-red
5. $cd node-red
6. $sudo npm install -g node-red
7. $node-red

![screenshot from 2016-07-07 17 42 56](https://cloud.githubusercontent.com/assets/15198006/16652801/9e04aa94-446a-11e6-9efe-0a4eaca0dd80.png)
![screenshot](https://cloud.githubusercontent.com/assets/15198006/16652802/9e0692b4-446a-11e6-86ec-0ce5a1ea48b3.png)

**Comment by knolleary** [comment]
You should install additional nodes in:

    /home/suraj/.node-red

not `/home/suraj/node-red` as you have done.

**Comment by vikas1369** [comment]
Thanks @knolleary. I corrected it.Now it's working perfectly as required.
