### ISSUE TITLE
MongoDB node connection problem

### ISSUE THREAD

**Issue by thegunshow** [node-red/node-red-nodes#221]
Hi

I see that if the MongoDB service/server is not running when you deploy the node-red application, the node never connects again. If the server is running when you deploy node-red and the connection fails, the node is able to recover when the connection is restored. It does this consistantly.

Do you have a work around for this?

Node-RED v0.14.4
Node.JS v4.4.7

Thanks

**Comment by dceejay** [comment]
Hi,
pushed a fix to auto retry the initial connection every 10 secs.
