### ISSUE TITLE
node-red-node-sensortag

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#225]
I'm seeing a lot of values like this
{ "temperature": -40, "humidity": 100 }
from the temperature/humidity sensor.

In the TI app on my phone, the humidity spikes to 119%, but then settles down to sensible (around 65%) values.
I wonder if there's a bit of magic needed to interpret the humidity values differently, or fix an over-range problem... or something?

I notice that the values (-40 and 100) are not to 1 decimal place, so suspect they're possibly "out of range" values, rather than values returned by the tag?

**Comment by dceejay** [comment]
of course technically humidity can go >100% ... but get your point ;-)

**Comment by andysc** [comment]
I'm not sure that's going to fix it - I was seeing vast streams of -40/100 values, with almost no proper values in there, so that would mean no data coming out from the node.
I was seeing far more valid data points coming out when I was paired with my phone and using the TI app.

**Comment by dceejay** [comment]
well it would mean less bad data coming out ... 
no idea re extra params - I think we just report what we see but I'll check with @hardillb 
Have you changed batteries recently ?

**Comment by andysc** [comment]
yes, new battery on monday. It gives a greater quantity of valid data when paired with the TI app on my phone (this is just the temp/hum sensor I'm talking about here... lux sensor works great (for example))

**Comment by dceejay** [comment]
we just use the underlying sensortag js library so without digging into it there's not much we can do.  No idea why your's is weird - I've never seen that with mine.

**Comment by andysc** [comment]
OK... thanks for looking into it... maybe it needs another new battery ;)
