### ISSUE TITLE
[warn] [serialport] Error: Module did not self-register.

### ISSUE THREAD

**Issue by AnduriI** [node-red/node-red-nodes#226]
Hey there,

I have a problem installing serialport. From first start of node-red I get the message that node-red-serialport did not self-register and no serialport node is available in node-red. When starting with command ```node-red```in terminal of my rpi3 I see the following:
```
Welcome to Node-RED
===================

10 Aug 19:20:49 - [info] Node-RED version: v0.14.6
10 Aug 19:20:49 - [info] Node.js  version: v4.4.5
10 Aug 19:20:49 - [info] Linux 4.1.19-v7+ arm LE
10 Aug 19:20:49 - [info] Loading palette nodes
10 Aug 19:20:53 - [warn] ------------------------------------------------------
10 Aug 19:20:53 - [warn] [serialport] Error: Module did not self-register.
10 Aug 19:20:53 - [warn] ------------------------------------------------------
10 Aug 19:20:53 - [info] Settings file  : /home/pi/.node-red/settings.js
10 Aug 19:20:53 - [info] User directory : /home/pi/.node-red
10 Aug 19:20:53 - [info] Flows file     : /home/pi/.node-red/flows_octopi.json
10 Aug 19:20:53 - [info] Creating new flow file
10 Aug 19:20:54 - [info] Starting flows
10 Aug 19:20:54 - [info] Started flows
10 Aug 19:20:54 - [info] Server now running at http://127.0.0.1:1880/
```

To solve it I tried to install different versions of node-red-serialport, namely 0.3.0, 0.2.1, 0.2.0 and 0.1.2.
I also installed gcc6 following these instructions: https://solarianprogrammer.com/2016/06/24/raspberry-pi-raspbian-install-gcc-compile-cpp-14-and-cpp-17-programs/ (without fortran compiler) and installed node-gyp. All without success.

Are there any tips on what to do to make it work?

**Comment by dceejay** [comment]
Hi,
generally this is a problem due to upgrades and having multiple copies around.
You will need to try and dig out all the "old" versions...  places to look are
  ~/.node-red/node_modules
  /usr/lib/node_modules/
then make sure to flush the npm cache
  npm cache clean
  sudo npm cache clean
then
  cd /usr/lib/node_modules/node-red
  sudo npm i --unsafe-perm node-red-node-serialport

**Comment by AnduriI** [comment]
Hi dceejay,

thanks for your hint. I tried this on a fresh image of jessie with only few things installed. But anyway, I will try your solution and report back.

**Comment by dceejay** [comment]
Hi - if it was a fresh install then serialport should already be installed and working. (from the apt-repository) - from a clean Jessie install just do a 
   sudo apt-get install nodered
If you want to upgrade to latest node.js use the built in command 
  update-nodejs-and-nodered

see http://nodered.org/docs/hardware/raspberrypi#manual-install

**Comment by AnduriI** [comment]
yeah I did a fresh install and installed nodered the way you said. When starting I got the error of serialport not self-registering

**Comment by dceejay** [comment]
well you must have upgraded at some point as the log says you have node v4.4.5 which is not the default 0.10.29 that comes with Jessie - so I suspect one of the commands was wrong.
when you installed the serialport did you use --unsafe-perm ?

**Comment by AnduriI** [comment]
yeah I also installed pimatic, which needs an upgrade of node to v4.4.5.
when installing nodered one day later I had this problem and tried different versions of serialport, but without the option --unsafe-perm. Will try all you wrote and report back.

**Comment by dceejay** [comment]
ah... so if you had the option... I'd start over from clean.. run sudo apt-get update && sudo apt-get upgrade - then  update-nodejs-and-nodered  - then re-install pimatic...

**Comment by AnduriI** [comment]
hey there,
I didn't found a way to make it work. So I started over and reinstalled a fresh image. One last question: where to issue the ```update-nodejs-and-nodered```? I tried it the ```~/.node-red/ and searched for that script, but couldn't find anything. Would be realy nice if you can help.

**Comment by dceejay** [comment]
Hi,
you should have Node-RED v0.14.6
if you run node-red you should see it print out the version in the first few lines of console.
If not 0.14.6 then run    sudo apt-get update && sudo apt-get install nodered
once that has run you should have the update script 
it should run from anywhere - but is is located in /usr/bin/update-nodejs-and-nodered

**Comment by AnduriI** [comment]
thanks a lot for your help, I was still doing the apt-get in another shell and searched for the update script. After completion I found it and succesfully upgraded. Now it's running fine.
