### ISSUE TITLE
Preventing feedparser from re-parsing items on new deploy?

### ISSUE THREAD

**Issue by khromov** [node-red/node-red-nodes#227]
I'm trying to send RSS items to a Wunderlist task list. This works fine but every time you re-deploy a bunch of duplicate tasks are created because the feedparsers sends all the items in the feed on each deploy.

Is there any way to mark an item as "sent" and then not re-send it on every new deploy? Would that require using a database to save the state of sent items?

**Comment by hardillb** [comment]
Questions like this should be asked on the mailing [list](https://groups.google.com/forum/#!forum/node-red) as we keep issues for actual defects

**Comment by dceejay** [comment]
Hi 
This is not really any different to a web browser. It will refetch the complete list also. So yes if you need to de-duplicate then you will need to do that as an extra step.
