### ISSUE TITLE
mongodb node issues warning on node-red startup

### ISSUE THREAD

**Issue by mblackstock** [node-red/node-red-nodes#228]
Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } js-bson: Failed to load c++ bson extension, using pure JS version

Fix: update mongodb to 2.2.5

**Comment by dceejay** [comment]
Mike - have you tested this fix ?

**Comment by mblackstock** [comment]
One of my guys @jmikerq tested it.  Just the package bump, and he tried inserting data and queries.
