### ISSUE TITLE
Make the search parameter dynamic.

### ISSUE THREAD

**Issue by pahoran** [node-red/node-red-nodes#231]
Others have asked for the authentication parameters to be dynamic - and we agree.  We'd also like to change the search parameter dynamically, but there's no facility in this node to accept user input and alter it.  Any suggestions for implementing this in the current version of this node?

I suppose we could use a standard HTTP Request and call the Twitter API 'manually'.

**Comment by knolleary** [comment]
Hi,
yes, this has come up a few times recently, both on the mailing list and feedback we've had. It is already on our to do list. Right now, the alternative would be to access the api directly.

For feature requests in general, please use the mailing-list in the first instance.

Nick

**Comment by dceejay** [comment]
Added capability to change search dynamically (but you still need to be aware of rate limits)  b0c93e44b84c54e81763ebe18846d0ba7528f764
