### ISSUE TITLE
Any Successful SensorTag Installation on Raspberry Pi?

### ISSUE THREAD

**Issue by rei-vilo** [node-red/node-red-nodes#234]
Installation goes fine (BlueZ `5.23`, node `0.12.0`, npm `2.15.11`, node-red-node-sensortag `0.0.16`) and the Raspberry Pi Zero + RedBear IoT pHAT connects to the SensorTag CC2650, but the SensorTag node doesn't show up on the Node-RED GUI.

Any pointer about where to look at?

**Comment by hardillb** [comment]
Have you installed the pre-reqs and set the flags to allow you to run as a none root user described in the readme?

**Comment by rei-vilo** [comment]
Yes, I proceed at per this [procedure](https://www.npmjs.com/package/node-red-node-sensortag#raspberry-pi).

**Comment by hardillb** [comment]
Anything in the Node-RED log output at startup?

**Comment by rei-vilo** [comment]
I've performed a complete reinstall of [node](http://conoroneill.net/download-compiled-version-of-nodejs-0120-stable-for-raspberry-pi-here/), [node-red and npm](http://nodered.org/docs/hardware/raspberrypi), [node-red-node-sensortag](https://www.npmjs.com/package/node-red-node-sensortag).

The SensorTag node now appears on the Node-RED GUI, but BLE no longer connects to the SensorTag.

>
$ node-red-start
>
Start Node-RED
>
Once Node-RED has started, point a browser at http://192.168.1.13:1880
On Pi Node-RED works better with the Firefox browser
> 
Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot
> 
To find more nodes and example flows - go to http://flows.nodered.org
You may also need to install and upgrade npm
      sudo apt-get install npm
      sudo npm i -g npm@2.x
> 
Started Node-RED graphical event wiring tool..
Welcome to Node-RED
===================
20 Sep 19:50:53 - [info] Node-RED version: v0.14.6
20 Sep 19:50:53 - [info] Node.js  version: v0.12.0
20 Sep 19:50:53 - [info] Linux 4.4.20+ arm LE
20 Sep 19:50:53 - [info] Loading palette nodes
pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py info
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
20 Sep 19:51:21 - [warn] ------------------------------------------------------
20 Sep 19:51:21 - [warn] [serialport] Error: Module did not self-register.
20 Sep 19:51:21 - [warn] [sensehat] Error: Can't find Sense HAT python libraries. Run sudo apt-get install sense-hat
20 Sep 19:51:21 - [warn] ------------------------------------------------------
20 Sep 19:51:21 - [info] Settings file  : /home/pi/.node-red/settings.js
20 Sep 19:51:21 - [info] User directory : /home/pi/.node-red
20 Sep 19:51:21 - [info] Flows file     : /home/pi/.node-red/flows_myPiZero.json
20 Sep 19:51:21 - [info] Server now running at http://127.0.0.1:1880/
20 Sep 19:51:21 - [info] Starting flows
20 Sep 19:51:21 - [info] Started flows
>

**Comment by rei-vilo** [comment]
`node-red` doesn't show the SensorTag node but `node-red-start` does.

Now, I get

>
noble warning: unknown handle 64 disconnected!
noble: unknown peripheral b0b448edb484 connected!
>

but the SensorTag node remains `discovering`, even when I enter the UUID.

<img width="383" alt="capture 2016-09-20 a 20 10 11" src="https://cloud.githubusercontent.com/assets/951776/18682945/82399998-7f6e-11e6-903c-3f7cb419e1c7.png">

**Comment by aleonnet** [comment]
Hi @dceejay I have installed it and it's showing 'connected'... but that the complete msg object shows nothing (no payload). Am I doing something wrong?

2 Dec 00:07:38 - [info] [sensorTag:fabf0c2.b1231f] found sensor tag: 247189bc1084
2 Dec 00:07:38 - [info] [sensorTag:fabf0c2.b1231f] connected to sensor tag: 247189bc1084
noble: unknown peripheral 247189bc1084 connected!

Thanks

**Comment by resolver101757** [comment]
Im also getting the same symptoms : the SensorTag node remains > discovering

Any help appreciated.  I've tried re-install node-red, bluetooth and the SensorTag node.  Still not working.

**Comment by rei-vilo** [comment]
When using Bluetooth, a conflict may occur. Two applications try to connect to the same BLE device.

In a separate connection, disconnect the SensorTag with `bluetoothctl`.

```
$ 
bluetoothctl
[NEW] Controller 11:22:33:44:55:66 myPiZero [default]
[NEW] Device AA:BB:CC:DD:EE:FF CC2650 SensorTag
[bluetooth]# disconnect AA:BB:CC:DD:EE:FF
Attempting to disconnect from AA:BB:CC:DD:EE:FF
Successful disconnected
```

And then, back to Node-RED GUI, press **Rescan** on the SensorTag node, and select the line with `AA:BB:CC:DD:EE:FF ` corresponding to the CC2650 SensorTag.

**Comment by babicmilan999** [comment]
Hi @aleonnet. I have the exact same problem as you do. If you have solved it please let me know how. Thanks in advance.

**Comment by loren-murphy** [comment]
@aleonnet @babicmilan999 I'm running into the same issue where my sensor tag is showing 'connected'... but the complete msg object shows nothing (no payload).... Did you find a fix?

**Comment by piersbarrios** [comment]
Same issue here (using raspbian light) 
@loren-murphy , have you found a fix to make it work ?

**Comment by piersbarrios** [comment]
@loren-murphy: I just managed to do it sucessfully. 
Issue was elsewhere: https://github.com/sandeepmistry/node-sensortag/issues/107
Fixed by this: https://github.com/noble/noble/pull/769

**Comment by loren-murphy** [comment]
@piersbarrios could you provide the commands you used for the fix?

**Comment by loren-murphy** [comment]
@piersbarrios I installed noble 1.8 and updated the noble.js file but am still unsuccessful... Can you share your steps

**Comment by piersbarrios** [comment]
I installed noble 1.9.0 and added the fix linked above. Tell me if you want more details

**Comment by piersbarrios** [comment]
I installed noble 1.9.0 and added the fix linked above. Tell me if you want more details

**Comment by loren-murphy** [comment]
@piersbarrios it works!! thanks!..I spent so much time on this :)
