### ISSUE TITLE
"Twitter in" doesn't filter for who you follow

### ISSUE THREAD

**Issue by LordDannyBoi** [node-red/node-red-nodes#236]
Node Version: **v0.10.29**
Node-RED Version: **v0.14.6**

I just installed and got everything running on my Raspbery Pi and all is well except that the option in "Twitter in" that says "the tweets of who you follow" seems to do the same as "all public tweets".
Hopefully I'm not misunderstanding how this is supposed to work, but my intention was to collect all the tweets of those who I follow on twitter so I set this option.

Within moments my database got flooded with 8,000 tweets from what seemed to be anywhere and everywhere and I hit the twitter limit (obviously).

Is there a way to collect tweets of who I follow correctly?

**Comment by knolleary** [comment]
I seem to remember the underlying twitter api made this harder to do than you'd expect.

Will take another look as we have some other enhancements to the node in the pipeline.

**Comment by dceejay** [comment]
Hi @LordDannyBoi
can you please check the latest version of twitter node... the who you follow should be working correctly now...

**Comment by dceejay** [comment]
Closed by c456f89441cacde8486dbfc0b70d6a87804b275d
