### ISSUE TITLE
pushbullet in as new device? 

### ISSUE THREAD

**Issue by mrummuka** [node-red/node-red-nodes#239]
I've been experimenting with both node-red and pushbullet but I haven't managed to setup the following scenario, which I initially thought would be possible, but currently am unaware of if it is or if it would require manual initialization and/or code changes.

I'd like to setup a node-red flow which listens (with pushbullet in node) only for specific input. That is, either for a specific channel, or alternatively, to act as a single device that listens only messages destined for that specific device. 

Is this possible at all? At first I thought these are something that could (should?) be selectable options for pushbullet in node, however as there are no such configuration options, I was wondering is this possible at all, e.g. by filtering the received messages by device_id or channel_id?

If the filtering should occur after pushbullet-in, then there is still the question of how to make the node-red flow to seem as a 'device', i.e. so that I could send a push directly towards that (by selecting that 'device') from other devices when sending a push.  

I hope I'm clear enough, but if not, I'll clarify what's necessary.

**Comment by knolleary** [comment]
Hi, for general questions, please use the node-red mailing list (linked at the bottom of nodered.org). If it leads to a specific feature request or bug, we can reopen this issue to track it.

Thanks!

**Comment by mrummuka** [comment]
OK, I wasn't aware of that.
