### ISSUE TITLE
change code around ... data && data.trim ....

### ISSUE THREAD

**Issue by gbrault** [node-red/node-red-nodes#242]
in daemon.js, and node.child.stdout.on function, in the case we want just the buffer, you have to change the code as data is not a string and this makes node-red crash!

Thx

**Comment by hardillb** [comment]
Can you be specific about which node you are talking about, this report holds many node-red nodes

**Comment by dceejay** [comment]
Hi,

yeah - oops.. was doing a string op, when not needed.

**Comment by gbrault** [comment]
many thanks @dceejay !
