### ISSUE TITLE
Add needsPermission to RED.httpAdmin.get for pushbullet module

### ISSUE THREAD

**Issue by ninjuki** [node-red/node-red-nodes#244]
can you configure needsPermission for pushbullet module?

`RED.httpAdmin.get('/pushbullet/:id/migrate', RED.auth.needsPermission('pushbullet.read'), function(req, res) {`

`RED.httpAdmin.get('/pushbullet/:id/devices', RED.auth.needsPermission('pushbullet.read'), function(req, res) {`

**Comment by knolleary** [comment]
Yes - we should do this. In fact, we should review all http end points in this repo and ensure they have sensible permission requirements.
