### ISSUE TITLE
ScanBLE node 

### ISSUE THREAD

**Issue by RGCairns** [node-red/node-red-nodes#245]
I've been trying to install the ScanBLE node on an Intel Edison and it is not working.
Could you recommend what file location to install the node? and the command to run the installation node-red-node-scanble doesn't work.

Any help would be greatly appreciated? 

Thank you,
Rob

**Comment by hardillb** [comment]
Please ask questions like this on the mailing list: https://groups.google.com/forum/#!forum/node-red. Issues are for known code problems

Also it would be useful to add the command you have run to install the node, which directory you were in at the time, along with any error messages produced either at install time, when node-red is running. Along with what platform you are running on.
