### ISSUE TITLE
unexpected behaviour of CSV node

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#247]
If you feed an array into the CSV node, it nulls out any zero entries.

e.g. [1,0,1] comes out as "1,,1".
I would expect it to deliver "1,0,1"

If you make the zero into a string ("0") it gets it right.

test case:

[{"id":"ec5b76f6.5f45d","type":"inject","z":"24d96058.497f1","name":"","topic":"","payload":"[1,\"0\",1,2,3]","payloadType":"json","repeat":"","crontab":"","once":false,"x":550,"y":380,"wires":[["798e7e6.53e03"]]},{"id":"798e7e6.53e03","type":"csv","z":"24d96058.497f1","name":"","sep":",","hdrin":"","hdrout":"","multi":"one","ret":"\\n","temp":"","x":730,"y":360,"wires":[["a08bb9ca.90c27"]]},{"id":"a08bb9ca.90c27","type":"debug","z":"24d96058.497f1","name":"","active":true,"console":"false","complete":"false","x":890,"y":360,"wires":[]},{"id":"e3a7348e.c63ff","type":"inject","z":"24d96058.497f1","name":"","topic":"","payload":"[1,0,1,2,3]","payloadType":"json","repeat":"","crontab":"","once":false,"x":540,"y":340,"wires":[["798e7e6.53e03"]]}]

**Comment by dceejay** [comment]
closed by a fix to the core project a235745be7ffaef2cad84c6a711ca70b7911595f

**Comment by andysc** [comment]
I see the quotes got mangled on that code snippet. Quick test:
[{"id":"b7b983a4.b25a","type":"inject","z":"922802a3.79001","name":"","topic":"","payload":"[0,\"1\",2]","payloadType":"json","repeat":"","crontab":"","once":false,"x":370,"y":160,"wires":[[]]}]
`[{"id":"b7b983a4.b25a","type":"inject","z":"922802a3.79001","name":"","topic":"","payload":"[0,\"1\",2]","payloadType":"json","repeat":"","crontab":"","once":false,"x":370,"y":160,"wires":[[]]}]`

**Comment by andysc** [comment]
Interesting - that worked fine!
