### ISSUE TITLE
node-red-node-pi-mcp3008 readings only outcomes 0, after...

### ISSUE THREAD

**Issue by aleonnet** [node-red/node-red-nodes#249]
node-red-node-pi-mcp3008 readings only outcomes 0, after deploying nodebot from raspi-io.
It worked perfectly before the deplyment. Also, if I remove them, it comes back to work.
What can I do to avoid this scenario?
Thanks

**Comment by fivdi** [comment]
See https://github.com/nebrius/raspi-io/issues/76

**Comment by aleonnet** [comment]
Would someone help us?

**Comment by dceejay** [comment]
I don't think we can. If @fivdi is correct and the J5 guys are taking over all the pins then nothing we can do here, apart from suggest you maybe just try the default GPIO nodes rather than J5 nodebot. What features of that are you trying to use ?

**Comment by aleonnet** [comment]
Hi Dave, I'd like to use PCA9685 to control 2 servos but I couldn't find anything but J5/Raspi-io.
Now I have to choose between MCP3008 or PCA9685...because deploying nodebot breaks MCP3008 node. :(

**Comment by dceejay** [comment]
Maybe you could use the raw i2c node to just talk to the PCA chip ? https://www.npmjs.com/package/node-red-contrib-i2c

**Comment by dceejay** [comment]
@aleonnet - is this OK to close ?

**Comment by aleonnet** [comment]
@dceejay Yes! Thanks for your support.

**Comment by dceejay** [comment]
Thanks. You're welcome.
