### ISSUE TITLE
node-red-node-mqlight: out function remembers node topic

### ISSUE THREAD

**Issue by mkpurcell** [node-red/node-red-nodes#251]
If there is no node topic set, but there is a message topic, the MQLightOut function sets the node topic on its first invocation from the contents of the message topic. As such, subsequent invocations ignore the message topic and re-use the newly set node topic. This occurs in version 0.0.7.

Suggested fix:

function MQLightOut(n) {
.
.
. 
                    node.on("input", function(msg) {
                        var topic = node.topic;
                        if (topic === "") {
                            if (msg.topic) {
                                //REMOVING THIS LINE: node.topic = msg.topic;
                                //AND REPLACING WITH
                                topic = msg.topic;
                            } else {
                                node.warn("No topic set in MQ Light out node");
                                return;
                            }
                        }
                        //REMOVING THIS LINE: sendClient.send(node.topic, msg.payload, function(err) {
                        //AND REPLACING WITH
                        sendClient.send(topic, msg.payload, function(err) {
                         if (err) {
                                node.error(err,msg);
                            }
.
.
.
};

**Comment by dceejay** [comment]
Yes - great catch... fixed- will be pushed in a short while as v0.0.10
