### ISSUE TITLE
Trying to authorize twitter just gives "Unauthorized"

### ISSUE THREAD

**Issue by Zordid** [node-red/node-red-nodes#253]
I have no clue what this means or why this happens.

I run Node-RED on an Azure Ubuntu VM with a public IP address but no domain.
I switched on https on my Node-RED and enabled admin authentication, but that's all.

Click on the button "Click here to authenticate with Twitter" immediately brings a new tab with just the word "Unauthorized".

Any clue?

**Comment by tjeerdytsma** [comment]
I have the same problem. Also Ubuntu, enabled login of Node-RED and are on https.
![screen shot 2016-12-12 at 10 50 28](https://cloud.githubusercontent.com/assets/6126045/21094791/d41b8a5c-c058-11e6-8b6c-3aa091592eaa.png)

**Comment by DaviGuanabara** [comment]
Same problem :(
I tried to do this using Google Chrome with Android and El Capitan, and Safari with IOS and El Capitan.

I think that its a bluemix settings problem.

**Comment by knolleary** [comment]
I think this may actually be related to us using our own twitter app credentials in the node, rather than require the user to register their own app credentials. I suspect the twitter api is rate limiting the sheer number of twitter connections coming from the Bluemix range using the node-red app credentials.

The long term solution is to deprecate this node and move to a model where the user has to register their own app and use its credentials - as we do with pretty much all other nodes that access 3rd party services.

**Comment by tjeerdytsma** [comment]
I think if you are using your own credentials that can be indeed the problem. It could explain why it works at my own computer at localhost but not at my server. Lot of API's require to whitelist an IP address first and make an exeption for localhost. Someone knows if this is true for Twitter too, or if they changed this recently?

**Comment by andypiper** [comment]
You don't need to be whitelisted, but yes, too many logins from a single IP range and App ID may cause an issue of this kind, as it would be a potential indicator of unusual behaviour to our antispam systems.

**Comment by jturner-22** [comment]
We're also seeing this issue, and I think I know at least one cause. I believe it was introduced in the 0.1.8 version of the Twitter node, and that it only affects Node-RED installs using authentication.

In [7917ca8d], an authorization check was added to several nodes, including Twitter. A call to     RED.auth.needsPermission() was added, which is actually used in quite a few other places and works fine.

Normally, calls are made with $.ajax() (or $.getJSON(), etc.), which in the [editor/js/settings.js](https://github.com/node-red/node-red/blob/master/editor/js/settings.js) file is configured to add an "Authorization" header with a Bearer token.

In the Twitter node's [27-twitter.html](https://github.com/node-red/node-red-nodes/blob/master/social/twitter/27-twitter.html) file, the "Click here to authenticate with Twitter" button is not making a JavaScript call. It's just using an anchor's _href_ field, like a regular link. In that case, the bearer token is not added, so the Twitter node (on the server side) rejects the request.

That button probably just needs a click handler added.

**Comment by ncthbrt** [comment]
I solved the problem by temporarily disabling admin auth

**Comment by rwcombs** [comment]
@ncthbrt I can confirm this works. Disable Node-RED authentication, stop/restart Node-RED, authenticate with Twitter in your flow, deploy, re-enable Node-RED authentication, stop/start Node-RED.
