### ISSUE TITLE
ScanBLE on PI3

### ISSUE THREAD

**Issue by aleonnet** [node-red/node-red-nodes#254]
Hi Dave @dceejay!
What do you recommend for a functional scanBLE on PI3?
I've tried node-red-contrib-noble... but It scanned only once. I have reinstalled every prerequisite module a dozen times...and no results. Bellow is the flow and information.
Would you help me pls. Thank you!

PI3----------------------------------------
Welcome to Node-RED
===================
22 Nov 22:51:51 - [info] Node-RED version: v0.15.2
22 Nov 22:51:51 - [info] Node.js  version: v4.6.1
22 Nov 22:51:51 - [info] Linux 4.4.21-v7+ arm LE

FLOW----------------------------------------
[{"id":"a399d01b.41029","type":"inject","z":"50d3c869.46ecf8","name":"True","topic":"","payload":"{\"scan\":true}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":160,"wires":[["2f4cc55.32d713a"]]},{"id":"2f4cc55.32d713a","type":"scan ble","z":"50d3c869.46ecf8","uuids":"","duplicates":true,"name":"","x":290,"y":160,"wires":[["6d2f506c.9d2e6"]]},{"id":"6d2f506c.9d2e6","type":"debug","z":"50d3c869.46ecf8","name":"","active":true,"console":"false","complete":"true","x":470,"y":160,"wires":[]},{"id":"91719118.70f24","type":"inject","z":"50d3c869.46ecf8","name":"False","topic":"","payload":"{\"scan\":false}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":200,"wires":[["2f4cc55.32d713a"]]}]

Start msg----------------------------------------
msg : Object
{ "statusUpdate": true, "error": false, "stateChange": false, "state": "poweredOn", "_msgid": "b88fb666.477048" }

The only time I got a response after a reboot----------------------------------------
{ "payload": { "peripheralUuid": "5353e59b4b2c" }, "peripheralUuid": "5353e59b4b2c", "detectedAt": 1479772282146, "detectedBy": "raspberrypi", "advertisement": { "manufacturerData": { "type": "Buffer", "data": [ 76, 0, 12, 14, 0, 246, 129, 30, 101, 1, 65, 214, 36, 240, 132, 83, 97, 55 ] }, "serviceData": [], "serviceUuids": [], "solicitationServiceUuids": [], "serviceSolicitationUuids": [] }, "rssi": -81, "_msgid": "daabd5a4.255428" }
>>

**Comment by knolleary** [comment]
Hi,

please use the mailing list (link at bottom of nodered.org) for general questions - particular as `node-red-contrib-noble` is not a node the project maintains.

Thanks!
