### ISSUE TITLE
'e-mail in' node does not pass 'to' or 'header'

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-nodes#258]
According to the info tab, teh 'e-mail in' node should pass 'to' and 'header' but neither show up. 

I was able to get 'to' to show by editing 61-email.js and after line185 - which is:
            msg.date = mailMessage.date;
I added:
            msg.to = mailMessage.to;
which then returns the ’to’. I had no luck with 'header'

**Comment by dceejay** [comment]
Hi - thanks for that, I have added to, cc and bcc to the msg just in case :-)
