### ISSUE TITLE
Email In Node marked everything as read

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red-nodes#260]
Though I had the disposition parameter set to "none", all of the emails in my inbox we marked as "Read" when it went through them.

**Comment by dceejay** [comment]
which kind of mail server ? pop or imap ?

**Comment by TotallyInformation** [comment]
Ah sorry, IMAP with SSL.

**Comment by dceejay** [comment]
Hi, ah yes I see - we were marking all as read - instead of only on request... now set to only mark read if requested... (but defaults to mark read) as that was the existing behaviour - even if wrong ;-)
