### ISSUE TITLE
Why is scanBLE not published on NPM like the rest of the nodes?

### ISSUE THREAD

**Issue by cowchimp** [node-red/node-red-nodes#261]
Why is scanBLE not published on NPM like the rest of the nodes?
Is there a special caveat related to this node?
Thanks!

**Comment by dceejay** [comment]
As I recall it was written by a 3rd party way back before we could npm  install nodes... As such we wrote to them to ask if they wanted to maintain it and got no reply - so we didn't want to just release it without any "ownership".

If you or anyone wants to show it some love and make sure it works and create the readme etc - then we'd be happy to accept a PR for it and then release it.

**Comment by cowchimp** [comment]
thanks for the explanation.

**Comment by hardillb** [comment]
Also see http://flows.nodered.org/node/node-red-contrib-noble
