### ISSUE TITLE
node-red-node-email : imap email not being marked as seen after read

### ISSUE THREAD

**Issue by elguiri** [node-red/node-red-nodes#265]
Node version 0.1.14

I have used the "e-mail in" node feeding directly into a debug node. The e-mail node is configured with protocol IMAP, use SSL, imap.gmail.com port 993, google account name and app password, folder INBOX, disposition Mark Read (these are the default settings along with my google Userid and Password).

I also set the refresh rate to 10 seconds.

I have one unread message in my mail inbox. Every 10 seconds, I get the same message appearing in my debug window; the message in the inbox is not being marked as read, even though it has been seen by the node. It is then seen again on the next scan. If I add an email to my inbox, I get two messages returned by the node on every scan.

This behaviour is not desirable for checking for new emails as all emails in the inbox are retrieved on every scan. It looks like the emails are not marked as seen after being read, even though Disposition is set to Mark Read.

**Comment by elguiri** [comment]
Further information. Test with same result on both Debian and Windows 10 (two different versions of Node.js):

20 Dec 17:30:03 - [info] Node-RED version: v0.15.2
20 Dec 17:30:03 - [info] Node.js  version: v0.10.29
20 Dec 17:30:03 - [info] Linux 3.16.0-4-amd64 x64 LE

20 Dec 17:11:53 - [info] Node-RED version: v0.15.2
20 Dec 17:11:53 - [info] Node.js  version: v4.7.0
20 Dec 17:11:53 - [info] Windows_NT 10.0.14393 x64 LE

**Comment by dceejay** [comment]
yes indeed - slight variable scoping issue

**Comment by dceejay** [comment]
But I would also say that hitting your mail server every 10 secs is a bit gratuitous....  ouch.

**Comment by elguiri** [comment]
Yes, 10 seconds was for testing because I didn't want to wait 300 seconds to find it wasn't working...

This may be a daft question, how do I update the nodes? I am trying to remove 0.1.14 from my palette without success.

**Comment by dceejay** [comment]
from the command line - go into your user directory
    cd ~/.node-red
    npm i node-red-node-email

then restart.
If via the UI- you will need to delete both the node and it's config node from the flow first. Then re-deploy so it is running "clean" - then you can uninstall and reinstall it from the palette manager.

**Comment by elguiri** [comment]
I have somehow ended up with both 0.1.14 and 0.1.15 installed.

In Manage Palette "Nodes", 0.1.14 cannot be removed (hangs with a cycling vertical bar animation).
In Manage Palette "Install", 0.1.15 is "installed" when filtering by email.

Any suggestions? I can't even work out how to re-install node-red (installed via "npm install -g --unsafe-perm node-red" command).

Thanks

**Comment by dceejay** [comment]
What device, and operating system is this on?

**Comment by elguiri** [comment]
It's on a Debian Jessie VM (micro VM installed on a qnap NAS).

**Comment by dceejay** [comment]
ok - may need to clean out one/both manually... 
they will either be in   ~/.node-red/node_modules directory or wherever node-red core got installed
typically  /usr/lib/node_modules/node-red/node_modules   or /usr/local/lib/node-red/node_modules/
you are looking for file 61-email.js and 61-email.html
once you have found and deleted them you can reinstall.

**Comment by elguiri** [comment]
Thanks very much Dave, all sorted.

I had to delete the whole node-red-node-email folder in /usr/local/lib/node_modules/node-red/node_modules before I could (re)install 0.1.15 from the palette manager.

It's now installed to /root/.node-red/node_modules as I installed node-red under root.

**Comment by dceejay** [comment]
Ah - ok - good... and the email problem itself ?

**Comment by umanganiello** [comment]
Hi @dceejay, I've just tried and the issue seems to be resolved: e-mail is correctly marked as read for me. Thanks!

**Comment by elguiri** [comment]
Hi Dave, as confirmed by umanganiello, the email is now marked correctly as read.

Thanks for the quick response to the bug and the help with installation. I will get back to my flow!

**Comment by er1z** [comment]
Just want to attach into this ticket — marking as read works fine but I after fetching an email is not being deleted (disposition `Delete` set). Anyone else struggles with the same issue?
