### ISSUE TITLE
Single non-scrolling character on SenseHat?

### ISSUE THREAD

**Issue by Technodad** [node-red/node-red-nodes#266]
I am having a proble getting the SenseHat to display a single character without scrolling.

The [documentation for the node](http://flows.nodered.org/node/node-red-node-pi-sense-hat) says it should be possible:

  > If the text is a single character, it will be displayed without scrolling. 

However, if I send a msg.payload with a single character (confirmed by a debug node) the character still scrolls across the screen. Either I'm missing something fundamental, or the node isn't working as documented. Any suggestions?

**Comment by dceejay** [comment]
Finally got round to fixing this...
