### ISSUE TITLE
Which wiring?

### ISSUE THREAD

**Issue by Ch3fk0ch88** [node-red/node-red-nodes#268]
Hi,
is this the right wiring?
https://www.tutorials-raspberrypi.de/wp-content/uploads/2014/05/ultraschall_Steckplatine.png

Or i have to use the one with the 1k ohm between Echo and GPIO?

Thanks

**Comment by hardillb** [comment]
Please use the mailing list (https://groups.google.com/forum/#!forum/node-red) for general questions
