### ISSUE TITLE
node-red-node-beaglebone installation fails

### ISSUE THREAD

**Issue by bsculley** [node-red/node-red-nodes#269]
[npm-debug.zip](https://github.com/node-red/node-red-nodes/files/724708/npm-debug.zip)

I am trying to install node-red-node-beaglebone using:

sudo npm install -g --unsafe-perm node-red-node-beaglebone

as instructed on the Node Red site, but the installation fails during the serialport build.  I can install serialport standalone with no problems, but the node-red-node-beaglebone installation is apparently trying to build a downlevel version that is incompatible with other components.  The debug log is attached.

Is there an alternative set of steps for installing node-red-node-beaglebone that would avoid this problem?  I read the comments on the landing page, but it wasn't clear exactly what procedure is required to do the installation.

**Comment by dceejay** [comment]
Yes... the underlying library octalbonescript needs to move to the latest version of serialport...
https://github.com/theoctal/octalbonescript/issues/71

**Comment by dceejay** [comment]
The latest version of Beaglbone Debian Images include Node-RED preinstalled with working GPIO..
So it is best not to over-install with our version unless you first remove the other. (but why would you ???)

Going to close this - but really the whole BBB support docs need a refresh.
