### ISSUE TITLE
node-red-node-twitter: Code 34 "Sorry, that page does not exist."

### ISSUE THREAD

**Issue by DerTomm** [node-red/node-red-nodes#270]
Hi,

in my flow I use the Twitter node for sending direct messages as notifications. Tweeting works fine, but I receive the following warning everytime a tweet is sent:

"Error: HTTP Error 404: Not Found, API message: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}"

Is this something to be worried about?

My node usage: msg.payload = "D _username_ This is my notification message!"

**Comment by dceejay** [comment]
Are the messages being delivered OK ?
It's odd - Error 34 is as it says same as a 404.

@knolleary - are we using the correct endpoints ? as per https://twittercommunity.com/t/404-errors-message-sorry-that-page-does-not-exist-code-34/1231/19

**Comment by DerTomm** [comment]
> Are the messages being delivered OK ?

Yes, the message text is submitted without problems.

**Comment by andypiper** [comment]
One thing to note is that is using the older SMS shortcode method of sending direct messages via the regular Twitter API (totally valid use case) so I'd have to see if there's a reason why that responds differently. Do you see the same behaviour if you send a regular Tweet (without D username), or only with DMs?

**Comment by DerTomm** [comment]
Interesting - I just tested tweeting directly and realized no error message. Afterwards I tested again with direct messaging and guess what - the error message did not appear either. So maybe temporary problems on Twitter side...?

**Comment by DerTomm** [comment]
As the problem cannot be reproduced at the moment I'll close this issue and observe the behaviour in the next time.

**Comment by HobbytronicsPK** [comment]
I am also facing the very same error. There is no error message on sending tweets.
`Error: HTTP Error 404: Not Found, API message: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}`

**Comment by jpdelopes** [comment]
Probably not your problem, but I was getting that error because I was using the curly brackets {} on my `msg.payload.` It is really `D user The direct message`, without any brackets.

**Comment by andypiper** [comment]
The `D user` syntax will no longer work on Twitter, this functionality was removed last year.

**Comment by knolleary** [comment]
@andypiper whilst that is true of the underlying api, the node-red node still looks for it and translates it to the appropriate DM api (albeit the one that is deprecated and needs updating... but that's a separate issue). This ensured user flows continued to work without disruption.

When we update the node to use the proper DM api, we can add a more explicit option to the node for sending DMs without resorting to the legacy syntax.

**Comment by andypiper** [comment]
Ah, cool! thanks!
