### ISSUE TITLE
node-red-node-smooth - how to reset or clear the node for new data set?

### ISSUE THREAD

**Issue by mogmedia** [node-red/node-red-nodes#273]
how can i reset or clear the node to process a completely new set of data and get an Mean only from the new data set?

Thanks

**Comment by hardillb** [comment]
Doesn't look like that's possible at the moment.

A Pull Request would probably be looked on favourably.

**Comment by dceejay** [comment]
@mogmedia - I have added the ability to reset the node by sending in a msg with a reset property of any value. (i.e. if `msg.reset` exists on `msg`) it will reset to the initial state - clear counters etc.

**Comment by srt9969** [comment]
Hi,
Been trying to set up a max-min thermometer using node red (ESP32/DHT22/MQTT/RPi3(please bear with me, I'm new at this)).
I need a reset button for the max and min gauges, so used a button to fire a function node setting msg.reset = 1 to reset the subsequent smooth node(s). the gauges (fed by the smooth nodes) reset to a value of 1 - fine for the max gauge which reset to current temp with next mqtt message, but min gauge will have to wait until temp falls below 1, presumably! 
So, what did I miss, or is there a better way, please? Thank you for your forebearance, I hope that all made sense...
My flow:

`[{"id":"f234654f.652a48","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"48bdc589.059a2c","type":"debug","z":"f234654f.652a48","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":970,"y":80,"wires":[]},{"id":"8389e5e8.a68428","type":"mqtt in","z":"f234654f.652a48","name":"Temperature","topic":"topic/temp1","qos":"2","datatype":"auto","broker":"91a70537.a84f08","x":290,"y":40,"wires":[["eef3a546.489468","b5e1f1b4.1b3c6","3f49bb03.3ff104","bba9cded.2fa2a"]]},{"id":"b0de5343.65e88","type":"mqtt in","z":"f234654f.652a48","name":"Humidity","topic":"topic/humid1","qos":"2","datatype":"auto","broker":"91a70537.a84f08","x":280,"y":100,"wires":[["d4f3ffbc.bc096","769696fb.5b7668","5f722a43.0e1d84","267a07f7.80e738"]]},{"id":"eef3a546.489468","type":"ui_chart","z":"f234654f.652a48","name":"Temperature","group":"3b204857.d75b68","order":1,"width":"13","height":"3","label":"Temperature","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":730,"y":40,"wires":[["48bdc589.059a2c"]]},{"id":"d4f3ffbc.bc096","type":"ui_chart","z":"f234654f.652a48","name":"Humidity","group":"3b204857.d75b68","order":3,"width":"13","height":"3","label":"Humidity","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":720,"y":100,"wires":[["48bdc589.059a2c"]]},{"id":"b5e1f1b4.1b3c6","type":"ui_gauge","z":"f234654f.652a48","name":"Temperature","group":"14bf30df.94ef3f","order":1,"width":"3","height":"3","gtype":"gage","title":"Current Temperature","label":"C","format":"{{value}}","min":"-15","max":"40","colors":["#00b500","#e6e600","#ca3838"],"seg1":"20","seg2":"25","x":730,"y":160,"wires":[]},{"id":"769696fb.5b7668","type":"ui_gauge","z":"f234654f.652a48","name":"Humidity","group":"14bf30df.94ef3f","order":6,"width":"3","height":"3","gtype":"wave","title":"Current Humidity","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":720,"y":220,"wires":[]},{"id":"3f49bb03.3ff104","type":"smooth","z":"f234654f.652a48","name":"MaxTemp","property":"payload","action":"max","count":"1000","round":"","mult":"single","x":520,"y":280,"wires":[["33c3d37d.7f032c"]]},{"id":"33c3d37d.7f032c","type":"ui_gauge","z":"f234654f.652a48","name":"Max Temp","group":"14bf30df.94ef3f","order":3,"width":"3","height":"3","gtype":"gage","title":"Max.","label":"C","format":"{{value}}","min":"-15","max":"40","colors":["#00b500","#e6e600","#ca3838"],"seg1":"20","seg2":"25","x":730,"y":280,"wires":[]},{"id":"bba9cded.2fa2a","type":"smooth","z":"f234654f.652a48","name":"MinTemp","property":"payload","action":"min","count":"1000","round":"","mult":"single","x":520,"y":340,"wires":[["5673286f.5d3508"]]},{"id":"5673286f.5d3508","type":"ui_gauge","z":"f234654f.652a48","name":"Min Temp","group":"14bf30df.94ef3f","order":2,"width":"3","height":"3","gtype":"gage","title":"Min.","label":"C","format":"{{value}}","min":"-15","max":"40","colors":["#00b500","#e6e600","#ca3838"],"seg1":"20","seg2":"25","x":720,"y":340,"wires":[]},{"id":"5f722a43.0e1d84","type":"smooth","z":"f234654f.652a48","name":"MaxHum","property":"payload","action":"max","count":"1000","round":"","mult":"single","x":520,"y":400,"wires":[["e4068ef.82b337"]]},{"id":"267a07f7.80e738","type":"smooth","z":"f234654f.652a48","name":"MinHum","property":"payload","action":"min","count":"1000","round":"","mult":"single","x":520,"y":460,"wires":[["6f216a5c.8e1894"]]},{"id":"e4068ef.82b337","type":"ui_gauge","z":"f234654f.652a48","name":"Max Humidity","group":"14bf30df.94ef3f","order":8,"width":"3","height":"3","gtype":"wave","title":"Max.","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":740,"y":400,"wires":[]},{"id":"6f216a5c.8e1894","type":"ui_gauge","z":"f234654f.652a48","name":"Min Humidity","group":"14bf30df.94ef3f","order":7,"width":"3","height":"3","gtype":"wave","title":"Min.","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":730,"y":460,"wires":[]},{"id":"91a70537.a84f08","type":"mqtt-broker","z":"","name":"NodeRed","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"3b204857.d75b68","type":"ui_group","z":"","name":"Graphs","tab":"cd8f0bc5.bb8598","order":1,"disp":false,"width":"13","collapse":false},{"id":"14bf30df.94ef3f","type":"ui_group","z":"","name":"Gauges","tab":"cd8f0bc5.bb8598","order":2,"disp":false,"width":"9","collapse":false},{"id":"cd8f0bc5.bb8598","type":"ui_tab","z":"","name":"Greenhouse","icon":"fa-leaf","order":1,"disabled":false,"hidden":false}]`

**Comment by hardillb** [comment]
Please ask how to questions on slack or the forum rather than on closed issues

**Comment by srt9969** [comment]
Oops, sorry. Told you I was new at this...
