### ISSUE TITLE
emoncms : not properly configured

### ISSUE THREAD

**Issue by Urs-Eppenberger** [node-red/node-red-nodes#275]
Hello

I leave the "Node" field open, since I set msg.nodegroup in a previous node, as per the instructions.
But on deploying I get the error "... not properly configured".
This error should not be thrown, since the instructions explicitly allow for the "Node" field to remain unconfigured.
I can avoid the error during a session when I cross the 'do not warn about this error again'. But at the next session, the error shows up again.

**Comment by Urs-Eppenberger** [comment]
Thanks for the quick response.
It was just a small nuisance, but now it is smooth.

**Comment by dceejay** [comment]
No problem - thanks for spotting it.
