### ISSUE TITLE
"management" of the connection to the remote server.

### ISSUE THREAD

**Issue by RogierQ** [node-red/node-red-nodes#276]
Connection to external mysql server stops functioning after 1 hour.
With internal database no problems...

**Comment by hardillb** [comment]
As an off the top of my head thought, this sounds like something a firewall might cause, dropping lightly used connections after a period of inactivity

**Comment by RogierQ** [comment]
Could be... you expect it then on server or client side?

**Comment by hardillb** [comment]
Usually neither, it would be somewhere in between.

I am make the assumption that internal means "with in the same network" an external means "cloud hosted or otherwise outside the local network".

**Comment by RogierQ** [comment]
Ok i will try to check it out if it is a firewall issue

**Comment by dceejay** [comment]
HI - I'm beginning to suspect @hardillb may be right. I've just been testing with a mysql instance on another lan connected device - and the connect / reconnect seems to work fine - over unplugs, reboots etc... and we don't stop trying, and the status indicator seems accurate.

**Comment by RogierQ** [comment]
I'm testing now with different settings on my sever.
There was no wait and interactive timeout set...

I set this now to : 
wait_timeout = 28800
interactive_timeout = 28800

So lets see what happens 

https://support.rackspace.com/how-to/how-to-change-the-mysql-timeout-on-a-server/

**Comment by dceejay** [comment]
on my test setup at home.... arrived home after day at work and the database connection reconnected and picked up just where it left off.

**Comment by RogierQ** [comment]
Frustrating... ( or not... )
Spoke to my hosting company, they were surprised to keep the connection...
So it is going to be another hosting company or something with http requests.
Thanks for your time and help!!!

**Comment by dceejay** [comment]
could you send a keep-alive (dummy) update every 55 minutes to keep it open ? :-)

**Comment by RogierQ** [comment]
Keep alive test is running... lets see

A properly close sounds like the best solutions.
But i gues this needs to be done internal in the node and isn't something i can do?

**Comment by RogierQ** [comment]
Test with fake database call is doing the job ;-)
Every 18 minutes a call and after few hours still working!

**Comment by RogierQ** [comment]
Still fighting for the best solution... with php get it is getting slower then i wish.
Is the close and reconnect option something to expect in the near future?
Then i can decide how to go on with my setup
Thanks!

**Comment by dceejay** [comment]
I'm not sure why it isn't detecting the failed connection and reconnecting. Is the remote server on a public server that I could set up a database on to test ?

**Comment by RogierQ** [comment]
I can setup a test database for you, can you send me an email?
Then i can send you the login details

**Comment by dceejay** [comment]
dceejay   {**at..} gmail.com

**Comment by dceejay** [comment]
closed by c6d214fcfee74e32f675b79b9cb2ec7b2af449ad
