### ISSUE TITLE
Sending authenticated emails with v0.1.18 is broken

### ISSUE THREAD

**Issue by timolehto** [node-red/node-red-nodes#279]
Broken by this pr: https://github.com/node-red/node-red-nodes/pull/277

What is broken is that the auth options are not passed as options to the createTransport method anymore, but instead are set on the NodeMailer instance returned by that method and NodeMailer couldn't care any less about such things. It is the SMTPTransport that checks the auth options here:
https://github.com/nodemailer/nodemailer-smtp-transport/blob/v1.1.0/src/smtp-transport.js#L145

So, this pr should probably be reversed and a new release be made asap as it likely breaks every auth using email sending node-red out there.

**Comment by timolehto** [comment]
Or accept my hotfix ^

**Comment by dceejay** [comment]
apologies - I'm on a slow 2g link and didn't see this - must have crossed in the ether.. yes will probably accept yours later when back on a decent link as it's a better fix

**Comment by timolehto** [comment]
Seems to be working now, closing this.
