### ISSUE TITLE
Error SMTP

### ISSUE THREAD

**Issue by nttra83** [node-red/node-red-nodes#284]
Hello,
I faced this issue when I'm trying send an email to someone.
Could you help me fix this issue?
Thanks,

"Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt-↵534-5.7.14 zPXsOHyn-XdTEcwxO9GPxKmPeT8WKUiz8l2gMTpoaq-xfQSvv4BIF-AFYSDDL6fcmDwlLD↵534-5.7.14 PEumDrVIlCQgaOORuCaq_UPsumE_o6cPSqdKEMnIXNjlt_DaoulJrK4ZIIF6FN5PlCu6SL↵534-5.7.14 aeQIUzpGdvpePZhyDqJ-2UB6k0r49pDwmbuV0UF3Jp5nKg6aMNANJuoCGEj9UO-ooolbpJ↵534-5.7.14 oxk1xidpoaostbBu24bi7IWN_wvO8> Please log in via your web browser and↵534-5.7.14 then try again.↵534-5.7.14 Learn more at↵534 5.7.14 https://support.google.com/mail/answer/78754 k76sm6774626pfg.42 - gsmtp"

<img width="1057" alt="screen shot 2017-03-08 at 9 40 44 pm" src="https://cloud.githubusercontent.com/assets/24289191/23708257/ef00d09c-0447-11e7-862a-8922d4153f90.png">
<img width="1048" alt="screen shot 2017-03-08 at 9 40 25 pm" src="https://cloud.githubusercontent.com/assets/24289191/23708262/f08a3962-0447-11e7-9a28-38db39dbda7d.png">

**Comment by dceejay** [comment]
We prefer general questions via the mailing list or slack channel please.

Have you configured your gmail account to allow 3rd party apps to access it ?
https://support.google.com/accounts/answer/185833?hl=en

**Comment by nttra83** [comment]
Thanks dceejay :). I fixed it.
