### ISSUE TITLE
node-red-node-what3words

### ISSUE THREAD

**Issue by vasquezj-ibm** [node-red/node-red-nodes#285]
I have deployed this node successfully and the node will not store my W3W API Key, in the debug output it states the following:

No what3words API key set
ERROR:API key not set

In the node I put in my API key, select English and put a name 'w3w' and click done and deploy, that is when the messages are produced in the debug output.

**Comment by dceejay** [comment]
Thanks, that has been a while since it was updated...

now fixed and pushed to npm as version 0.0.5
