### ISSUE TITLE
Unable to update node-red-node-sensortag to V1.3 

### ISSUE THREAD

**Issue by Clause16** [node-red/node-red-nodes#291]
I've posted an issue over at the node-sensortag and got redirected over to here. It would be greatly appreciated if I can get some help here! 

Issue: https://github.com/sandeepmistry/node-sensortag/issues/98

Basically, I am unable to update node-red-node-sensortag to V1.3 because it pins the node-sensortag dependency to 1.2.x

**Comment by hardillb** [comment]
I'm having a look at this.

While I can update the underlying node to 1.3.0 there is no way to subscribe to changes to the battery status so the node will not be able output that data.

The battery level can be polled, but this would be different behaviour from all the other sensor values.

**Comment by dceejay** [comment]
updated to 1.3.0 as requested...  though as Ben notes, not sure it will help much.
