### ISSUE TITLE
Email with buffer as payload always includes email.default-message

### ISSUE THREAD

**Issue by DJWassink** [node-red/node-red-nodes#292]
Sending a email with a buffer as payload the `email.default-message` is always displayed.
Is there any reason why it always shows this string? Even though the `description` property is set it still shows this default-message.

The hardcoded string can be seen here:
https://github.com/node-red/node-red-nodes/blob/master/social/email/61-email.js#L98

Wouldn't it be better if the content of the email gets set by the description property if the payload is a buffer?

**Comment by dceejay** [comment]
good thought.... as long as msg.description actually exists.

**Comment by DJWassink** [comment]
I actually wanted to say I am in favor of not automatically adding anything, but then I looked at the code and it also tries to generate a filename if the user didn't add one. Pretty nifty!

Maybe a solution would be if a user mentioned something like `__filename__`  in the description a simple replace will do the trick?

Maybe even then, there could be a check if the user did supply the `__filename__` keyword. If not the current behavior is actually pretty good. This would also prevent any "breaking changes" if users updated. But then users are forced to supply a `__filename__` or else they are still stuck with the default message.

**Comment by dceejay** [comment]
Then users have to know to use the __filename__ syntax (or whatever we chose)...

**Comment by DJWassink** [comment]
Yeah I guess that would break the simplicity that node-red stands for for the end users... Maybe a better solution is to allow a boolean flag to print the default-message and else only the description? Then it's the duty of the end user to also set the filename property and include the same name in the description (if they want the filename as content in the mail)

**Comment by dceejay** [comment]
That then becomes an explicit option to have to set. How about we just reverse the order... put the description first then the default "Your file is attached..." as the last line.

**Comment by DJWassink** [comment]
That would definitively be better, and also seems more logical since an attachment usually is at the bottom of a mail.

**Comment by dceejay** [comment]
OK - let's try it that way... msg.description gets prepended instead of appended.
pushed as version 0.1.22 to npm

47520ea5aab165113c991e79f7a8c288a06a3a8c
