### ISSUE TITLE
mongo db aggregate not works

### ISSUE THREAD

**Issue by gabbiano83** [node-red/node-red-nodes#294]
on CLI:
db.users.aggregate([{ $group: { _id : "$customer"}}])
{ "_id" : "customer1" }
{ "_id" : "customer2" }
{ "_id" : "customer3" }

on nodered the payload after aggregate query contains all documents like a simple db.users.find() call.

Someone can explain me why?

**Comment by hardillb** [comment]
As I said on the previous issue, please ask usage questions on the mailing list or the Slack team linked to from the homepage. Issues are for defects in the code.

Also the [doc](https://github.com/node-red/node-red-nodes/tree/master/storage/mongodb) for the mongo node suggests it only supports .find queries.

**Comment by knolleary** [comment]
The node does mention support for the aggregate pipeline.

@gabbiano83 can you provide more specific details on what you are doing? What msg are you passing the node?

As hardillb says, we prefer to deal with questions on the mailing list, but if you provide some more information we may be able to help out here.
