### ISSUE TITLE
Serial on Raspberry Pi 3.

### ISSUE THREAD

**Issue by scargill** [node-red/node-red-nodes#296]
I've always used this serial port - well familiar with it - used it on Pi and lots of other similar boards.

However, the Pi3 has me beat.

http://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3/

When code I know works on the Pi2 failed to work on the Pi3, I found the above. Apparently - there are now TWO serial ports on the Pi3 (I think the second is software)  and to use the serial on the GPIO pins as normal - you have to use /dev/ttyS0

So - I made the change suggested to the boot file, rebooted and sure enough in the search dialog in the serial port /dev/ttyS0.   Connected up - the output lights up green and says connected - the input is grey and says not connected. NEITHER work - nothing comes out of the output.

HELP.

**Comment by hardillb** [comment]
Have you tested it with something else (like picocom) first to make sure you have configured the pi right?

**Comment by scargill** [comment]
The Pi installation is identical to the previous one. I’ve no idea what a Picocom is.

**Comment by hardillb** [comment]
picocom is a serial terminal app like minicom and it's not the same as the previous setups as you've had to change the Bluetooth settings to move it to the 2nd (software) serial port.

**Comment by scargill** [comment]
Oh I see – oh no, there’s nothing coming out. A debug port before the output shows buffers of data going in – my oscilloscope (50Meg analog) says nothing is coming out…

**Comment by dceejay** [comment]
and for more info 
http://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3

**Comment by scargill** [comment]
And a good start with that is it says there is a /dev/serial0    - no there isn’t – there’s a /dev/S0

 

However – the BOTTOM part of that link – shows how to disable the Bluetooth and after a reboot – I’m up and running – however – good for others to know – if you DO need serial out on those pins – and reliable serial – why bother with a Pi 3!!

 

Thanks Dave – I’m one step forward.

**Comment by dceejay** [comment]
so - ok to close this ? 
(as it's not an issue with Node-RED...)

**Comment by scargill** [comment]
Yes thanks
