### ISSUE TITLE
RBE - ‘block unless value changes by more than' needs to be split into two because of edge case

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-nodes#300]
if you use ‘block unless value changes by more than' and the value to change is 10 (or 10%) and the first number thru is 100 and the second is 110, the second number will be passed thru because the logic is using an '>=' when it should be just using an '>'. 

There should be two cases
1) ‘block unless value is greater than'
2) ‘block unless value is equal to or greater than'

and should there be a 'less than' and 'equal to or less than' cases?

**Comment by dceejay** [comment]
yes - and yes there should be < and <= equivalents also.

**Comment by dceejay** [comment]
closed by 774bc50589b93df04337610f12aa19191c29d751
