### ISSUE TITLE
node-red-node-twilio - placing credentials in twiliokey.js file results in warning

### ISSUE THREAD

**Issue by mitchmitchell** [node-red/node-red-nodes#306]
When I place my twilio account sid and auth token in the twiliokey.js file above the node-red directory as per described in the documentation, I am able to successfully use twilio nodes in my flow to send message but on deploy I always receive a message about improperly configure twilio nodes -- they work but still give a warning.

Also (may be unrelated) when the twiliokey.js file exists, the twilio configuration dialog does not allow selection of global vs. local settings but rather simply requests twilio credentials be configured.

**Comment by dceejay** [comment]
Wow that is a very old node ;-).... we don't use/encourage placing credentials like that anymore... So I should remove them from any docs...
