### ISSUE TITLE
node-red-node-daemon STDOUT blocked

### ISSUE THREAD

**Issue by mjoey89** [node-red/node-red-nodes#307]
Hi!

It seems like at STDOUT output of the daemon does not appear the text what was printf-ed by my script running by the daemon. Later when I use my exit command at STDIN, then my script ends, and at STDOUT (directed to debug) comes all the texts **at once** which were printed before. 

Is it supposed to work like that?

My script is a C code compiled with GCC, and all of the printed texts have '\n' at the end.

Best Regards

**Comment by hardillb** [comment]
Your application will be buffering STDOUT, you need to make sure you flush the output stream if you want things to be output immediately.

You may also be able to change how libc buffers output.

**Comment by dceejay** [comment]
What kind of app is it ? Python, for example let's you add -u to the command line to flush immediately.

**Comment by mjoey89** [comment]
It is a C code.
@hardillb - You were right, it has been buffering. From stackoverflow I found out, that if STDOUT is a terminal then new line character is flushing. This is why the app worked for me from putty.
So now I am using **setbuf(stdout, NULL);** to turn off buffering.

Thank you guys!

**Comment by dceejay** [comment]
some more options documented here - http://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin

**Comment by dceejay** [comment]
and other options if you can't recompile the app... stdbuf looks like a good starting point for Pi users 
  https://unix.stackexchange.com/questions/25372/turn-off-buffering-in-pipe
