### ISSUE TITLE
node-red-snmp "snmp set" lacking.

### ISSUE THREAD

**Issue by mscbpi** [node-red/node-red-nodes#310]
Forking the existing node, I added an "snmp set" node I would like to offer. Takes a oid as an object as described in net-snmp node.js lib (oid / type / value).

**Comment by hardillb** [comment]
If you have a pull request, no need to raise an issue as well, just raise the pull request and include a detailed explanation of what changes you have made and why. Also please read the Contributing.md to ensure you understand the process of signing the Contribution Agreement.

**Comment by dceejay** [comment]
Thanks for the heads up. Sounds useful... (if you like that sort of thing :-) 
and it's documented of course :+1:

**Comment by bimalyn-IBM** [comment]
Can we close this issue now?
