### ISSUE TITLE
Can't find Raspberry_pi section (rpi gpio ) in node-red after an update

### ISSUE THREAD

**Issue by kraeml** [node-red/node-red-nodes#313]
After running `update-nodejs-and-nodered` I coldn't find the Rasspberry Pi GPIO Section.

Ther is an stackvoerflow task [here](http://stackoverflow.com/questions/43858438/cant-find-raspberry-pi-section-rpi-gpio-in-node-red-after-an-update?newreg=24cfc05483fe4bd9842b34dde2fe0224):

The python gpio is installed I could not find an error.

**Comment by knolleary** [comment]
Closing this issue as you've already asked the question on StackOVerflow and raised another issue on a different repo.
