### ISSUE TITLE
HTTP input node data leak

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#320]
If you dump the whole message object of an HTTP input request to the console (maybe also in the debug tab, but I can't find the position in the structure to look for it), you'll see a (way down in the structure somewhere) a body object which contains all the JSON for the flow you most recently deployed.
I'm not sure if this is necessarily bad - it can make the object quite enormous and messy to wade through in the console log.
But it seems to me that kind of data shouldn't be "leaking" into the user-space flows from the insides of Node-RED

**Comment by knolleary** [comment]
Any hints for where in the structure?

**Comment by knolleary** [comment]
We have to attach the request to the message object, so there is a limit to what we can do about this. We have previously tried to hide the request object and only provide a proxy to it in the message - but that broke existing flows.

**Comment by knolleary** [comment]
Also - I assume you mean the HTTP In node that is part of the core palette rather than any of the extra nodes that are in this repository?

**Comment by knolleary** [comment]
Oh, one final thing... ;) would prefer that potential security issues are raised privately rather than disclosed publicly before we can assess and do anything about it. I should update our contribution guidelines to make that clear.

**Comment by knolleary** [comment]
I've just dumped an http request object to the console and I don't see any flow information in there. You meantion the `body` element (`msg.req.body` I assume?). That is the body of the request... data you'd absolutely want to have access to in a flow. Are you posting flow data to your http flow?

**Comment by dceejay** [comment]
closing this as no follow up (in this thread) - and in wrong project anyway.
