### ISSUE TITLE
Dawn +30 is triggering in the PM

### ISSUE THREAD

**Issue by rgerrans** [node-red/node-red-nodes#321]
I have a timer scheduled to come on at dawn +30 minutes and go off at 08:00.  I also have a second timer scheduled to come on at dawn and go off 30 minutes later.  Both work as expected in the am, but I've noticed that the dawn +30 minute timer comes on in the evening.  I verified that the dusk offset is 0.

**Comment by dceejay** [comment]
which node is this ?

**Comment by rgerrans** [comment]
@dceejay Sorry, it was for TimeSwitch - https://flows.nodered.org/node/node-red-node-timeswitch 

I hit his github link and wasn't paying attention that it took me to the main node page not his.
