### ISSUE TITLE
SerialPort: programmatically close/reopen

### ISSUE THREAD

**Issue by dvv** [node-red/node-red-nodes#330]
Hello!

I have SerialPort <-> MQTT as part of my flow and I would like to have means for the portIn and portOut nodes to temporarily release its ttyUSBx so that avrdude could update the firmware of connected device.

So far I do manually assign different (dummy) port to portIn/Out nodes, apply changes, manualy flash then restore node assignments.

Any pointers?

TIA

**Comment by dceejay** [comment]
We have no plans to do this from within a flow.
We could consider a Pull request if anyone wanted to build one.
