### ISSUE TITLE
Unicorn Hat node RGB blues below 217 don't work

### ISSUE THREAD

**Issue by tim-minter** [node-red/node-red-nodes#333]
Passing any RGB string it seems that at least one R,G or B must be above 216 otherwise the pixel goes out.
Testing shows: 
This works "217,0,0" = red background.
This gives blank background "216,0,0"
This gives blank background "216,216,0"
This gives green background "217,217,0"

**Comment by dceejay** [comment]
Hi - the underlying library got updated while we weren't looking... the node has now been updated - can you retry with the latest ? Thanks

**Comment by dceejay** [comment]
closing as no response
