### ISSUE TITLE
node-red-node-serialport install script urls broken

### ISSUE THREAD

**Issue by onedumbtrucker** [node-red/node-red-nodes#337]
https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v48-linux-arm.tar.gz

no longer exists and there is no way to install or use this library at the moment. Then it tries to build and estimate 5,000,000 seconds (57ish days) to regenerate makefile?

node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/build'
make: Warning: File '../../../../../../../root/.node-gyp/6.11.0/include/node/common.gypi' has modification time 4919303 s in the future
  ACTION Regenerating Makefile

**Comment by dceejay** [comment]
unusual - but 4.0.7 is still their latest build on npm.  If I run `npm i serialport`  in the /tmp  directory for example it downloads and builds in about 50 secs

![image](https://user-images.githubusercontent.com/5375409/27245132-bc0960b2-52e1-11e7-81c7-2f191ac877d0.png)

**Comment by onedumbtrucker** [comment]
Hmm, that does seem to work and then i was able to `npm i node-red-node-serialport` but I still get this when starting node-red

![image](https://user-images.githubusercontent.com/23708543/27290133-4d026bfa-54da-11e7-82f0-e14d0eb0e80d.png)

**Comment by hardillb** [comment]
Where did you run that command? Because that output shows it's trying to use the globally installed version and you ran npm with out a -g you will only install locally and not update the global version

**Comment by onedumbtrucker** [comment]
good question. I have tried so many diiferent things so many different ways. Now trying to start over from a fresh raspbian. This is where it all began and where it fails;
`bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)`

**Comment by onedumbtrucker** [comment]
Can I ask what may be a stupid question (I am an embedded programmer, still learning Linux) what is the difference between installing a node package globally or just in the node-red/ directory? I mean why would you need to install globally?

**Comment by dceejay** [comment]
not a stupid question. In general you don't need to install nodes globally... However... when we pre-install Node-RED we do so as root user and don't know what user you will pick to run as (though 99% of time folk start out as pi user) - no matter - net is we can't 100% guess what user they will use so need to pre-install globally and that includes the serialport. The upgrade script is normally very reliable and does the right thing if run exactly as you had it there. As long as that is run as the user you want to run as (normally pi), that  will then update node.js and Node-RED and then update the serialport and other global nodes... - no need to do it locally.

If you do just install / upgrade one of the pre-installed nodes then you will indeed end up with two versions - one global and one local... and things may/will get confused.

**Comment by dceejay** [comment]
The install script now moves nodes out of global space into the user space so that the palette manager can now uninstall or re-install them. This means that the serialport node would then be in s position for a normal install to work as per normal install / update instructions - ie from ~/.node-red directory  (after the upgrade script has been run). 

So closing this issue.
