### ISSUE TITLE
node-pisrf SRF05 bug

### ISSUE THREAD

**Issue by cyber035** [node-red/node-red-nodes#338]
Hello I have this strange problem when using Node Red module for reading SRF04 sensor.
After some time the sensor reports some high value and gets stuck so the only way to fix it is to reboot raspberry pi or reconnect sensor...
I tried with 3 different sensors same result...

Can you add like custom value that can be set from Node Red, that specifies interval in seconds between measurements - readouts from the sensor (sending pulse and measuring echo, then wait interval in seconds for next...).

That would solve my problem completely because when I use simple py script with bigger interval between measurements, everything works..

Thanks

**Comment by denisfrench** [comment]
I concur that the default interval is too short for an SRF04 on an RPi A+ (256MB) or RPi Zero W, leading to distance readings ceasing after several minutes. I don't have any other models to test with.

I have locally modified nrsrf.py to increase the interval to 2 seconds ( ie time.sleep(0.5) becomes time.sleep(2.0) ), which solved the issue for me. time.sleep(1.0) did not fix the problem.

This is an effective fix for me, but may not be suitable for time sensitive applications. Further investigation is probably warranted.

Thanks for your work on all these nodes; hundreds of thousands of us must be in your debt!

**Comment by dceejay** [comment]
Added the option to be able to set the repeat time in the config

**Comment by denisfrench** [comment]
Thanks for your quick fix for this @dceejay .

Looks like I spoke too soon and a longer interval just postpones the problem. That was a bit misleading on my part, but now you have a new feature :-D

I've added some debugging output locally, and this error is being thrown when the echo signal is not received:
> global name 'Main' is not defined

Give me a couple of days to play with it and I'll submit a pull request. I recommend this issue be re-opened until resolved.
