### ISSUE TITLE
msgpack.js -> overSized buffers generate an error, when it (probably) shouldn't

### ISSUE THREAD

**Issue by prochat** [node-red/node-red-nodes#341]
Receiving buffers larger than the msgpack content, the node doesn't decode them.

Problem is from msgpack-js (required by node-red-node-msgpack):
https://github.com/creationix/msgpack-js/issues/20

**Comment by dceejay** [comment]
The v0.1.26 of msgpack node was migrated to the newer msgpack-lite module instead as this supports the newer msgpack format as int64 etc... - does this also fix this problem ? Can we close it ?

**Comment by dceejay** [comment]
Closing as no response
