### ISSUE TITLE
When Delay is configured as "Delay each message" and "Set delay with msg.delay" the desktop 

### ISSUE THREAD

**Issue by diverjoe** [node-red/node-red-nodes#345]
![image](https://user-images.githubusercontent.com/5911531/28276792-f9110764-6ae5-11e7-812e-ad5a5627c3ac.png)

When Delay is configured as "Delay each message" and "Set delay with msg.delay" the desktop thinks the node is not configured correctly.  The node works as expected, but simply shows this warning.  

BTW - I have been needing this msg-based delay added to this node - I love it!

This is on NR v0.17.4

**Comment by knolleary** [comment]
Hi,

this is a core node, so ought to be raised on https://github.com/node-red/node-red

Can you export the node and share its JSON? I cannot reproduce manually.

**Comment by dceejay** [comment]
somehow your node has not got a timeout set (should be "5" by default and not "") - it should have a value even when not being used. Not sure how this can happen yet.

![image](https://user-images.githubusercontent.com/5375409/28284782-2a5011fa-6b2a-11e7-86af-12d5ebb9ac56.png)

**Comment by diverjoe** [comment]
That made the error go away.  That field is not visible when in Set Delay with Msg mode.   However, I would expect it to be blank in those instances as it is in other nodes that accept values in the msg when left blank.
