### ISSUE TITLE
JOIN tables result in missing data

### ISSUE THREAD

**Issue by MarcusTorndahl** [node-red/node-red-nodes#350]
**Package:** node-red-node-mysql@0.0.16
When querying data from two tables, with columns in the two tables with the same name (for instance **table1.id** and **table2.id**), by using JOIN the data from one of the columns are missing. 
(The two columns are not related two each other they only share the same name.)

For illustration purpose
**table1** {Id, Name, Description, ProductID, Active, Ordered}
**table2** {Id, Product, Description}

**SQL-query:**
SELECT * FROM table1 JOIN table2
ON table1.ProductID = table2.Id 
WHERE table1.ProductID = 1 AND Active = 1 
ORDER BY table1.Ordered ASC

**Result:**
[{Id, Name, Description, ProductID, Active, Ordered, Product}

**Comment by hardillb** [comment]
The workaround for this is to use the SQL `as` keyword to rename the columns to make them unique

**Comment by MarcusTorndahl** [comment]
Ok I tried using the SQL alias keyword (AS) with a couple of columns:

**SQL-query:**
SELECT table1.Id AS table1Id, table2.Id AS table2Id 
FROM table1 JOIN table2
ON table1.ProductID = table2.Id
WHERE table1.ProductID = 1 AND Active = 1
ORDER BY table1.Ordered ASC

**Result:**
[{table1Id, table2Id}]

Is there a cleaner way on selecting a prefix for all columns of each table? As I have numerous instances to update this would really be helpful :).

**Comment by chainhead** [comment]
I use this style:
```
SELECT t1.id, t2.id from table1 t1, table2 t2 where t1.productId = t2.Id
```
