### ISSUE TITLE
node-red-node-serialport two ports simultaneously?

### ISSUE THREAD

**Issue by FrankBillig** [node-red/node-red-nodes#351]
Hi,

I try to use two serial ports simultaneously, with no luck.
Every time I change the serial port of a node all other serial port nodes are changed too !?
So I am not able to have to nodes with different ports.
Each port alone works as expected.

Any hints?

Thanks

**Comment by knolleary** [comment]
You need to add a second serial port configuration. To do that, select 'add new serial-port...' from the drop-down list in the serial nodes edit window then click the pencil to add it.

**Comment by dceejay** [comment]
Hi 
please use the google group mailing list or slack channel for quick how-to type questions are there are more people there who can help you.

in the config just got to the select - 
![image](https://user-images.githubusercontent.com/5375409/29457806-fab9feda-8413-11e7-81ef-a226ed5eca80.png)
and add a new port
