### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by aelg305** [node-red/node-red-nodes#354]
Im using a RPi B (old, but does the trick...when it works)
Node: v6.11.2
I have a ninja cape (used to be an awesome project to control RF devices as well as other things...but they went broke :( )

I get the "Error: Could not locate the bindings file." 

My installation steps:
-install jessie-lite and:
sudo apt-get update -y
sudo apt-get upgrade -y

-install proper dependencies:
bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)
update-nodejs-and-nodered
update-nodejs-and-nodered
sudo apt-get install sense-hat

-any errors, check the log:
sudo cat /var/log/nodered-install.log

-start on boot:
sudo systemctl enable nodered.service

-install npm & packages:
sudo apt-get install npm -y
sudo npm install -g npm@2.x

sudo su     -I read somewhere that I needed to run node as root in order for serial to work!?  
hash -r
#cd ~/.node-red
cd /root/.node-red

sudo npm install -g node-red-contrib-ninja
sudo npm install -g serialport --unsafe-perm --build-from-source
sudo npm install node-red-node-serialport
 (tried with -g and without....also tried with sudo su and whitout)

Once I run "node-red-start"
I get:

Starting as a systemd service.
Started Node-RED graphical event wiring tool..
1 Sep 21:57:06 - [info]
Welcome to Node-RED
===================
1 Sep 21:57:06 - [info] Node-RED version: v0.17.5
1 Sep 21:57:06 - [info] Node.js  version: v6.11.2
1 Sep 21:57:06 - [info] Linux 4.9.35+ arm LE
1 Sep 21:57:13 - [info] Loading palette nodes
1 Sep 21:57:40 - [warn] ------------------------------------------------------
1 Sep 21:57:40 - [warn] [serialport] Error: Could not locate the bindings file. Tried:
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/build/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/build/Debug/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/build/Release/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/out/Debug/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/Debug/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/out/Release/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/Release/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/build/default/serialport.node
→ /usr/lib/node_modules/node-red-node-serialport/node_modules/serialport/compiled/6.11.2/linux/arm/serialport.node
1 Sep 21:57:40 - [warn] ------------------------------------------------------
1 Sep 21:57:40 - [info] Settings file  : /root/.node-red/settings.js
1 Sep 21:57:40 - [info] User directory : /root/.node-red
1 Sep 21:57:40 - [info] Flows file     : /root/.node-red/flows_node.json
1 Sep 21:57:40 - [info] Server now running at http://127.0.0.1:1880/
1 Sep 21:57:45 - [info] Waiting for missing types to be registered:
1 Sep 21:57:45 - [info]  - serial-port (provided by npm module node-red-node-serialport)
1 Sep 21:57:45 - [info]  - serial out (provided by npm module node-red-node-serialport)
1 Sep 21:57:45 - [info]  - serial in (provided by npm module node-red-node-serialport)
1 Sep 21:57:45 - [info] To install any of these missing modules, run:
1 Sep 21:57:45 - [info]   npm install <module name>
1 Sep 21:57:45 - [info] in the directory:
1 Sep 21:57:45 - [info]   /root/.node-red

**Comment by dceejay** [comment]
Hi - have just pushed out new version of serialport node.
Can you try that..
Also if on nodejs 6.x then you should be using npm 3.x.
And NO you don't need to run as root - so you may well need to clean out those files...
Alternatively if you are running as root  then you need to install the modules as root... into the user directory owned by root - rather than the one owned by the default user.
