### ISSUE TITLE
-pisrf Error stopping node: TimeoutError: timed out after 15000ms

### ISSUE THREAD

**Issue by SupotSaeEa** [node-red/node-red-nodes#355]
The -pisrf work perfectly with other widget such as dashboard, mqtt etc.
But whenever 'function' widget connect to output of -pisrf. I faced the problem of TimeoutError.
I try to publish out the output of -pisrf to Mqtt-out widget and use Mqtt-in to get result.
I put debug widget to Mqtt-in, I got perfectly result.
It weird when I connect 'function' to Mqtt-in, the TimeoutError problem is heppened.
The flow be caught up and not to use again. I will delete it and make new flow.

![image](https://user-images.githubusercontent.com/4257341/30002674-ba8f72b8-90d9-11e7-9f47-a5c1f519712f.png)

**Comment by dceejay** [comment]
Is this still a problem ? Can we close ?
If it is - we will need to dig deeper into some of that flow - there were definite bugs with the Mosca node for example that may now have been fixed (or not).

**Comment by SupotSaeEa** [comment]
Yes, please close this issue.
It still a problem.
