### ISSUE TITLE
Inject Once at Start is too soon...

### ISSUE THREAD

**Issue by rossnewby** [node-red/node-red-nodes#356]
When an inject node with 'inject once at start?' is used to initiate the mysql node, a Database not Connected error is thrown, despite the database details being correct. This means a delay (>= 1s) must be used, to give the database time to connect before the msg arrives; a rather sloppy work around which could maybe be incorporated into the node itself?

**Comment by dceejay** [comment]
Incorporated into which node ? the mysql node ? what happens if it never connects ? Does it store up all the messages that should have been sent ? until the memory runs out ? when does it throw them away ? Surely it should just report that it wasn't connected and you should retry ?

**Comment by Paul-Reed** [comment]
Yes! I get the same message, but just accept the message as information, not a need to rectify anything.
But yes, IMO it would be better if a delay stopped the message.
Does it really matter if messages during node-red-start are lost? the important thing is that messages are not lost once NR is powered up.

Paul

**Comment by rossnewby** [comment]
I've been using the node to populate a dashboard, therefore it took me a while to figure out the problem, since I want to populate the menu items as soon as the dashboard is launched. I felt as though input messages should be delayed slightly when the flow is first deployed to prevent others having the same issue, but perhaps some documentation about it would be better as Nick has explained the problem with that [here](https://groups.google.com/forum/#!topic/node-red/rTumyIumvO40)
