### ISSUE TITLE
Can't edit credentials on twilio node

### ISSUE THREAD

**Issue by Fohdeesha** [node-red/node-red-nodes#357]
I can no longer edit local credentials on the twilio node. When I click the edit button to add new credentials, nothing happens.

I believe it was this commit that broke it, as it worked fine before - https://github.com/node-red/node-red-nodes/commit/7af48ce10ba69a780e1ce268210ccfe3d3acc678

I get this error in the chrome dev console when clicking the edit button:

> red.min.js:16 Uncaught TypeError: Cannot use 'in' operator to search for 'format' in password
    at c (red.min.js:16)
    at p (red.min.js:16)
    at Object.success (red.min.js:16)
    at j (vendor.js:2)
    at Object.fireWith [as resolveWith] (vendor.js:2)
    at x (vendor.js:5)
    at XMLHttpRequest.b (vendor.js:5)

**Comment by dceejay** [comment]
That was just a documentation update. Which version of node.js are you using ? Which version of Node-RED ?

**Comment by Fohdeesha** [comment]
If you scroll down on that commit link you can see 56-twilio.js was also changed, specifically credential related code similar to what I'm getting in the chrome console when clicking the edit credentials button. it worked before that commit but my node-red version is 0.17.5 with node.js version of 6.11.3. Also getting the issue on my remote box which is running node-red 0.17.5 and node.js v6.11.2

**Comment by dceejay** [comment]
those are just formatting changes - placing the lines onto one line.

**Comment by Fohdeesha** [comment]
Good point - the only conclusion I can come to then is that an underlying node package that it relies on has introduced this bug. Can you install the twilio node and try clicking the edit credentials button to confirm this for me? I've done fresh node installs on 3 different systems now and am getting this issue on all of them

**Comment by nicklasl** [comment]
I also have this issue but for me it was the first time using this node, haven't added any credentials before.

**Comment by dceejay** [comment]
Thanks for spotting this. fix now pushed as version 0.0.15 on npm

**Comment by Fohdeesha** [comment]
Thanks so much!
