### ISSUE TITLE
Emoncms does not post numeric value zero

### ISSUE THREAD

**Issue by isteiner** [node-red/node-red-nodes#359]
The Emoncms does not post value if numerical value is zero. It works fine with other values except zero.
If the value is boolean FALSE than works.
![inject2emoncms](https://user-images.githubusercontent.com/2821783/31055347-cb8cb64a-a6c1-11e7-990d-fcdea45bada5.png)

Regards, Igor

**Comment by dceejay** [comment]
Hi,
not quite sure how that can happen. Can you do me a favour and edit the 68-emoncms.js file to add a line just before line 50 (the http.get(this.url,... line)... 
    console.log("EMONCMS",this.url);
then stop and restart Node-RED - in the console you should now see the url it's using to send the data... it should include something like json={something} or csv={something} - the    {something should be the value it posts...  what is that in the cases above ?
(please make sure you don't copy/paste your API key with any answer... :-)

**Comment by isteiner** [comment]
Hi dceejay,
thank you for fast replay, here are the results of test.
when inject value 2:
EMONCMS https://emoncms.org/input/post.json?json=2&apikey=xxxxxxxxxxxxx&node=88
when inject value 0:
EMONCMS https://emoncms.org/input/post.json?json=0&apikey=xxxxxxxxxxxxx&node=88

Actually I don't see a difference between both posts except values. Is this a problem with Emoncms itself?
Igor

**Comment by dceejay** [comment]
yeah - so looks more like an emoncms thing at present...
can you try a string 0  - "0"   (rather than numeric) ? see if that make a difference...
but yes - currently looks like we are sending the right thing.

**Comment by isteiner** [comment]
I tested with two data types:
First with string "0" and got:
EMONCMS https://emoncms.org/input/post.json?csv=0&apikey=xxxxxxxxxxxxxxxxxxxxx&node=88
this post has no influence on value on remore emoncms.org, value there stay unchanged (node 88)

Second I tried with boolean value FALSE:
EMONCMS https://emoncms.org/input/post.json?json=false&apikey=xxxxxxxxxxxxxxxxxxxx&node=88
this post changed remote value (node 88) on zero.

I'm quite sure this is the issue with emoncms platform, have to ask for additional help them.
Thanks again for help :)

**Comment by dceejay** [comment]
will let you close this when you get a reply / result from them.

**Comment by dceejay** [comment]
Any feedback from emoncms ?

**Comment by isteiner** [comment]
Just checked and unfortunately no feedback from emoncms :(
I solved my problem with using boolean variable.
