### ISSUE TITLE
add DM capability to twitter output node

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#36]
Because of the potential sensitivity about visibility of a DM versus a public tweet, it would be good if a twitter output node could be configured to send DMs.

So a "tweet" or "DM" pull down, and if you pick DM, it opens a text box to put in the recipient twitter ID. 
Then call the appropriate API to send either a normal tweet or a DM.

Workaround is to prepend "D andysc " to a tweet but it would be better if it could be explicit, because of the sensitivity of getting it wrong and publicly tweeting something ;)

Also wondering about the same for an @reply, if the "in response to" original tweet ID is available in the msg structure coming in from an inbound tweet... ?

**Comment by dceejay** [comment]
Enhancing Info panel to make it clear how to do DM.
(not feeling the need to make the UI more complex for this simple extra use)
