### ISSUE TITLE
twitter node won't be able to send DMs after 1-Nov

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#361]
Twitter is removing support for the "D {username} {message}" functionality of their API.
So the advice in the info tab to send DMs won't work.
We need a new way to send a DM.

Maybe an option in the node "tweet or DM", with either a hard-wired recipient, or the ability to pass it in in a msg. variable?

**Comment by fraz3alpha** [comment]
You beat me to it Andy! 

This library also uses the deprecated endpoint (https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update_with_media) and it will at some stage need to move to another one.

As some re-work will probably be required anyway, maybe the code should just parse the payload first and provide the same capability as before, but via a different implementation using the correct API calls to maintain this interface in Node-RED itself?

**Comment by andysc** [comment]
oh, yes please - that would save the change from breaking a whole load of my existing apps!

**Comment by hardillb** [comment]
@fraz3alpha you were already planing a pull request for your earlier Twitter node update.... ;-)

**Comment by andypiper** [comment]
Actually already will not allow you to send DMs as from Oct 1. It will let you opt-in to send the string as a regular Tweet. From Nov 1, that's default, and all the options go away.

For DMs you should use the new Direct Message "beta" endpoints for [event creation](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event).

For Tweets with media you'll need the two-step media upload, then Tweet with attached IDs, method.

**Comment by eRudy** [comment]
It seems that it's already broken. I don't receive DM anymore, and get this in the console:

> HTTP Error 403: Forbidden, API message: {"errors":[{"code":151,"message":"There was an error sending your message: DM commands are no longer allowed!."}]}

:/

**Comment by knolleary** [comment]
@eRudy yes - see the comment from @andypiper above.

We'll get this sorted as soon as we can... but if anyone wants to help out, just let us know!

**Comment by eRudy** [comment]
Indeed @andypiper had already said that it's broken, sorry.

I would love to help, but I do not think I can write a suitable clean code :(
But I can gladly help with testing if needed !

**Comment by mastix** [comment]
Hey guys,

are there any updates already?

Just a hint: I'm currently migrating from OpenHab to NodeRed and the OpenHab 2 Binding for Twitter can actually still send DMS. Maybe it's worth a look (although it's Java - but REST ist REST, right? :)).

Regards,

Sascha

**Comment by cbrandlehner** [comment]
Any updates on this? This one is still broken.

**Comment by hardillb** [comment]
I think the general hope was that someone would volunteer to help fix it as most of the core team are a bit busy with other things at the moment. It would make a good first issue for somebody new to start with...

**Comment by eRudy** [comment]
Hello,

As far as I understand the code and the new API, the module needs to change (only in the case of a direct message) a "simple" POST to 

https://api.twitter.com/1.1/statuses/update_with_media.json?status=D%20username%20direct%20message%20sent%20to%20username

with a POST to: 
https://api.twitter.com/1.1/direct_messages/events/new.json

with json data that look like: 
{
   "event": {
      "type": "message_create",
         "message_create": {
            "target": {
               "recipient_id": "1234567890"
            },
            "message_data": {
               "text": "Direct message sent to username!",
            }
         }
   }
}

Am I right ?

**Comment by eRudy** [comment]
So, I tried something... 
let me know if it works for you, too: https://github.com/eRudy/node-red-nodes.git

**Comment by ahreyes25** [comment]
Is this feature still broken? I've been trying all day to figure it out, thinking that it was an issue with my code, but now I'm starting to realize this may still not be working. Any updates?

**Comment by eRudy** [comment]
I think you all be happy with the last commit: https://github.com/eRudy/node-red-nodes/commit/7e342173aeab946a632b0e905ee0d872dcae11dd

I reduce the code needed, since all was already in the twitter-ng library :)

**Comment by knolleary** [comment]
@eRudy if you have something that works, we'd welcome a pull request so we can get the node updated!

**Comment by hardillb** [comment]
@eRudy if you submit the pull request now, we can review it for code style and probably offer any tips for improvement while people test it.

**Comment by eRudy** [comment]
Ok, so let's go ;)

**Comment by dceejay** [comment]
closed by 17744a51c0bc5afaa7a250c701b9dbe75d4b3c1d
