### ISSUE TITLE
daemon: multiple inject after restart

### ISSUE THREAD

**Issue by OpaStefanVogel** [node-red/node-red-nodes#365]
Flow:
inject "7+8;" ------> daemon -----> debug="15"
msg.kill="SIGQUIT" ----^
msg.start="" ---------------^

Inject "7+8" results in debug=15. This is ok.
If I stop the daemon with msg.kill and then restart with msg.start followed by inject "7+8", then I get the result debug="15 15". If I stop and restart daemon again, then I get debug="15 15 15", three times the "15" and so on four times, five times...

.flow: 
[{"id":"e78f5b16.6cb1d8", "type":"daemon", "z":"3616d484.0cd17c", "command":"node", "args":"-i", "cr":true,"redo":false,"op":"string", "name":"", "x":550,"y":60,"wires":[["46897335.78afec"],["46897335.78afec"],["46897335.78afec"]]},{"id":"970fc607.b4a798", "type":"inject", "z":"3616d484.0cd17c", "name":"", "topic":"", "payload":"7+8;", "payloadType":"str", "repeat":"", "crontab":"", "once":false,"x":130,"y":60,"wires":[["e78f5b16.6cb1d8"]]},{"id":"9df26e1f.8c471", "type":"inject", "z":"3616d484.0cd17c", "name":"start", "topic":"", "payload":"", "payloadType":"date", "repeat":"", "crontab":"", "once":false,"x":130,"y":220,"wires":[["183eddb.9110d22"]]},{"id":"46897335.78afec", "type":"debug", "z":"3616d484.0cd17c", "name":"", "active":true,"console":"false", "complete":"false", "x":790,"y":60,"wires":[]},{"id":"1baae0e6.8859df", "type":"function", "z":"3616d484.0cd17c", "name":"SIGQUIT", "func":"delete msg.payload;\nmsg.kill=\\"SIGQUIT\\";\nreturn msg;", "outputs":1,"noerr":0,"x":300,"y":140,"wires":[["e78f5b16.6cb1d8"]]},{"id":"349785c5.2fd15a", "type":"inject", "z":"3616d484.0cd17c", "name":"stop", "topic":"", "payload":"", "payloadType":"date", "repeat":"", "crontab":"", "once":false,"x":130,"y":140,"wires":[["1baae0e6.8859df"]]},{"id":"183eddb.9110d22", "type":"function", "z":"3616d484.0cd17c", "name":"start", "func":"msg.payload=\\"\\";\nmsg.start=\\"\\";\nreturn msg;", "outputs":1,"noerr":0,"x":290,"y":220,"wires":[["e78f5b16.6cb1d8"]]}]

Instead of [..."command":"node", "args":"-i"...] I have testet too [..."command":"python", "args":"-i -u"...] and [..."command":"gap", "args":""...] (https://www.gap-system.org) all with the same error multiple inject. Instead of SIGQUIT I have testet SIGKILL with the same error.

Node-RED version: v0.17.5                                                               
Node.js  version: v6.11.4                                                               
Linux 4.9.35+ arm LE (Raspberry Pi Zero W + Raspbian)

**Comment by OpaStefanVogel** [comment]
It works now, thank you!

**Comment by OpaStefanVogel** [comment]
A subsequent error? If I set the flag "Relaunch command on exit or error", deploy and send msg.kill, then daemon stops and restart after few seconds, this is ok. But then inject "7+8;" does not work??? I'm not sure and send the comment as a precaution.

**Comment by OpaStefanVogel** [comment]
Perfect! Both variants set flag and unset flag are ok. Thank you very much!

**Comment by dceejay** [comment]
Thanks for spotting and reporting it !
