### ISSUE TITLE
Arduino Uno not being interacted by the Arduino node.

### ISSUE THREAD

**Issue by ErFillion** [node-red/node-red-nodes#368]
Every times I try using the arduino input or output option, I always get the message ```[error] [arduino in:f29f48e.96bd8] TypeError: Cannot read property 'board' of null```
Is there a fix for this issue? and yes I have reconnected it. Currently only the serial nodes work.

**Comment by hardillb** [comment]
You are running firmata firmware on the Arduino?

**Comment by ErFillion** [comment]
how do I check that?

**Comment by knolleary** [comment]
@ErFillion This isn't about the firmware... its whether you have installed the firmata sketch onto your Arduino using the Arduino IDE?

See https://nodered.org/docs/hardware/arduino.html#firmata for details.

**Comment by ErFillion** [comment]
Yeah, haven't touched the firmware. Am I supposed to install firmata?

**Comment by knolleary** [comment]
Yes.
