### ISSUE TITLE
ECONNREFUSED ERROR

### ISSUE THREAD

**Issue by mshaz** [node-red/node-red-nodes#369]
I followed the steps and added this line in /etc/rc.local

/usr/bin/pigpiod -l

its giving ECONNREFUSED ERROR in nodered

**Comment by dceejay** [comment]
In general we prefer how-to questions and requests for help via either slack channel or google mailing list so a wider group of people can see the question and possibly help, keeping th eissue ist for actual bugs and confirmed code issues.

In this instance - how have you configured the node at the node-red end ? if you specified -l then only localhost will work (and Node-RED and pigpiod must be running on the same machine)

**Comment by mshaz** [comment]
I apologize on using github for questions.  

Nodered and pigpiod is running on the same machine. I want to control servo so i put inject node and pigpiod node. Host i left it as localhost 8888. It used to work then i did same putting /usr/bin/pigpiod -l in rc.local but it doesn't work . Do i have to run pigpiod daemon. 

Thank you

**Comment by dceejay** [comment]
That should work as that is how they suggest to run it - you need to reboot to make it start.

**Comment by mshaz** [comment]
I did reboot. Its not working. 
![image](https://user-images.githubusercontent.com/16055146/32557955-99073b56-c4de-11e7-9a03-84666152b457.png)

**Comment by dceejay** [comment]
if you run

    netstat -an | grep 8888

does it show that the process is running ? eg something like
tcp6       0      0 ::1:8888                :::*                    LISTEN

**Comment by mshaz** [comment]
nothing

**Comment by dceejay** [comment]
then it's not running...
make sure that is the correct path for the pigpiod file...  

     which pigpiod

should give you the full path, and that the rc.local ends with an exit 0

**Comment by mshaz** [comment]
It works but i got to run sudo pigpiod at /usr/bin manually. How do i make it start auto?

I have 4 servos to control how do i do this using functions node? Suppose i want to move 2 foot servos up and down at same time? 


![image](https://user-images.githubusercontent.com/16055146/32560294-3961ca44-c4e4-11e7-8059-881153bada3f.png)

**Comment by knolleary** [comment]
Hi, please take any further questions you have to the [node-red mailing list](https://groups.google.com/forum/#!forum/node-red). This isn't the forum for answering basic how-to questions. Thanks!

**Comment by dceejay** [comment]
final thought on autostart... read the manual ;-) https://gpiozero.readthedocs.io/en/stable/remote_gpio.html#command-line-manual
