### ISSUE TITLE
Serial-port hang

### ISSUE THREAD

**Issue by Eckehard** [node-red/node-red-nodes#370]
Hy all,

using node-red-node-serialport on RPi Model 1+ and 2B. communication stops after some time and can only be reestablished by:

a) unplugging serial port
b) resetting node red
c) deploy the current flow

Details see: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/node-red/72exwkAfGdw/c7mQ3ZXQBwAJ
related posts: 
https://github.com/raspberrypi/linux/issues/1187
https://github.com/node-red/node-red/issues/881

If there is no cleaner solution, maybe it´s possible to include some watchdog function to restart communication? Any other suggestions?

Best regards
Eckehard

**Comment by dceejay** [comment]
which version of Node-RED ? node.js ? and version of serialport node ?
the first two are logged in the cmd window when you start Node-RED, the serialport version should be found by `cd ~/.node-red && npm ls serialport`
