### ISSUE TITLE
wemo node prevents node-red boot when Neeo brain plugged into network

### ISSUE THREAD

**Issue by Roaders** [node-red/node-red-nodes#378]
This probably isn't a node-red issue but I thought that I would post to see if anyone can shed some light on what might be happening.

I have bought a Neeo remote control (https://neeo.com/) which has a brain. I think that the remote and brain communicate over wifi and the brain plugs into the network to control hue lights, sonos ect and some other network devices.
As well as node red not booting it seems to be affecting network performance generally. Turning my hue lights on and off through node-red is really slow and streaming / web pages seem slow.

I've posted on the neeo forum as well to get some idea of what is going on.

Any help or suggestions much appreciated.

**Comment by hardillb** [comment]
unplug the Neeo....

**Comment by hardillb** [comment]
What error messages do you get when Node-RED fails to start

**Comment by Roaders** [comment]
yup, already tried unplugging - that's how I managed to diagnose it!! :-)

**Comment by Roaders** [comment]
```
Started Node-RED graphical event wiring tool..
21 Nov 21:08:23 - [info]
Welcome to Node-RED
===================
21 Nov 21:08:23 - [info] Node-RED version: v0.16.2
21 Nov 21:08:23 - [info] Node.js  version: v6.10.2
21 Nov 21:08:23 - [info] Linux 4.9.24-v7+ arm LE
21 Nov 21:08:24 - [info] Loading palette nodes
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py info
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
21 Nov 21:08:28 - [info] Dashboard version 2.3.9 started at /ui
21 Nov 21:08:32 - [info] Settings file  : /home/pi/.node-red/settings.js
21 Nov 21:08:32 - [info] User directory : /home/pi/.node-red
21 Nov 21:08:32 - [info] Flows file     : /home/pi/.node-red/flows_livingroompi.json
21 Nov 21:08:32 - [red] Uncaught Exception:
21 Nov 21:08:32 - TypeError: Parameter "url" must be a string, not undefined
at Url.parse (url.js:88:11)
at Object.urlParse [as parse] (url.js:82:5)
at SsdpClient.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:121:24)
at emitThree (events.js:116:13)
at SsdpClient.emit (events.js:194:7)
at SsdpClient.parseResponse [as _parseResponse] (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:372:8)
at SsdpClient.SSDP._parseMessage (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:215:10)
at Socket.onSocketMessage (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:170:10)
at emitTwo (events.js:106:13)
at Socket.emit (events.js:191:7)
at UDP.onMessage (dgram.js:549:8)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
```

**Comment by hardillb** [comment]
OK, so it looks like it's responding like a WeMo device, but not 100% the same.

We should add some better error handling so it doesn't crash. but the error looks to be coming from within the SsdpClient node so it might have to be an upstream bug.

I'll look but it will have to be at the weekend.

**Comment by Roaders** [comment]
According to the forum for Neeo I think that it pretends to be a wemo switch for integration with Alexa - seems like a pretty hacky thing to do to me and prone to cause issues like this...

**Comment by dceejay** [comment]
Can we close this now ?

**Comment by hardillb** [comment]
I vote yes

**Comment by Roaders** [comment]
I can't test it anymore as I sold my neeo remote. It's probably still an issue but I would say not an issue with this lib, am issue with Neeo instead. I'll close it.
