### ISSUE TITLE
Node-red-node-wemo output nodes forgetting device when using multiple wemos

### ISSUE THREAD

**Issue by eford321** [node-red/node-red-nodes#379]
When configuring multiple wemo outlets (ie; family room, living room table, living room wall), device settings are lost and each node defaults to one of the same device option (ie; family room).

**Comment by hardillb** [comment]
What browser are you using?

**Comment by eford321** [comment]
Browser is Safari 11.0.1.
Wemo node is 0.1.13.
Node red is v0.17.4.
no errors.

tried with chrome 62.0.3202.94 and have the same result. opening the Wemo output node and editing the device changes the devices in all Wemo nodes.

**Comment by hardillb** [comment]
Are you using real WeMo devices or things pretending to be WeMo devices.

Have you restarted Node-RED?

This shouldn't be possible as all the devices are config nodes, so it's basic low level Node-RED stuff to handle that selection and can't be affected by the node it's self

**Comment by eford321** [comment]
They are real WeMo v1 switches. They're running the latest firmware and I have reconfigured them from scratch.   I have restarted Node-Red multiple times. No change.   

Any ideas of other things to try?

**Comment by hardillb** [comment]
I've just set up a new install here and I can't reproduce this.

All I can think is you are using the edit function rather than adding new WeMo devices when you change one of the nodes.

For each device you need to use the "Add new wemo-dev" option then click on the pencil icon. If you just click on the pencil and change the selected device it will change the device bound to that config node (and as such change all the nodes)

**Comment by hardillb** [comment]
Did the last update help?

**Comment by eford321** [comment]
I was editing wrong by not using the "Add new demo-dev" option.  Sorry for the waste of your time on this.   Its is working perfectly now. 

Is there any documentation or example configuration for the WeMo nodes? I could not find any.
Thanks!

**Comment by hardillb** [comment]
Only that info sidebar and my blog posts about when I wrote the nodes. 

https://www.hardill.me.uk/wordpress/2016/01/11/new-wemo-nodes-for-node-red/

https://www.hardill.me.uk/wordpress/2017/04/06/more-improvements-to-the-wemo-node-red-nodes/
