### ISSUE TITLE
node-red-node-serialport: serial out node not work

### ISSUE THREAD

**Issue by kangskii** [node-red/node-red-nodes#384]
Hello,

I am now applying the node-red-node-serialport on an embedded liniux 4.4.18 yocto platform (Siemns IOT2040 https://support.industry.siemens.com/tf/ww/en/conf/60/).
Node-RED version: v0.15.2, Node.js version: V6.9.2. GCC version: 5.3.0

Here is my test steps.
(1) serial in node 
A PC-based serial port utility(Spu) is used to send data to the IOT2040 via serial port /dev/ttyS0 over USB2TTL connection. Serial in node can receive the data.

(2)  serial out node 
An inject node, sending data at specified interval, is connected to the serial out node, with the same serial port configuration. The PC-based serial port utility(Spu) is used to receive data.
Nothing showed.

I have used the oscilloscope to see the output of serial out node in step (2), also with nothing showed.
Obviously, the driver of  serial out does not work.

Can you please help to locate the problem ?

**Comment by dceejay** [comment]
Is the node correctly installed . does it appear in the palette ok ?
Any messages in the console log on startup ? or when in use ?
Does the out node work if the in node is removed ?

**Comment by kangskii** [comment]
Hi,
Thanks for your reply.
It worked after I enabled the UART in IO2000setup.
