### ISSUE TITLE
sqlite node makes node-red malfunction

### ISSUE THREAD

**Issue by st3inar** [node-red/node-red-nodes#385]
After installing and utilizing the sqlite node in my flows, node-red halts and does not operate correctly. The "Node not deployed" error keeps popping up whenever i try to activate a debug node.

Any ideas?

node-red v0.15.3.

**Comment by dceejay** [comment]
In general we prefer how-to type questions via the mailing list or slack channel where more people can see them and offer suggestions. What does the console log report ? Which versions of Node-RED ? What hardware platform/ OS ? Did the node install correctly ? Which sqlite node ?
