### ISSUE TITLE
stream error: http (401)

### ISSUE THREAD

**Issue by battosai30** [node-red/node-red-nodes#387]
Hi,

Since ~1 month, my twitter nodes stop to work properly. I get in debug tab "stream error: http (401)".

To be sure that the problem was not coming from my server, I installed nodered on another one and got exactly the same error. I check my log, the problem seemed to appear without any intervention. 

I tried with two different Twitter account, same error.

Any idea ?

Regards

Nodered versions : 6.12.2 and 8.9.3

**Comment by andypiper** [comment]
How many instances of the Twitter nodes are you running on your nose-red runtime? Twitters streaming API only supports 2 concurrent connections and after that you’ll find that new connections disconnect any previous ones.

**Comment by battosai30** [comment]
Hi, 

Only one. I tested on another server (the third so !) and this time it works. As this server is a fresh install, and the other two not, I suppose there is a conflict with another package ... But which could it be ?

**Comment by battosai30** [comment]
Ok I got it : my server had a time shifting and Oauth considers request as outdated. More informations here : https://github.com/sixohsix/twitter/issues/285

I just did a NTP time adjusting and it was good.

Regards

**Comment by knolleary** [comment]
Ah yes - I forget about that gotcha. Glad to hear its resolved.
