### ISSUE TITLE
How to control the silent-interval in node-red-serial-in/out ?

### ISSUE THREAD

**Issue by kangskii** [node-red/node-red-nodes#388]
Hello,

I want to set and check the time interval within one message frame, and between consecutive message frames in serial-in and out nodes.

Could you please tell how to set the time interval between
(1) two consecutive bytes in a message frame ?
(2) two message frames ?

Do I have to develop application program to realize this, or does the serial in/out configurations support this ?

Thanks.

**Comment by dceejay** [comment]
Hi as per our contribution guidelines we generally prefer how-to type questions via the mailing list or slack channel in the first instance so more people can see them and respond.
The serial port node itself doe not have any rate limiting features apart from setting the baud rate like any of the serial port.  If you need gaps between bytes then you can use a delay node set to rate-limit mode to slow down the flow of messages to the serialport. Whether this is in between each byte or between groups of bytes is up to you.

**Comment by kangskii** [comment]
Hello,
Thanks for your reply.
The delay node encapsulates all the function within, i.e. cache all coming commands and send the first cached command when specified timeout has been reached.

The commands cached in Delay node will be sent at fixed time interval, say T1. My current requirement is: if the response has been received in a very very short time, less than T1, then the first cached command should be sent immediately, rather than still waiting for fixed time T1.

Could you please give some support to this topic ? If I don't use available delay node, are there any available class/object for cache management ?
Thanks.

**Comment by dceejay** [comment]
No, I said to use it in RATE-LIMIT mode. This sends the first straight away.
