### ISSUE TITLE
RBE node would benefit from a reset function

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#389]
There are times when it would be useful to be able to tell the RBE node to forget its stored value, so that the next value that comes in will be passed through to the output, regardless of whether or not it is the same as the previous value.

For consistency with the trigger node, this could be sent in using msg.reset.

The RBE node has topic-level functionality, so I would suggest the ability to clear the buffer on either one topic, or *all* topics. This could be done by putting the topic name as the value of msg.reset (to clear a specific topic), or empty (or True?) to reset all buffers on all topics.

**Comment by andysc** [comment]
I think it does on the trigger node, doesn't it? i.e. you don't have to put any content in the message, just the existence of it is enough. So I think we should be consistent... i.e. an empty message resets all, a string is treated as a topic to try to reset just that one.

**Comment by dceejay** [comment]
since when has consistency had anything to do with it ;-)   we want "clearly defined areas of doubt and uncertainty" 

(agree)

**Comment by andysc** [comment]
:D

**Comment by dceejay** [comment]
Q2) during a reset operation... should the msg.topic be relevant... ? ie should it be the msg.topic that specifies which topic to reset (as per trigger node) rather than the text in msg.reset.

(currently the trigger node ONLY has reset specific topic - pointed at by msg.topic - you can't clear all)

**Comment by andysc** [comment]
I didn't know trigger node is topic specific ???!!! It doesn't mention that in the info tab...

**Comment by dceejay** [comment]
Ah - may not be in the released version yet...

![image](https://user-images.githubusercontent.com/5375409/34153610-93dbfb30-e4aa-11e7-8cc4-da4bad448083.png)

**Comment by andysc** [comment]
oh, wow, that's fabulous! Thank you.

So back to your question, then... Hmm, not sure - if you think of setting up a change node to reset the RBE, in my mind, I'd set msg.reset and then set it to some value. If I then had to remember to add a msg.topic and set that to some value, it kind of makes it two steps (even though in the same change node).
On the other hand, putting a topic string anywhere other than in msg.topic just feels wrong.

So, I think, yes, msg.topic for the topic, and msg.reset just needs to exist and have *something* in it, to reset the RBE node.

**Comment by dceejay** [comment]
so then ... that leads to the question... 
if msg.topic is blank/non-existent - we currently treat that as an "other" bucket. So msg.reset with no msg.topic would "just" reset this bucket... or reset all ? 
(I think just reset the "other" bucket)

**Comment by dceejay** [comment]
Hmm just changed my mind... I think now maybe reset all... as we don't have a way in rbe to specify if we are doing rbe per topic or not (always yes) - so not sure just clearing the "other" bucket has much value/understanding.

**Comment by dceejay** [comment]
Ok - msg.reset capability added
adding "any" msg.reset will cause a reset.
If msg.topic is specified then just that "queue" is reset - if not then the whole node is reset.
Closed by 032a9d64357177dc967ec098bcd452473e6a0266

**Comment by muglar** [comment]
Hi dceejay,

I'm testing this functionality with version 1.14.  It appears that sending a msg.reset property with no topic doesn't reset the rbe node in full or at all.  See below.  I would assume that injecting once would allow one value to pass, but no it doesn't.

What am I doing wrong?


[{"id":"264cf8ba.b58718","type":"rbe","z":"f6ad3e79.294ec","name":"","func":"deadband","gap":"0.4%","start":"","inout":"out","x":500,"y":420,"wires":[["88130663.fb9bb8"]]},{"id":"732cc981.2b89c8","type":"inject","z":"f6ad3e79.294ec","name":"","topic":"topic1","payload":"1.6","payloadType":"num","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":420,"wires":[["264cf8ba.b58718"]]},{"id":"88130663.fb9bb8","type":"debug","z":"f6ad3e79.294ec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":670,"y":420,"wires":[]},{"id":"ce36c118.c6c1a","type":"inject","z":"f6ad3e79.294ec","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":520,"wires":[["2173eeb6.2cc442"]]},{"id":"2173eeb6.2cc442","type":"change","z":"f6ad3e79.294ec","name":"","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"},{"t":"delete","p":"topic","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":500,"wires":[["264cf8ba.b58718","88130663.fb9bb8"]]}]
