### ISSUE TITLE
io/emoncms - requires update to new API syntax and options

### ISSUE THREAD

**Issue by borpin** [node-red/node-red-nodes#391]
The emoncms input API has been changed recently and I think that the node requires an update to meet the new specification allowing full json.

**Comment by borpin** [comment]
I have done a bit of work on this so that the node will now accept a valid JSON object and successfully push it to Emoncms server running 9.8.27 (which is what I needed).  I have put the files in a [gist ](https://gist.github.com/borpin/6adfc5be44e558785ae2e9fbdc8345ed) for now.

I have modified the node so that the type of data is selectable, rather than the node having to guess.  this allows for a legacy mode which should work exactly as before.

I have modified the time input to accept ISO dates or seconds.  Yes I used Date.parse which is not always ideal, to check the validity of the date.  Emoncms does more checking so it is probably safe to do.

I cannot easily check this node of other types of data.

**Comment by hardillb** [comment]
Any reason not to follow the contribution guidelines and submit a pull request rather than the gist? It makes it a lot easier to see how the changes fit with the existing code.

**Comment by borpin** [comment]
Part of the guidelines is to not do that until there has been a discussion :).  I'm also new to collaborating on GitHub so I'm a little concerned I may do something 'unfortunate'.  I have it in a local repository using GitHub Desktop.

**Comment by dceejay** [comment]
One of the main things to check is how the changes affect existing flows... It's all too easy to all the new features to seem to be non-conflicting - but does an existing node open up with sensible defaults in any new fields etc... - but yes - happy for you to put up a PR to look at if you like.

**Comment by borpin** [comment]
It is a little tricky to check how the flow will impact existing flows as I had to modify it to get it to work n the first place as the underlying server API has changed.

So this may sound daft, but how do I do a PR. Should I have created a fork first?

**Comment by Paul-Reed** [comment]
Yes, create a fork of `node-red-nodes`, make your changes to the fork, test, and then submit a PR for consideration & discussion.

**Comment by borpin** [comment]
Ok, I think I have managed that.  I wait and see :)

**Comment by dceejay** [comment]
closing this as should now be fixed... please repoen if the new PR didn't fix (Or create a new issue)
