### ISSUE TITLE
Add different mcp's in dropdown menu

### ISSUE THREAD

**Issue by shubham0490** [node-red/node-red-nodes#394]
Hi, please add mcp3208 and others in selection options, these are already supported by mcp-spi-adc dependency

**Comment by knolleary** [comment]
This repository contains many different nodes. Which node in particular are you talking about?

**Comment by dceejay** [comment]
Or possibly a PR to look at ?

**Comment by shubham0490** [comment]
hi, node is mcp3008 and i have already modified the code for my project you can see the files https://github.com/shubham0490/mcp3208
it would be better if we can select the MCP via dropdown menu, these are already updated in mcp-spi-adc library, i was trying but getting errors.
