### ISSUE TITLE
MCP3008 will not work.  Error SPI interface can't find SPI device.

### ISSUE THREAD

**Issue by albertstuder** [node-red/node-red-nodes#396]
I installed on Raspi 3 Node Red Version 8.9.4 with NPM Version 5.6. I installed module 'node-red-node-pi-mcp3008'. But every time an error come up   'can't find SPI device'. Because I had an old setup with the same driver working i found out that the file pimcp3008.js was different from the old one. I took the old file and the module was working again. Probably there Is a problem of selecting the different devices mcp3002 till mpc3304 in the new version. The old version had only mcp3008 selected.

**Comment by dceejay** [comment]
Many thanks for reporting this...
basic typo in the new method names... mea culpa ! 
now fixed and pushed.

**Comment by albertstuder** [comment]
Thanks for immediate response. Now it works perfectly.
