### ISSUE TITLE
Timeout is appending to serial output as newline

### ISSUE THREAD

**Issue by insolite** [node-red/node-red-nodes#399]
#### STR
1. Create "Serial Out" node and any output injection node connected to it
2. Open serial port config from node configuration
3. In the `Input` section select "Split input" as "on the character"
4. In the `Output` section below check "add split character to output messages"
5. Change "Split input" to "timeout", type `200` as timeout value (note that disappeared checkbox from the previous step)
6. Confirm port and node config, deploy flow
7. Inject message, (in my GSM modem case it's `AT+CMGF=1`, for example)

#### ER
`AT+CMGF=1` was sent to serial port

#### AR
`AT+CMGF=1200` was sent to serial port

#### Conclusion
As we see here, `200` at the end was appended as newline, cause timeout is saved under this variable regardless to "Split input" choice and [there is no check](https://github.com/node-red/node-red-nodes/blob/d8263eab251bf48fb80844d3969403505e0c0f96/io/serialport/25-serial.js#L39) that `node.serialConfig.out` is actually `char`.

Node-RED version: v0.17.5
Node.js version: v9.3.0

I hope that should be enough to reproduce the issue but here is my flow just in case:
```json
[
    {
        "id": "4eca797.ad2c788",
        "type": "inject",
        "z": "6caeafa0.a82a4",
        "name": "AT+CMGF",
        "topic": "",
        "payload": "AT+CMGF=1",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 120,
        "y": 60,
        "wires": [
            [
                "bb71d488.dc2028"
            ]
        ]
    },
    {
        "id": "bb71d488.dc2028",
        "type": "serial out",
        "z": "6caeafa0.a82a4",
        "name": "GSM modem",
        "serial": "7f0f693f.f305c8",
        "x": 340,
        "y": 60,
        "wires": []
    },
    {
        "id": "7f0f693f.f305c8",
        "type": "serial-port",
        "z": "",
        "serialport": "/dev/ttyS0",
        "serialbaud": "9600",
        "databits": "8",
        "parity": "none",
        "stopbits": "1",
        "newline": "200",
        "bin": "false",
        "out": "time",
        "addchar": true
    }
]
```

**Comment by dceejay** [comment]
great bug report... many thanks.
