### ISSUE TITLE
Reset function not documented on rbe node

### ISSUE THREAD

**Issue by vzorglub** [node-red/node-red-nodes#400]
Hello,
The reset function is not explained in the information documentation on the node-red info tab.
I have tried to use it on reading the code but I am getting something wrong.
Thanks

**Comment by knolleary** [comment]
Hi - this repository contains main nodes. Please specify which node you are raising this issue against.

Thanks!

**Comment by vzorglub** [comment]
I have updated the title of the issue
It is concerning the rbe node
apologies
Vincent

**Comment by dceejay** [comment]
Hi - which version of the node do you have installed ? the latest one is 0.2.0 and has
![image](https://user-images.githubusercontent.com/5375409/35652848-60c8ef1e-06dd-11e8-8e5f-9bcd961c1889.png)
If msg.topic is set AND msg.reset exists then it will reset the rbe for that topic. If just msg.reset is set it will flush all topics.

**Comment by vzorglub** [comment]
Hi,
I had updated node-red and assumed that this node had updated too.
It turns out it didn't and I had to update via npm manually only this node.
I can see the comment now.
And it's working just as planned
Thank you
Issue closed I presume
