### ISSUE TITLE
node-red-node-serialport: 100% CPU use if serial port is used by another process 

### ISSUE THREAD

**Issue by Dannsei** [node-red/node-red-nodes#406]
### What are the steps to reproduce?

1. create a flow communicating via serialport using node-red-node-serialport 
2. run a Python script also using the serial port (using pySerial module, not set to exclusve access to the serial port)

### What happens?

node red works as expected and CPU usage is minimal until the Python script is run.  When the Python script starts running, node red uses all available CPU, and continues to do so even after the Python script terminates and until node red is stopped.  Serial communication in both node red and Python works without errors.  When node red is not running, the Python script runs with minimal CPU usage.

### What do you expect to happen?

no excessive CPU use when sharing access to the serial port.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.2
- [ ] node.js version: 8.9.4
- [ ] npm version:
- [ ] Platform/OS: Raspbian OS Stretch (Linux 4.9.59+ #1047) 
- [ ] Browser:

using node-red-node-serialport v.0.6.3 

(running on Raspberry Pi Zero Wireless)

**Comment by dceejay** [comment]
Closing in sync with ref to other issue.
