### ISSUE TITLE
uncaught exception in twitter input node

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#409]
I *think* it's the twitter input node.

19 Feb 13:01:49 - [info] Started flows
19 Feb 13:01:49 - [red] Uncaught Exception:
19 Feb 13:01:49 - Error: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at TLSSocket.socketCloseListener (_http_client.js:245:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:487:12)

There are no other network-interacting nodes in my flow (apart from MQTT input)

19 Feb 13:03:10 - [info] Node-RED version: v0.18.0
19 Feb 13:03:10 - [info] Node.js  version: v4.6.2

**Comment by dceejay** [comment]
Is this reproducible ?

**Comment by andysc** [comment]
probably not ;)

**Comment by dceejay** [comment]
has it happened again ?

**Comment by andysc** [comment]
no, I haven't used that flow much on 0.18.0, but I haven't seen it again.

**Comment by dceejay** [comment]
OK closing this for now then.

**Comment by andysc** [comment]
yup, that's fine
