### ISSUE TITLE
node-red-node-pilcd Hardware Question

### ISSUE THREAD

**Issue by joearkay** [node-red/node-red-nodes#413]
Hi, 

I wouldn't usually use Github issues for hardware questions, but I can't find too much info on the node-red-node-pilcd usage other than on this repo! 

Do we require level shifters, or can the HD44780 lcd be connected directly to the GPIO? 

Adafruit's wiring example (different library, mind) connects the lcd up directly (https://cdn-learn.adafruit.com/downloads/pdf/drive-a-16x2-lcd-directly-with-a-raspberry-pi.pdf). 

However, my LCD seems to show bogus data, and then clears when I try and use my node-red-flow to update the screen (flow below):

`[{"id":"4626b928.e182f8","type":"rpi-lcd","z":"3fc08e34.cfde82","name":"","pins":"26,24,22,18,16,12","x":480,"y":280,"wires":[]},{"id":"a587d296.c247a","type":"inject","z":"3fc08e34.cfde82","name":"","topic":"","payload":"Hello World","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":200,"wires":[["4626b928.e182f8"]]}]`

I've made sure the RPi.GPIO library has been installed & updated, and have stopped/started node-red, with no avail. 

Have tested the LCD with an Arduino and it works fine. 

Thank you.

**Comment by dceejay** [comment]
Should be ok direct... are you sure you have the pins connected in the correct order 
RS,E,D4,D5,D6,D7
we use the physical pin numbers

**Comment by dceejay** [comment]
Also note that pins 26 and 24 that you have chosen are dual use with CE0 and CE1 - so if you have SPI enabled (via raspi-config) then you may be getting a conflict.

**Comment by joearkay** [comment]
Hi @dceejay - I'm giving this a go now. The reason I chose pins 26,24,22,18,16 and 12 was because these were the pins detailed in the readme.

**Comment by joearkay** [comment]
Ok I've moved to pins 31,29,23,21,19,15 and I can confirm the same problem as before - when first powered up, the display shows bogus data. I inject my 'hello world' string twice, which updates the screen two times with bogus data, clearing it on the third. 

I have disabled SPI and still the same problem?

**Comment by joearkay** [comment]
Here's an annotated image of the setup, using the pins from the guide (26,24,22,18,16,12):

https://drive.google.com/file/d/1bZQ8v5XwWPyTr4-dmWO8zVomk48np24d/view?usp=sharing

Again, I'm confident that the connections LCD-side are correct, as I have tested this using an Arduino with the liquidcrystal library.

**Comment by joearkay** [comment]
Honestly a little stumped now, appreciate the help so far.

**Comment by dceejay** [comment]
Me too - I'll try to get my hands back on the lcd I was testing with when we wrote it. It was a HD44780 type.

**Comment by topcat1959** [comment]
Hi @dceejay - I am experiencing the same issue as @joearkay is having - i have checked the wiring over and over - tried to avoid any pins on the Pi that could be troublesome.  waiting on any potential issue i may not have looked at - 
Tom

**Comment by dceejay** [comment]
seemed to be a timing issue initialising the display... - I have pushed a slight change - (version 0.0.7 ) let me know if it now works for you...

**Comment by joearkay** [comment]
Hi @dceejay - this worked, thank you for sorting it. 

@topcat1959 - I had to completely remove the node, deploy changes and then reconfigure the lcd node for it to start working after updating the lib and rebooting node-red. I'm happy to close this, now, if you are happy @topcat1959 ? 

Thanks all, especially @dceejay

**Comment by topcat1959** [comment]
I will check this evening!  I appreciate the work on this!

**Comment by joearkay** [comment]
@topcat1959 You should be able to follow the instructions above - so I'm closing this issue.

**Comment by topcat1959** [comment]
Sorry for the late reply – got the flu – but yes all good!!
