### ISSUE TITLE
node-red-node-pilcd - Bug for displays with >2 lines

### ISSUE THREAD

**Issue by joearkay** [node-red/node-red-nodes#416]
Hi @dceejay - thanks for the work fixing the timing bug with this library. 

However, whilst working on developing my system with node-red, I've discovered another bug. It seems that for my 20x4 LCD display, lines 1 and 2 behave normally (as per the [readme](https://www.npmjs.com/package/node-red-node-pilcd), however lines 3 and 4 don't give expected behaviour. 

Sending a msg.payload of `3: 123456789abcdefghijk` will actually start the text at position 13. The text then overflows onto line 2, when you would expect it to overflow to line 4. 

Likewise, doing the same with `4:123456789abcdefghijk` starts again at position 13, overflowing onto line 1. 

I've taken some images:

[LCD Line 1](https://drive.google.com/file/d/1t9Q2ee8MwSEIgnusSv7BRLzbnhFNeqKN/view?usp=sharing) - this behaviour is expected

[LCD Line 2](https://drive.google.com/file/d/1WMvJZgvgN-q_QENwcI1l848DhUFtjUdw/view?usp=sharing) - Again, expected behaviour 

[LCD Line 3](https://drive.google.com/file/d/1W1wJW3ZpQCN8ezmyvoZZxcpD19-dBrTK/view?usp=sharing) - Not expected - bug?

[LCD Line 4](https://drive.google.com/file/d/1IXpzVQtXvaRRYqeFTLKmG8oJYl4Nwlcb/view?usp=sharing) - Not expected - bug? 

See below the node-red flow that I'm using for this test. I'm issuing the `clr:` command between tests:

```
[{"id":"2bd698e2.f190f8","type":"rpi-lcd","z":"316032e9.3dc69e","name":"","pins":"26,24,22,18,16,12","x":1540,"y":180,"wires":[]},{"id":"6966692b.28f4a8","type":"inject","z":"316032e9.3dc69e","name":"Clear the LCD","topic":"","payload":"clr:","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1270,"y":100,"wires":[["2bd698e2.f190f8"]]},{"id":"f0db392b.5125d8","type":"inject","z":"316032e9.3dc69e","name":"","topic":"","payload":"2:123456789abcdefghijk","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1290,"y":400,"wires":[["2bd698e2.f190f8"]]},{"id":"33ebfff4.5c504","type":"inject","z":"316032e9.3dc69e","name":"","topic":"","payload":"4:123456789abcdefghijk","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1290,"y":480,"wires":[["2bd698e2.f190f8"]]},{"id":"e75ebdd1.922b8","type":"inject","z":"316032e9.3dc69e","name":"","topic":"","payload":"3:123456789abcdefghijk","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1290,"y":440,"wires":[["2bd698e2.f190f8"]]},{"id":"cb88f229.1fbf8","type":"inject","z":"316032e9.3dc69e","name":"","topic":"","payload":"1:123456789abcdefghijk","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1290,"y":360,"wires":[["2bd698e2.f190f8"]]}]
```

Thanks

**Comment by dceejay** [comment]
Hi, great bug report...
Can you do me a favour... :-).... If you can find the file `nrlcd.py` and edit lines 34 and 35
currently

    LCD_LINE_3 = 0xA0 # LCD RAM address for the 3rd line
    LCD_LINE_4 = 0xE0 # LCD RAM address for the 4th line

can you fiddle with the numbers and tell me what they should be... I'd expect maybe 0x94 and 0XD4 ?
Thanks

**Comment by joearkay** [comment]
Hi @dceejay - Sorry I was away - would have loved to have helped, but it looks like you've sorted - thanks!

**Comment by dceejay** [comment]
Well - I hope so - but please confirm it's now working for you.

**Comment by joearkay** [comment]
@dceejay I've just realised the version number is still showing as 0.0.7 (within the Node-RED palette) however [you've updated to 0.0.8?](https://github.com/node-red/node-red-nodes/commit/34199142ddd5a8760fd72dd7417abdfdcfa67a57)

**Comment by dceejay** [comment]
sorry - is there on npm now

**Comment by joearkay** [comment]
No worries at all - thank you.
