### ISSUE TITLE
Request SQLite Node -- Pass database file via msg.

### ISSUE THREAD

**Issue by scottrcarlson** [node-red/node-red-nodes#417]
Request: Pass database filename via msg payload to sqlite node.

@dceejay, thanks for the recent update to include prepared statements, excellent!

Thanks Again.

**Comment by dceejay** [comment]
as per the contribution guidelines we prefer suggestions and discussion via the mailing list or slack channels so the wider community can get involved, leaving the issue list for actual bugs and issues.

by passing the database in on payload you would need to open and close a connection on every message. This is not good for performance in any way so unlikely to be implemented. (but we will see if there is a good reason)
