### ISSUE TITLE
Moving node does not cause inject node to fire once on "Deploy Modified flows"

### ISSUE THREAD

**Issue by andig** [node-red/node-red-nodes#418]
Consider this flow (inject with initial message after 0.1s -> trigger (reset after 2s) -> debug):

	[{"id":"47661190.83f43","type":"inject","z":"e3e3666a.550d1","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":"0.1","x":170,"y":110,"wires":[["97b7a741.920c2"]]},{"id":"2755aae3.99049e","type":"debug","z":"e3e3666a.550d1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":560,"y":240,"wires":[]},{"id":"97b7a741.920c2","type":"trigger","z":"e3e3666a.550d1","op1":"received","op2":"missing","op1type":"str","op2type":"str","duration":"2","extend":true,"units":"s","reset":"","bytopic":"all","name":"","x":360,"y":170,"wires":[["2755aae3.99049e"]]}]

After deploying the flow it should trigger after 2.1s but doesn't.

**Comment by dceejay** [comment]
errr.  it sends  "received" after 0.1 seconds and then "missing" after 2.1 seconds

http://g.recordit.co/PUtfvsRmSS.gif

works fine here....

**Comment by andig** [comment]
Doesn't here. Move a node, click deploy. Nothing.

**Comment by dceejay** [comment]
a) does it work if you manually click the inject ?
b) try increasing the initial delay on start in the inject node.

what hardware are you running on ? which version of Node-RED, OS, etc ?

**Comment by andig** [comment]
When I add logging to console I get nothing more than:

	22 Mar 15:54:54 - [info] Stopping modified flows
	22 Mar 15:54:54 - [info] Stopped modified flows
	22 Mar 15:54:54 - [info] Starting modified flows
	22 Mar 15:54:54 - [info] Started modified flows

No log of the trigger unless I manually inject.

**Comment by dceejay** [comment]
so - what happens if you set the inject timer to be 3 secs for example ?

**Comment by andig** [comment]
Ok, slowly- sorry for not being clearer node-red docker:latest, just upgraded to 0.18.4 running on Synology NAS.

Think I've found it. "Deploy modified flows"- after just moving a box- does simply not deploy the flow. So- no initial message because no flow deployment.

Wondering if it would be possible to ensure "Deploy" button doesn't get enabled when there's nothing to deploy really?

**Comment by dceejay** [comment]
Hmmm - now that DOES look like a bug... 
If you moved it that is a change... 
And for example turning off and on the debug output does cause it to fire...

**Comment by dceejay** [comment]
actually this should be against the main project... :-)

**Comment by andig** [comment]
I'll move it
