### ISSUE TITLE
Can not install MCP 3008 with new NodeRed Version

### ISSUE THREAD

**Issue by xVini16x** [node-red/node-red-nodes#423]
NodeRed v.0.18.4

Error log says: Failed at the spi-device@1.0.2 install script

**Comment by dceejay** [comment]
which version of node.js ?
have you enabled SPI interface on the Pi ?
what happens if you try to install it manually ?
  
    cd ~/.node-red
     npm install node-red-node-pi-mcp3008

**Comment by xVini16x** [comment]
Nodejs v8.10.0
yes i have spi interface enabled, everything worked before i updated nodered with the update script
Manually the same error appears: 

Failed at the spi-device@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is it working for you?

**Comment by dceejay** [comment]
yes - works fine... :-)
try `npm cache clean --force`
then retry

**Comment by xVini16x** [comment]
thanks for the quick reply, now some different errors poped up... i will inform you when something new comes up, it will take a few days sadly

**Comment by dceejay** [comment]
different - but related to this ? or unrelated ?
