### ISSUE TITLE
irc: receiving (and/or sending) of `/me` message

### ISSUE THREAD

**Issue by hibiyasleep** [node-red/node-red-nodes#427]
*sending* can be easily done with sending raw messages, but receiving isn't really easy as normal `PRIVMSG`. Could this be improved?

**Comment by dceejay** [comment]
Hi - as per the contribution guidelines, generally we prefer feature requests to go via a discussion on the mailing list or slack channel to see if anyone has thoughts or ideas that can help. I must admit we haven't looked at this node for a long while so I can't easily guess what the answer may be. I do think it used to handle priv messages but I could be mistaken.

More than happy for someone to have a look and raise a PR to be looked at if they wish.
