### ISSUE TITLE
Run Java jar file in Daemon node ?

### ISSUE THREAD

**Issue by bohtho** [node-red/node-red-nodes#428]
I´m not your most savvy node.js or unix user, but could you explain why I only get errors running "java -jar [...]" with "java" as command and "-jar path/file -arguments" as arguments ? It works just fine in the terminal. The specific error is that it cannot find a usb device from inside the Daemon node versus in the terminal. Is that a known/logical issue ? (maybe not java issue per se, but device permissions?!)

**Comment by dceejay** [comment]
Hi as per the contribution guidelines we prefer general how-to queries via the mailing list or slack channel so the widest possible audience can jump in and help.

To answer - quite possibly...  Node-RED is running as the user you set it to run as... (eg on Pi the default is the pi user) - if that user doesn't have permission to access the device then it won't be able to. You may need to add the user to a group that does have access to whatever device it is.
