### ISSUE TITLE
email node username and password not copying when exporting clipboard

### ISSUE THREAD

**Issue by Kartheek1512** [node-red/node-red-nodes#432]
I created a node-red flow which has an email node. I want to copy it in 10 other raspberry pis. So, I imported the clipboard and pasted it in the 10 pis. Now, I dont see the email user name and password that i entered in the 1st pi. Do I have to manually enter email username and password to all the email nodes in every Pi? 
Can anyone help me with any other alternative?
1. By telling me the location of file where the email node saves the username and password? May be I can copy that file to the new pis too. 
2. Can I send the username and password through a function node?

**Comment by hardillb** [comment]
This is working as designed, The credentials are not kept in the editor (browser) once the node has been deployed, they are only kept on the runtime side as it would be a security vulnerability if they could be accessed from the browser or copy & pasted elsewhere.

All usernames and passwords are stored in the encrypted `[flow_name]_cred.json` file in the user directory (normally `~/.node-red` if you copy the that file and the flow file between machines then the whole flow and all it's credentials should be copied as well. But it is important to note that each machine will generate it's own random encryption key for the creds file which is stored in the `~/.config.json` in the _credentialSecret key. You will also need to copy this across as well.

If you use the new projects feature you are asked for the _credentialSecret value when you set up a project and when you clone it to a new location, this may be easier than copying manually.

In future please use the Mailing list or Slack channel (both linked to at the bottom of the Node-RED website) to ask questions (as pointed out in the [Contribution Guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)  as issues are normally used for defects.
