### ISSUE TITLE
node-red-node-pi-neopixel

### ISSUE THREAD

**Issue by cymplecy** [node-red/node-red-nodes#434]
I think something has gone wrong with git merging see lines 116-126 in neopixels.js

> <<<<<<< Updated upstream
        node.child = spawn(piCommand, [node.pixels, node.wipe, node.mode, node.brightness, node.gamma]);
        node.status({fill:"green",shape:"dot",text:"ok"});
||||||| merged common ancestors
        node.child = spawn(piCommand, [node.pixels, node.wipe, node.mode]);
        node.status({fill:"green",shape:"dot",text:"ok"});
=======
        if (allOK === true) {
            node.child = spawn(piCommand, [node.pixels, node.wipe, node.mode]);
            node.status({fill:"green",shape:"dot",text:"ok"});
>>>>>>> Stashed changes

**Comment by dceejay** [comment]
Yikes - thanks - re-edited and pushed as 0.0.18
