### ISSUE TITLE
node-red-node-pi-unicorn-hat 0.17 not connecting

### ISSUE THREAD

**Issue by ijengland** [node-red/node-red-nodes#435]
Since upgrading to 0.0.17 the node-red-node-pi-unicorn-hat is no longer able to connect to the unicorn HAT on my Raspberry Pi 2. Node Status = rpi.gpio.status.not-available. It was working on the previous version and my unicorn HAT works with a alternative node.

**Comment by dceejay** [comment]
in the main console.log - is there an error reported ? it should have `rpi-unicorn` in the relevant line

**Comment by dceejay** [comment]
Ah.. was checking for an invalid command - now pushed 0.0.18

**Comment by ijengland** [comment]
Great. Thanks very much! Much appreciated.

**Comment by dceejay** [comment]
You're welcome. Thanks for reporting it so quickly.
