### ISSUE TITLE
base64 node ver 0.1.1 does not decode base64 string in to buffer.

### ISSUE THREAD

**Issue by Vini74** [node-red/node-red-nodes#437]
It always decode base64 string to string!

- [ ] Node-RED version: 0.18.4
- [ ] node.js version: nodejs-8.11.1
- [ ] npm version: 5.8.0
- [ ] Platform/OS: CentOS Linux release 7.4.1708 (Core)
- [ ] Browser: CHROME (windows)

**Comment by knolleary** [comment]
Hi - please can you provide an example flow that demonstrates the issue you are report?

**Comment by Vini74** [comment]
This exampe with base64 ver 0.1.0 works fine.

[{"id":"ef2b5ad3.b503f8","type":"inject","z":"257c50b.3cc53b","name":"","topic":"","payload":"[123,34,65,66,67,68,69,70,34,58,34,49,50,51,52,53,34,125]","payloadType":"bin","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":80,"wires":[["1f8e72da.17f74d"]]},{"id":"bacc266c.3d4f98","type":"debug","z":"257c50b.3cc53b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":650,"y":140,"wires":[]},{"id":"1f8e72da.17f74d","type":"base64","z":"257c50b.3cc53b","name":"","property":"payload","x":300,"y":80,"wires":[["9b1c76cc.349ef8","bacc266c.3d4f98"]]},{"id":"9b1c76cc.349ef8","type":"base64","z":"257c50b.3cc53b","name":"","property":"payload","x":480,"y":80,"wires":[["bacc266c.3d4f98"]]}]

**Comment by Vini74** [comment]
This exampe with base64 ver 0.1.1 returns String
[{"id":"ef2b5ad3.b503f8","type":"inject","z":"257c50b.3cc53b","name":"","topic":"","payload":"[123,34,65,66,67,68,69,70,34,58,34,49,50,51,52,53,34,125]","payloadType":"bin","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":80,"wires":[["1f8e72da.17f74d"]]},{"id":"1f8e72da.17f74d","type":"base64","z":"257c50b.3cc53b","name":"","action":"","property":"payload","x":300,"y":80,"wires":[["9b1c76cc.349ef8","bacc266c.3d4f98"]]},{"id":"9b1c76cc.349ef8","type":"base64","z":"257c50b.3cc53b","name":"","action":"","property":"payload","x":480,"y":80,"wires":[["bacc266c.3d4f98"]]},{"id":"bacc266c.3d4f98","type":"debug","z":"257c50b.3cc53b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":650,"y":140,"wires":[]}]
