### ISSUE TITLE
[node-red-node-xmpp] 	xmpp in node isn't working

### ISSUE THREAD

**Issue by RingoAl** [node-red/node-red-nodes#438]
### Which node are you reporting an issue on?
node-red-node-xmpp
### What are the steps to reproduce?
I've added xmpp-in node, and linked it to debug.
If I send a message to node-red XMPP user nothing happens. There are no any messages on debug tab.
Also, if only xmpp-in node is present (without xmpp-out), node-red XMPP user is in offline state.

### Please tell us about your environment:

Node-RED version: v0.18.4
node.js version: v8.11.1
npm version: 6.0.0
Platform/OS: Raspberry Pi 3 model B
Browser: Google Chrome 66.0.3359.117

**Comment by zosky** [comment]
the **out node** is a flawless replacement for my *hack* _( an exec node with `sendxmpp`)_

the **in node** shows connected, but output nothing on either port ?

nodeRed: _0.18.1_
node.js: _8.9.4_
npm: _6.0.0_
node-red-node-xmpp: _0.1.7_
platform: _Ubuntu 16.04.4 LTS_
xmpp server: _talk.google.com_

**Comment by RingoAl** [comment]
I've uncommented this line (42) `xmpp.setPresence('online', node.nick+' online');` in `.node-red/node_modules/node-red-node-xmpp/92-xmpp.js` and, it seems, that in node now working fine.

**Comment by dceejay** [comment]
Currently re-working this node - so will update soon

**Comment by dashingsuma** [comment]
Hello, I need to create an xmpp server via Node-red I am not getting any tutorial or example.
