### ISSUE TITLE
upgrade to non-deprecated version of nodemailer

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red-nodes#439]
```
nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
```

**Comment by hardillb** [comment]
yeah, Just seen that as well, I knew it had changed at some point but looks like it's back to being good to use

**Comment by boneskull** [comment]
...which isn't a bad thing, since Node.js v4 is EOL'd now.

**Comment by knolleary** [comment]
Not a bad thing... but we still have the headache of node 4 being in Debian
Stable and the default on Jessie. Would mean Pi users would no longer have
the email node until they used our update script to get onto LTS

**Comment by dceejay** [comment]
well they need to install npm anyway in order to install extra nodes so...

**Comment by boneskull** [comment]
@dceejay they can do it thru the palette

**Comment by dceejay** [comment]
not without npm they can't

**Comment by hardillb** [comment]
No, t he palette just uses npm....

**Comment by boneskull** [comment]
you have to install npm separately??

**Comment by hardillb** [comment]
Welcome to Debian....

**Comment by dceejay** [comment]
on debian yes - and the version in apt is v1.x !!!

**Comment by knolleary** [comment]
you guys, you know we have a real-time chat tool for conversations like this...

**Comment by dceejay** [comment]
as long as the conclusion gets documented back here...
