### ISSUE TITLE
XMPP room control 

### ISSUE THREAD

**Issue by tomdavidson** [node-red/node-red-nodes#449]
I would like my node red flow to create temporary private xmpp to treat as a message channel. I can contribute but am hoping for some level direction.

https://www.npmjs.com/package/simple-xmpp doesn't have direct reserved group control, but I think I could do this by sending presence stanza to the room to create?

**Comment by dceejay** [comment]
HI - I'm afraid I'm not a big user of XMPP - so don't really know what to suggest. You may be better asking in the discourse.nodered.org forum - but happy to consider any Pull Requests you may like to contribute.

**Comment by tomdavidson** [comment]
Thanks for the quick reply. Ill reopen if needed.
