### ISSUE TITLE
Can't install node-red-node-serialport v0.6.7

### ISSUE THREAD

**Issue by Chart3JS** [node-red/node-red-nodes#454]
Hi,
my Node Red server running on Raspberry Pi (node -v 10.4.1 ) stoped to read modbus data with node-red-node-serialport  v0.6.7 Now I get an error when try to install it again from Pallete, using of command line brings the same result:

Jun 18 19:02:15 raspberrypi Node-RED[942]: 18 Jun 19:02:15 - [info] Server now running at http://127.0.0.1:1888/
Jun 18 19:02:57 raspberrypi Node-RED[942]: 18 Jun 19:02:57 - [info] Installing module: node-red-node-serialport, version: 0.6.7
Jun 18 19:03:19 raspberrypi Node-RED[942]: 18 Jun 19:03:19 - [info] Installed module: node-red-node-serialport
Jun 18 19:03:19 raspberrypi Node-RED[942]: 18 Jun 19:03:19 - [info] Added node types:
Jun 18 19:03:19 raspberrypi Node-RED[942]: 18 Jun 19:03:19 - [info]  - node-red-node-serialport:serial in : Error: Could not locate the bindings file. Tried:
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/default/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/compiled/10.4.1/linux/arm/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]: 18 Jun 19:03:19 - [info]  - node-red-node-serialport:serial out : Error: Could not locate the bindings file. Tried:
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/default/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/compiled/10.4.1/linux/arm/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]: 18 Jun 19:03:19 - [info]  - node-red-node-serialport:serial-port : Error: Could not locate the bindings file. Tried:
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Debug/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/out/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/Release/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/build/default/serialport.node
Jun 18 19:03:19 raspberrypi Node-RED[942]:  → /home/pi/.node-red/node_modules/serialport/compiled/10.4.1/linux/arm/serialport.node

Please help to solve the issue

**Comment by dceejay** [comment]
Can you try with node 8.x ?
Otherwise did you clear the npm cache. And then rebuild the serial port node. ? What errors does that give?

**Comment by Chart3JS** [comment]
dceejay it worked with node 8.x and 9.x as well. I tried to clear npm cache as you suggested, and now I get another error message on the install: 
```
Jun 18 21:57:35 raspberrypi Node-RED[1666]: 18 Jun 21:57:35 - [warn] ------------------------------------------
Jun 18 21:58:46 raspberrypi Node-RED[1666]: 18 Jun 21:58:46 - [info] Installing module: node-red-node-serialport, version: 0.6.7
Jun 18 21:59:01 raspberrypi Node-RED[1666]: 18 Jun 21:59:01 - [warn] Installation of module node-red-node-serialport failed:
Jun 18 21:59:01 raspberrypi Node-RED[1666]: 18 Jun 21:59:01 - [warn] ------------------------------------------
Jun 18 21:59:01 raspberrypi Node-RED[1666]: 18 Jun 21:59:01 - [warn] npm WARN deprecated parser-byte-length@1.0.2: renamed to @serialport/parser-byte-length
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm WARN deprecated parser-cctalk@1.0.2: reanmed to @serialport/parser-cctalk
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm WARN deprecated parser-readline@1.0.2: reanmed to @serialport/parser-readline
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm WARN deprecated parser-regex@1.0.2: reanmed to @serialport/parser-regex
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm WARN deprecated parser-ready@1.0.2: reanmed to @serialport/parser-ready
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm WARN deprecated parser-delimiter@1.0.2: reanmed to @serialport/parser-delimiter
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm ERR! code EAI_AGAIN
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm ERR! errno EAI_AGAIN
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm ERR! request to https://registry.npmjs.org/npmlog failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm ERR! A complete log of this run can be found in:
Jun 18 21:59:01 raspberrypi Node-RED[1666]: npm ERR!     /home/pi/.npm/_logs/2018-06-18T21_59_01_140Z-debug.log
Jun 18 21:59:01 raspberrypi Node-RED[1666]: 18 Jun 21:59:01 - [warn] ------------------------------------------
```

Here's  /home/pi/.npm/_logs/2018-06-18T21_59_01_140Z-debug.log last lines:

`307 timing stage:runTopLevelLifecycles Completed in 11985ms
308 silly saveTree node-red-project@0.0.1
308 silly saveTree ?~T~T?~T~@?~T? node-red-node-serialport@0.6.7
308 silly saveTree   ?~T~T?~T~@?~T? serialport@6.2.0
308 silly saveTree     ?~T~\?~T~@?~T~@ bindings@1.3.0
308 silly saveTree     ?~T~\?~T~@?~T~@ commander@2.15.1
308 silly saveTree     ?~T~\?~T~@?~T? debug@3.1.0
308 silly saveTree     ?~T~B ?~T~T?~T~@?~T~@ ms@2.0.0
308 silly saveTree     ?~T~\?~T~@?~T~@ nan@2.10.0
308 silly saveTree     ?~T~\?~T~@?~T? parser-byte-length@1.0.2
308 silly saveTree     ?~T~B ?~T~T?~T~@?~T~@ safe-buffer@5.1.2
308 silly saveTree     ?~T~\?~T~@?~T~@ parser-cctalk@1.0.2
308 silly saveTree     ?~T~\?~T~@?~T~@ parser-delimiter@1.0.2
308 silly saveTree     ?~T~\?~T~@?~T~@ parser-readline@1.0.2
308 silly saveTree     ?~T~\?~T~@?~T~@ parser-ready@1.0.2
308 silly saveTree     ?~T~\?~T~@?~T~@ parser-regex@1.0.2
308 silly saveTree     ?~T~\?~T~@?~T? prebuild-install@2.5.3
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ detect-libc@1.0.3
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ expand-template@1.1.1
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ github-from-package@0.0.0
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ minimist@1.2.0
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ mkdirp@0.5.1
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ node-abi@2.4.1
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ noop-logger@0.1.1
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ os-homedir@1.0.2
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ rc@1.2.8
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ simple-get@2.8.1
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ tar-fs@1.16.2
308 silly saveTree     ?~T~B ?~T~\?~T~@?~T~@ tunnel-agent@0.6.0
308 silly saveTree     ?~T~B ?~T~T?~T~@?~T~@ which-pm-runs@1.0.0
308 silly saveTree     ?~T~\?~T~@?~T~@ promirepl@1.0.1
308 silly saveTree     ?~T~\?~T~@?~T~@ prompt-list@3.2.0
308 silly saveTree     ?~T~T?~T~@?~T~@ safe-buffer@5.1.2
309 verbose type system
310 verbose stack FetchError: request to https://registry.npmjs.org/npmlog failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
310 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
310 verbose stack     at ClientRequest.emit (events.js:182:13)
310 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:382:9)
310 verbose stack     at TLSSocket.emit (events.js:182:13)
310 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
310 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
310 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
311 verbose cwd /home/pi/.node-red
312 verbose Linux 4.14.34-v7+
313 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-prefix=~" "--production" "node-red-node-serialport@0.6.7"
314 verbose node v10.4.1
315 verbose npm  v6.1.0
316 error code EAI_AGAIN
317 error errno EAI_AGAIN
318 error request to https://registry.npmjs.org/npmlog failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
319 verbose exit [ 1, true ]
`

**Comment by Chart3JS** [comment]
Hi, I reproduced a situation when I do node js version upgrade on Raspberry Pi to v10.0.0 and try to run modbus serial I get 
`Error: TypeError: this._client.isOpen is not a function`
in log file
 In the Pallete I see node-red-node-serialport version 0.6.6 and a suggestion for update to 0.6.7. If I make an update it fails with the  above message

**Comment by dceejay** [comment]
node 10 is not yet on the underlying serialport library list of supported versions - so please stick to the recommended node 8.x for now

https://github.com/node-serialport/node-serialport#platform-support

**Comment by dceejay** [comment]
closing as no reply - but fix should work.
