### ISSUE TITLE
Splitting Serial Input by `\n` Does Not Work

### ISSUE THREAD

**Issue by KSR-Yasuda** [node-red/node-red-nodes#457]
I tried serial input node with splitting by **`\n`**,
but it does not output any message on enter-key push.

Other settings (such as `a` and `a`-key push, ` ` (space) and space-key push, etc.) does work.

What is worse, *it is the default setting.*

### Environment:

- **Node-RED version:** v0.17.5
- **node.js version:** v6.11.2
- **npm version:** v3.10.10
- **Platform/OS:** Ubuntu 16.04.4 LTS (x64)
- **Node-RED Node:** `node-red-node-serialport` v0.6.7
    - **Serial Port Setting:** `/dev/tty` (Other ports will also fail)

**Comment by dceejay** [comment]
Hi - in general we prefer problems to be discussed on either the slack channel or discourse forum (as per the form you deleted) prior to raising an issue so as many people as possible can help rather rely on the core developers.

can you share a flow that shows this failure ? 
Are you sure the terminal is sending what you think it is  ? As stty for example can be configured to send different things for the Enter key.

**Comment by KSR-Yasuda** [comment]
> Are you sure the terminal is sending what you think it is ?

Rechecking what Enter-key sends, it was rather **`\r` (0x0D)** than `\n` (0x0A) on Ubuntu.
Setting separate char `\r` made it work as expected.

I am not familiar, but is this OS specific?
Anyway, I think making `\n` default is confusable...

----

Flow is below.
Default serial-port `newline` param was `\n`.

```json
[
    {
        "id": "4d0beb92.56dc64",
        "type": "serial in",
        "z": "ca764784.09d5b8",
        "name": "",
        "serial": "dbc220bb.d27eb",
        "x": 94,
        "y": 20,
        "wires": [
            [
                "e1f55c4.a9c99a"
            ]
        ]
    },
    {
        "id": "e1f55c4.a9c99a",
        "type": "debug",
        "z": "ca764784.09d5b8",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 285,
        "y": 20,
        "wires": []
    },
    {
        "id": "dbc220bb.d27eb",
        "type": "serial-port",
        "z": "",
        "serialport": "/dev/tty",
        "serialbaud": "115200",
        "databits": "8",
        "parity": "none",
        "stopbits": "1",
        "newline": "\\r",
        "bin": "false",
        "out": "char",
        "addchar": false
    }
]
```

**Comment by KSR-Yasuda** [comment]
And sorry for overlooking about the [Forum](https://discourse.nodered.org) etc. in issue draft note.

**Comment by dceejay** [comment]
Hi - No worries.
most Linux line endings are \n so we chose that as a default... changing it now would probably break anyone. But yes we could add something to the info / hints to suggest alternatives.
