### ISSUE TITLE
nodegroup fake ERROR

### ISSUE THREAD

**Issue by wifixcort** [node-red/node-red-nodes#459]
### Which node are you reporting an issue on?
Emoncms Push Node
### What are the steps to reproduce?

Create a custom function and add to the message a nodegroup(msg.nodegroup = "someting") and leave blank "Node" field in "Emoncms Push Node"
### What happens?
If you make the above configuration although the message already has the nodegroup, nodered sends an error message. In emoncms the node enters without any problem.

This is the fake error: ERROR: A Node group must be specified - undefined
### What do you expect to happen?
Read if the incoming message have a nodegroup: 

- If it have it then, all is good

- if not throw and error message
### Please tell us about your environment:

- [ v0.17.5] Node-RED version:
- [ v6.14.3] node.js version:
- [ 3.10.10] npm version:
- [ Debian 9.4] Platform/OS:
- [ Chromiun 66.0.3359.117] Browser:

**Comment by dceejay** [comment]
which version of the emoncms node do you have. I've just tried 0.2.1 and it seems to work fine in that scenario.

```
[{"id":"969232a.24beed","type":"inject","z":"745a133b.dd6dec","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":2400,"wires":[["bda3cab2.1b9778"]]},{"id":"bda3cab2.1b9778","type":"change","z":"745a133b.dd6dec","name":"","rules":[{"t":"set","p":"nodegroup","pt":"msg","to":"someting","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":270,"y":2400,"wires":[["a33799b8.038ce8"]]},{"id":"a33799b8.038ce8","type":"emoncms","z":"745a133b.dd6dec","name":"Emoncms Push","emonServer":"ec4aff1.cf9b3","nodegroup":"","datatype":"CSV","x":480,"y":2400,"wires":[]},{"id":"ec4aff1.cf9b3","type":"emoncms-server","z":"","server":"http://localhost","name":""}]
```

**Comment by dceejay** [comment]
closing as no reply
