### ISSUE TITLE
support HTML-mode in Pushover node

### ISSUE THREAD

**Issue by cowchimp** [node-red/node-red-nodes#467]
Hi.

Would you be interested in a Pull-Request that will allow setting `html` mode on an outgoing Pushover notification?
It's a mode they now support which means that if you include HTML in your notification payload it will be rendered accordingly.
You can read about it in their [docs](https://pushover.net/api#html).

If you are interested, would you like me to include this is a radio-button in the node UI, or just as an option which you can enable by setting the `html` property of the `msg` passed to the Pushover node?

Thanks.

**Comment by dceejay** [comment]
Sounds good. Checkbox or select box preferred. Default to existing so existing flows continue to work please.

**Comment by knolleary** [comment]
Sounds reasonable - probably should be an option to enable html handling.

For future reference, *please* read the issue template you are shown when raising issues. You would have seen we prefer feature requests to be made via the forum, rather than the issue tracker.
