### ISSUE TITLE
Broken link in node-red-node-blinkstick readme

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-nodes#472]
### Which node are you reporting an issue on?

node-red-node-blinkstick

### What are the steps to reproduce?

Broken link in README - http://www.w3schools.com/html/html_colornames.asp now 404s

This was reported to me via email with the suggestion to replace it with their own page here: https://dgtl.link/colors

I admire their attempt to improve their own SEO - we should review that post and see if it is a suitable alternative. I'm not sure we need a link to a full explanation of web colours, rather an authoritative list of valid html colour names.

**Comment by dceejay** [comment]
this works also - https://www.w3schools.com/colors/colors_names.asp

**Comment by dceejay** [comment]
closed by f3b0e2277d20ecf5dba00849bd95f54a8c313f9a
