### ISSUE TITLE
dant views parameters

### ISSUE THREAD

**Issue by richardtomsett** [node-red/node-red-nodes#477]
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
@richardtomsett accidental issue opening or are there some specific details to follow?

**Comment by richardtomsett** [comment]
@knolleary sorry Nick, totally accidental, browser went funny. Will close.
