### ISSUE TITLE
STOMP node becomes inactive after restart 

### ISSUE THREAD

**Issue by thiamcheng** [node-red/node-red-nodes#478]
### Which node are you reporting an issue on?
node-red-node-stomp
### What are the steps to reproduce?
When ActiveMQ has restarted, the node-red stomp node will become inactive, and it requires NodeRED to be deployed again to activate the stomp node. 
### What happens?
Stomp node becomes inactive, not able to consume any incoming messages. 
### What do you expect to happen?
Stomp node should be activated once the ActiveMQ restarted and do not require any intervention from NodeRED to redeploy the flow. 
### Please tell us about your environment:

- [ ] Node-RED version:  v0.17.2
- [ ] node.js version:  v6.10.3
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Linux 3.10.0-693.2.2.el7.x86_64 x64 LE
- [ ] Browser: Mozilla

**Comment by dceejay** [comment]
Good spot - hopefully new version  0.0.11 should fix retries
