### ISSUE TITLE
node-red-daemon should have an option to prevent autostarting

### ISSUE THREAD

**Issue by davericher** [node-red/node-red-nodes#479]
As useful has this is for monitoring long running processes, it would be nice to have a way to start those processes at our leisure rather then them auto-starting when the engine is fired up

https://github.com/node-red/node-red-nodes/blob/35cbcb3345ff9551129ef60a77995ee8ad298598/utility/daemon/daemon.js#L131

**Comment by dceejay** [comment]
Hi - in general we prefer ideas and suggestions via the discourse forum so the wider community can discuss them first, though I don't see any reason not to do this, as we already have msg.start to restart if you kill the process.
