### ISSUE TITLE
MySQL Node - User name and password reset at reboot

### ISSUE THREAD

**Issue by kpagnat** [node-red/node-red-nodes#484]
Hi,

Thanks for the mysql-node which is working just great.
However, everytime my raspberry reboots, it reset the parameters User and Password of the database.

I looked in the json flows and of course the user and password are not saved.

Is that something normal ? Can it be changed ?

Thanks !
Kevin

**Comment by hardillb** [comment]
This project contains lots of different Node-RED nodes, you are going to have to be explicit about which one use are using.

**Comment by kpagnat** [comment]
I edited my first message to add the information that I'm using mysql database node.

**Comment by kpagnat** [comment]
Ok, I found a not proper solution by editing the 68-mysql.js and specifying my credentials in raw.
It works now !
