### ISSUE TITLE
node-red-node-email always fetches 0.1.29

### ISSUE THREAD

**Issue by BerndGewehr** [node-red/node-red-nodes#485]
Caused by the lock file https://github.com/node-red/node-red-nodes/blob/master/social/email/package-lock.json, my node.red installation always fetches version 0.1.29 of the node-red-node-email node.

I want to use 1.0.3 now - but did not find  a way to upgrade correctly on bluemix node-red 0.19.3 with node 8.x.

**Comment by knolleary** [comment]
@BerndGewehr this is not related to the package-lock.json file in this module.

Node-RED 0.19.3 pulls in 0.x of the email node as that level of node-red still has to support Node 4 and 6.

The latest version of the email node requires Node 8.

When we release Node-RED 0.20, we drop support for Node 4/6 and will be able to pull in the 1.x stream of the email node.

There really isn't much we can do about this before then. Sorry.

Have you tried adding an explicit entry for `node-red-node-email@1.0.3 in your application's package.json?

**Comment by BerndGewehr** [comment]
Yes, I tried that in several ways and at different positions in the file. It never helped in any way. Caching is switched off in my blumix environment:

![image](https://user-images.githubusercontent.com/21081707/45157933-bf98fd80-b1e2-11e8-8629-5e14f4632b35.png)


```
{
    "name"         : "node-red-bluemix",
    "version"      : "0.8.0",
    "dependencies": {
        "when": "~3.x",
        "nano": "6.2.x",
        "bcrypt": "1.0.2",
        "cfenv":"~1.0.0",
        "express":"4.x",
        "body-parser":"1.x",
        "http-shutdown":"1.2.0",
        "node-red-node-email":"1.x",
        "node-red": "0.x",
        "node-red-bluemix-nodes":"1.x",
        "node-red-node-watson":"0.x",
        "node-red-node-openwhisk":"0.x",
        "node-red-node-cf-cloudant":"0.x",
        "node-red-contrib-scx-ibmiotapp":"0.x",
        "node-red-nodes-cf-sqldb-dashdb":"0.x"
    },
    "scripts": {
        "start": "node --max-old-space-size=180 index.js --settings ./bluemix-settings.js -v"
    },
    "engines": {
        "node": "8.x"
    }
}
```

I get 0.1.29 all the time. Any trick to use 1.0.3 NOW?

**Comment by knolleary** [comment]
The suggestion to add it to your package.json file was the only thing I could think of trying - I wasn't sure what npm would make of resolving the different required versions, and what Node-RED would do if it found multiple globally installed versions.

**Comment by BerndGewehr** [comment]
You could take it out of the node-red-nodes package and everybody installs it locally via the pallette manager.

**Comment by knolleary** [comment]
We already have a plan of action that is tied to the next major release of Node-RED.

If we removed `node-red-node-email` as a dependency of the `node-red` module (there is no `node-red-nodes` package) in a maintenance release, that would break existing users. We do not make breaking changes in maintenance releases.

**Comment by BerndGewehr** [comment]
Any existing timeframe for the 0.20 update you talked about?

**Comment by dceejay** [comment]
not yet. Is very much work in progress. I'd guess a few weeks. (Though Nick also has an upcoming business trip, and house move)
