### ISSUE TITLE
Twitter node needs D for DMing

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-nodes#493]
The DM functionality `D userid message` syntax insists on an upper case D, which means it's very easy to tweet publicly on your timeline the message you intended to send privately to someone.

Please can you allow either case D?

from
line 569:                  
`if (msg.payload.slice(0,2) == "D ") {`
to
` if (msg.payload.slice(0,2).toLowerCase() == "d ") {`

In v1.1.2 of Twitter node

**Comment by dceejay** [comment]
makes sense

**Comment by andysc** [comment]
TVM :)
