### ISSUE TITLE
node-red-daemon autorun option has no effect

### ISSUE THREAD

**Issue by derdanielmoin** [node-red/node-red-nodes#494]
Hi,

thanks for the node-red-nodes addon, it save me a lot of work! But I got the following issue:

regarding #479 the autorun-option should prevent the given script to start at node-red start. But this did not work for me (steps to reproduce: added the node to a flow, set path to a simple executable bash script, disable autorun-option, deploy, restart node-red, the script started). In the source code (daemon.js) the autorun option is never used after assignment (lines 15 - 16 in actual HEAD). I think missing is a if statement before line 133. Something like

`if (this.autorun) runit();`

thank you.

best regards,

Daniel

**Comment by dceejay** [comment]
You are correct of course. Thanks !
