### ISSUE TITLE
node-red-node-email: wrong folder name causes service crashs

### ISSUE THREAD

**Issue by baxcoders** [node-red/node-red-nodes#495]
Hi, 
as written in the title if I use the email node "node-red-node-email" and in the node configuration I set a wrong folder name an unhandled error occurred and causes the crash of node-red. The error "No mailbox is currently selected" is expected but not the crash of the service.
The exception is thrown in Connection.js (search function) after that the imap.search() has been invoked in "61-email.js" in the function "checkIMAP". 

Environment info:
- node.js v8.11.3
- node-red v0.19.2
- email node v1.0.4
- Windows 10, Google chrome

Thank you,
Best regards.

**Comment by dceejay** [comment]
@baxcoders 
Thanks for reporting it.
