### ISSUE TITLE
node-red-node-serialport

### ISSUE THREAD

**Issue by tokke100** [node-red/node-red-nodes#496]
### Which node are you reporting an issue on?
node-red-node-serialport
### What are the steps to reproduce?
add a serial-in node and serial-out node. Connect them to the **same** port. Do the initial setup and deploy. Make an adjustment and deploy again.
### What happens?
After the adjustment and deploy, only the output node connects again: https://imgur.com/a/W7UE4dC
### What do you expect to happen?
connect both nodes to the port again.
### Please tell us about your environment:

- [v0.19.3 ] Node-RED version:
- [V8.11.4 ] node.js version:
- [5.6.0] npm version:
- [Windows 7] Platform/OS:
- [Chrome] Browser:

**Comment by dceejay** [comment]
Seems to be a fairly common problem with Bluetooth ? Are you using bluetooth ?

https://www.google.com/search?q=serial+port+error+1168&oq=serial+port+error+1168&aqs=chrome..69i57.5280j0j7&sourceid=chrome&ie=UTF-8

**Comment by dceejay** [comment]
so - I think you'll have to dig around to see what is likely to be a fix - as I don't have that kit to try.
As it seems to be an upstream problem in the Windows 10 Bluetooth stack I'm not sure what we can do about it.

**Comment by tokke100** [comment]
Using windows 7 but. I noticed if I wait it just times out and eventually reconnects

**Comment by dceejay** [comment]
Closing as I don't think there is anything we can fix here.
