### ISSUE TITLE
inReplyTo in node-red-node-email doesn't work

### ISSUE THREAD

**Issue by saratSubramaniam** [node-red/node-red-nodes#502]
Hello,

I have configured an email out node from my outlook account. ( I'm using node-red-node-email version 1.0.6 - https://flows.nodered.org/node/node-red-node-email )

Below is the function node that I have, which is passed to the email out node.

```
msg.to = "test@test.com";
msg.topic = "Re: Test";
msg.payload = "Test Payload";
msg.references = ["<CAGk7PxNeM3g41xzROKz+BWD97=eeyA2uUepgASJODVm7f1YD=g@mail.test.com>"];
msg.inReplyTo = ["<CAGk7PxNeM3g41xzROKz+BWD97=eeyA2uUepgASJODVm7f1YD=g@mail.test.com>"];

return msg;
```

However the mail is received as a new email, not a reply for the referred one. I tried checking the mail header and it obviously didn't have the In-Reply-To and References attrbutes set.

Any mistake in the code ? Anybody having any idea ?

- Node-RED version: 0.19.5
- node.js version: 8.11.1
- npm version: 6.4.1
- Platform/OS: Windows
- Browser: Google Chrome

**Comment by knolleary** [comment]
Hi,

the node help does not say anything about supporting `msg.references` or `msg.inReplyTo`. so I don't know where you got those from.

As far as I can see, the node doesn't provide anyway to provide that sort of metadata with the message.
