### ISSUE TITLE
wake on lan stops working after some time

### ISSUE THREAD

**Issue by bednim** [node-red/node-red-nodes#508]
hi there, wake on lan node stops responding after some time of being idle. not exactly sure how long before it idles out. please ask any questions you may have so I can try and help establish the situation.

- [ ] Node-RED version: 0.19.5
- [ ] node.js version: v8.12.0
- [ ] npm version: npm@6.4.1 /
- [ ] Platform/OS: raspi3b
- [x] Browser: chrome

**Comment by dceejay** [comment]
I'm not sure how this can happen as the node just listens for any input and sends a packet when it is triggered... so...
can you find the file 39-wol.js on your machine  (probably under ~/.node-red/node_modules/node-red-node-wol directory or similar) and add some debug after it

    if (chk.test(mac)) {
        node.warn("Got " +JSON.stringify(msg));

then run Node-RED and check it sends a packet OK (and reports to the sidebar... then keep an eye on it and see what it says or doesn't when it fails.

Ideally start Node-RED from the command line like this (so stop it first then)

     node-red -v 

As that will add some extra debug messages.

**Comment by bednim** [comment]
hi - I was surprised that this happens too. I have for now reinstalled the
node and will observe. Where exactly do you want me to paste the piece of
code please?

Thank you

**Comment by bednim** [comment]
Reinstall didn't help. Will have to observe log. Will report tomorrow
morning - if I place extra correctly!

**Comment by bednim** [comment]
> sorry - line 17

ok - didn't have to wait long - this is the output from the node-red -v screen:

`6 Dec 21:57:34 - [warn] [wake on lan:M73 WOL] Got {"payload":1544133454589,"socketid":"FjacA4_th-Cr5JlKAAAE","_msgid":"a1996095.18bf6"} 
6 Dec 21:57:34 - [info] [wake on lan:M73 WOL] sent WOL magic packet`

**Comment by dceejay** [comment]
and did it wake up ?

**Comment by bednim** [comment]
No, it didn't.

**Comment by dceejay** [comment]
Ok - lets try...
Line 24 (as was) from `else if (RED.settings.verbose) {`   to just  `else {`
so it should then print out if it thinks it really sent it ok...
and likewise change line 31 from `if (RED.settings.verbose) { node.log("WOL: socket error"); }`
to be just `node.log("WOL: socket error");`

And then maybe line 19 to be

    wol.wake(mac, {address: host, interval:200, num_packets: 5}, function(error) {

I.E. Send more packets - spread further apart...

**Comment by bednim** [comment]
Hi there, thank you for trying and help me out here. I think that my
problem is that I use UDP port 9 and that I can't call it from within that
node. I have tried other npm project from
https://github.com/agnat/node_wake_on_lan and when I specify just MAC and
port 9 - my pc wakes up.

I hope I haven't wasted your time in trying to find the solution.

Thank you

**Comment by dceejay** [comment]
Well the node does use port 9 so...

I thought you said it does work some times... then stops working... Are you now saying it never works ?
Though that is indeed the library we use under the covers...  so it should be identical

**Comment by bednim** [comment]
Dave, I have just broken my node-red completely... let me bring it up to
'life'.

Yes - WOL was working immediately after powering down PC. It stops after
some time.

I have tried to use WOL node with just MAC address but that did not work (I
believe node needs IP to work), whereas npm command takes mac and port on
its own and works fine.

Thank you

**Comment by bednim** [comment]
I have left it blank and it didn't work, I will try broadcast address. If
you please give me about 30min as after that time it usually stopped
working. Thank you

**Comment by bednim** [comment]
it works!!!! thank you so much for pointing it out that I could use
broadcast ip! If I only knew...

Thanks again!

**Comment by dceejay** [comment]
Great. I’ll improve the docs

**Comment by khorchanov** [comment]
Hello I got the same problem, and setting the ip address blank or broadcast does not solve my problem.
Ps: I am running nodered on docker

**Comment by max-frei** [comment]
Hi, I'm facing the same issue. Running nodered in docker as well. I've done some testing and am able reproduce the following behavior: Using the same configuration it first works, then doesn't the next day and after restarting the container works again. When it's broken, changing the configuration doesn't seem to do anything and it keeps being broken. Using broadcast or not doesn't seem to have an impact to the mentioned behavior. Note that I am able to manually wake my computer e.g. via router interface. Appreciate any hints on what I could do to further narrow down this issue.

**Comment by dceejay** [comment]
Is there any simple way to replicate what you have so we can try to help ? Can't think of any obvious reason why it should stop after a time.

**Comment by max-frei** [comment]
I've been trying to minimize complexity and eliminate as many potential side-effects and here's how I'm able to replicate the issue: I'm running the default docker nodered on an Ubuntu host. I'm installing the wol plugin via the webinterface. Creating a simple flow to verify it's working and my machine wakes up. Then I wait a couple of hours and try the very same thing, it doesn't work. 

One thing I don't fully get and maybe someone can help me to understand: How does the plugin actually work "under the hood"? Is there a way to trace it or check logfiles? The only file I found was the one "defining" the plugin and the flow element, but not how the actual magic packet gets sent. 

My workaround for now is just running a separate little web service that gets called with an HTTP get request by nodered and handles the wol. But it's a really ugly solution for something that should work just out of the box.

**Comment by max-frei** [comment]
After some more digging, I understood that the plugin uses the npm wol functionality. That definitely gets called correctly. My current assumption would be that there's some kind of issue related to the way that the docker container handles networking. I'm just surprised that it's working for a while and then suddenly doesn't anymore. It's been a couple of years that I've actively worked with node.js, so I'm not entirely sure where to look for answers. However, I'd be fairly certain that this is not an issue related to nodered or the wol plugin. 

For those facing similar issues, I'd recommend a solution that sends the magic packet from outside the docker container. If you happen to use a FritzBox, you might want to look into using TR-064 for it. There's node-red-contrib-fritz available, providing a WOL by MAC address (Service: Host:1, Action: X_AVM-DE_WakeOnLANByMACAddress).

**Comment by embeeweezer** [comment]
You're correct, docker broadcasts to it's own (container) subnet by default. You can change this by running the containter with '--network host'. Please beware of network security issues since your container will be completely exposed to your networks.
