### ISSUE TITLE
HTML node used for webscraping

### ISSUE THREAD

**Issue by DrLucyRogers** [node-red/node-red-nodes#510]
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by DrLucyRogers** [comment]
HTML node

There is a space at the beginning of the "class" tag I want to get. This produces a Debug  error of "Cannot read property '0' of null" - I am expecting an array or something else!

Node-RED v 0.19.5
npm v 6.5.0
node.js v v10.14.2

Raspberry Pi - Linux localhost 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

Browser - Safari (from Mac to Pi)

I want to get the number of views of a TED page e.g. https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity has 55,022,000 + views.

Here's my efforts:

[{"id":"fcf973b1.499b48","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":160,"wires":[["4e24a3db.19753c"]]},{"id":"4e24a3db.19753c","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.npmjs.com/package/node-red","tls":"","x":274.5,"y":160,"wires":[["c8b917fb.9f5028"]]},{"id":"fb5fce07.0faa68","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":630,"y":160,"wires":[]},{"id":"c8b917fb.9f5028","type":"html","z":"61857189.43b1d8","name":"","property":"","tag":".pretty-number","ret":"text","as":"single","x":451.5,"y":160,"wires":[["fb5fce07.0faa68"]]},{"id":"ebcd7d25.84eca","type":"comment","z":"61857189.43b1d8","name":"GET request example","info":"https://cookbook.nodered.org/http/simple-get-request","x":100,"y":120,"wires":[]},{"id":"e7f40168.8758b","type":"comment","z":"61857189.43b1d8","name":"Assumption: This website has changed?","info":"","x":380,"y":120,"wires":[]},{"id":"ff11cf70.2ce62","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":300,"wires":[["a32abc4.a093f4"]]},{"id":"a32abc4.a093f4","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"http://www.ukho.gov.uk/EASYTIDE/EasyTide/ShowPrediction.aspx?PortID=0066&PredictionLength=1","tls":"","x":274.5,"y":300,"wires":[["4ac72a19.6a35a4"]]},{"id":"8cfe7a37.90a408","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":650,"y":300,"wires":[]},{"id":"4ac72a19.6a35a4","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".HWLWTableCell","ret":"text","as":"single","x":461.5,"y":300,"wires":[["8cfe7a37.90a408"]]},{"id":"4ad8eefd.ca4478","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 1 Tide Times","info":"","x":140,"y":260,"wires":[]},{"id":"e233a50d.1a07f","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":440,"wires":[["e5316e3c.bfa858"]]},{"id":"e5316e3c.bfa858","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"http://www.ukho.gov.uk/EASYTIDE/EasyTide/ShowPrediction.aspx?PortID=0066&PredictionLength=1","tls":"","x":274.5,"y":440,"wires":[["37d89eee.0a19aa"]]},{"id":"202106b8.30d922","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":650,"y":440,"wires":[]},{"id":"37d89eee.0a19aa","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":". HWLWTableCell","ret":"text","as":"single","x":461.5,"y":440,"wires":[["202106b8.30d922"]]},{"id":"57f3e8c4.500a78","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 1b Tide Times","info":"","x":140,"y":400,"wires":[]},{"id":"6cd81e4d.1d4ae","type":"comment","z":"61857189.43b1d8","name":"Using .HWLWTableCell","info":"Using .HWLWTableCell\nTaken from <td class=\"HWLWTableCell\"> 04:34</td>","x":460,"y":260,"wires":[]},{"id":"ca53542.5b9b2a8","type":"comment","z":"61857189.43b1d8","name":"Using . HWLW... (Added space)","info":"Using . HWLWTableCell\nTaken from <td class=\"HWLWTableCell\"> 04:34</td>","x":410,"y":400,"wires":[]},{"id":"befcc9c9.a46438","type":"comment","z":"61857189.43b1d8","name":"Debug \"Cannot read property '0' of null\"","info":"","x":720,"y":400,"wires":[]},{"id":"d8c37d62.752658","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":560,"wires":[["3a874153.3b83d6"]]},{"id":"3a874153.3b83d6","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":274.5,"y":560,"wires":[["21bce98b.ffc26e"]]},{"id":"675b03ab.b94094","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":650,"y":560,"wires":[]},{"id":"21bce98b.ffc26e","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":". f-w:700 f:3 ","ret":"text","as":"single","x":441.5,"y":560,"wires":[["675b03ab.b94094"]]},{"id":"d0b818b0.a42968","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2 - TED Talk","info":"","x":140,"y":520,"wires":[]},{"id":"608cb62d.0bb168","type":"comment","z":"61857189.43b1d8","name":"Using . f-w:700 f:3 ","info":"Using . f-w:700 f:3 \nTaken from <span class=\" f-w:700 f:3 \">55,022,089</span>","x":430,"y":520,"wires":[]},{"id":"f6803b4.43637c8","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":660,"wires":[["238cd9a9.9f442e"]]},{"id":"238cd9a9.9f442e","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":274.5,"y":660,"wires":[["b6fbbb90.c01338"]]},{"id":"269bf945.f3ad7e","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":650,"y":660,"wires":[]},{"id":"b6fbbb90.c01338","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".f-w:700 f:3 ","ret":"text","as":"single","x":441.5,"y":660,"wires":[["269bf945.f3ad7e"]]},{"id":"2e893949.e40ede","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2b - TED Talk","info":"","x":140,"y":620,"wires":[]},{"id":"dfd14585.780ab8","type":"comment","z":"61857189.43b1d8","name":"Using .f-w:700 f:3","info":"\nTaken from <span class=\" f-w:700 f:3 \">55,022,089</span>","x":430,"y":620,"wires":[]},{"id":"2041dba0.19f69c","type":"comment","z":"61857189.43b1d8","name":"Debug \"Cannot read property '0' of null\"","info":"","x":700,"y":520,"wires":[]},{"id":"f2ce85cd.74b32","type":"comment","z":"61857189.43b1d8","name":"Debug \"unmatched pseudo-class :700\"","info":"","x":690,"y":620,"wires":[]},{"id":"7c009622.40967","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":760,"wires":[["9b404568.87cf4"]]},{"id":"9b404568.87cf4","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":274.5,"y":760,"wires":[["a143a286.83ab"]]},{"id":"3719aafb.b7faee","type":"debug","z":"61857189.43b1d8","name":"","active":true,"console":"false","complete":"false","x":650,"y":760,"wires":[]},{"id":"a143a286.83ab","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".f","ret":"text","as":"single","x":421.5,"y":760,"wires":[["3719aafb.b7faee"]]},{"id":"df4cd6ff.809888","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2c - TED Talk","info":"","x":140,"y":720,"wires":[]},{"id":"7008d36.4a2bcac","type":"comment","z":"61857189.43b1d8","name":"Using .f","info":"Using .f\nTaken from <span class=\" f-w:700 f:3 \">55,022,089</span>","x":430,"y":720,"wires":[]},{"id":"e0462a7b.fc6e9","type":"comment","z":"61857189.43b1d8","name":"Debug [ empty ]","info":"","x":640,"y":720,"wires":[]},{"id":"b3fa5322.f24638","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":860,"wires":[["8d94acb1.e4d0a"]]},{"id":"8d94acb1.e4d0a","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":274.5,"y":860,"wires":[["99fecacb.8a96a"]]},{"id":"4bab0304.48b0fc","type":"debug","z":"61857189.43b1d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":650,"y":860,"wires":[]},{"id":"99fecacb.8a96a","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".Grid","ret":"html","as":"single","x":421.5,"y":860,"wires":[["4bab0304.48b0fc"]]},{"id":"d1eea13b.d69ca8","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2d - TED Talk","info":"","x":140,"y":820,"wires":[]},{"id":"d888d480.f10688","type":"comment","z":"61857189.43b1d8","name":"Using .Grid","info":"","x":450,"y":820,"wires":[]},{"id":"1403d289.af7dd5","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":110,"y":960,"wires":[["40f772d7.290bac"]]},{"id":"40f772d7.290bac","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":274.5,"y":960,"wires":[["14de0ebb.6a7cb9"]]},{"id":"d4ad9a8d.0de7b8","type":"debug","z":"61857189.43b1d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":650,"y":960,"wires":[]},{"id":"14de0ebb.6a7cb9","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".shoji","ret":"html","as":"single","x":421.5,"y":960,"wires":[["d4ad9a8d.0de7b8"]]},{"id":"1a6a3f85.714cb8","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2e - TED Talk","info":"","x":140,"y":920,"wires":[]},{"id":"ccd6e4bd.d7fda8","type":"comment","z":"61857189.43b1d8","name":"Using .shoji","info":"","x":450,"y":920,"wires":[]},{"id":"57b58436.f38504","type":"inject","z":"61857189.43b1d8","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":130,"y":1060,"wires":[["83a43f82.ec1108"]]},{"id":"83a43f82.ec1108","type":"http request","z":"61857189.43b1d8","name":"","method":"GET","ret":"txt","url":"https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity","tls":"","x":294.5,"y":1060,"wires":[["3da0a9f2.38734e"]]},{"id":"58c01197.ee11d8","type":"debug","z":"61857189.43b1d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":670,"y":1060,"wires":[]},{"id":"3da0a9f2.38734e","type":"html","z":"61857189.43b1d8","name":"","property":"","outproperty":"","tag":".f-w","ret":"html","as":"single","x":441.5,"y":1060,"wires":[["58c01197.ee11d8"]]},{"id":"919f77b8.581db","type":"comment","z":"61857189.43b1d8","name":"Lucy's example 2e - TED Talk","info":"","x":160,"y":1020,"wires":[]}]



Please  / Thank you / Merry Christmas :)
Lucy

**Comment by hardillb** [comment]
Hi Lucy

Can you please ask questions like this in the forum or in Slack then the whole community can help answer them, rather than just the core team.

Thanks

**Comment by dceejay** [comment]
valid class names can't have spaces...

**Comment by DrLucyRogers** [comment]
> Hi Lucy
> 
> Can you please ask questions like this in the forum or in Slack then the whole community can help answer them, rather than just the core team.
> 
> Thanks

Just uploaded it to Slack - my apologies. Lucy
