### ISSUE TITLE
node-red-node-serialport Node.js version: v10.15.0 Error

### ISSUE THREAD

**Issue by italschwob** [node-red/node-red-nodes#511]
### Please tell us about your environment:

- [x] Node-RED version:
- [x] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
When you change the major version of node.js you'll need to rebuild all modules that have a binary component - such as the serialport module used by the serial node.

In `/home/pi/data/node-red/` run `npm rebuild serialport`

You may find other modules have similar issues... the `npm rebuild` command should help sort them out.

**Comment by knolleary** [comment]
For general problems like this, please consider using the [forum](https://discourse.nodered.org) so the wider community can help and not rely on the core developers. Thanks!
