### ISSUE TITLE
node-red-node-email - fetch on demand

### ISSUE THREAD

**Issue by qwertangel** [node-red/node-red-nodes#513]
### Which node are you reporting an issue on?
node-red-node-email
### What are the steps to reproduce?
set email node
### What happens?
it fetches one email periodically
### What do you expect to happen?
ability to trigger email fetch from other nodes/input , ability to fetch multiple emails
### Please tell us about your environment:

[0.19.5 ] Node-RED version:
[8.10.0 ] node.js version:
[3.5.2 ] npm version:
[ Ubuntu 16.4] Platform/OS:
[ Chrome] Browser:

I am a heavy user of email node. I am wondering if you will consider following enhancements - 

1) Currently the node fetches email periodically. Is it possible to have it so that it can be triggered manually ? That way I can create a flow which fetches email only when certain conditions are triggered.
2) Currently it fetches only 1 email. Is it possible to make that number configurable (with some upper max)

**Comment by dceejay** [comment]
In general we prefer enhancements to be discussed on the discourse forum first so the wider community can participate (if they wish).
1) I'd prefer not to as that then means adding an input to the node which is just meh. (Hmm could it be optional ... not tried that - so worth playing with.
2) It should fetch any unread mail - not just one  - and output each as a separate message. If not then it should... so needs to be fixed... so yes please to a PR.

**Comment by qwertangel** [comment]
Thanks for response. I just checked. Yes, it fetches more than one email. So we can scratch off second point. ( i was thrown off by description which says that it will fetch only one).

For first request, since built-in 'inject' node already provides capability of firing at regular interval (and more), email node doesn't necessarily need it's own in-built frequency. If add a input to email node (in addition to output), email can be either fetched at regular interval or on demand. Currently there is no way to fetch on demand.
Just to be clear, I am not requesting to make it input node, but rather a function node. It would fetch email on demand and pass on payload to downstream nodes.

**Comment by dceejay** [comment]
> Just to be clear, I am not requesting to make it input node, but rather a function node. It would fetch email on demand and pass on payload to downstream nodes.

Yes I know - it is already an input node - this changes it to be an inline node, so any extra change in behaviour needs to be done in a way so as not to break existing users. Hence why i was wondering if we could make adding the extra input optional, rather than there permanently. eg default is as-is - edit config - tick a select box to add input, save config - input now visible to be wired.

**Comment by qwertangel** [comment]
awesome ! If that can be done, that would be great. :) 

I can already see multiple benefits -
1) it would help people who are on metered connection and don't want to take overhead of repeated polls. (e.g. only try fetching when internet is up or between hours of 10pm-2am when cost is low )
2) other flows can trigger email fetch, rather than email triggering the flow .  (fetch email based on presence detection) etc.
3) input can be extended to accept other parameters like  'folder' (or subject/to/cc etc) when fetching. So calling node can pass on the search requirements and that flow will fetch only the emails it is interested in.
