### ISSUE TITLE
Duplicate msg objects returned by email node, after a disconnection

### ISSUE THREAD

**Issue by saratSubramaniam** [node-red/node-red-nodes#514]
**### Which node are you reporting an issue on?** - node-red-node-email (email-in)         

**### What are the steps to reproduce?** - Force disconnect the email node (maybe by switching to airplane mode) and let the email-in node fetch an UNSEEN flagged email. This throws a connect error. Now switch the connection back on, let the node fetch again. The email object will be returned to node-red console multiple times (2 or more, based on the fetch interval)

**### What happens?** - Duplicate msg objects returned.

**### What do you expect to happen?** - Unique/Single msg object to be returned.

**### Please tell us about your environment:**

- [x] Node-RED version: 0.1.29
- [x] node.js version: 8.11.1
- [x] npm version: 6.5.0
- [x] Platform/OS: Windows 10
- [x] Browser: Chrome

**Comment by saratSubramaniam** [comment]
May I know why this was closed without communicating ?

**Comment by dceejay** [comment]
Apologies. If you follow the link in the close message, you can see the fix that has been applied. Now pushed out to npm.

**Comment by saratSubramaniam** [comment]
Thank you so much @dceejay ! I missed to follow the link, just saw the Closed tag. Will verify the fix asap.

**Comment by saratSubramaniam** [comment]
@dceejay , I was able to verify the node only today.
I installed the new email node with the fixes and tried, and see that the e-mail node is **not getting registered** properly. If I install the new node while I have a working e-mail node in an existing flow, the console says "Waiting for e-mail in node to be registered".
Or if I do a fresh install, it just doesn't show up under the installed nodes side panel.

**Comment by dceejay** [comment]
which version of Node-RED are you running ?
As it is a core node it is (was) installed slightly differently - so needs to be installed globally over the existing one on older versions of Node-RED. From 0.19.5 it should be possible to just install normally and the new local one will take over from the global one. If you need to stay on an older Node-RED we can talk you through that if you let us know the platform you are running on.

**Comment by saratSubramaniam** [comment]
I'm using Node-RED version 0.20.0-beta.4.
