### ISSUE TITLE
node-red-node-mysql truncates query  

### ISSUE THREAD

**Issue by ReclusiveGeek** [node-red/node-red-nodes#520]
I have a table with a longtext(655535) field that contains the json input for graphs after a restart to give permanent storage. The node-red-node-mysql query truncates the result.

mqsl json_data contains 

[{"series":[""],"data":[[{"x":1549238400000,"y":5.00},{"x":1549242000000,"y":5.00},{"x":1549245600000,"y":5.00},{"x":1549249200000,"y":5.00},{"x":1549252800000,"y":5.00},{"x":1549256400000,"y":6.00},{"x":1549260000000,"y":6.00},{"x":1549263600000,"y":6.00},{"x":1549267200000,"y":6.00},{"x":1549270800000,"y":6.00},{"x":1549274400000,"y":6.00},{"x":1549278000000,"y":7.00},{"x":1549285200000,"y":9.00},{"x":1549288800000,"y":9.00},{"x":1549292400000,"y":9.00},{"x":1549296000000,"y":7.00},{"x":1549299600000,"y":4.00},{"x":1549303200000,"y":4.00},{"x":1549306800000,"y":5.00},{"x":1549310400000,"y":5.00},{"x":1549314000000,"y":3.00},{"x":1549317600000,"y":3.00},{"x":1549321200000,"y":2.00},{"x":1549324800000,"y":2.00},{"x":1549328400000,"y":1.00},{"x":1549332000000,"y":0.00},{"x":1549335600000,"y":0.00},{"x":1549339200000,"y":0.00},{"x":1549342800000,"y":0.00},{"x":1549346400000,"y":0.00},{"x":1549350000000,"y":0.00},{"x":1549353600000,"y":0.00},{"x":1549357200000,"y":0.00},{"x":1549360800000,"y":1.00},{"x":1549364400000,"y":3.00},{"x":1549368000000,"y":4.00},{"x":1549371600000,"y":6.00},{"x":1549375200000,"y":6.00},{"x":1549378800000,"y":7.00},{"x":1549382400000,"y":7.00},{"x":1549386000000,"y":7.00},{"x":1549389600000,"y":7.00},{"x":1549393200000,"y":7.00},{"x":1549396800000,"y":7.00},{"x":1549400400000,"y":6.00},{"x":1549404000000,"y":7.00},{"x":1549407600000,"y":7.00},{"x":1549411200000,"y":8.00},{"x":1549414800000,"y":8.00},{"x":1549418400000,"y":8.00},{"x":1549422000000,"y":8.00},{"x":1549425600000,"y":8.00},{"x":1549429200000,"y":7.00},{"x":1549432800000,"y":6.00},{"x":1549436400000,"y":5.00},{"x":1549440000000,"y":4.00},{"x":1549443600000,"y":4.00},{"x":1549447200000,"y":5.00},{"x":1549450800000,"y":6.00},{"x":1549454400000,"y":7.00},{"x":1549458000000,"y":8.00},{"x":1549461600000,"y":8.00},{"x":1549465200000,"y":8.00},{"x":1549468800000,"y":9.00},{"x":1549472400000,"y":8.00},{"x":1549476000000,"y":7.00},{"x":1549479600000,"y":5.00},{"x":1549483201000,"y":5.00},{"x":1549486800000,"y":5.00},{"x":1549490400000,"y":5.00},{"x":1549494000000,"y":5.00},{"x":1549497600000,"y":5.00},{"x":1549501200000,"y":6.00},{"x":1549504800000,"y":6.00},{"x":1549508400000,"y":7.00},{"x":1549512000000,"y":7.00},{"x":1549515600000,"y":6.00},{"x":1549519200000,"y":6.00},{"x":1549522801000,"y":5.00},{"x":1549526400000,"y":5.00},{"x":1549530000000,"y":5.00},{"x":1549533600000,"y":5.00},{"x":1549537200000,"y":5.00},{"x":1549540800000,"y":5.00},{"x":1549544400000,"y":6.00},{"x":1549548000000,"y":7.00},{"x":1549551600000,"y":8.00},{"x":1549555200000,"y":8.00},{"x":1549558800000,"y":7.00},{"x":1549562400000,"y":6.00},{"x":1549566000000,"y":6.00},{"x":1549569600000,"y":5.00},{"x":1549573200000,"y":5.00},{"x":1549576800000,"y":5.00},{"x":1549580400000,"y":5.00},{"x":1549584000000,"y":5.00},{"x":1549587600000,"y":6.00},{"x":1549591200000,"y":7.00},{"x":1549594800000,"y":6.00},{"x":1549598400000,"y":7.00},{"x":1549602000000,"y":8.00},{"x":1549605600000,"y":8.00},{"x":1549609200000,"y":8.00},{"x":1549612800000,"y":9.00},{"x":1549616400000,"y":9.00},{"x":1549620000000,"y":9.00},{"x":1549623600000,"y":10.00},{"x":1549627200000,"y":11.00},{"x":1549630800000,"y":11.00},{"x":1549634400000,"y":11.00},{"x":1549638001000,"y":12.00},{"x":1549641600000,"y":11.00},{"x":1549645200000,"y":10.00},{"x":1549648800000,"y":10.00},{"x":1549652400000,"y":8.00},{"x":1549656000000,"y":8.00},{"x":1549659600000,"y":7.00},{"x":1549663200000,"y":7.00},{"x":1549666800000,"y":7.00},{"x":1549670400000,"y":6.00},{"x":1549674000000,"y":6.00},{"x":1549677600000,"y":6.00},{"x":1549681200000,"y":6.00},{"x":1549684800000,"y":6.00},{"x":1549688400000,"y":6.00},{"x":1549692000000,"y":6.00},{"x":1549695600000,"y":7.00},{"x":1549699200000,"y":7.00},{"x":1549702800000,"y":7.00},{"x":1549706400000,"y":7.00},{"x":1549710000000,"y":8.00},{"x":1549713600000,"y":8.00},{"x":1549717200000,"y":9.00},{"x":1549720800000,"y":9.00},{"x":1549724400000,"y":9.00},{"x":1549728000000,"y":9.00},{"x":1549731600000,"y":8.00},{"x":1549735200000,"y":8.00},{"x":1549738800000,"y":7.00},{"x":1549742400000,"y":6.00},{"x":1549746000000,"y":6.00},{"x":1549749600000,"y":6.00},{"x":1549753200000,"y":6.00},{"x":1549756800000,"y":5.00},{"x":1549760400000,"y":5.00},{"x":1549764000000,"y":5.00},{"x":1549767600000,"y":5.00},{"x":1549771200000,"y":5.00},{"x":1549774800000,"y":4.00},{"x":1549778400000,"y":4.00},{"x":1549782000000,"y":4.00},{"x":1549785600000,"y":4.00},{"x":1549789200000,"y":4.00},{"x":1549792800000,"y":4.00},{"x":1549796400000,"y":4.00},{"x":1549800000000,"y":5.00},{"x":1549803600000,"y":6.00},{"x":1549807200000,"y":6.00},{"x":1549810800000,"y":7.00},{"x":1549814400000,"y":7.00},{"x":1549818000000,"y":6.00},{"x":1549821600000,"y":6.00},{"x":1549825200000,"y":4.00},{"x":1549828800000,"y":4.00},{"x":1549832400000,"y":4.00},{"x":1549836000000,"y":4.00},{"x":1549839600000,"y":3.00},{"x":1549843200000,"y":3.00},{"x":1549846800000,"y":3.00},{"x":1549850400000,"y":2.00},{"x":1549854000000,"y":3.00},{"x":1549857600000,"y":2.00},{"x":1549861200000,"y":2.00},{"x":1549864800000,"y":2.00},{"x":1549868400000,"y":3.00},{"x":1549872000000,"y":3.00},{"x":1549875600000,"y":4.00},{"x":1549879200000,"y":5.00},{"x":1549882800000,"y":6.00},{"x":1549886400000,"y":7.00},{"x":1549890000000,"y":7.00},{"x":1549893600000,"y":8.00},{"x":1549897200000,"y":8.40}]],"labels":[""]}]

and the node-red-node-mysql only returns 

[{"json_data":"[{\"series\":[\"\"],\"data\":[[{\"x\":1549238400000,\"y\":5.00},{\"x\":1549242000000,\"y\":5.00},{\"x\":1549245600000,\"y\":5.00},{\"x\":1549249200000,\"y\":5.00},{\"x\":1549252800000,\"y\":5.00},{\"x\":1549256400000,\"y\":6.00},{\"x\":1549260000000,\"y\":6.00},{\"x\":1549263600000,\"y\":6.00},{\"x\":1549267200000,\"y\":6.00},{\"x\":1549270800000,\"y\":6.00},{\"x\":1549274400000,\"y\":6.00},{\"x\":1549278000000,\"y\":7.00},{\"x\":1549285200000,\"y\":9.00},{\"x\":1549288800000,\"y\":9.00},{\"x\":1549292400000,\"y\":9.00},{\"x\":1549296000000,\"y\":7.00},{\"x\":1549299600000,\"y\":4.00},{\"x\":1549303200000,\"y\":4.00},{\"x\":1549306800000,\"y\":5.00},{\"x\":1549310400000,\"y\":5.00},{\"x\":1549314000000,\"y\":3.00},{\"x\":1549317600000,\"y\":3.00},{\"x\":1549321200000,\"y\":2.00},{\"x\":1549324800000,\"y\":2.00},{\"x\":1549328400000,\"y\":1.00},{\"x\":1549332000000,\"y\":0.00},{\"x\":1549335600000,\"y\":0.00},{\"x\":1549339200000,\"y\":0.00},{\"x\":1549342800000,\"y\":0.00},{\"x\":1549346400000,\"y\":0.00},{\"x\":1549350000000,\"y\":0.00},{\"x\":1549353600000,\"y\":0.00},{\"x\":1549357200000,\"y\":0.00},{\"x\":1549360800000..."}]

So I am assuming this is a bug and not a limitation of the module.

node-red-node-mysql 0.0.18
Node-RED 0.19.5
node.js  v8.15.0
npm  6.4.1
Ubuntu 18.04 
Browser Chromium Version 71.0.3578.98 (Official Build) snap (64-bit)

**Comment by hardillb** [comment]
How are you using this? The debug node will always truncate output to the debug tab, but the message will contain the whole output. You can check this by setting the debug node to output to the console as well as the debug tab as that output will always have the full output.

**Comment by knolleary** [comment]
How are you determining what has been returned?

If you are using the Debug node, then it does truncate how much of the message gets displayed in the sidebar, but that is not a reflection of the full message contents

**Comment by ReclusiveGeek** [comment]
Thanks for the speedy response. I did fall into debug truncating the message. I added a function to format the output as JSON and in shows all the data.

Thanks again
