### ISSUE TITLE
"RequestTimedOutError: Request timed out"

### ISSUE THREAD

**Issue by rihani** [node-red/node-red-nodes#525]
sometimes when the server is down, the snmp node prints the timeout message, how can i capture this msg so that i can tell the server is offline and stop pinging the server with snmp msgs. thanks

**Comment by dceejay** [comment]
As per the issue template you have managed to erase - we much prefer simple ho-to questions via the slack channel or discourse forum so the widest possible community can help. 

If it's a status message use a status node to also receive the message. If it's an error use the catch node.
