### ISSUE TITLE
node-red-node-wol 0.0.10 does not work (0.0.9 works well)

### ISSUE THREAD

**Issue by Attila-FIN** [node-red/node-red-nodes#528]
### Which node are you reporting an issue on?
node-red-node-wol
### What are the steps to reproduce?
Try to send WOL packet to 192.168.100.254 (static ARP in router to FF:FF:FF:FF:FF:FF)
### What happens?
Packet is not sent
### What do you expect to happen?
Packet is sent, like it is sent using version 0.0.9.
### Please tell us about your environment:

- [ ] Node-RED version: v0.19.6
- [ ] node.js version: v10.15.0
- [ ] npm version: 
- [ ] Platform/OS: Raspbian GNU/Linux 9 (stretch)
- [ ] Browser:

**Comment by Appelg** [comment]
I can confirm this problem.
Thanks @Attila-FIN for the 'workaround', I tried to get 0.0.10 working without any luck, downgrade to 0.0.9 worked immediately.

**Comment by MarcusElyob** [comment]
I am having problemps with update wol 0.0.12.
Can i ask, how did you downgrade to 0.0.9 ? Dont have much experience with this , so i greatly appreciated any assistance.

**Comment by dceejay** [comment]
standard npm commands

    cd ~/.node-red
    npm i node-red-node-wol@0.0.9

**Comment by MarcusElyob** [comment]
Thanking you deejay for your reply. Will give it a go..
