### ISSUE TITLE
Problems with (Node-red-node-sqlite) can't install

### ISSUE THREAD

**Issue by marchdna** [node-red/node-red-nodes#529]
Node-red-node-SQLite  can't install with some problems 
![image](https://user-images.githubusercontent.com/48979588/55058206-e4c95c80-509d-11e9-9d81-c064b8636e2f.png)

root@axcf2152:/usr/bin# sqlite3 --version 3.20.0 

I hope this must can solve this problems soon.

- [x] Node-RED version:
V.20.3
- [x] node.js version:
V11.12.0
- [x] npm version:
6.7.0
- [x] Platform/OS:
Linux 4.14.63-rt-40-pxc arm LE
- [x] Browser:
Chrome

**Comment by knolleary** [comment]
This is an issue installing the sqlite3 module this node uses.

The error comes from a python build script in that module - what version of python have you got installed?

You may need to follow up with the maintainers of the sqlite3 module for help

**Comment by marchdna** [comment]
Python 3.5.3

**Comment by knolleary** [comment]
Does running `npm install sqlite3` manually hit this same error?

As I said in my earlier post, you may need to followup with the sqlite3 maintainers.

**Comment by marchdna** [comment]
`root@axcf2152:/opt/plcnext# npm install sqlite3

> sqlite3@4.0.6 install /opt/plcnext/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaw                                                                                                                                                             s.com/sqlite3/v4.0.6/node-v67-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and node@11.12.                                                                                                                                                             0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%                                                                                                                                                             s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:988:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:404:11)
gyp ERR! stack     at Socket.emit (events.js:197:13)
gyp ERR! stack     at Pipe._handle.close (net.js:611:12)
gyp ERR! System Linux 4.14.63-rt40-pxc
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_mod                                                                                                                                                             ules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/                                                                                                                                                             plcnext/node_modules/sqlite3/lib/binding/node-v67-linux-arm/node_sqlite3.node" "                                                                                                                                                             --module_name=node_sqlite3" "--module_path=/opt/plcnext/node_modules/sqlite3/lib                                                                                                                                                             /binding/node-v67-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_b                                                                                                                                                             uild_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /opt/plcnext/node_modules/sqlite3
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local                                                                                                                                                             /lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback                                                                                                                                                             -to-build --module=/opt/plcnext/node_modules/sqlite3/lib/binding/node-v67-linux-                                                                                                                                                             arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/plcnext/node                                                                                                                                                             _modules/sqlite3/lib/binding/node-v67-linux-arm --napi_version=4 --node_abi_napi                                                                                                                                                             =napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/plcnext/node_modul                                                                                                                                                             es/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:988:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                                                                                                                             ld_process.js:265:5)
node-pre-gyp ERR! System Linux 4.14.63-rt40-pxc
node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/plcnext/node_modules/.bin/                                                                                                                                                             node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/plcnext/node_modules/sqlite3
node-pre-gyp ERR! node -v v11.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modu                                                                                                                                                             les/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/plcnext                                                                                                                                                             /node_modules/sqlite3/lib/binding/node-v67-linux-arm/node_sqlite3.node --module_                                                                                                                                                             name=node_sqlite3 --module_path=/opt/plcnext/node_modules/sqlite3/lib/binding/no                                                                                                                                                             de-v67-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --                                                                                                                                                             node_napi_label=node-v67' (1)
npm WARN enoent ENOENT: no such file or directory, open '/opt/plcnext/package.js                                                                                                                                                             on'
npm WARN plcnext No description
npm WARN plcnext No repository field.
npm WARN plcnext No README data
npm WARN plcnext No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fse                                                                                                                                                             vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                             1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"}                                                                                                                                                             )

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/root/.npm/_logs/2019-03-27T09_25_01_929Z-debug.log
`


same error

**Comment by dceejay** [comment]
I think gyp pre-reqs python 2.7 - so that has to be your system default. It won't work with python3.
"print "%s.%s.%s" % sys.version_info[:3];"   is invalid in python3...

**Comment by marchdna** [comment]
Yes I try with Python 2.7 before but it's still have another error

**Comment by marchdna** [comment]
![image](https://user-images.githubusercontent.com/48979588/55067324-164c2300-50b2-11e9-9162-b37f29b73199.png)

this is after I use Python2.7

**Comment by knolleary** [comment]
You are missing the `make` command.

Run:
```
sudo apt-get install build-essential
```
to get the necessary prereqs and try again.

**Comment by hardillb** [comment]
Please don't post screen shots they are really hard to read, copy and paste the text and use markdown to format it.

Also as Nick has said, this is a problem with the underlying sqlite3 node, not the node-red wrapper. You need to raise this with them. It sounds like you are missing the pre-reqs for building nodejs modules with native components

**Comment by marchdna** [comment]
we cannot use apt-get command 
our hardware is a modify Debian-base

**Comment by knolleary** [comment]
So use whatever tools you have available to install the make command and it's dependencies.

**Comment by dceejay** [comment]
Closing as this is an edge case that needs local specialist knowledge to get the underlying library binary to compile. Not a Node-RED issue per se.
