### ISSUE TITLE
Unlike node-red-node-serialport, node-red-node-arduino does not reconnect if arduino disconnected. 

### ISSUE THREAD

**Issue by paulhayes** [node-red/node-red-nodes#532]
### Which node are you reporting an issue on?

node-red-node-arduino

### What are the steps to reproduce?

Disconnect arduino, reconnect arduino.

### What happens?

No change to the status of arduino nodes ( still says connected ). However any flows with output to arduino fail to cause that output on the microcontroller.

### What do you expect to happen?

The node to detect when disconnected ( not necessarily immediately, but after a timeout ). And to attempt a reconnect if something has gone wrong.

### Please tell us about your environment:

- [ v0.20.5 ] Node-RED version:
- [ v10.15.3 ] node.js version:
- [ 6.4.1 ] npm version:
- [ Windows 10 ] Platform/OS:
- [Chrome ] Browser:

**Comment by dceejay** [comment]
Yes this could be improved.

**Comment by dceejay** [comment]
pushed version 0.2.0 which should now reconnnect automatically.

**Comment by paulhayes** [comment]
Thank you so much @dceejay. I'll test it immediately.

**Comment by dceejay** [comment]
added a slight update to only report connection error once rather than every time it retries.
