### ISSUE TITLE
Error: ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by connected201** [node-red/node-red-nodes#534]
hi, everyone, i have this problem: "Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client"
i have installed latest nodered (0.20.5), and latest version of flow 0.0.18 (https://flows.nodered.org/node/node-red-node-mysql)
i run mysql in docker from https://hub.docker.com/_/mysql, but i cannot connect :(

**Comment by dceejay** [comment]
What is your mysql server version ?
I think the library may not support some of the version 8 features.
https://github.com/mysqljs/mysql/issues/2046

**Comment by connected201** [comment]
8.0.15 version

**Comment by connected201** [comment]
ok, wich version support? i will use supported version!

**Comment by connected201** [comment]
i using previous version (5.7.25) all, ok, we will waiting update, best regards!

**Comment by juggledad** [comment]
A user reports (https://discourse.nodered.org/t/mysql-connection-error/20953/4) that you can do the following

> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'
> Where root as your user localhost as your URL and password as your password
> Then run this query to refresh privileges:
> flush privileges;
