### ISSUE TITLE
Analog input not working with 0.20?

### ISSUE THREAD

**Issue by n3odon** [node-red/node-red-nodes#535]
I am running Node-RED on Raspbian, Raspberry Pi 3B+. I had tested some weeks ago to use Arduino with Firmata and arduino-nodes for both input and output. Back then the Node-RED version was 0.18.4. Both Servo-output and Analog-input worked fine.

Now I made a new Raspberry Pi with the same setup. Firmata on Arduino and Arduino-nodes in Node-RED. Now, Node-RED is in version 0.20.5. Now I get an error message from the analog-in input-node:

"TypeError: Cannot read property 'serverConfig' of undefined"

The output-nodes seem to work as before. What has changed from 0.18.4 to 0.20.5 that could have resulted in this issue?

I tried the jonny-five-nodes, and there the input-node is working again. However, jonny-five-nodes are not reconnecting as robustly as the arduino-nodes did. I always have to push the reset button before deploying to make the changes happen. This wasn't neccessary with the arduino-nodes before.

Thanks for any help in advance.

**Comment by dceejay** [comment]
will investigate

**Comment by dceejay** [comment]
pushed version 0.2.2 of arduino node to npm.
(The update was to make it try to reconnect if serial was unplugged and replugged... and this was obviously not 100% successful... hopefully now fixed (well works for me on simple test case for digital and analogue in) - so please update and retry, and let us know. Thanks

**Comment by n3odon** [comment]
Thanks for the quick fix! I works now!
The only issue is that the nodes keep saying 'connecting', however without any functional problem.

**Comment by dceejay** [comment]
How are you getting that ? Are you starting with the device connected or not connected ? - If it's plugged in when you deploy it should connect up ok after a couple of seconds.
