### ISSUE TITLE
Stop the daemon node from removing context from the message

### ISSUE THREAD

**Issue by andreas-ibm** [node-red/node-red-nodes#536]
### Which node are you reporting an issue on?
node-red-node-daemon

### What are the steps to reproduce?
HTTP request -> daemon -> http response

### What happens?
HTTP response says no response object

### What do you expect to happen?
HTTP response

### Please tell us about your environment:

- [x] Node-RED version: 0.20.0
- [x] node.js version: 8.10.0
- [x] npm version: 5.6.0
- [x] Platform/OS: OpenWRT
- [x] Browser: Vivaldi

**Comment by dceejay** [comment]
Well it doesn't remove them... just never keeps them in the first place.
I suspect this is a bit of a special case where you have one message in and one one (and indeed want to keep the res object matched up). Most use cases of this node were not envisaged like that... more that they would keep running and produce async output that would be modified by incoming input messages (think video stream or some such) - in which cases there would not be a one to one relationship between in and out. In those situations a) would you really want the whole input copied to every output message ? certainly we wouldn't want to clone a large msg object just in case.

For a one in one out situation would an exec node not be able to handle it ?

**Comment by dceejay** [comment]
closed by 2070a932be677c39cc9b79433c1a24b0d39c6332
