### ISSUE TITLE
error in node-red

### ISSUE THREAD

**Issue by chirag10590** [node-red/node-red-nodes#538]
AFTER USING MODBUS SERVER NODE MY NODE-RED IS NOT WORKING.

![node-red error](https://user-images.githubusercontent.com/49580857/57178319-e4d22e80-6e8b-11e9-8d49-2b7bbc5bed83.png)

**Comment by hardillb** [comment]
You seem to have ignored the template you were shown when you opened this issue. Please make sure you read it fully in future.

There is no modbus node in this repo, you need to raise any issue against the contrib node, not the core Node-RED project.
