### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by geekYatao** [node-red/node-red-nodes#541]
Hello
I need to split the input data with hexadecimal digits
I found the version 0.8.1 could not Split input  by  "0x03" 。The  error  is ""TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received type object"".This error did not appear in previous versions。
My Version
13 May 16:24:55 - [info] Node-RED version: v0.20.5
13 May 16:24:55 - [info] Node.js  version: v10.15.3
13 May 16:24:55 - [info] Windows_NT 10.0.17763 x64 LE
How can I solve this problem? Looking forward to your reply.
![Snipaste_2019-05-13_16-53-04](https://user-images.githubusercontent.com/24561933/57608505-a2050a80-759f-11e9-894d-d7321590a0d5.jpg)

**Comment by dceejay** [comment]
Will be fixed in version 0.8.3
