### ISSUE TITLE
node-red-node-pi-gpiod: stop servo output

### ISSUE THREAD

**Issue by MKaiser96** [node-red/node-red-nodes#543]
I want to control my servo. When it is in neutral (50), I want to be able to stop the signal. I want to adjust it manually without him working against it.

**Comment by knolleary** [comment]
Please use the issue template you were given when raising the issue.

**Comment by dceejay** [comment]
The library should already support sending 0 to turn off the output.

**Comment by dceejay** [comment]
Have updated the node to now let you send null or "" when in servo mode to turn off output.
Version 0.0.12

**Comment by MKaiser96** [comment]
Hi,

thank you for editing.
Today I tested it and it doesn't work. I use node-red combined with ioBroker. There I created a variable to control the servo. First it was a number. But now it is a string to type in a Space, "" or null. The steering works really well. But the disabling doesn't work.

There is a photo of my flow with different input signals and the settings of the node.

Why doesn't is work?

![pi_gpiod_Servo_off](https://user-images.githubusercontent.com/50888445/61213047-3efd3480-a704-11e9-85ed-c4881ebb52b7.jpg)

**Comment by dceejay** [comment]
Well the API docs - http://abyz.me.uk/rpi/pigpio/python.html#set_servo_pulsewidth say the param 0 (from my code) _ should set the output to off - and that is how I call it here - https://github.com/node-red/node-red-nodes/blob/master/hardware/pigpiod/pi-gpiod.js#L102 so...  are you sure you have latest version ?
