### ISSUE TITLE
unable to install on RpiZW

### ISSUE THREAD

**Issue by realjanek** [node-red/node-red-nodes#549]
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment]
You need to fill in the template

**Comment by realjanek** [comment]
node v10.16.0
npm v 6.9.0
nodered v0.20.6
unable to install any version of sensortag. Which one works?

**Comment by hardillb** [comment]
As stated in the contribution guide and in the template, please ask questions on the forum, in the Node-RED Slack or on StackOverflow with the appropriate tag
