### ISSUE TITLE
`{"state":"off"}` works, but `{"state":"on"}` doesn't

### ISSUE THREAD

**Issue by hepcat72** [node-red/node-red-nodes#551]
I just set up my WeMo node for the first time.  I was confounded by the fact that I could turn them off in my flow, but not on. Finally got them all to work by using 0 or 1 without quotes.  The documentation says on/off strings should work...

### Which node are you reporting an issue on?

WeMo Output

### What are the steps to reproduce?

Create an inject node that sends this json: `{"state":"on"}`

### What happens?

The debug shows it was sent, but device does not turn on.

### What do you expect to happen?

Socket to turn on.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.5
- [x] node.js version: v11.12.0
- [x] npm version: 0.1.14
- [x] Platform/OS: RP1 3
- [x] Browser: Safari (on Mac)

**Comment by hardillb** [comment]
The doc says it accepts inputs of:

 - Strings with "on" or "off"

These are meant to be the content of `msg.payload` not an object with at key of `state: "on"` or `state: "off"`

The object is explicitly for light type devices and there the state is 1/0

**Comment by hepcat72** [comment]
Huh. I suppose the doc could be improved with an explicit example. Anyway....

So why does any JSON with {“state”:1}, {“state”:0}, {“state”:”off”} work?

**Comment by hepcat72** [comment]
And will that way of doing it continue to work in the future? It’s nice to just create 1 json string from IFTTT and have it pass through conditionals without needing to create a separate string...

**Comment by dceejay** [comment]
Currently the code takes any incorrect parameter to mean off... ie it tests for on - else it's off.
I'm sure a Pull Request to improve the docs (and/or code) would be useful.
Happy to re-open if you want to provide some.
