### ISSUE TITLE
node-red-node-serialport node shows in command line but no output into debug node

### ISSUE THREAD

**Issue by drowsylogic** [node-red/node-red-nodes#556]
### Which node are you reporting an issue on?
node-red-node-serialport
0.8.3

### What are the steps to reproduce?
Set Up Serial Device
Connect to USB of Raspberry Pi
Enter command and scan for some data:
`~ $ cat /dev/ttyACM0
`TAICB1160999

Data is successfully returned in command line.
Try to scan in node red from serial node to debug node.
Says connected but no data output to the debug node.

### What happens?
No data shows up in the debug node.

### What do you expect to happen?
The same data that is showing up in the command terminal to show up in the debug window.
### Please tell us about your environment:

- [0.20.7 ] Node-RED version:
- [ 10.15.2] node.js version:
- [ 5.8.0] npm version:
- [ Raspbian Version 10 (buster)] Platform/OS:
- [ Chromium Version 74.0.3729.157] Browser:

**Comment by dceejay** [comment]
what line ending have you set to split on ? many devices send \r rather than \n.

In general we prefer how-to type questions via the discourse forum or slack channel so the widest possible audience can help resolve them, leaving the issue list for bugs in the code. Thanks

**Comment by drowsylogic** [comment]
I'm sorry... I made such a stupid mistake. It works fine. Sorry for wasting your time.

**Comment by dceejay** [comment]
No worries. We’ve all done it.
