### ISSUE TITLE
_timerpass documentation is inadequate.

### ISSUE THREAD

**Issue by truglodite** [node-red/node-red-nodes#559]
### Which node are you reporting an issue on?
node-red-contrib-stoptimer
node-red-contrib-looptimer
...perhaps others?
### What are the steps to reproduce?
Wire output of stoptimer to input of looptimer. Now, try to restart the looptimer from the stoptimer after the looptimer has been stopped.
### What happens?
The looptimer never restarts. The reason is timer modes add a "_timerpass:true" to the message, which makes subsequent timer nodes ignore it. To get it working, most folks are adding a change node to delete the _timerpass part.
### What do you expect to happen?
Looptimer should restart when it gets the next message.
### Please tell us about your environment:
Pi3b+, hassio 0.96.2, latest nodered addon for hassio.

### proposed change?
I think the _timerpass thing may be useful for some situations. The default for timer nodes has _timerpass:true enabled, which breaks the most basic application (2 timer modes in a row). I believe the defaulting it off would be compatible with most common implementations. I also believe that adding a checkbox to timer nodes where a user can toggle _timerpass on/off would be great... if not that, at least add some documentation to timer modes regarding _timerpass and what it does.

**Comment by knolleary** [comment]
Hi, those are not nodes that are in this repository, nor are they maintained by the Node-RED project.

You should raise an issue against their own repository. You should be able to find it linked from their page of flows.nodered.org.
