### ISSUE TITLE
 failed to install node-red-contrib-pca9685 on the latest version of nodered err i2c bus

### ISSUE THREAD

**Issue by farihaPriyanka** [node-red/node-red-nodes#563]
### Please tell us about your environment:

- [x] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
`node-red-contrib-pca9685` is not a module we are responsible for.

You can find a link to its own github page on the flow library - https://flows.nodered.org/node/node-red-contrib-pca9685

**Comment by farihaPriyanka** [comment]
I had tried this but its not working

**Comment by knolleary** [comment]
> I had tried this but its not working

Then you should raise an issue against the node. This repository is not the right place to do that.
Follow the link on the node's page to its own github repository. You can then raise an issue there.

You will need to provide more information than you have here. An actual error message for example.

**Comment by farihaPriyanka** [comment]
ok thank you
