### ISSUE TITLE
bug in RBE mode "block if value change greater than"

### ISSUE THREAD

**Issue by ianmacs** [node-red/node-red-nodes#569]
### Which node are you reporting an issue on?
RBE

### What are the steps to reproduce?
Configure the rbe node fields to 
- "block if value change greater than" 
- 0 (that's the number zero)
- "compared to last input value".

Deploy it and pass to RBE the same numeric payload repeatedly. 

This is done in the following minimal example flow:
`[{"id":"93bea00e.4ce7e","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"6b75e49.0e87f1c","type":"inject","z":"93bea00e.4ce7e","name":"","topic":"","payload":"1","payloadType":"num","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":80,"wires":[["1891a3c5.984d6c","11c26259.6ce816"]]},{"id":"1891a3c5.984d6c","type":"debug","z":"93bea00e.4ce7e","name":"log rbe input","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"\"Input: \" & msg.payload","targetType":"jsonata","x":250,"y":160,"wires":[]},{"id":"11c26259.6ce816","type":"rbe","z":"93bea00e.4ce7e","name":"block if value change greater than zero","func":"narrowband","gap":"0","start":"","inout":"in","property":"payload","x":350,"y":80,"wires":[["46c3192f.842cc8"]]},{"id":"46c3192f.842cc8","type":"debug","z":"93bea00e.4ce7e","name":"log rbe OUTPUT","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"\"OUTPUT: \" & msg.payload","targetType":"jsonata","x":530,"y":160,"wires":[]}]`

### What happens?
All messages are blocked by RBE.

### What do you expect to happen?
Since the input values are always the same, the value change is not greater than zero, and therefore the messages should not be blocked by RBE (starting with the second message).

### Please tell us about your environment:

- [X] Node-RED version: v0.20.7
- [X] node.js version: v10.15.2
- [X] npm version: 5.8.0
- [X] Platform/OS: Raspberry Pi 4, Raspbian Lite
- [X] Browser: Firefox 68.0.1 (64-bit) on Ubuntu

**Comment by dceejay** [comment]
as a work around you can use a switch node and check == against previous value.

**Comment by ianmacs** [comment]
Thanks for the workaround suggestion!

**Comment by dceejay** [comment]
Published as version 0.2.5
