### ISSUE TITLE
Mail to web.de fails

### ISSUE THREAD

**Issue by fah** [node-red/node-red-nodes#572]
### Which node are you reporting an issue on?
node-red-node-email@1.6.3

### What are the steps to reproduce?

Send full secured email to smtp.web.de:587

Following instructions here:
https://hilfe.web.de/pop-imap/pop3/serverdaten.html#indexlink_help_pop-imap_pop3

### What happens?
```
Error: 3069662880:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```
And no email was sent.

### What do you expect to happen?
Send an email in a secure way.

### Please tell us about your environment:

- [ ] Node-RED version: 1.9.0
- [ ] node.js version: v10.16.3
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Raspberry 4 / 4GB
Linux _name_ 4.19.57-v7l+ #1244 SMP Thu Jul 4 18:48:07 BST 2019 armv7l GNU/Linux
- [ ] Browser: Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit) on MacOS Mojave 10.14.6

**Comment by hardillb** [comment]
Please update with exactly how you configured the node. e.g. did you tick the "Use Secure Connection" box (and what happens if you don't tick that box

**Comment by hardillb** [comment]
Also the node-red version you have given is not vald, there is no 1.9.0 version, do you mean 0.19?

**Comment by fah** [comment]
node-red-is used as an iobroker adapter.
Checking https://github.com/ioBroker/ioBroker.node-red/blob/master/README.md show the version 1.9.0 of the adapter.
Digging there shows node-red 0.20.7 is used inside the adapter.

I ticked all boxes for maximum security. "Use TLS?" and "Use secure connection.".

**Comment by hardillb** [comment]
Untick the "Use TLS box" leave the "Use secure connection" ticked.

**Comment by fah** [comment]
Without TLS:
```
Error: 3069662880:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**Comment by fah** [comment]
I'm using the settings I used here in several other applications and email programs. So they work.

**Comment by hardillb** [comment]
Port 587 on that server is not a SSL connection, you need to connect in the clear then use the `STARTLS` command to upgrade it to a secure connection. I've tested this with openssl s_client and it works properly.

Swap the tick boxes over, tick the "Use TLS" and untick the "Use secure connection" (I might have got the underlying order wrong in the node, but it's not clear)

**Comment by hardillb** [comment]
Actually reading the docs for [Nodemailer](https://nodemailer.com/smtp/), odd as it seems both should probably not be ticked.

For port 587 you should not be making a native TLS connection and if secure is passed `false` the node will still use `STARTTLS` to secure the connection as long as the server advertises it (which it does).

**Comment by fah** [comment]
Just TLS on:
```
Error: Mail command failed: 550-Requested action not taken: mailbox unavailable550 Sender address is not allowed.
```

Both off:
same

Thats strange as I do not provide any sender address.
The "to" address is my own.
Name has the same email address.
Is the "From:" set somewhere else?

**Comment by hardillb** [comment]
Right, so both off is what you want to fix the error you reported (which should probably documented better).

You can set the from in the `msg.from` property of the object passed to the node

**Comment by hardillb** [comment]
From the node's sidebar

> You may optionally set msg.from in the payload which will override the userid default value.

**Comment by fah** [comment]
Ok, it works, but is that a good way? I will not change the "From" that often. It should be in the form to set it static.

Also it does not improve my good feeling to unset security boxes to send my password - even though the password is actually encrypted after the handshake.

So I think there are two open points.
- Strange ticking boxes naming / behavior
- Missing "From" textfield in the settings form  as it is mostly a static value.

Thank you for your help!
