### ISSUE TITLE
Cosmetic issue - function issue with status

### ISSUE THREAD

**Issue by michaelblight** [node-red/node-red-nodes#581]
### Which node are you reporting an issue on?
function
### What are the steps to reproduce?
Link an inject node to a function node. Put the following in the function node:
```
node.status({ 
    fill: "green", 
    shape: "dot", 
    text: "Other"
});
```
Deploy and click the inject node to run and see the status. Now open the function node and change the number of outputs to 3 or more and click done. 
### What happens?
Having 3 outputs causes the function node to expand in height, but the status does not move and ends up overlapping the function node. Cosmetic I know, but just in case you haven't seen it already.
### What do you expect to happen?
The status node should always be below the bottom of the function node.
### Please tell us about your environment:

- [ ] Node-RED version: v1.0.0
- [ ] node.js version: v10.16.3
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Ubuntu
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
closed in core project by https://github.com/node-red/node-red/commit/147d2a02bee96471bd1cdc0639842c88c7a60134

**Comment by knolleary** [comment]
Ah, that's why I couldn't find the original report of this issue when I fixed it... Was looking in the wrong repo.
