### ISSUE TITLE
node-red-node-mysql: msg.payload of INSERT INTO is string, not JSON

### ISSUE THREAD

**Issue by boldt** [node-red/node-red-nodes#583]
### What are the steps to reproduce?

1) Create a function node with a MySQL _INSERT INTO_ Query:

```js
msg.topic = "INSERT INTO revpi (value) VALUES ('10');";
return msg;
```
2) Execute this with a mysql node 
3) Print `msg.payload` with a debug node

### What happens?

The `msg.payload` is string `"[object Object]"`, not a JSON object:

![grafik](https://user-images.githubusercontent.com/750793/66835015-0e28d780-ef5f-11e9-81e9-4304cccffad2.png)

Like this, it is not possible to determine, whether the MySQL statement was successful or not.

### What do you expect to happen?

A JSON object like this (as returned by the mysql library):

![grafik](https://user-images.githubusercontent.com/750793/66835125-416b6680-ef5f-11e9-8e82-2fc77e5a0460.png)

With `affectedRows: 1` and `insertId: 89` it is possible to determine, whether the MySQL statement was successful or not.

### Please tell us about your environment:

- [X] Node-RED version: 1.0.1
- [X] node.js version: docker conatiner `nodered/node-red`
- [X] npm version: docker conatiner `nodered/node-red`
- [X] Platform/OS: docker conatiner `nodered/node-red` on Ubuntu 18.04.1 LTS
- [X] Browser: Firefox

**Comment by dceejay** [comment]
OK - have managed to recreate... if i change the debug node to show complete message it then displays the payload OK...

![image](https://user-images.githubusercontent.com/5375409/66857771-da11de80-ef7f-11e9-93b1-6381ae8204fc.png)

It seems to be because the payload is of a type "OkPacket" - so not quite sure how best to handle that...

**Comment by dceejay** [comment]
If I convert the OkPacket to a "normal" object it works fine
![image](https://user-images.githubusercontent.com/5375409/66860368-fbc19480-ef84-11e9-8d15-55ec13aa00d4.png)

So I propose to do that conversion to fix it... any possible downsides ? would anyone (in Node-RED)  expect or know how to handle an OkPacket type ? (when all other results get sent as a standard array object)

**Comment by dceejay** [comment]
So - another thought - all other results end up as an array object `[ rows ]`.  Should this OK result end up inside an array also ? or just a regular object ? Would consistency be best - or is the difference useful to be able to tell them apart ? 
(I think keep them different)

**Comment by boldt** [comment]
Since the results are created by the mysql-library, I propose to keep the syntax of the library to be consistent to it. Means: keep an array for SELECT and an object for INSERT and DELETE statements.

We should double check the SELECT result-array. As far as I recall, it also contains some kind of special "packets" (I don't have node/nodered on my mobile to check). I'll update this post tomorrow. 

Wrt to the OkPacket, I believe it's okay to convert it to a normal object. Let's double check with the mysql-library implementation.

**Comment by dceejay** [comment]
Thanks - will await your further investigation.

**Comment by boldt** [comment]
I ran the same query in plain node (mysql lib) and in NodeRed. I also added a debug message after the line `msg.payload = rows;`, which is hown in the Docker log:

https://github.com/node-red/node-red-nodes/blob/master/storage/mysql/68-mysql.js#L132

# INSERT INTO 

### Node
![grafik](https://user-images.githubusercontent.com/750793/66905689-9f06be00-f006-11e9-8aef-dc385b8df80c.png)

### Docker log

![grafik](https://user-images.githubusercontent.com/750793/66908206-fad34600-f00a-11e9-8dc4-7f40f6c5563e.png)
### NodeRed Debug UI

![grafik](https://user-images.githubusercontent.com/750793/66906026-379d3e00-f007-11e9-890c-5b5e9b18bf96.png)

### OkPacket

The OkPacket is this one:

* https://github.com/mysqljs/mysql/blob/master/lib/protocol/packets/OkPacket.js

It's an object, which contains a bunch attibutes:

```js
function OkPacket(options) {
  options = options || {};

  this.fieldCount   = undefined;
  this.affectedRows = undefined;
  this.insertId     = undefined;
  this.serverStatus = undefined;
  this.warningCount = undefined;
  this.message      = undefined;
  this.protocol41   = options.protocol41;
}
```

# SELECT

### Node
![grafik](https://user-images.githubusercontent.com/750793/66905608-7383d380-f006-11e9-8a40-838f8966d55c.png)

### Docker log 

![grafik](https://user-images.githubusercontent.com/750793/66908286-1b030500-f00b-11e9-8d0e-e85cca601559.png)

### NodeRed Debug UI
![grafik](https://user-images.githubusercontent.com/750793/66905970-218f7d80-f007-11e9-89d0-e031e808b5fd.png)

## Observation

* SELECT: The result array contains "normal" Javascript-Objects and not the `RowDataPacket`. I dont see any kind of processing happening? Why is the RowDataPacket showing w/o any trouble?
* INSERT INTO: From my point of view its ok to convert/cast it to "normal" JS object, since its juste the object as sown above.
* We also need a proper handle for `ErrorPackets` (e.g. a broken query).

**Comment by dceejay** [comment]
Do you have an example that creates an ErrorPacket ?

**Comment by boldt** [comment]
Maybe smth like this will be useful:

```js
var packets = require('mysql/lib/protocol/packets');
[...]
if (rows instanceof packets.OkPacket) {
    // Convert
} else if (rows instanceof packets.ErrorPacket) {
    // Convert
}
```

**Comment by boldt** [comment]
> Do you have an example that creates an ErrorPacket ?

Sure, just break the query:

```sql
SELECT * FROM doesNotexists ORDER BY date DESC LIMIT 10
```

**Comment by dceejay** [comment]
That seems to trap and raise an error ok
![image](https://user-images.githubusercontent.com/5375409/66910138-e6407f00-f005-11e9-95a8-5bf73b8d2b55.png)

**Comment by dceejay** [comment]
OK - have pushed version 0.0.19 to npm. See what you think ?

**Comment by boldt** [comment]
I just had a look inside your code. I propse to use the following to clone the objcet into a new object:

```js
msg.payload = Object.assign({}, rows)
```

instead of

```js
msg.payload = JSON.parse(JSON.stringify(rows));
```

I'll check it in my nodeRed now.

**Comment by boldt** [comment]
From NodeRed UI, I cannot update, [since it is not available yet](https://flows.nodered.org/node/node-red-node-mysql).

Thus, I jumped in the docker container and I forced the installation to 0.0.19:

```bash
npm install node-red-node-mysql@0.0.19
```

The result looks good to me:

![grafik](https://user-images.githubusercontent.com/750793/66912739-70dbab00-f013-11e9-9b80-0db8d7c5312f.png)

**Comment by boldt** [comment]
SELECT seems to be brkoen now:

![grafik](https://user-images.githubusercontent.com/750793/66913785-a7b2c080-f015-11e9-919f-42629b73eb48.png)

**Comment by boldt** [comment]
How about my `Object.assign`-proposal?

**Comment by dceejay** [comment]
Well object.assign is faster - but is only a shallow copy. Mine does a deep copy. So depends if you think anyone/anything may change one of those will it's still in use. i guess you would hope a subsequent query would not modify it.
