### ISSUE TITLE
node-Arduino issues extra/redundant pinmode commands to Firmata?

### ISSUE THREAD

**Issue by m-elias** [node-red/node-red-nodes#584]
### Which node are you reporting an issue on?
Node-Arduino

### What are the steps to reproduce?
Flash the StandardFirmataPlus example sketch onto an Arduino
Connect to rPi via usb
Use a ui-slider node to output 0-255 to an arduino-out node configured for analog output
Alternately, use a inject node set to repeat to output a static value to the arduino-out node
Use LED or oscope to observe "flickers" in the pwm signal.

### What happens?
It appears the PWM output randomly skips an output period only when analog values are being sent to the Arduino running Firmata regardless of whether it's the a static value or changing values. Possibly, the respective IO's pinmode is being updated every time which causes a momentary 0 value to be output by the Firmata setPinModeCallback function.

### What do you expect to happen?
I expect the PWM output to be steady, the IO's pinmode should only be set once.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.1
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Node-Red runs on a Raspberry Pi Zero W
- [ ] Browser: Chrome on W7x64

**Comment by m-elias** [comment]
I originally posted on Firmata's github, and soundanalogous kindly pointed to the pinmode command on Node-Arduino that causes the repeated pinmode settings.
https://github.com/firmata/arduino/issues/430#issuecomment-542804566

**Comment by m-elias** [comment]
In setPinModeCallback:

`

    case PIN_MODE_PWM:
      if (IS_PIN_PWM(pin)) {
        pinMode(PIN_TO_PWM(pin), OUTPUT);
        analogWrite(PIN_TO_PWM(pin), 0);   // causes a flicker if timing of write syncs with PWM output update
        Firmata.setPinMode(pin, PIN_MODE_PWM);
      }
      break;
    case PIN_MODE_SERVO:
`

**Comment by dceejay** [comment]
HI, I don't have an arduino to hand right now but can see your point. Would you be willing to try some patched code yourself ? dm me   dceejay  @  gmail.com and I can send you a patched file.

**Comment by dceejay** [comment]
Any joy @m-elias ?

**Comment by m-elias** [comment]
I won't have time to test it until tomorrow.

**Comment by dceejay** [comment]
no worries - action is now with you :-)

**Comment by dceejay** [comment]
any luck ?

**Comment by m-elias** [comment]
Sorry, real life keeps getting in the way of my hobbies. I've stepped up from a rPi Zero W to an Odroid XU4 w/ eMMC for development so I'm looking forward to the increase in speeds. I had no issue installing the library in node red now so I'm going to test it very soon. I'll bring an Arduino with me next time to try it at home if need be.

**Comment by m-elias** [comment]
Today I'm testing node-arduino on a new Odroid XU4 Linux install/setup without changing the FirmataStandardPlus firmware on my Arduino. I installed node-arduino yesterday(?) from the npm repository, not from your attached test, and I visually see very very little PWM output flicker. Then I installed your 0.2.4 test and it visually looks the same.

I switched to using my new Odroid because the Pi Zero W is just too slow for dev. Do you want me to fire it up and see what happens there?

**Comment by dceejay** [comment]
Yes please - If it improves the old situation that would be good.

**Comment by m-elias** [comment]
Now after restarting Node-Red on my oDroid, I see absolutely no flickering, even less than before. The LED is very smooth using either the dashboard slider or a pot on an analog input on the same firmata Arduino. I'll setup and test again on my rPi Zero W.

**Comment by m-elias** [comment]
I spooled up the rPi Zero W with node-Arduino 0.2.2 and the PWM output flickered but with your test 0.2.4 it's nice and smooth just like my Orange Pi One! (I mistakenly confused my oPi with my oDroid XU4 in my previous posts)

**Comment by dceejay** [comment]
Great - I will publish the fix to npm.
Thanks for finding the original bug and thanks for helping to fix it.
