### ISSUE TITLE
Wemo Input Node connected to motion sensor not sending json

### ISSUE THREAD

**Issue by hepcat72** [node-red/node-red-nodes#585]
### Which node are you reporting an issue on?

node-red-node-wemo

### What are the steps to reproduce?

Add a wemo input node to a flow, configure it by selecting a wemo motion sensor from the list of devices, connect it to a debug node, deploy, then trip the motion sensor and watch the debug panel.

### What happens?

No debug message appears in the debug panel. The motion sensor definitely triggers because it itself turns blue and my WeMo app sends me a push notification, but nothing is coming out of the corresponding wemo input node.

### What do you expect to happen?

According to:

https://github.com/node-red/node-red-nodes/blob/master/hardware/wemo/WeMoNG.html

a wemo motion detector is listed as supported and should send a json payload as described in the linked doc above.

I used the node in a flow to post a web hook and set a global variable. When that didn’t happen, I connected the debug node and noted it wasn’t sending anything.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.5
- [x] node.js version: 11.12.0
- [x] npm version: 6.9.0
- [x] Platform/OS: Raspberry Pi 3
- [x] Browser: Safari

**Comment by hardillb** [comment]
The motion sensor is not supported, mainly because I never got my hands on one to play with

**Comment by hardillb** [comment]
Hmm, I see the doc says it is, but I definitely never had one to play with

**Comment by hepcat72** [comment]
I installed a program on my Mac a long time ago called automation-server (formerly wemo-server) and I wrote a script to process its log output and capture events. I used it to trigger spoken reminders when I pass by by motion sensor. I wonder if there’s any output from it I could send you that would allow for an update to make it work...

**Comment by hepcat72** [comment]
Or maybe you could look at the code for automation-server to glean some info.

**Comment by hardillb** [comment]
I'll look at it properly when I get home

**Comment by hepcat72** [comment]
https://sites.google.com/site/mppsuite/downloads/wemoserver-java

**Comment by hardillb** [comment]
Can you uncomment ling 459 in the `WeMoNG.js` file

https://github.com/node-red/node-red-nodes/blob/master/hardware/wemo/WeMoNG.js#L459

And send me the log output (should be a blob of XML) when you trigger the motion sensor.

**Comment by hepcat72** [comment]
Sure.  I'll have to do it when I get home.  My wife's going to figure drawing tonight, so I should have time to play around with it.

**Comment by hepcat72** [comment]
I was messing around with it last night. I’m not sure that the problem is specific to the motion sensor. I have wemo output nodes that are unresponsive as well. In fact, I think I have a few things going on that I need to address. I can’t rule out some issue with the wemo nodes yet though. Let me ask a few questions:

1. Would a wemo input node not work (by design)  if it’s in a subflow?
2. Can you have multiple copies of wemo output nodes configured for the same device in separate flows? Because test node copies I created in another flow weren’t working.
3. Should config nodes exist globally or do I have a miscounting that is creating them per flow? Because I appear to have a config node in each flow that has a wemo node and I get warnings about unused config nodes when in fact the offending node is used (by the motion sensor in 1 case, but another copy is used in another flow). And I have to re-add devices in each flow. Plus, my config nodes appear to be named randomly as one of the devices.
4. New copies of nodes I created in a separate flow didn’t work initially, but either after a redeploy or node-red restart or both, a green square under them showed up which I’d never seen before labeled “found” and they started working (including a copy of the motion sensor). I have about a dozen other wemo nodes in another flow that seem to work, I.e. they control the devices, but they neither have the “found” icon nor output anything to the debug node they’re connected to. Could this be because they’re in a subflow?

I had other issues going on. There are errors in the console output about my garage door (not wemo) and I was seeing “too many open file handles” errors in one terminal window. I restarted the pi and that seems to have addressed that issue.

**Comment by hardillb** [comment]
1. No subflows will have no impact at all on the way the node works
2. Yes, you can have as many copies of the node as you want pointing to the device
3. Config nodes should be global, there is no need to limit their scope to just a specific flow.
4. None of the nodes will work until the green dot and found is displayed. You can probably help things by making sure you are only deploying the changed nodes, not everything. When you do a full deploy it tears everything down and that throws out all the discovered devices and it has to do discovery again.

Please make the change I asked for earlier, then restart node-red. Wait for the green dot "found" to show up then trigger the motion sensor. This should create the XML I  need.

**Comment by hepcat72** [comment]
1. OK.  I assumed limitations imposed by subflows would explain why the motion sensor node in the subflow wouldn't work and the one in the regular flow did.  Guess not.
2. I considered this as an alternate explanation as to why the motion sensor node didn't work in the subflow, but worked in the regular flow.  I guess this isn't the case either.
3. This one surprises me. How is it that I have separate wemo config nodes that appear to be flow-specific (i.e. their device select lists are all different in each flow)? How do I set up one wemo config node that is global? When I added an input wemo node for the motion sensor to a test workflow, it created a new config node and its device select list was initially empty.  I had to click the pencil next to the select list to add the motion sensor to the select list. And when I deployed, I got a message saying it was an unused config node (though there were other wemo config nodes under other flows that apparently are "used") and that config node was named by the motion sensor device. I added a copy of an output node for my "bedroom AC" socket and that seemed to get around the unused config node warning and the motion node seemed to work after deployment then the socket node was also in the flow.
4. Both of my new input/output test nodes were labeled "found" and the motion sensor node seemed to work after deployment (I.e. the motion sensor input node spits out debug messages when I step in front of the motion sensor). However all my old output nodes in a different subflow all work (as in, they can control the devices via injection) even though they do not have the "found" label under them and they do not spit out debug messages. However, weirdly, I could not control new bedroom AC output node using inject nodes despite the green "found" label being there.

I did in fact uncomment the line you requested last night, but I had trouble identifying the specific output in the log. Besides, the motion sensor seemed to be working (with the test node copy I made, but not the original input node in the subflow) so I assumed I was doing something wrong and figured I'd be wasting your time by having you look into some issue with the motion sensor's json, because it's basically the same as the socket's json. I suspect the problem is some sort of weird config node issue or some dumb mistake of my own. I was hoping to say, "OK, my bad, I figured it out", but ended up going to bed without a resolution.

I noticed that the motion sensor outputs a state every 20 seconds.  It appears to be polling.  Do I have an old version?  I thought there was supposed to be only event-driven output.

Incidentally, I don't know how to do deployments other than what you get when you click the red deploy button.  Is that a "full" deploy or does that just deploy changes?

**Comment by hardillb** [comment]
Click the arrow on the end of the Deploy button, it has 3 levels.

I have no idea what version you have, you'll have to look that up (it will be in the `package.json` next to the `WeMoNG.js`) but on, there never was a polling version.

It might be that the motion sensor publishes it's state on a regular basis.

**Comment by hardillb** [comment]
You won't see the status flags when looking at the subflow, because what you edit is just the template, not the actual running instances of that subflow.

**Comment by hepcat72** [comment]
That makes sense I guess.  Look, I'll close this.  The description of this issue is at the least, inaccurate.  I don't think I've identified the real problem yet.  If I do, I'll create a separate issue.  Thanks for your help thus far.

**Comment by hepcat72** [comment]
Incidentally, the node configured for the motion sensor doesn't work when it's in a subflow. Like you said, it's a template, so it's not going to trigger with motion on its own. And I don't know if it's the sensor or what (though other wemo software I use doesn't display this behavior), but there is definitely a message coming out of the node every 20 seconds (state:0) unless motion is detected - then it's state:1. Anyway, I don't think there's anything wrong with the code WRT the motion sensor.
