### ISSUE TITLE
node-red-gpiod add hardware PWM

### ISSUE THREAD

**Issue by stevenaeola** [node-red/node-red-nodes#596]
As discussed on https://discourse.nodered.org/t/raspberry-gpio-pwm-frequency-wrong/3474/15

**Comment by stevenaeola** [comment]
Needs refactoring to use pigpiod-client instead of js-pigpio

**Comment by dceejay** [comment]
No need to raise an issue if you are about to raise a PR (having discussed it as per above)

**Comment by stevenaeola** [comment]
Sorry, I was trying to follow https://nodered.org/about/contribute/

**Comment by dceejay** [comment]
Hi - yes not a problem. As we have had the discussion and decided to go ahead - then yes please proceed straight to PR :-)
