### ISSUE TITLE
NODE RED GET TWEETS

### ISSUE THREAD

**Issue by NDNELSON** [node-red/node-red-nodes#598]
How can I received in msg.payload tweets, messages more than 140 characters, I am running hassio add on but all tweets what i received only catch first 140 characters

Node-RED hassio add-on: 5.0.3

**Comment by hardillb** [comment]
As stated in the template you were shown when you opened the issue, general questions should be asked on the forum or in the Node-RED Slack.

Version 5.0.3 is the hassio version and we have no idea what that means for the Node-RED version.

Also please read the other open issues about the twitter nodes e.g. #464
