### ISSUE TITLE
node-red-contrib-email strange behaviour

### ISSUE THREAD

**Issue by DamianosS** [node-red/node-red-nodes#602]
Hi, 
I use two instances of the node-red-contrib-email node, which repeatedly are fetching emails from an IMAP server. 

Since installing 1.7.2 (I suppose) I encounter the following awkward behavior:
- I can't change the attributes of the nodes (when hitting "Done". All fields are populated again with the previously set values.
- When dragging a new instance on the canvas the fields are also populated with the values of the other used nodes. 

I deleted the used nodes (even the entire flow), but the behavior didn't change. A new node keeps getting the values from the deleted node.

The only thing I didn't try is removing the nodes from the palette and re-installing them. But, maybe it is useful for debugging reasons.

Please, advise. Thanks.

- [ ] Node-RED version: 1.0.2
- [ ] node.js version: 10.17.0
- [ ] npm version: 6.13.0
- [ ] Platform/OS: Raspberry Pi
- [ ] Browser: Chrome (on Windows 10)

**Comment by hardillb** [comment]
This is most likely chrome being "helpful" and filling in the form fields for you. But you should be able to change them before hitting done

**Comment by DamianosS** [comment]
Indeed. All works fine in Opera. Sorry for the hassle.
