### ISSUE TITLE
node-red-node-serialport and Electron 7.1.1 

### ISSUE THREAD

**Issue by rei-vilo** [node-red/node-red-nodes#603]
`node-red-node-serialport@0.8.8` dependd on `serialport ^7.1.5`, which does not support the current version of Electron 7.1.1.

As a workaround,

```
git clone https://github.com/node-red/node-red-nodes.git
cd node-red-nodes/io/serialport/
vi package.json
```

Change
```
   "dependencies"  : {
-        "serialport"   : "^7.1.5"
+        "serialport"   : "^8.0.5"
```
Then
```
npm install
electron-rebuild --version 7.1.1 
```

_From https://github.com/sakazuki/node-red-desktop/issues/16#issuecomment-552644140_

**Comment by dceejay** [comment]
Have now bumped serialport node to use 8.0.5 library.
