### ISSUE TITLE
Unexpected 'C2' is made. 

### ISSUE THREAD

**Issue by alsrjs2441** [node-red/node-red-nodes#607]
### Which node are you reporting an issue on?
[{"id":"ddd8e73f.825cc8","type":"tab","label":"플로우 2","disabled":false,"info":""},{"id":"307c0eb8.857d72","type":"function","z":"ddd8e73f.825cc8","name":"msg maker (global count)","func":"var a = String.fromCharCode(0x02, 0x01, 0xB1, 0x00, 0x00, 0x00, 0x00, 0x03);\n\nfunction hex2bin(hex){\n    return (parseInt(hex, 16).toString(2)).padStart('B', '1');\n}\n\nvar b = hex2bin(0xB1);\n\nconsole.log(b);\n\n\nvar buf1 = Buffer.from(a);\nconsole.log(a);\nconsole.log(buf1);\nvar arr = [buf1];\n\nvar buf = Buffer.concat(arr);\nconsole.log(buf);\n\nvar resultlist = [] ;\nfor (i = 0; i<a.length; i++) { //str 길이만큼 반복\n  hex = a.charCodeAt(i).toString(16); //str에서 i번째 문자를 16진법으로 변환하여 hex에 지정\n  resultlist.push((\"0\"+hex).slice(-2)) ;//hex값을 st\n}\nconsole.log(resultlist);\nreturn msg;\n","outputs":1,"noerr":0,"x":670,"y":60,"wires":[["54abbf58.b2ea9","b99e84ff.04aa78","fab0a029.540ed"]]},{"id":"54abbf58.b2ea9","type":"serial out","z":"ddd8e73f.825cc8","name":"","serial":"e8f4cc0a.d4907","x":970,"y":60,"wires":[]},{"id":"85a6a7c3.5ca1f8","type":"inject","z":"ddd8e73f.825cc8","name":"XFPTRT","topic":"Xenon_Foolproof_Temperature_Request_Timer","payload":"","payloadType":"date","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":80,"wires":[["307c0eb8.857d72"]]},{"id":"ff17215.5940fe","type":"serial in","z":"ddd8e73f.825cc8","name":"","serial":"e8f4cc0a.d4907","x":170,"y":380,"wires":[["9b0a94b5.a6de78","d9657389.99a3b"]]},{"id":"4a271bbb.fc0064","type":"debug","z":"ddd8e73f.825cc8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":570,"y":240,"wires":[]},{"id":"fa88377e.c27018","type":"function","z":"ddd8e73f.825cc8","name":"result1","func":"var str = msg.payload.result1 ;\nmsg.payload = str ;\nreturn msg;","outputs":1,"noerr":0,"x":550,"y":300,"wires":[["383b04fc.b9168c"]]},{"id":"fa067695.57fdf8","type":"debug","z":"ddd8e73f.825cc8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":930,"y":300,"wires":[]},{"id":"383b04fc.b9168c","type":"function","z":"ddd8e73f.825cc8","name":"returned data","func":"var str = msg.payload ; //PF에서 나온 결과값을 str로 지정\nvar resultlist = [] ; //빈 array인 strlist 생성\nfor (i = 0; i<str.length; i++) { //str 길이만큼 반복\n  hex = str.charCodeAt(i).toString(16); //str에서 i번째 문자를 16진법으로 변환하여 hex에 지정\n  resultlist.push((\"0\"+hex).slice(-2)) ;//hex값을 strlist에 저장\n}\nmsg.payload = resultlist ;\nreturn msg ;\n","outputs":1,"noerr":0,"x":730,"y":300,"wires":[["fa067695.57fdf8"]]},{"id":"9b0a94b5.a6de78","type":"function","z":"ddd8e73f.825cc8","name":"Datastore","func":"var json_obj = global.get('json_obj')\n\n  json_obj = {result1 : ''} ;\n  json_obj.result1 = msg.payload ;\n  global.set('json_obj',json_obj) ;\n  msg.payload = json_obj ;\n\nreturn msg;\n","outputs":1,"noerr":0,"x":340,"y":380,"wires":[["fa88377e.c27018","4a271bbb.fc0064","1a4f7d37.f3d003"]]},{"id":"1a4f7d37.f3d003","type":"function","z":"ddd8e73f.825cc8","name":"Transfer data","func":"if (msg.payload.result6 != '') {\n  //데이터 전송\n}","outputs":1,"noerr":0,"x":570,"y":180,"wires":[[]]},{"id":"b99e84ff.04aa78","type":"debug","z":"ddd8e73f.825cc8","name":"","active":false,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":890,"y":160,"wires":[]},{"id":"d9657389.99a3b","type":"debug","z":"ddd8e73f.825cc8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":310,"y":460,"wires":[]},{"id":"fab0a029.540ed","type":"function","z":"ddd8e73f.825cc8","name":"returned data","func":"var str = msg.payload ; //PF에서 나온 결과값을 str로 지정\nvar resultlist = [] ; //빈 array인 strlist 생성\nfor (i = 0; i<str.length; i++) { //str 길이만큼 반복\n  hex = str.charCodeAt(i).toString(16); //str에서 i번째 문자를 16진법으로 변환하여 hex에 지정\n  resultlist.push((\"0\"+hex).slice(-2)) ;//hex값을 strlist에 저장\n}\nmsg.payload = resultlist ;\nreturn msg ;\n","outputs":1,"noerr":0,"x":1130,"y":60,"wires":[["b2aadbd6.cc7fc8"]]},{"id":"b2aadbd6.cc7fc8","type":"debug","z":"ddd8e73f.825cc8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":1280,"y":84,"wires":[]},{"id":"e8f4cc0a.d4907","type":"serial-port","z":"","serialport":"COM7","serialbaud":"19200","databits":"8","parity":"none","stopbits":"1","waitfor":"0x02","newline":"0","bin":"false","out":"time","addchar":"","responsetimeout":"1000"}]

### What happens?
The buffer is created like this

101110111
±    
<Buffer 02 01 c2 b1 00 00 00 00 03>
<Buffer 02 01 c2 b1 00 00 00 00 03>
[
  '02', '01', 'b1',
  '00', '00', '00',
  '00', '03'
]
### What do you expect to happen?
I want to send buffer like this

101110111
±    
<Buffer 02 01 b1 00 00 00 00 03>
<Buffer 02 01 b1 00 00 00 00 03>
[
  '02', '01', 'b1',
  '00', '00', '00',
  '00', '03'
]
Without 'C2', I want to send just ' 02 01 b1 00 00 00 00 03'
### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2
- [ ] Platform/OS: windows
- [ ] Browser: crome

**Comment by knolleary** [comment]
Please update the issue to say which node you are reporting an issue on.

**Comment by dceejay** [comment]
"C2" is often part of a UTF8 string so I suspect you are using default string conversions to/from utf8 rather than specifying binary mode. Which node is causing the issue ?
