### ISSUE TITLE
Password Protected SQLite Database

### ISSUE THREAD

**Issue by 1978maarten** [node-red/node-red-nodes#608]
I am using a SQLite database in my node-red application.
For security purposes, the database is password protected.
Is there any way to supply the password to the SQLite node within the Node-Red Flow?
If remove the password from the database then everything works as expected.
Any help here would be appreciated.

**Comment by dceejay** [comment]
No - all the default sqlite libraries don't seem to support encryption - we use sqlite3.
There is a very old writeup here about how to wrap it - https://github.com/mapbox/node-sqlite3#building-for-sqlcipher that may still work - but you would also still then need to edit the node to add the extra calls.

**Comment by 1978maarten** [comment]
thanks for the clarification and the tip i will look into it.
