### ISSUE TITLE
XMPP - config node server & port fields commented out ?

### ISSUE THREAD

**Issue by zosky** [node-red/node-red-nodes#613]
hi all - i updated node-red and the nodes a few hours ago... xmpp no longer works with gApps. 

seems easy enough to *fix*; or am i missing something ?

- *node*: **xmpp**
- *situation*: as a gApps client my JID is _user-at-my-domain.com_ **but** the server is not on my-domain.com, need to set _talk.google.com_ (and the default port:5222)
- *cause*: v0.2.0 b856ee6439c45d9d927a39fbbbe4e985240cf633 the server & port fields where commented from the config node ? 
- **fix needed: uncommenting these 2 blocks**
  - https://github.com/node-red/node-red-nodes/blob/698af48500dcac0273fa168f35f1446b6cba5736/social/xmpp/92-xmpp.html#L112-L117 
  - https://github.com/node-red/node-red-nodes/blob/698af48500dcac0273fa168f35f1446b6cba5736/social/xmpp/92-xmpp.js#L9-L10
- **now i can send & receive again** 

is there a reason this stuff was turned off ?

### Please tell us about your environment:

- [x] Node-RED version: **1.0.3** 
- [x] node-red-node-xmpp: **0.2.3** 
- [x] npm version: **6.4.1**
- [x] Platform/OS: **linux ubuntu xenial 4.15.0-9-generic**
- [x] node.js version: **8.15.1**
- [x] Browser: chrome **73.0.3683.103**

**Comment by dceejay** [comment]
Hi,
I must admit I can't recall why it was commented out. I guess for most users they are on the same domain so the server could be assumed... I'll restore it as it was until I can recall :-)
