### ISSUE TITLE
node-red-node-rbe: "deadband" is not visible in the GUI, only in the Node Help

### ISSUE THREAD

**Issue by elmicha** [node-red/node-red-nodes#620]
### Which node are you reporting an issue on?

node-red-node-rbe 0.2.6

### What are the steps to reproduce?

In the rbe node properties you can select options like "block unless value changes", "block unless value changes (ignore initial value)".

### What happens?

In the Node Help there's no reference to these options, the help only talks about "RBE mode" and "Deadband mode" and so on, but these options are not mentioned. I had to grep around in /.node-red/node_modules/node-red-node-rbe to find how these terms are related:

```
locales/en-US/rbe.json:            "rbe": "block unless value changes",
locales/en-US/rbe.json:            "rbei": "block unless value changes (ignore initial value)",
locales/en-US/rbe.json:            "deadband": "block unless value change is greater than",
locales/en-US/rbe.json:            "deadbandEq": "block unless value change is greater or equal to",
locales/en-US/rbe.json:            "narrowband": "block if value change is greater than",
locales/en-US/rbe.json:            "narrowbandEq": "block if value change is greater or equal to",
```

### What do you expect to happen?

Either the Help should mention the option values or the select box should also show the option keys.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3
- [ ] node.js version: v10.18.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Raspbian
- [ ] Browser: Firefox 72.0.1

**Comment by dceejay** [comment]
The words are in the description in the info panel. But yes we can make them more exactly match.

How about

<p>In RBE mode this node will <b>block until</b> the <code>msg.payload</code>,
    (or selected property) value is different to the previous one. If required 
    it can ignore the intial value, so as not to send anything at start.</p>
    <p>In the Deadband modes the incoming value must contain a parseable number and will <b>block
    unless the change is greater than</b> + or - the band gap away from a previous value.</p>
    <p>Deadband also supports % - only sends if the input differs by more than x% of the original value.</p>
    <p>The Narrowband modes will <b>block if the incoming value change is greater than</b> + or - the band gap
    away from the previous value. Useful for ignoring outliers from a faulty sensor for example.</p>
    <p>Both Deadband and Narrowband allow comparison against either the previous valid output value, thus
    ignoring any values out of range; or the previous input value, which resets the set point, thus allowing
    gradual drift (deadband), or a step change (narrowband).</p>

**Comment by elmicha** [comment]
Ah yes, I think with the bold words I would have seen them. Thank you!
