### ISSUE TITLE
node-red-node-leveldb can't store json object

### ISSUE THREAD

**Issue by celevra** [node-red/node-red-nodes#626]
### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [x] node.js version: 10.18.1
- [x] npm version: 6.13.4
- [x] Platform/OS: ubuntu 18.04
- [x] Browser: Chrome

Hi, i try to store a json object in leveldb.
on retriev i get "[object] [object]"

here is a example flow:

```
[
    {
        "id": "6d5a0eb0.7491f",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": ""
    },
    {
        "id": "12379602.7c8b1a",
        "type": "inject",
        "z": "6d5a0eb0.7491f",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 160,
        "wires": [
            [
                "4c21f7cf.9b4188"
            ]
        ]
    },
    {
        "id": "b965858c.56df98",
        "type": "inject",
        "z": "6d5a0eb0.7491f",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 260,
        "wires": [
            [
                "38405a21.aa6fc6"
            ]
        ]
    },
    {
        "id": "4c21f7cf.9b4188",
        "type": "function",
        "z": "6d5a0eb0.7491f",
        "name": "",
        "func": "msg.topic = \"test\";\nmsg.payload = {}\nmsg.payload.test1 = \"blub\"\nmsg.payload.test2 = \"blub2\"\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 310,
        "y": 160,
        "wires": [
            [
                "6902f915.aa8fb8"
            ]
        ]
    },
    {
        "id": "6902f915.aa8fb8",
        "type": "leveldb out",
        "z": "6d5a0eb0.7491f",
        "level": "2bd65aac.27fb16",
        "operation": "store",
        "name": "",
        "x": 500,
        "y": 160,
        "wires": []
    },
    {
        "id": "5ccdf844.95f4a8",
        "type": "leveldb in",
        "z": "6d5a0eb0.7491f",
        "level": "2bd65aac.27fb16",
        "name": "",
        "x": 500,
        "y": 260,
        "wires": [
            [
                "bac5d7e4.c1e4c8"
            ]
        ]
    },
    {
        "id": "bac5d7e4.c1e4c8",
        "type": "debug",
        "z": "6d5a0eb0.7491f",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 660,
        "y": 260,
        "wires": []
    },
    {
        "id": "38405a21.aa6fc6",
        "type": "change",
        "z": "6d5a0eb0.7491f",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "test",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 310,
        "y": 260,
        "wires": [
            [
                "5ccdf844.95f4a8"
            ]
        ]
    },
    {
        "id": "2bd65aac.27fb16",
        "type": "leveldbase",
        "z": "",
        "db": "DBStore"
    }
]
```

am i doing something wrong?

regards

celevra

**Comment by knolleary** [comment]
I suspect the node is doing a simple string conversion of the object you are giving it.

If you want it to store a JSON representation of your object, then use a JSON node immediately before hand to do that conversion.

**Comment by celevra** [comment]
I don't get it
The data is already json
Could you show a little example?
________________________________
Von: knolleary <notifications@github.com>
Gesendet: Donnerstag, 6. Februar 2020 22:26
An: node-red/node-red-nodes
Cc: Philipp Zeitschel; Author
Betreff: Re: [node-red/node-red-nodes] node-red-node-leveldb can't store json object (#626)


I suspect the node is doing a simple string conversion of the object you are giving it.

If you want it to store a JSON representation of your object, then use a JSON node immediately before hand to do that conversion.

**Comment by knolleary** [comment]
You are passing a JavaScript object in, not a JSON string. They are different ways of representing the same thing.

As I said, add a JSON node between the Function node and the leveldb node.

**Comment by celevra** [comment]
Ah you mean stringify ok I will try that
________________________________
Von: knolleary <notifications@github.com>
Gesendet: Donnerstag, 6. Februar 2020 22:49
An: node-red/node-red-nodes
Cc: Philipp Zeitschel; Author
Betreff: Re: [node-red/node-red-nodes] node-red-node-leveldb can't store json object (#626)


You are passing a JavaScript object in, not a JSON string. They are different ways of representing the same thing.

As I said, add a JSON node between the Function node and the leveldb node.

**Comment by dceejay** [comment]
Good spot - by default it can only store strings...
I have added the option to allow storing JSON (and binary) options...
pushed as version 0.3.0.
(defaults to text as before)
