### ISSUE TITLE
node-red-node-serialport serial-in stopping flow

### ISSUE THREAD

**Issue by drowsylogic** [node-red/node-red-nodes#628]
### Which node are you reporting an issue on?
node-red-node-serialport "serial-in node"

### What are the steps to reproduce?
1. Create an executable version of Node-RED/Node.js and execute on a computer using:
[PKG-Node-RED](https://github.com/imZack/pkg-node-red).
2. Install node-red-node-serialport from the palette manager.
3. Drag serial in node to flow.
4. Deploy

### What happens?
Error Popup:
```
Flows stopped due to missing node types.
    serial-port
    serial in
```

### What do you expect to happen?
Successful deployment with serial messages flowing our of the serial-in node.

Error in logs:
[stdout.log](https://github.com/node-red/node-red-nodes/files/4215195/stdout.log)
I can see that it wants to attempt to recompile the binary for this but since Node-RED is packaged I do not believe that I have access to NPM to rebuild or reinstall the node. 
If packaging the environment into an executable is not to be supported functionality please let me know and I will close this issue.

### Please tell us about your environment:
Node-RED version: 

- [v1.0.3] Node-RED version:
- [v12.2.0] node.js version:
- [v6.9.0] npm version:
- [Linux 4.4.0-cip-uc8100a-me arm LE - Debian 9] Platform/OS:
- [Firefox 73.0 (64-bit) - Mozilla Firefox for Ubuntu Canonical - 1.0] Browser:

Thank you!

**Comment by hardillb** [comment]
You should raise this with the pkg-node-red folk, that is not a core Node-RED project

**Comment by dceejay** [comment]
As @hardillb points out this is due to different versions of node.js being used by that packager. You will need to ask them for advice on how to add extra packages - or rebuild the package with the serialport node built in. So closing it here.
