### ISSUE TITLE
SQLite: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by alexk111** [node-red/node-red-nodes#630]
### Which node are you reporting an issue on?

SQLite

### What are the steps to reproduce?

- Subflow-X (config + error handling): input - SQLite - output
- Subflow-Y (some reusable common logic, configured via env vars): input - switch with 9 outs to their own template and Subflow-X nodes - output
- Flow 1: 4 Subflow-Y nodes
- Flow 2: 9 Subflow-Y nodes

### What happens?

When starting NR it shows:
```MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added to [Database]. Use emitter.setMaxListeners() to increase limit```
```MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Database]. Use emitter.setMaxListeners() to increase limit```

Probably caused by this:
https://github.com/node-red/node-red-nodes/blob/master/storage/sqlite/sqlite.js#L16-L26

### What do you expect to happen?

No warnings

### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [x] node.js version: 12.13.1
- [x] npm version: 6.12.1
- [x] Platform/OS: Ubuntu 18.04
- [x] Browser: Chrome

**Comment by dceejay** [comment]
sounds like it's working well... giving a warning when you have added more than 10 instances :-)
But yes the node should get re-used more efficiently...  (or rather - should not keep attaching listeners to itself)

**Comment by alexk111** [comment]
Thanks for the quick fix :)
