### ISSUE TITLE
Give time example and sort by time

### ISSUE THREAD

**Issue by wernight** [node-red/node-red-nodes#633]
May I suggest to add the README some example time for each option:

1. 05:16 Astronomical twilight starts
2. 05:55 Nautical twilight starts
3. 06:30 Civil twilight starts
4. 07:00 Sunrise
5. 07:03 Sunrise end
6. 07:40 End of morning golden hour

7. 17:35 Start of evening golden hour
8. 18:15 Sunset starts
9. 18:18 Sunset, civil twilight starts
10. 18:50 Dusk, astronomical twilight starts
11. 19:30 Nautical twilight starts
12. 20:00 Dark enough for astronomy

I'd suggest to sort also the dropdown by start time (as in my list).

**Comment by hardillb** [comment]
Please uses the template you were shown when you opened this issue. Specifically the bit about which node you are talking about as this repo holds a lot of different nodes.

If you have doc updates please feel free to open a pull request adding the changes and we can review it.
