### ISSUE TITLE
node-red-node-serialport get /serialports endpoint throws error "node is not defined"

### ISSUE THREAD

**Issue by scottpageindysoft** [node-red/node-red-nodes#637]
node-red version: 1.0.4 (embedded inside of a Docker container)
node version: 13.8.0

Issue:
At line 468 of 25-serial.js, node is referenced, but not defined in the exported module.
`node.log('Error listing serial ports', err)`.  `node = this` is defined inside of each node constructor function, but that's not accessible at the module's scope level.  As a result, any request to /serialports hangs in the pending status.  Also, there's no visual error that anything wrong occured, until the request finally fails, then it appears in the console.  I'm running embedded so I see the error server-side.

Note:
The call to `node.log` is a side-effect of anther error being thrown, mainly because I'm running in Docker, and I haven't configured the container to access external tty devices.  So, under normal working conditions, this issue wouldn't be noticed.

Offending line for reference:
https://github.com/node-red/node-red-nodes/blob/e3e6c41030e20779875e85d4fe932a71c20b6ea9/io/serialport/25-serial.js#L468

**Comment by dceejay** [comment]
thanks. will fix/remove.
