### ISSUE TITLE
Max number of leds for node-red-node-pi-neopixel

### ISSUE THREAD

**Issue by braghettos** [node-red/node-red-nodes#638]
### Which node are you reporting an issue on?
node-red-node-pi-neopixel

### What are the steps to reproduce?
use docker image braghettos/makealedwheaterboard:latest
source code is available at https://github.com/braghettos/makealedweatherboard.git

### What happens?
After 8 strips of 60 leds each, connected as a single led strip, leds start to flicker.

### What do you expect to happen?
Leds not flickering. What is the maximum number of leds that the library can control?

### Please tell us about your environment:

- [ ] Node-RED version: nodered/node-red:1.0.4-12-minimal-arm32v6
- [ ] node.js version: Node.js  version: v12.16.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Linux 4.19.97+ arm LE (Alpine)
- [ ] Browser: Version 80.0.3987.132 (Build ufficiale) (a 64 bit)

**Comment by hardillb** [comment]
This will be much more likely to be down to how much power you can supply to the strip and nothing to do with the node. Also as the template clearly stated, do not use issues to ask questions, they are for defects only.

**Comment by dceejay** [comment]
no idea - though it's not really a Node-RED question - I would googling around may be the best answer.

**Comment by braghettos** [comment]
Thank you so much!
