### ISSUE TITLE
NODE-Red shows not the right timezone in nodes

### ISSUE THREAD

**Issue by nexro567** [node-red/node-red-nodes#640]
Hello,

I'm running on NODE-Red node:

> node-red-node-timeswitch

Is it possible to fix the place text place within time selection and not only in dawn/dusk because we changed in timezone here in The Netherlands. Now thinks my node it's 21:00, but it's now 23:00..

Thanks!

**Comment by nexro567** [comment]
I used `date` and `docker` exec -it <container id> date` the time as shown is right but still wrong in NODE-Red. So the host time set right..

**Comment by nexro567** [comment]
Fixed the issue.
In your local storage you find `local/nodered/settings.js`.
Fill in line 1 `process.env.TZ = "Europe/Amsterdam";` and restart your host.

All nodes shown now the right timezone.

**Comment by hardillb** [comment]
You should be able to pass the TZ env var in on the Docker command line as well
