### ISSUE TITLE
daemon node - "output lines of text" only outputs the last line

### ISSUE THREAD

**Issue by freddyli** [node-red/node-red-nodes#642]
### Which node are you reporting an issue on?
daemon

### What are the steps to reproduce?
(1) Create a python script with following content:
```python
import sys

for line in sys.stdin:
    print('Hello')
    print('World')
```

(2) Setup a daemon node with the script using "output lines of text" mode

(3) Use an inject node to inject some input and watch the output of the daemon node using debug.

### What happens?
The daemon node outputs 2 times the content: "World"

### What do you expect to happen?
The daemon node outputs 2 messages - 1: "Hello" - 2: "World"

### Please tell us about your environment:

- [x] Node-RED version: v1.0.3
- [x] node.js version: v10.19.0
- [x] npm version: v6.13.4
- [x] Platform/OS: docker "nodered/node-red:latest"
- [x] Browser: Chrome v80

### Code review

I looked into `master/utility/daemon/daemon.js` and see this:

```javascript
                node.child.stdout.on('data', function (data) {
                    .........
                        while (bits.length > 1) {
                            lastmsg.payload = bits.shift();
                            node.send([lastmsg,null,null]);
                        }
```

I am not that much of a JS programmer but I think the issue is that the `lastmsg` object is reused for the different payloads, but when the time (slot in the event loop) comes to actually send those out, only the last change on the payload property is being seen.

**Comment by dceejay** [comment]
as oer the info - did you try using the -u option for python so as not to buffer the output ?

**Comment by freddyli** [comment]
Jep thats the
Command: `python3`
Arguments: `-u /tmp/go.py`

**Comment by freddyli** [comment]
The problem can be worked around by waiting in between the line outputs - e.g.
```python
    print('Hello')
    time.sleep(1)
    print('World')
```

Then the event loop has enough time to send the `lastmsg` object out, before its `payload` property is modified again.

**Comment by freddyli** [comment]
I think the proper solution would be not to reuse the `lastmsg` object, or to duplicate it. Because otherwise there will always be modification of an existing object, which may even be on the way through different successor nodes, I guess

**Comment by dceejay** [comment]
Thanks for spotting it. new version published to npm

**Comment by freddyli** [comment]
OMG, that was fast! Thank you, I'll test it out!
