### ISSUE TITLE
node-red-node-mysql can't set propper collation

### ISSUE THREAD

**Issue by holnburger** [node-red/node-red-nodes#648]
The query results using node-red-node-mysql seems to be missing emojis and display ? instead. It looks like the node is using the standard collation charset defined in https://www.npmjs.com/package/mysql which happens to be "UTF8_GENERAL_CI".

I'm using the "UTF8MB4_GENERAL_CI" in my environment as it also allows the (proper) use of emojis within strings and varchars. I can't change or overwrite the default settings via node-red-node-mysql. 

It would be great if custom collation charset would be made available to modify from within the node settings:
![image](https://user-images.githubusercontent.com/22478441/79617406-b5055080-8107-11ea-9477-d5a375538523.png)

### What are the steps to reproduce?
MariaDB with UTF8MB4 collation, tables with VARCHAR or TEXT columns containing emojis like 🇪🇺

### What happens?
node-red-node-mysql seems to use the default setting of UTF8_GENERAL_CI

### What do you expect to happen?
Correct export of emojis using the server collation

### Please tell us about your environment:

- Node-RED version: 6.1.4
Using Home-Assistants Docker-Container for Node-RED integration
- Platform/OS: Ubuntu 18.04 + Docker

**Comment by dceejay** [comment]
is there a way for the client to detect the required setting from the server ? 
If the client was defaulted to UTF8MB4 instead - would it still work with non-UTF8MB4 servers ?
Should it be UTF8MB4_UNICODE_CI instead ? would that be more useful ?

**Comment by holnburger** [comment]
> is there a way for the client to detect the required setting from the server ?

There is, you can check the collation of the used database via 
`SELECT @@character_set_database, @@collation_database;`

> If the client was defaulted to UTF8MB4 instead - would it still work with non-UTF8MB4 servers ?

I checked the default settings in https://www.npmjs.com/package/mysql#connection-options and if I get it correct, this npm package was used for this node.

It is strongly recommended to use UTF8MB4 instead of the UTF8 implementation as mysql made a mistake back then implementing it wrongly. More on this: 
https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

The devs are even planing on removing the "old" collatioon, but it is still being used:
https://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/

> Should it be UTF8MB4_UNICODE_CI instead ? would that be more useful ?

I think it should be, but I'm not sure about backwards compatibility. UTF8MB4_UNICODE_CI is the current default character set for MySQL since Version 8.0. 
Older implementations are depricated and will be removed.
https://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/

I think its best to extend the settings by the option "charset" and make UTF8MB4_UNICODE_CI the new default.
![image](https://user-images.githubusercontent.com/22478441/79638671-06a0f000-8187-11ea-8377-2fcd0b066058.png)
![image](https://user-images.githubusercontent.com/22478441/79638686-1a4c5680-8187-11ea-8dfa-16e2f8dee5a4.png)

**Comment by dceejay** [comment]
I think the default would need to be as per existing in order not to break anyone already using it. The way I read it you need to configure the server end also to use it - so if someone hasn't done that - (or have been using general utf8) - to write to it then you can't just swap the client to MB4 and carry on working... or am I mistaken ?

**Comment by holnburger** [comment]
I think you are correct.

It would be great to have MB4 as an option then.

**Comment by dceejay** [comment]
the docs seem rather spare - could you do some testing for us please ? 
if you find and edit the file 68-mysql.js around line 42 (in the createPool call -  add a line as you suggest
```
charset: "utf8mb4",
```
save - stop and restart Node-RED - see if that works... my worry is that they seem to mention utf8_general_ci  (lowercase) , UTF8_GENERAL(CI (uppercase) - utf8mb4 (without -general etc) - so we need a list of definite working options.

**Comment by holnburger** [comment]
Will test it tonight and report.

**Comment by dceejay** [comment]
hmm - have found a list of over 250 charsets in the library - https://github.com/mysqljs/mysql/blob/master/lib/protocol/constants/charsets.js
so maybe just a text input would be simplest.

**Comment by dceejay** [comment]
Actually I have pushed a change for you to try... - please try to install direct from github
```
cd ~/.node-red
npm i https://github.com/node-red/node-red-nodes/tree/master/storage/mysql
```
hopefully that will get it installed. 
a) please check it still works "as-is" with an older flow
b) can work with UTF8MB4 when configured to do so.
and let me know
Thanks

**Comment by holnburger** [comment]
Had to download the files in https://github.com/node-red/node-red-nodes/tree/master/storage/mysql and install it locally but: Good News!

a) Checked it with the older flow, still working as expected with "?" instead of correct emojis
b) Checked it with UTF8MB4 in settings on another machine, exact same flow: Emojis coming through!

Great job! And blazing fast!

**Comment by dceejay** [comment]
Ok - pushed to npm as 0.1.1
