### ISSUE TITLE
Unable to Have Disposition Setting to Delete Work With Yahoo

### ISSUE THREAD

**Issue by tkdrob** [node-red/node-red-nodes#650]
Which node are you reporting an issue on?
e-mail in

What are the steps to reproduce?
Set up my nodes. Everything else works, mark read disposition works

What happens?
emails are not deleted

What do you expect to happen?
for emails in specified folder to be deleted

Please tell us about your environment:

- [ ] Node-RED version: 1.0.5
- [ ] node.js version:  12.15.0
- [ ]npm version: 6.14.4
- [ ] Platform/OS: Synology Home Assistant Addon
- [ ] Browser: Chrome

**Comment by qivhou** [comment]
@tkdrob  you can install the master version to try again.
this issue has been fixed, can be closed now.
