### ISSUE TITLE
node-red-node-ping output values even without connection when using url

### ISSUE THREAD

**Issue by Leonel-Toledo** [node-red/node-red-nodes#651]
# Which node are you reporting an issue on?
node-red-node-ping

### What are the steps to reproduce?
Creating to nodes:  PING_A: target "8.8.8.8", PING_B: target "facebook.com"

### What happens?
When connection is lost:
  * PING_A outputs "false" status (as expected)
  * PING_B outputs "false" one time, after that output values (like there was response)

If interface is shutdown, PING_B outputs "false", if interface is up again (still with network failure), PING_B return to output response values.

![01 - Results with network ok](https://user-images.githubusercontent.com/64513493/80559465-99256880-89ab-11ea-8133-83b35c08cb81.jpg)
![02 - Results with network failure](https://user-images.githubusercontent.com/64513493/80559468-9b87c280-89ab-11ea-9649-a6f9f0ba1423.jpg)

### What do you expect to happen?
  if there is no connection, there is no way for url address to respond the request, so the output
should be "false", as correctly happens when target is an IP address

### Please tell us about your environment:
Node-RED version: v1.0.4
Node.js  version: v12.16.2
NPM version: 6.14.4
Platform: Linux 5.3.0-46-generic #38~18.04.1-Ubuntu
node-red-node-ping version: 0.2.0
Browser: Google Chrome Versión 81.0.4044.129

**Comment by dceejay** [comment]
Hi 
can you supply a small flow that demonstrates this ? 
The latest ping node can accept an array of targets - is that what you are using ? 
Thanks

**Comment by Leonel-Toledo** [comment]
Greetings,

Attached you will find the flow I'ḿ using. It's quite simple

I was running the flow in my laptop when a power outage happened, then I
saw that PINGs targeted to URLś  showed response, while PINGs targeted to
IP addresses returned "false".

  For further testing:
  - I disabled my Wifi card. Then PING to URLs returned false,
  - I enabled again my Wifi card, still no electricity (router off). then
PING to URLś returned values again

  Best regards,

  Leonel Toledo

**Comment by Leonel-Toledo** [comment]
Sorry, I need to make a correction from my previous report:

  If the wifi is on but not connected to any router, PING output to URLs is
"false"

  if the wifi is connected to a router,  but there is no internet
connection on that router, PING output to URL provide values  (PING output
to IP addresses correctly output "false")

  Best regards,

  Leonel Toledo

**Comment by dceejay** [comment]
Still no flow attached that I can see - but a simple test here seems to work ok... maybe your router is doing something weird cacheing wise ? Or are you going via  proxy ? or ... not really sure.

**Comment by Leonel-Toledo** [comment]
Grettings,

 The flow was attached on the first email, but it's extremely simple.

  Anyway, it turns out your idea is right. When connecting to a different
router and removing the internet service, all PINGs output "false".

  First router tested open a portal-like page when it's offline, Probably
the logic for doing so generates the answer the PING node receives.

  Thank you for your kind and diligent support. The bug report is
satisfactory closed.

  Best regards,

  Leonel Toledo

**Comment by hardillb** [comment]
Email attachments are not added to the issue. You need to add files via the web interface
