### ISSUE TITLE
Email send html message

### ISSUE THREAD

**Issue by grafoteka** [node-red/node-red-nodes#659]
### Which node are you reporting an issue on?
Email node

### What are the steps to reproduce?
Send something in msg.html. 
E.g:
```
msg.payload = 192.168.1.1;
msg.topic = "router";
msg.html = '<a href="www.google.com"></a>';
```

### What happens?
Only is sent msg.payload and msg.topic

### What do you expect to happen?
It should send msg.topic and msg.html

### Please tell us about your environment:

- [x] Node-RED version: 1.0.5
- [ ] node.js version: 
- [x] npm version: 1.0.16
- [x] Platform/OS: Raspberry Pi 3
- [x] Browser: Firefox and safari

**Comment by hardillb** [comment]
`msg.html` is an output from the email-in node, it is not a supported option for the email-out node.

If you want to send a html email  then you put the html content in the `msg.payload`

**Comment by grafoteka** [comment]
Thank you for your answer @hardillb, after fighting a little bit with the URL variable, the code is like that:
```
ip_str = "http://" + ip_str + ":1880/ui";
msg.payload = "La nueva direccion IP es: " + "<a href="+ip_str+">enlace</a>";
msg.topic = "San Cristobal IP router";
```
Thank you!
