### ISSUE TITLE
Sense hat shows question mark

### ISSUE THREAD

**Issue by Schwenkner** [node-red/node-red-nodes#661]
### Which node are you reporting an issue on?
Sense hat
### What are the steps to reproduce?
Show character or text,
### What happens?
Text is shown shortly, at the end a question mark "?" is displayed unless I trigger the aoutput again.
### What do you expect to happen?
Th character shall stay on the display, in case of scrolling text it shall left blank at the end of the scrolling.
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
What text *exactly* are you passing the sensehat? It will display a `?` for any character it doesn't support in its limited font.

Can you pass the message you are sending the sensehat to a Debug node and share its output here so we can see exactly what you're passing in?

**Comment by Schwenkner** [comment]
sure, here it is, I think, nothing special.
{"_msgid":"c07a636e.234b4","topic":"","payload":" ","color":"off"}

**Comment by Schwenkner** [comment]
I solved my problem, sorry for my post here. It was my fault. I had a second output on another flow with silly output and this was also timer based. I didn't remember having this.
