### ISSUE TITLE
node-red-node-sqlite using msg.topic reports "Error: SQLITE_RANGE: column index out of range" when msg.payload is an array.

### ISSUE THREAD

**Issue by janvda** [node-red/node-red-nodes#670]
see also node-red forum discussion: 
* https://discourse.nodered.org/t/node-red-node-sqlite-using-via-msg-topic-reports-error-sqlite-range-column-index-out-of-range/31462

### Which node are you reporting an issue on?
node-red-node-sqlite
### What are the steps to reproduce?
Configure the node to use "Via msg.topic" and pass as input not only the query in the msg.topic but also an array in the msg.payload.

Here an example of the input giving the problem:
![image](https://user-images.githubusercontent.com/17238398/90008283-5fe3e080-dc9c-11ea-8b09-228cd378d26c.png)

### What happens?
It reports the following error:
```
Error: SQLITE_RANGE: column index out of range
```

### What do you expect to happen?
As the query in msg.topic is valid no error should be returned, instead it should return in the payload the query result output.

*Workaround*: Note that it works fine when the input message doesn't have a msg.payload.

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.4
- [ ] node.js version: v12.16.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: linux 4.18.0-193.6.3.el8_2.x86_64 x64 LE
- [ ] Browser: chrome

The version of node-red-node-sqlite: 0.4.3

**Comment by ibmrcruicks** [comment]
the error would appear to be because of mixing the use of msg.topic with fully-populated SQL, and a payload with bind-able values. it's the sqlite3 package that is raising the error.

The SQL has no bind place-holders "?" so there is no array of placeholders to which the payload values can be bound.
_"select * from country where id in (?,?,?,?,?,?,?,?,?)"_ would most likely work, but i suspect is probably not the best way to achieve what you  want - just set msg.topic to your query, and set msg.payload to be empty.

**Comment by janvda** [comment]
@dceejay 
Should Node-RED not ignore the msg.payload in case the msg.topic is specified ?

I think that the documentation is even not mentioning msg.payload as input parameter.
In order to bind parameters I am using msg.params as per the documentation and not msg.payload.

**Comment by ibmrcruicks** [comment]
currently, the node will treat { msg.topic + payload (if array) }  in much the same way as { Prepared + msg.params } but you're right, the docs don't say anything about combining the SQL query/command in msg.topic with msg.payload.
either we improve the docs, to allow sql with placeholder to be passed in msg.topic, and bind values in payload[], or ignore when `msg.topic` is specified

**Comment by janvda** [comment]
Updating the documentation is indeed also an option to address this issue.
(Note that in current documentation msg.payload is nowhere mentioned as input parameter).

**Comment by dceejay** [comment]
well - in Node-RED payload is always assumed to be the input parameter unless specified... but yes - I guess docs should mention it. Anything else would change behaviour and break something/someone.

**Comment by knolleary** [comment]
If someone was considering a PR to clarify the docs, I'll just throw in that I notice this node hasn't been updated to follow the help style guide yet either... would be a nice 2-for-1. https://nodered.org/docs/creating-nodes/help-style-guide

**Comment by janvda** [comment]
To be clear on the documentation as it seems to be different from what @dceejay reports here above.
This is what I see and use as documentation for that node (should I also look somewhere else ?)

![image](https://user-images.githubusercontent.com/17238398/95557861-b14aea80-0a15-11eb-9a06-4b6eb4f1081e.png)

**Comment by dceejay** [comment]
sorry... no idea why I was looking at mysql node rather than sqlite. Yes needs to be edited.

**Comment by r0ller** [comment]
> 
> 
> currently, the node will treat { msg.topic + payload (if array) } in much the same way as { Prepared + msg.params } but you're right, the docs don't say anything about combining the SQL query/command in msg.topic with msg.payload.
> either we improve the docs, to allow sql with placeholder to be passed in msg.topic, and bind values in payload[], or ignore when `msg.topic` is specified

I definitely vote for the latter one (ignore payload when msg.topic is specified). This issue has just hit us (when upgrading to sqlite node 1.0.0 ) and we had to downgrade to 0.6 in order to avoid adding a line to hundreds of functions to clear the payload. Guys, what are your plans with this?

**Comment by dceejay** [comment]
happy to consider a Pull request to fix code / clarify docs.

**Comment by dceejay** [comment]
Actually had 5 mins to have a quick look - I don't think we want to completely ignore payload as there are times when you can use it (ie if the array is actually correct)- but maybe a better check would help... eg maybe edit the node's sqlite.js file line 56
https://github.com/node-red/node-red-nodes/blob/master/storage/sqlite/sqlite.js#L56
to be
```
                            if (Array.isArray(msg.payload)) {
                                if (msg.payload.length === (msg.topic.split('$').length - 1) ) { bind = msg.payload; }
                                else { bind = []; }
                            }
```

If you wanted to try that and let us have feedback that would be useful.

**Comment by r0ller** [comment]
> If you wanted to try that and let us have feedback that would be useful.

Thanks for the patch! Tested it and seems to work fine :) What's next? Shall I create a pull request for your patch -which would then look as if I created the patch- but I'm willing to get this merged anyhow :)

**Comment by dceejay** [comment]
no probs - I'll merge it here.
