### ISSUE TITLE
Pushbullet input node: unknown push type: sms_changed

### ISSUE THREAD

**Issue by elmicha** [node-red/node-red-nodes#674]
### Which node are you reporting an issue on?

node-red-node-pushbullet 0.0.14

### What are the steps to reproduce?

Have Pushbullet on an Android phone and receive an SMS.

### What happens?

I got two of these error messages in the same second:

    Aug 20 09:15:57 rpi Node-RED[566]: 20 Aug 09:15:57 - [error] [pushbullet-config:elmicha] unknown push type: sms_changed content: {"type":"sms_changed","source_device_iden":"XXX","notifications":[{"thread_id":"57","title":"+49XXX","body":"XXX","timestamp":1597907754}]}

### What do you expect to happen?

I'd like to get these pushes in the output of the Pushbullet in node, not as an error message.

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.3
- [ ] node.js version: v10.22.0
- [ ] npm version: .14.6
- [ ] Platform/OS: Linux/Raspbian 5.4.51-v7l+
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
add sms_changed as a type to version 0.0.15
