### ISSUE TITLE
mondgoDB support for clustering

### ISSUE THREAD

**Issue by ibmrcruicks** [node-red/node-red-nodes#677]
### Which node are you reporting an issue on?
node-red-mongodb
### What are the steps to reproduce?
add mongodb-in node
configure with cluster name as hostname, username/password, target database
### What happens?
error - port not supported for cluster connections
error - hostname (clustername) not found
### What do you expect to happen?
try specific shard hostname instead of clustername - make connection -- does not work
### Please tell us about your environment:

- [ 1.0.3] Node-RED version:
- [ 10.13] node.js version:
- [6.10.3 ] npm version:
- [Mac OS 10.15.6 ] Platform/OS:
- [ Chrome 85] Browser:

**Comment by ibmrcruicks** [comment]
working on mods to support old and new connections - 

new needs clustername (not hostname), no port number, "mongodb+srv"  vs "mongodb" as protocol
[mongodb docs](https://docs.atlas.mongodb.com/driver-connection/)

connection working , but need UI (or auto-detect) mechanism to select appropriate connection string.

would a simple checkbox/toggle for clustered vs non-clustered in the UI be sufficient?

**Comment by dceejay** [comment]
Hi @ibmrcruicks 
generally we prefer a select box as it can usually be made more readable - and then use that select to show/hide any different UI fields further down the page (eg swap host/port for clustername etc)

**Comment by ibmrcruicks** [comment]
closed by #685
