### ISSUE TITLE
unable to send DM with Twitter out node

### ISSUE THREAD

**Issue by ThibautRuy** [node-red/node-red-nodes#686]
### Which node are you reporting an issue on?
Name | Tweet
Type | twitter out

### What are the steps to reproduce?
`msg.payload="D username test blablalala"; `

### What happens?
If I try to send the above DM with my authenticated user, DM is not received on the receiver side nor sent on the sender side. However:
- I can tweet any message with the same user
- receiver username seems to be recognized, as when I try to add @ in front of it, it fails

### What do you expect to happen?
I would expect a DM to be sent

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.2
- [ ] node.js version: v12.12.0
- [ ] npm version: 6.11.3
- [ ] Platform/OS: aws/ubuntu
- [ ] Browser: Chrome

**Comment by phillduffy** [comment]
I am able to use it currently with no issues

[{"id":"126f5670.bc356a","type":"twitter out","z":"a5ea52f5.fba92","twitter":"","name":"Tweet","x":1690,"y":300,"wires":[]},{"id":"69968cef.2b5474","type":"template","z":"a5ea52f5.fba92","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"D {{username}} {{payload}}","output":"str","x":1410,"y":620,"wires":[["ad66c761.8e0a68","126f5670.bc356a"]]},{"id":"ec9c2893.9436d8","type":"inject","z":"a5ea52f5.fba92","name":"","props":[{"p":"payload"},{"p":"username","v":"phillduffy","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"hello world","payloadType":"str","x":1160,"y":680,"wires":[["69968cef.2b5474"]]}]

**Comment by andypiper** [comment]
@phillduffy are you sure that is sending a Direct Message? I think you'll find it sends a regular Tweet. The "D [username]" syntax was [retired in 2017](https://twittercommunity.com/t/retiring-legacy-dm-commands-on-the-standard-tweet-api/86653). The Direct Message API is completely different now and takes a JSON body (and does not go through the `statuses/update` flow.

**Comment by phillduffy** [comment]
yeah, 100% certain. I have sent several today, unless I am using a different package...

https://share.site.page/Blu1eG4R

**Comment by andypiper** [comment]
huh, I'll have to dig into the client library that this node is using, I think Nick forked it so maybe he made this transparent.

**Comment by andypiper** [comment]
Yup, that's exactly how it works, it transparently converts to the new format, which makes sense. @ThibautRuy do you see any error in the Node-RED log?

Does the user you are SENDing to, follow you? or, do they have "open" Direct Messages from anyone?

**Comment by phillduffy** [comment]
Video too: https://share.site.page/DOu9yrZ9

It's magic

**Comment by ThibautRuy** [comment]
Ok I will check

**Comment by ThibautRuy** [comment]
ok, I tried again, using your flow above. Still no DM sent.
When I mistype the user name, I get an error "unknown user", which seems to tell me the API connection is fine.
Then, I use the correct user name and it runs fine, but no message is sent. Nothin in debug console, nothing in Event log.
I upgraded my node-red to v 1.2.2 and I use the v1.6 of this contrib...

**Comment by phillduffy** [comment]
I did find that some accounts didn't recieve, but might be down to DM permissions.

Try sending something to me: phillduffy

**Comment by ThibautRuy** [comment]
Ok, I found the issue... My app permission was just set to read/write, no DM. It works now, but when I deploy, I get an error message: Failed to get user profile. It does not prevent me to send DMs though.
