### ISSUE TITLE
extend topic gpiod

### ISSUE THREAD

**Issue by kadenbach** [node-red/node-red-nodes#687]
### Which node are you reporting an issue on?
node-red-node-pi-gpiod
### What are the steps to reproduce?
two pi with contact sensor on same gpio 
### What happens?
same topic for different contacts
### What do you expect to happen?
different topics for different pi's like piA/16, piB/16 or more general [host]/[pio] instead pi/[pio]

**Comment by dceejay** [comment]
good thought. I won't change the existing topic as that may break existing users - but we can certainly add a `msg.host` property to report the host - the combination of the two being available should be enough to work out where it came from.
