### ISSUE TITLE
POOL_CLOSED

### ISSUE THREAD

**Issue by Ricardo-Miguel-Caldeira** [node-red/node-red-nodes#694]
I'm getting this error... 

What does this means?

![Pool Closed](https://user-images.githubusercontent.com/52119136/94878833-77e30f80-0456-11eb-98b9-233468b0cfb3.PNG)

**Comment by hardillb** [comment]
You need to fill out the full template you were shown when you opened this issue so we have enough information to be able to start to investigate.

### Which node are you reporting an issue on?

### What are the steps to reproduce?

### What happens?

### What do you expect to happen?

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment]
As there has been no update in a week I'm closing this issue. We can reopen it if you supply the required details
