### ISSUE TITLE
Disabling Serial port for Arduino firmware updates

### ISSUE THREAD

**Issue by nielsnl68** [node-red/node-red-nodes#699]
Hello,

I love to see a switch option to the serial components to enable/disable temporary the serial port's used in the streams so i can update my arduino that is using the same serial connection.

My idea is to add a switch button like the debug-node.
Is that possible?

**Comment by dceejay** [comment]
We have no plans to disable the serial port via switches. If someone wants to offer up a PR we could consider it. Closing this issue as we have no plans to fix it.
