### ISSUE TITLE
Node-red-node-serialport

### ISSUE THREAD

**Issue by nezra** [node-red/node-red-nodes#700]
first off, running on a raspberry pi with jessie. getty and ama0 are disabled.

Arduino UNO is connected via USB.

Both are connected at 57600,8N1.

Arduino is set to repeatedly transmit a string ever 700 ms "id=1,value=4000,unit=9fe600001214". This is all it does. there are no other includes or libraries used.

cat /dev/ttyUSB0 returns the string correctly. As does the serial monitor when the arduino is connected to the PC.

the flow is literally serialport->debug

Serialport returns all kinds of things instead. sometimes it truncates the middle of the string, some times it doubles the string. I get things like this out of debug from msg.payload:

id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4it=9fe600001214
unitid=1,value=4000,unit=9fe60014
id=1,value=40id-unit=9fe600001214id=e=40id-unit=9fe6
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214

the garbled text isn't always broken in the same place, it's alllll over the place.

cat /dev/ttyUSB0 returns:

id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214
id=1,value=4000,unit=9fe600001214

Not sure why the node is returning all kinds of messed up information though debug, while everything, including python, returns it correctly. I'm not competent enough to get the data via python and pipe it into node red, as I was opting for a cleaner solution.

Is node-red's serialport simply unreliable for string based communication?

I've updated both serialport and node-red-node-serialport twice, and it still does the same thing. after a few tries, it fragments the crap out of the string it gets and winds up with garbage. 

I can build in a function to try and cope with the mess, but is there another way to get this fixed, or a node I should be using instead to get around the broken node?

**Comment by dceejay** [comment]
the serialport and the underlying library has been updated many times since 2016 - including adding adding other parsing actions like wait for character etc... Closing this as no longer relevant.

**Comment by sajad8267** [comment]
Hello,
I want to set the parameters of an industrial drive using a node through RS485 serial communication.
In this project, I need to use the hex codes of an industrial drive and control the drive using the hex codes.
Can you help me with this project with node-red-node-serial port?
I have already done this using macros in DOPSoft software, but now I want to do this using node red.
please guide me.
Regards.
Sajjad

**Comment by hardillb** [comment]
@sajad8267 Please do not use issue to ask questions, Please post to the Node-RED discourse forum or ask on the Node-RED slack
