### ISSUE TITLE
node-red-node-email: stops flowif no new mail detected

### ISSUE THREAD

**Issue by Diddlik** [node-red/node-red-nodes#702]
The problem occurs when you have no new mails, the node does not deliver anything and the flow stops. 

- [ ] Node-RED version: 1.1.3
- [ ] node.js version: 
- [ ] npm version:
- [ ] Platform/OS: Docker
- [ ] Browser: Firefox

**Comment by hardillb** [comment]
Yes, this node delivers new email, it is working as intended

**Comment by Diddlik** [comment]
> 
> 
> Yes, this node delivers new email, it is working as intended

I have a trigger, which start email cheking every 15 Minutes, if there a no new mail hte flow is stopped on this node. Is it possible to get a state that I have no new mails?

**Comment by dceejay** [comment]
Use a status node - it will report the number of mails fetched in `msg.status.results`
