### ISSUE TITLE
Can i use priority in email?

### ISSUE THREAD

**Issue by RogierQ** [node-red/node-red-nodes#706]
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment]
As stated in the template (which you have not completed) questions should be asked on the Forum or in the Node-RED Slack instance.

**Comment by dceejay** [comment]
currently no.

**Comment by RogierQ** [comment]
Clear. Thanks. 
Any future planning on it?

**Comment by dceejay** [comment]
No-one has ever mentioned it until now. So no plans as yet. No reason why not.

**Comment by RogierQ** [comment]
Ok i would like to use it for monitoring. Daily message is just the status and if there is an error or problem i would like to give it priority   
Would be nice if possible. Thanks and have a nice day!
Rogier

**Comment by dceejay** [comment]
pushed version 1.0.2 that accepts msg.prority

**Comment by RogierQ** [comment]
Wow amazing!
How nice thanks a lot!
