### ISSUE TITLE
mongodb- correction to handling of aggregate cursor

### ISSUE THREAD

**Issue by ibmrcruicks** [node-red/node-red-nodes#714]
Discourse thread -- https://discourse.nodered.org/t/problem-with-mongodb-aggregate-function/35601/9

### Which node are you reporting an issue on?
mongodb
### What are the steps to reproduce?
select aggregate pipeline results
### What happens?
receive find results
### What do you expect to happen?
receive aggregate results
### Please tell us about your environment:

- [ 1.2.3] Node-RED version:
- [10.13 ] node.js version:
- [6.10 ] npm version:
- [ mac ] Platform/OS:
- [chrome ] Browser:

**Comment by dceejay** [comment]
Closed by #715
