### ISSUE TITLE
Node Red container with machine-learing-v2 node

### ISSUE THREAD

**Issue by s19k15** [node-red/node-red-nodes#716]
I have created a container from Node-Red.
There are several images of Node-Red with or without modules, like python.

docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered nodered/node-red:latest

Some nodes like machine-learing-v2 node require **pandas** and **sklearn** modules.
Unfortunately, these modules are not contained in Node-Red image and I am looking for a way to install them inside the container.

I already had opened questions:

on Node-Red
https://discourse.nodered.org/t/node-red-container-and-machine-learning-node/35701/12

on Stackoverflow
https://stackoverflow.com/questions/64782894/docker-images-and-modules

**Comment by hardillb** [comment]
This really isn't a question about node-red or any of the nodes held in this repository, it's about his you build custom docker containers.

As such this really isn't the right place for this.

I'll try and find some time to look at the discourse question later.
