### ISSUE TITLE
Allow usage of the MCP3008 node when not running on a Pi?

### ISSUE THREAD

**Issue by BenWoodford** [node-red/node-red-nodes#718]
Useful not only for debugging other people's flows, but also when developing before rolling out to a Pi. The GPIO module does this happily, but MCP3008 throws an exception (below) when not running on a Pi

https://github.com/node-red/node-red-nodes/blob/75df218a23621b82bf389191b109c00473146b38/hardware/mcp3008/pimcp3008.js#L8

**Comment by dceejay** [comment]
Pushed fix as version 0.3.0.
