### ISSUE TITLE
node-red-node-pi-neopixel

### ISSUE THREAD

**Issue by p0tt3rpeti** [node-red/node-red-nodes#719]
Hello everyone!

My question is, is it possible to add an input field to set the gpio port number to be used by the node?
Because i want to control more than one ws2812 led strip. I know that I can modify neopix.py file's 
`LED_PIN        = 18      # GPIO pin connected to the pixels (must support PWM!).` line. But in this way still only one GPIO port is used...
Thank you in advance!
Regards
Peter

**Comment by dceejay** [comment]
Potentially yes - but as per that comment - which other pins support hardware PWM ? I think they have to because of the tight timing requirements ? Have you tested it with other pins ? Which ones work OK ? - Is this true for all Pi or just latest fastest ones etc ?

**Comment by p0tt3rpeti** [comment]
Wow you replied so fast! Thank you!
ok so. I just tested it, on a Raspberry Pi 2 Model B.
There are two PWM channels for the raspberry pi. For channel 0 GPIO 18; GPIO 12. For channel 1 GPIO13; GPIO19
I've modified the python script. It works. Tested all four pins. For channel 1 you also have to modify the LED_CHANNEL line from 0 to 1.
`LED_COUNT      = 8      # Number of LED pixels.`
`LED_PIN        = 13      # GPIO pin connected to the pixels (must support PWM!).`
`LED_FREQ_HZ    = 800000  # LED signal frequency in hertz (usually 800khz)`
`LED_DMA        = 10      # DMA channel to use for generating signal (try 10)`
`LED_BRIGHTNESS = 255     # Set to 0 for darkest and 255 for brightest`
`LED_INVERT     = False   # True to invert the signal (when using NPN transistor level shift)
`LED_CHANNEL    = 1       # PWM channel`
I've also edited neopixel.html
now it looks like this:
![kép](https://user-images.githubusercontent.com/72990368/101480857-89fc9500-3954-11eb-82e2-fc54171b30dc.png)
This is as far as a can go, since I am an electrician/HVAC professional...
Java and python scripts are not in my knowledge. 
Thank you for your help!
regards 
Peter


PS
I have a raspberry pi 4 Model B later I can try that one aswell...

**Comment by dceejay** [comment]
Hi,
so the channel and pins are linked ? If so then we need to ui to reflect that - first choose channel, then that should let you choose the two pins that channel can use. So the user can't make a mistake. Obviously the defaults need to be 0 and 18.
But yes - more than happy to look at  Pull request to do that.

**Comment by dceejay** [comment]
Reading docs like [this](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=105044)  makes me think that there are only three real pins available to use ? 18 and 32 (on channel 0) and 35 (on channel 1)

Can you confirm ?

**Comment by p0tt3rpeti** [comment]
Ok so I've done some experiments. Physical pins 12;32;33;35 are capable of hardware PWM. You can use each of them separately for driving ws2812 LEDs. If I started two scripts (simultaneously) that controls pins on the same channel things gone mad, but if I started a script that drove different channels (1 and 2) it worked. So my conclusion is that you can drive more than one ws2812 strip with one raspberry pi. But they have to use different PWM channels.

**Comment by dceejay** [comment]
Ok have pushed version 0.1.0 that supports those 4 pins.

**Comment by p0tt3rpeti** [comment]
Nice!! I'll tinker with it tomorrow and I'll share my experiences!

**Comment by p0tt3rpeti** [comment]
Hey deecjay!
First of all happy new year to you! During the Christmas craziness I didn't have time try out your new version. Yesterday I had some. It works perfectly! I can control 2 strips of LEDs with one raspberry pi! Thank you for all of your help and work! It was pretty exciting for me to work on a project like this!
Thank you again!
