### ISSUE TITLE
"node-red-node-feedparser" works only the first time, after that "Error: read ECONNRESET"

### ISSUE THREAD

**Issue by Staubgeborener** [node-red/node-red-nodes#720]
### Which node are you reporting an issue on?
node-red-node-feedparser

### What are the steps to reproduce?
```cml
[
    {
        "id": "aff3f9f4.7ca868",
        "type": "feedparse",
        "z": "6ef372b0.d92a24",
        "name": "feedparser",
        "url": "https://website.com/rss.xml",
        "interval": "1",
        "x": 590,
        "y": 300,
        "wires": [
            [
                "984b9e8f.a52238"
            ]
        ]
    },
    {
        "id": "e7433a6b.2f6b4",
        "type": "debug",
        "z": "6ef372b0.d92a24",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 990,
        "y": 300,
        "wires": []
    },
    {
        "id": "984b9e8f.a52238",
        "type": "function",
        "z": "6ef372b0.d92a24",
        "name": "",
        "func": "if (msg.payload.includes(\"WHATEVER\"))\n{\n   msg.payload = \"it works!\";\n   return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 800,
        "y": 300,
        "wires": [
            [
                "e7433a6b.2f6b4"
            ]
        ]
    }
]
```

### What happens?
After deploying, this node only works once: thats exactly after Deploying. `node-red-node-feedparser` sniffs the rss feed `https://www.website.com/rss.xml` and if this contains the word "WHATEVER" i'll get an output "it works!" in my debug node. But after 1 minute (`interval`) i'll get everytime 
> "Error: read ECONNRESET"

### What do you expect to happen?
I want to get every minute a "it works!" message in the debugger. I simply can't find the issue here, because nothing changed?

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.1
- [ ] node.js version: 14.15.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Arch Linux, rolling
- [ ] Browser: Firefox 83.0

**Comment by hardillb** [comment]
A ECONNRESET error message normally means that the server reset/closed the connection.

I would guess that what ever server you are connecting to has implemented some sort of rate limiting and for are making requests too quickly

**Comment by Staubgeborener** [comment]
@hardillb that would be weird, cause i'll get a response everytime i press "deploy". But i will try this out with a bigger intervall and will post the result.

**Comment by Staubgeborener** [comment]
Can't confirm it yet. Always get the A ECONNRESET error message. I did this now with the `http request` node. But sure, the server could be the problem. I close this issue now.
