### ISSUE TITLE
node-red-node-discovery broken in 1.2.6 on RPi

### ISSUE THREAD

**Issue by parasaurolophus** [node-red/node-red-nodes#722]
### Which node are you reporting an issue on?

node-red-node-discovery

### What are the steps to reproduce?

- Attempt to install from palette manager
- Attempt to use when installed using npm

Note: to install manually it is necessary to stop the node-red service. `npm install` fails with an error related to node-gyp otherwise.

### What happens?

Installation fails when node-red is running, so the palette manager cannot be used. Manual installation with node-red running produces this:

```
$ npm install node-red-node-discovery

> mdns@2.7.2 install /home/kirk/.node-red/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/kirk/.node-red/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:177: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/kirk/.node-red/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kirk/.node-red/node_modules/mdns
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kirk/.npm/_logs/2020-12-09T15_58_47_963Z-debug.log
```

The referenced log is attached:

[2020-12-09T15_58_47_963Z-debug.log](https://github.com/node-red/node-red-nodes/files/5667111/2020-12-09T15_58_47_963Z-debug.log)

Stopping node-red allows `npm install` from a local clone of the latest master branch to complete.

```
$ npm install ~/node-red-nodes/io/mdns/
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-node-discovery@0.0.22
added 1 package from 1 contributor and audited 248 packages in 7.291s

12 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

However, the installed nodes cause runtime errors. In particular, clicking "Done" after setting the "Service" property of a _discovery_ node results in:

```
Error: Cannot find module '../build/Release/dns_sd_bindings'Require stack:- /home/kirk/node-red-nodes/io/mdns/node_modules/mdns/lib/dns_sd.js- /home/kirk/node-red-nodes/io/mdns/node_modules/mdns/lib/mdns.js- /home/kirk/node-red-nodes/io/mdns/mdns.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js- /usr/lib/node_modules/node-red/lib/red.js- /usr/lib/node_modules/node-red/red.js
```

### What do you expect to happen?

- To be able to install node-red-node-discovery normally
- To be able to use the discovery node without runtime errors

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.6
- [ ] node.js version: 14.15.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Raspberry Pi OS (Debian 10.6, kernel 5.4.79-v7+)
- [ ] Browser: Chrome 87.0.4280.66 (Official Build) (64-bit)

**Comment by knolleary** [comment]
This module has some prerequisites that have to be installed first. Details in the readme: https://flows.nodered.org/node/node-red-node-discovery#prerequisites

**Comment by parasaurolophus** [comment]
I get the described error with those prerequisites installed:

```
$ sudo apt-get install libavahi-compat-libdnssd-dev libudev-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-compat-libdnssd-dev is already the newest version (0.7-4+b1).
libudev-dev is already the newest version (241-7~deb10u4+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by hardillb** [comment]
Just to be clear, you will need to reinstall the node after installing the pre-reqs because as part of the install a native component it built.

If you still have the problem please include the errors shown when you run `npm install` so we can see why it's failing to build

**Comment by parasaurolophus** [comment]
Yes, I get the error after re-installing. I tried bumping the mdns module dependency to the latest version in my local clone and everyting re-installs successfully but I still get the same runtime error whenever node-red is restarted.

**Comment by hardillb** [comment]
The npm build error is because it's looking for `dns_sd.h` which should be in `/usr/include/avahi-compat-libdns_sd/` and is supplied by `libavahi-compat-libdnssd-dev` package.

I've checked on an up to date 64bit Raspberry Pi OS build and it's installing and building just fine with the pre-reqs installed.

Can you check if  `/usr/include/avahi-compat-libdns_sd/dns_sd.h` is present on your machine

**Comment by parasaurolophus** [comment]
It is

```
$ ls /usr/include/avahi-compat-libdns_sd/dns_sd.h
/usr/include/avahi-compat-libdns_sd/dns_sd.h
```

**Comment by hardillb** [comment]
Can you try running `npm rebuild` in `/home/kirk/.node-red` and restart node-red afterwards

If that doesn't work try and make sure there is no remnant of the old install left over. To do this delete the `/home/kirk/.node-red/node-modules/node-red-node-discovery` directory and remove the `node-red-node-discovery` line from the `/home/kirk/.node-red/package.json`'s dependency section.

Then do a clean install.

**Comment by parasaurolophus** [comment]
`npm rebuild` appeared to be what was required. Sorry for the false alarm but I truly believed I had cleaned everything out. (I tend to resist `npm rebuild` because of how long it takes my poor old pi3 to recompile openzwave, the serial interface stuff etc. -- and now, mdns. Sigh.)

**Comment by dceejay** [comment]
you can just say `npm rebuild {packagename}`   (in this case mdns) to save time
