### ISSUE TITLE
Need to update pi-gpiod.html help

### ISSUE THREAD

**Issue by aiot-maker** [node-red/node-red-nodes#729]
### Which node are you reporting an issue on?

pigpiod-in
pigpio-out

### What are the steps to reproduce?

Drag a node to the canvas and check the node help text

### What happens?

The link to pigpio web site is outdated. 

### What do you expect to happen?

Need to change as below (lines 174 and 420):

From: href="http://abyz.co.uk/rpi/pigpio/pigpiod.html"
To: href= "http://abyz.me.uk/rpi/pigpio/pigpiod.html

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment]
Can you submit a pull request with the change please?

**Comment by aiot-maker** [comment]
Sure, pull request submitted. Thank you hardillb.

**Comment by hardillb** [comment]
We'll close this when the pull request gets merged
