### ISSUE TITLE
node-red-node-xmpp Multiple Server Sessions and huge error log

### ISSUE THREAD

**Issue by wewondr** [node-red/node-red-nodes#736]
### What are the steps to reproduce?
I'm using node-red-node-xmpp, having one config-node and two xmpp-out nodes. Enviroment: iobroker + node-red.

### What happens?
I'm using node-red-node-xmpp succesfully. Sending and receiving work.
The administrator of my xmpp server reported to me that NodeRed created multiple sessions (25+) sessions with the server within a few seconds. My local error log is also "well filled" after restarting the xmpp server.
 
### Error log
[node-red.log](https://github.com/node-red/node-red-nodes/files/5837375/node-red.log)

### Enviroment
- [ ] Node-RED version: v1.2.7
- [ ] node.js version: v12.20.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Raspbian GNU/Linux 10 (buster)
- [ ] Browser: Firefox 84.0.2
- [ ] XMPP-Server is running Prosody 0.11.7 / Compliance status 100%

**Comment by dceejay** [comment]
We have recently updated the xmpp client nodes to fix a presence/connection issue - can you retry with latest ? Thanks

**Comment by wewondr** [comment]
Seems to be solved. Logs are inconspicuous and there are only a few server connections. Thank you.
