### ISSUE TITLE
node-red-node-pi-gpio | PWM Select frequency and precision

### ISSUE THREAD

**Issue by navivfr** [node-red/node-red-nodes#745]
2 points :

**PWM @100 is not 100% DUTY**
- if I set the msg.payload to 100. In the oscilloscope I dont get a 'flat' output. More like a 99% duty.

**FREQUENCY SELECTION : How to ?**
- Frequency seem to be set a 800Hz. There is a way to change it (ie 2Khz)

_REM : on python I can set frequency (I tested 42Khz without any issue), and the Duty precision is crazy (Nice Dirac peak)
From 0 to 1.000.000 (100% duty)_

- [ ] Node-RED version:  1.2.7
- [ ] node.js version: 12.18.2
- [ ] npm version: 6.14.18
- [ ] Platform/OS: PI 4 4gb/ Ubuntu 20.10
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
Not sure what the "ask" is here ? Is there something to fix ? 

we set it up using `p = GPIO.PWM(pin, freq)`
and change the dutycycle using `p.ChangeDutyCycle(float(data))` where data is 0 to 100... 
As these are the underlying python GPIO library not sure how why 100 !== 100 etc...

**Comment by navivfr** [comment]
Ohhh my mistake... is was speaking about node-red-node-pi-gpio**d**
I used this one, but since is NOT GPIO hardware, the PWM is software and not so "clean and precise" for my need... I re push in the correct module...

Sorrryyyy

**Comment by navivfr** [comment]
dear admin can you delete this thread ?

**Comment by knolleary** [comment]
I can close this issue (in the same way you could) - but I see you've opened *another* issue for the same thing #746 

If you identified the wrong node, you can edit the title/description of this issue - you don't need to keep opening new issues.

**Comment by navivfr** [comment]
please delete this one since the awnser concern the other GPIO module, with is different and can be confusing.
