### ISSUE TITLE
[node-red-node-daemon] Command arguments with spaces are not working.

### ISSUE THREAD

**Issue by tkanjar** [node-red/node-red-nodes#754]
### Which node are you reporting an issue on?
node-red-node-daemon

### What are the steps to reproduce?

Node settings:
  Command: `****\TestApp.exe`
  Arguments: `"AAA BBB CCC"`

TestApp.cpp:

```c++
#include <iostream>

int main(int argc, char* argv[])
{
    for (int i = 0; i < argc; i++) {
        std::cout << argv[i] << std::endl;
    }
}
```

### What happens?
Output strings are separated.
`"AAA`
`BBB`
`CCC"`

### What do you expect to happen?
`AAA BBB CCC`

### Please tell us about your environment:

- [ ] Node-RED version: V1.2.2
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: Windows 10
- [ ] Browser:

**Comment by dceejay** [comment]
fixed as version 0.1.3

**Comment by tkanjar** [comment]
Thank you fixing.

I expect the output excluding double quotations:
`AAA BBB CCC`
But now the output is:
`"AAA BBB CCC"`

In the command prompt, the output of
`TestApp.exe "AAA BBB CCC"`
is
`AAA BBB CCC`.
(excluding double quotations)

**Comment by dceejay** [comment]
The quotes are only there in the debug window to show you it is a string.

**Comment by tkanjar** [comment]
> The quotes are only there in the debug window to show you it is a string.

I tested to output command arguments to file.

TestApp.cpp:
```c++
#include <iostream>
#include <string>
#include <fstream>

int main(int argc, char* argv[])
{
    std::ofstream ofs("C:\\Users\\****\\output.txt");
    for (int i = 0; i < argc; i++) {
        std::string s(argv[i]);
        std::cout << s << std::endl;
        ofs << s << std::endl;
    }
}
```

The output file is:
C:\Users\kanja\source\repos\TestApp\Debug\TestApp.exe
"AAA BBB CCC"

It seems including quotation marks.
