### ISSUE TITLE
Tail node splits message after each character instead of each line

### ISSUE THREAD

**Issue by JsBergbau** [node-red/node-red-nodes#759]
### Which node are you reporting an issue on?
Tail Node
![grafik](https://user-images.githubusercontent.com/37013344/108975710-13378400-7687-11eb-879d-6574b4a2b011.png)

### What are the steps to reproduce?
Add a tailnode and let it watch a file like `/var/log/syslog`

### What happens?
each character gets a message by its own

### What do you expect to happen?
one message per line in the file

This issue was already disscussed here https://github.com/node-red/node-red-nodes/issues/555
As far as I understand this was fixed, but somehow problem seems to be back.

Wrong Regex for splitting
![grafik](https://user-images.githubusercontent.com/37013344/108976005-627db480-7687-11eb-991c-d8a6b2c61534.png)

Regex working for splitting as from other issue:
![grafik](https://user-images.githubusercontent.com/37013344/108976253-9b1d8e00-7687-11eb-8fd4-9affc5d04ba0.png)

### Please tell us about your environment:

- [x] Node-RED version: 1.2.9
- [x] node.js version: 12.20.2
- [x] npm version: 6.14.11
- [x] Platform/OS: Linux ARM Raspberry PI
- [x] Browser: Firefox

**Comment by dceejay** [comment]
On a clean install here the regex is `[\r]{0,1}\n` so seems to be correct.
Is this an old flow you had previously as we won't update existing installs

**Comment by JsBergbau** [comment]
Thanks for the fast reply.

I've installed Node-RED a few days ago. 
Then I've imported the flows of an older installation. But the Tailnode shown above I've just added to the flow. I had no tail node before in the flow(s).

**Comment by JsBergbau** [comment]
Don't know how this could happen but indeed there was a very old version of tail node installed. All other nodes were/are up to date. 
Installed new version and now it works.
