### ISSUE TITLE
MQTT-Node: Messages are lost on connection problems, despite QOS-Level 1

### ISSUE THREAD

**Issue by JsBergbau** [node-red/node-red-nodes#760]
### Which node are you reporting an issue on?
MQTT-Node

![grafik](https://user-images.githubusercontent.com/37013344/109066238-136a6a80-76ed-11eb-8237-3e579157f7c8.png)

### What are the steps to reproduce?
You need an MQTT Broker on another machine. Please adapt IPs to your setup.
Create this flow with QOS 1 set
![grafik](https://user-images.githubusercontent.com/37013344/109066300-2a10c180-76ed-11eb-82ad-18fcd68ed47e.png)
```
[{"id":"f1b85ea2.84c608","type":"mqtt out","z":"e82c1d84.6da8","name":"","topic":"/testtopic","qos":"1","retain":"","broker":"e30d744f.9a1ae","x":800,"y":320,"wires":[]},{"id":"13f29a84.bf60a5","type":"inject","z":"e82c1d84.6da8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"before IP-Tables DROP","payloadType":"str","x":480,"y":320,"wires":[["f1b85ea2.84c608"]]},{"id":"f3219f21.2f62e","type":"inject","z":"e82c1d84.6da8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"while connection lost","payloadType":"str","x":480,"y":400,"wires":[["f1b85ea2.84c608"]]},{"id":"352b718.1bd928e","type":"inject","z":"e82c1d84.6da8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"while connecting","payloadType":"str","x":470,"y":440,"wires":[["f1b85ea2.84c608"]]},{"id":"30723580.c7ec0a","type":"inject","z":"e82c1d84.6da8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"after re-establish","payloadType":"str","x":510,"y":480,"wires":[["f1b85ea2.84c608"]]},{"id":"d187c4df.6dca7","type":"inject","z":"e82c1d84.6da8","name":"set to DROP but still showing connected","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"set to DROP but still showing connected","payloadType":"str","x":440,"y":360,"wires":[["f1b85ea2.84c608"]]},{"id":"e30d744f.9a1ae","type":"mqtt-broker","name":"192.168.178.79","broker":"192.168.178.79","port":"1883","clientid":"","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]
```

Please connect an MQTT-Client to your MQTT broker like `mosquitto_sub -h 192.168.178.79 -u <username> -P <Password> -t /testtopic -q 1`

Now click action button on before IP-Tables DROP
then execute on NodeRED host
`sudo iptables -A OUTPUT -d 192.168.178.79/32 -j DROP`

Immediatley after that click twice action button on ` set to DROP but still showing connected`

Then wait until MQTT node shows "connection lost" and then click twice action button on ' while connection lost' 

Wait again until MQTT node show "connecting" and then click twice action button on ' while connecting' 

Wait about 3 minutes, now make MQTT broker available again via `sudo iptables -D OUTPUT -d 192.168.178.79/32 -j DROP`

Now wait until MQTT node is connected again, then click `after re-establish`

### What happens?

Mosquitto_sub will show
![grafik](https://user-images.githubusercontent.com/37013344/109067961-85dc4a00-76ef-11eb-9787-a85bfad9dfa1.png)

So all messages are lost as soon as MQTT node realized, that connection is lost. 

However `set to DROP but still showing connected` is displayed twice despite at that time there was no connection to the MQTT broker available. So there is some kind cache.

Also there is no error which you could catch and react to when message is not send via MQTT.

### What do you expect to happen?

Since QOS-Level is set to 1 I expect that all messages are sent as soon as connection is re-established. At least a catchable error has to be thrown when message is not send via MQTT, but preferably there is a huge cache that sends all in the meantime received messages as soon as connection is established.

### Please tell us about your environment:

- [x] Node-RED version: 1.2.9
- [x] node.js version: 12.20.0
- [x] npm version: 6.14.8
- [x] Platform/OS: Linux arm / Raspberry PI
- [x] Browser: Firefox

**Comment by knolleary** [comment]
Hi - you've already raised this issue here: https://github.com/node-red/node-red/issues/2864

As the MQTT nodes are part of the core, this issue is not needed.

**Comment by JsBergbau** [comment]
Yes. Since it is a node, I thought it fits better here.
