### ISSUE TITLE
node-red-node-serialport  throw uncaught errors

### ISSUE THREAD

**Issue by msillano** [node-red/node-red-nodes#767]
messages:
````
 8/3/2021, 18:17:13
   msg : string[37]
             "serial port COM19 closed unexpectedly"
8/3/2021, 18:17:28
    msg : string[61]
             "serial port COM19 error: Error: Opening COM19: File not found"
````
Also if a 'catch node' is in the flow, to catch the error.

Vinodsr, for the node ["node-red-contrib-tuya-smart-device"](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/blob/master/CHANGELOG.md) founds a good solution:

> Added support for catch node. If there a catch node in the flow, the 'tuya smart device' node will not throw any error to the debug window.

The same solution for the serial port would be much appreciated. 

Best regards,
m.s.

**Comment by dceejay** [comment]
Normally thrown errors include the incoming msg as the second parameter (which is what then makes them catchable) - quite a few of these errors have no incoming msg so not sure what can be attached.

**Comment by dceejay** [comment]
have added some self generated msg.error objects so maybe this will help.
pushed as v 0.12.0

**Comment by msillano** [comment]
thanks... I will try it soon.
