### ISSUE TITLE
[node-red-node-daemon] Command argument including quotation marks

### ISSUE THREAD

**Issue by tkanjar** [node-red/node-red-nodes#768]
If the command argument includes double quotation marks, the process received command arguments with double quotation marks.
It expects without double quotation marks.

--

> The quotes are only there in the debug window to show you it is a string.

I tested to output command arguments to file.

TestApp.cpp:
```c++
#include <iostream>
#include <string>
#include <fstream>

int main(int argc, char* argv[])
{
    std::ofstream ofs("C:\\Users\\****\\output.txt");
    for (int i = 0; i < argc; i++) {
        std::string s(argv[i]);
        std::cout << s << std::endl;
        ofs << s << std::endl;
    }
}
```

The output file is:
```
C:\****\TestApp.exe
"AAA BBB CCC"
```
It seems including quotation marks.

_Originally posted by @tkanjar in https://github.com/node-red/node-red-nodes/issues/754#issuecomment-775578558_

**Comment by dceejay** [comment]
err - because the input was "AAA BBB CCC" - that is indeed the parameter you passed in.
If you pass in AAA BBB CCC that is three separate parameters - the only way I know to make them into one is to wrap them in quotes.

**Comment by hardillb** [comment]
The problem is that if you were to run it on the command line, the shell would strip the quotes and bundle the 3 parts as one argument.

**Comment by dceejay** [comment]
version 0.2.0 naw accepts parameter as a proper array with [ ], so `["aaa bbb ccc"]` should now work..
