### ISSUE TITLE
node-red-node-mysql@0.1.2 seems to break named parameters

### ISSUE THREAD

**Issue by emes** [node-red/node-red-nodes#770]
### Which node are you reporting an issue on?
node-red-node-mysql

### What are the steps to reproduce?
the named parameter sample from https://flows.nodered.org/node/node-red-node-mysql (and mine) fails with node-red-node-mysql@0.1.2 but worked before.  

### What happens?

```Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':userToChange, :newUsername) ON DUPLICATE KEY UPDATE `username`=:newUsername' at line 1```

and with mine...

```Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':topic, :uuid) ON DUPLICATE KEY UPDATE uuid = :uuid' at line 1```

### What do you expect to happen?

Downgrading with npm install node-red-node-mysql@0.1.1 fixes.

### Please tell us about your environment:

- [x] Node-RED version: 1.2.9, 1.3.0-beta.1
- [x] node.js version: v10.23.2, v12.21.0
- [x] npm version: 6.14.10, 6.14.11
- [x] Platform/OS: Pi OS, Docker/Ubuntu
- [x] Database: MySQL version: 5.5.5-10.5.9-MariaDB-1:10.5.9+maria~focal

**Comment by dceejay** [comment]
sorry about that regression - refixed in v0.1.3
