### ISSUE TITLE
Delay node limit topics

### ISSUE THREAD

**Issue by slopsjon** [node-red/node-red-nodes#790]
Node-red v1.2.9

If I use a delay node in rate limit mode for all messages it will send the first message straight away and then the next messages after the delay.

`[{"id":"bd97c8ed.a5c8d8","type":"delay","z":"e003c02f.a6c068","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"minute","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":610,"y":280,"wires":[["bd66f03e.bdf0c"]]}]`

It I set the delay node to rate limit topics it only sends the first message after the delay period and not straight away as in the all messages setting. Is this working correctly, I was expecting it to send the first message immediately.

`[{"id":"1fccc223.7ba87e","type":"inject","z":"e003c02f.a6c068","name":"Inject Array","props":[{"p":"payload"},{"p":"topic","v":"[0,1,2,3,4,5,6,7,8,9]","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[0,1,2,3,4,5,6,7,8,9]","payloadType":"json","x":330,"y":280,"wires":[["b2837466.e02a38"]]}]`

**Comment by knolleary** [comment]
Yes, that is working as implemented.

In rate limit mode it spreads messages across the configured interval.
