### ISSUE TITLE
node-red-node-wemo uncaught exception on EHOSTUNREACH

### ISSUE THREAD

**Issue by Achronite** [node-red/node-red-nodes#791]
### Which node are you reporting an issue on?
node-red-node-wemo v0.2.0

### What are the steps to reproduce?
Switch off the mains power to a wemo switch, and try to use the wemo-lookup node to query the status of the device.

### What happens?
Node-red crashes with:
2 Apr 19:06:08 - [red] Uncaught Exception:
2 Apr 19:06:08 - Error: connect EHOSTUNREACH 192.168.86.22:49153
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

### What do you expect to happen?
Device should respond with output msg to say it is unreachable, node-red should not crash.

### Please tell us about your environment:

- [ ] Node-RED version: v1.2.5
- [ ] node.js version: v10.19.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: rPi raspbian
- [ ] Browser: firefox

**Comment by hardillb** [comment]
There is a possible fix on my fork. I can't test it at the moment as I'm away from my WeMo Hardware for the weekend. If you want to give it a test and let me know:

https://github.com/hardillb/node-red-nodes

**Comment by Achronite** [comment]
I'm having difficulty installing locally in ~/node-red directory. I keep getting write access permissions problems despite chmod'ing the node-modules directory. 
`pi@pi3:~/.node-red $  npm install ~/development/node-red-nodes/hardware/wemo`

npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/assert-plus
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/aws-sign2
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/caseless
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/form-data
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/node-uuid
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/oauth-sign
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/process-nextick-args
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/punycode
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/qs
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/string_decoder
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/tough-cookie
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/tunnel-agent
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/readable-stream
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/bl
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/http-signature
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/har-validator
npm WARN checkPermissions Missing write access to /home/pi/development/node-red-nodes/hardware/wemo/node_modules/request
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /home/pi/development/node-red-nodes/hardware/wemo/node_modules/assert-plus
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/home/pi/development/node-red-nodes/hardware/wemo/node_modules/assert-plus'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-04-04T12_07_29_621Z-debug.log
pi@pi3:~/.node-red $ ls -l /home/pi/development/node-red-nodes/hardware/wemo/
total 56
drwxr-xr-x 2 pi pi  4096 Apr  4 12:51 icons
drwxr-xr-x 2 pi pi  4096 Apr  4 12:51 lib
-rw-r--r-- 1 pi pi   627 Apr  4 12:51 LICENSE
drwxrwxrwx 2 pi pi  4096 Apr  4 13:03 node_modules
-rw-r--r-- 1 pi pi   884 Apr  4 12:51 package.json
-rw-r--r-- 1 pi pi  3910 Apr  4 12:51 README.md
-rw-r--r-- 1 pi pi 10124 Apr  4 12:51 WeMoNG.html
-rw-r--r-- 1 pi pi 18485 Apr  4 12:51 WeMoNG.js
pi@pi3:~/.node-red $ ls -l /home/pi/development/node-red-nodes/hardware/wemo/node_modules
total 0

What am I doing wrong

**Comment by hardillb** [comment]
Without access to the system to have a look at all the file permissions for the whole directory tree I can't really help here.

I would suggest deleting the `node_modules` dir in the `node-red-nodes/hardware/wemo` directory then use the `npm pack` command to create a tgz of the and then installing from the tgz file.

**Comment by Achronite** [comment]
I've managed to get it installed via the npm pack route you suggested, but it crashed as soon as I added the wemo-in back node:
```
5 Apr 09:31:36 - [info] Starting modified nodes
5 Apr 09:31:36 - [info] Started modified nodes
5 Apr 09:31:37 - [red] Uncaught Exception:
5 Apr 09:31:37 - ReferenceError: request is not defined
    at SsdpClient.<anonymous> (/home/pi/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:175:5)
    at SsdpClient.emit (events.js:198:13)
    at SsdpClient.parseResponse [as _parseResponse] (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:436:8)
    at SsdpClient.SSDP._parseMessage (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:279:10)
    at Socket.onSocketMessage (/home/pi/.node-red/node_modules/node-ssdp/lib/index.js:231:12)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
```

**Comment by hardillb** [comment]
Uncomment line 8 in the lib/wemo.js file.

I was trying to tidy something else up while fixing the original problem and missed something

**Comment by Achronite** [comment]
Yeah that would do it :). Running tests now

**Comment by Achronite** [comment]
Looks like there is still an uncaught exception:
```
5 Apr 09:41:33 - [red] Uncaught Exception:
5 Apr 09:41:33 - Error: connect EHOSTUNREACH 192.168.86.22:49153
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

**Comment by hardillb** [comment]
OK, then I'm at a loss as there doesn't look to be anywhere else to try and catch that error.
The Lookup node should be calling getSocketStatus which is here:
https://github.com/node-red/node-red-nodes/blob/master/hardware/wemo/lib/wemo.js#L382

And there is a valid `on('error',...)` callback that should catch this.

**Comment by hardillb** [comment]
Having dug a bit deeper it looks like there is no way to catch some of the errors from the `http.request` code.

I suspect the only way to fix this will be to go replace all the `http.request` calls with a different http client library (not request as that is deprecated). This will be a relatively large bit of work, especially testing it all.

**Comment by Achronite** [comment]
Does it need a `res.on('error'...`   adding?  (as opposed to the `post_request.on('error'...`

**Comment by hardillb** [comment]
You can give it a try

**Comment by hardillb** [comment]
OK, I'm testing this with the standard shipped 0.2.0 and I can't get this to fail.
I'm having to use a socket as the light switches are not available outside the US (and don't work with UK wiring)
But it prints the error to the log, but doesn't crash

**Comment by Achronite** [comment]
It is a wemo switch I am using, and I'm in the UK too.  It still consistently fails when I unplug the socket.

I believe the error is in the 'subscribe' function code that is causing it to fail. It console.logs the 'Callback URL = ... ' line just before it has the uncaught exception.  I've managed to catch the error now, by adding the following:

```
                sub_request.on('error', function() {
                    console.log("failed to subscribe to ", device.ip);
                    //need to find a way to resubsribe
                    //delete subscriptions[subs[s]];
                    //delete sub2dev[sub.sid];
                    //subscribe({dev: subs[s]});
                });
```

But what should I do about resubscribing?

**Comment by hardillb** [comment]
Errr, the wemo-lookup node doesn't use the subscribe code at all so that's not possible

**Comment by Achronite** [comment]
I'm using the wemo-in node at the moment, I maybe switched after the other node failed.

**Comment by hardillb** [comment]
That information would have been useful when you opened the issue (which explicitly states the wemo-lookup node)

**Comment by Achronite** [comment]
Sorry, I forgot that i switched node type between raising the issue and you posting the fix in my attempts to get it working.

**Comment by hardillb** [comment]
So you've not actually tested the stuff I put up with the wemo-lookup node?

The current version on my fork will not crash and throws an error you can catch with the catch node to be notified that the device is offline.

I'll add that on('error') block to the subcriptions to stop it crashing as well. But if you turn the device off you are going to loose the subscription.

**Comment by Achronite** [comment]
No it looks like I wasn't!  Really sorry about the confusion earlier, I mistakenly believed that the code was shared between the nodes.

I'm testing it now, it does now report an EHOSTUNREACH to the console.log when it fails.  Is there any chance this could be reported back as 'available: false' state similar to what was added for the insight switches?

{
  available: false,
  state: 0
}

**Comment by hardillb** [comment]
No, that's what the catch node is for

**Comment by Achronite** [comment]
I don't believe the wemo-lookup node is throwing the error back to node-red.  It appears that the code goes via the `if(done)` route in your new code so it never hits the `node.error(err,msg)`.

```
                console.log("socket");
                // classic socket: no power measurement, so only request current switch status
                wemo.getSocketStatus(dev)
                .then(function(status) {
                    msg.payload = {
                        state: status
                    };
                    send(msg);
                    if (done) {
                        done()
                    }
                })
                .catch(function(err){
                    if (done) {
console.log("****err done");
                        done(err)
                    } else {
console.log("****err not done");
                        node.error(err,msg)
                    }
```

```
socket
{ Error: connect ECONNREFUSED 192.168.86.22:49153
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.22',
  port: 49153 }
{"host":"192.168.86.22","port":"49153","path":"/upnp/control/basicevent1","method":"POST","headers":{"SOAPACTION":"\"urn:Belkin:service:basicevent:1#GetBinaryState\"","Content-Type":"text/xml; charset=\"utf-8\"","Accept":""}}
****err done

```

**Comment by Achronite** [comment]
Just realised that is ECONNREFUSED is shown above, but it does the same for EHOSTUNREACH too.

`HttpActions:reportState(): success
{ Error: connect EHOSTUNREACH 192.168.86.22:49154
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.86.22',
  port: 49154 }
{"host":"192.168.86.22","port":"49154","path":"/upnp/control/basicevent1","method":"POST","headers":{"SOAPACTION":"\"urn:Belkin:service:basicevent:1#GetBinaryState\"","Content-Type":"text/xml; charset=\"utf-8\"","Accept":""}}
****err done
`

**Comment by hardillb** [comment]
Have you added a catch node to the flow?

**Comment by Achronite** [comment]
Yes I have a catch node.  I've done some further debugging; The catch block triggers if I change the `done(err)` to `done("My error message")`

Maybe it needs a specific done function defining?

**Comment by hardillb** [comment]
version 0.2.1 published
