### ISSUE TITLE
Result of Sending Multiple Queries being an Array of Nested Objects instead of JSON arrays

### ISSUE THREAD

**Issue by shubhampatel123** [node-red/node-red-nodes#797]
### Reporting on mysql node

Version 0.1.6 (or maybe something in the recent commits related to it) broke the case of multiple separate queries in the same request..

Our example:
If the below two queries are sent:

`Variable assignment based on query result;
SELECT values FROM x WHERE <includes variable from query 1>;`

Before, this would return an array of length 2 of arrays of length 1 with each element of the nested array being an object...

payload; [ [{res}], [{r1}, {r2}, {r3}]
Now, it comes back as an array of 3 objects, with each element having the following form:

`{
payload: [
   {0: {}},
   {
     0: {r1},
     1: {r2},
     2:{r3}
   }
]}`
See images below of both cases...

This is because by line 157 of the [mysql.js](storage/mysql/68-mysql.js) file, we have made the assumption that each top-level result should be a query result row..

We've fixed our codebase to use version 0.0.18 , and we'll test others to see as well... Do you have any ideas of what we could do to fix this? It's not clear to us why this else case exists, maybe if we could get some clarification on that, we could propose another special case, or even recursively check the constructor.. but then at that point it's not clear why we wouldn't just rely on the first condition which handles that for us using JSON... Alternatively, maybe the else case should be a little more specific about what its goal is?

Old result
![v0.0.18](https://user-images.githubusercontent.com/17260106/115264324-310feb00-a104-11eb-88db-fadf863f7373.png)

New Result
![v0.1.6](https://user-images.githubusercontent.com/17260106/115264542-63214d00-a104-11eb-8226-dc994a02a2a0.png)

You can refer to the [comment](https://github.com/node-red/node-red-nodes/commit/c1c82a623e01992e2862d68e65fcc306dd9bcdd1#commitcomment-49218901) on the [commit](c1c82a623e01992e2862d68e65fcc306dd9bcdd1) by @dceejay

**Comment by dceejay** [comment]
Hi, the intention of the original "fix" was to convert the resultrow object into a standard json object to make downstream processing easier. When you say you get multiple results do you have a simple example ? Most results come back as an array or resultrows and we want to make hem into an array of normal objects.

**Comment by shubhampatel123** [comment]
An example would be something like: Let's say we have a table `tbl` in MySQL that contains an `id` as a unique primary key. And I pass in two queries for the table:
`SELECT
@min := min_id,
@max := max_id
from (SELECT min(id) as min_id, max(id) as max_id from tbl);
SELECT * from tbl where id between @min and @max limit 1000;`

There above two queries should return something like the picture you see under the `Old result`, meaning both results coming in as arrays of standard JSON objects. And the result of the second query being an array of length 1000, each item in the array representing a a standard JSON object with field:value mappings.

With v0.1.6 of the node, however, the result looks something like what you see under `New Result`, which has both results coming in as objects of nested objects. I was wondering why this new change was made since the older one seems to be much easier to parse and process...? Or would you have any idea of what we could do to fix this?

**Comment by dceejay** [comment]
Hi - I've pushed a fix that hopefully now fixes this. It looks a bit deeper at the result before converting it - so should handle the multiple return array more carefully. Hopefully this now works for you. on npm as 0.1.8.
