### ISSUE TITLE
[node-red-node-twitter] Feature mentioned in Twitter-In Node Tip box not available

### ISSUE THREAD

**Issue by hgill** [node-red/node-red-nodes#798]
### Which node are you reporting an issue on?
node-red-node-twitter: Twitter In node

### What are the steps to reproduce?
I have set up the node to emit streaming messages - this works fine, however, the handles to track have to be hardcoded.
The description (image) mentions 
"Leave *for* blank to set using message.payload"

However, this node doesn't have an input connector. It looks like this feature doesn't exist or is not enabled.

![image](https://user-images.githubusercontent.com/18014590/115377254-0fd6f980-a1ed-11eb-8f14-cfcde6053b19.png)

### What happens?
Node doesn't have an expected input feature - so unclear how to programmatically pass in handles, rather than hardcode into node settings.

### What do you expect to happen?
The node should be converted to one which takes an input as well. the input could be triggered by an inject node. In such a case, this node would have to do state management in a way that there is only one such stream and not multiple streams. Believe this can be easily done using flow-level or global properties. This would also allow twitter handles to be added without restarting node-red flow.

### Please tell us about your environment: Not an environment-related issue

- [x] Node-RED version: 1.2.9
- [x] node.js version: 14.16.1
- [x] npm version: 6.14.12
- [x] Platform/OS: Windows/WSL2/Docker
- [x] Browser: Chrome

**Comment by hardillb** [comment]
If you leave the "For" filed blank and hit save the node should get a input point

**Comment by hgill** [comment]
That was very quick, thank you. 

To add a minor point, for field has to be left blank when you first set up the node. If you try changing this on existing Twitter-In node, the node won't get an input point.

**Comment by hardillb** [comment]
For needs to be empty and Search needs to be set to "Public"

https://github.com/node-red/node-red-nodes/blob/master/social/twitter/27-twitter.html#L159

**Comment by hgill** [comment]
To get this working for specific Users instead of global search, would that be a feature request?

**Comment by hardillb** [comment]
We do not use Issues for feature requests.

**Comment by hardillb** [comment]
Sorry, I should have said, you can make a suggestion for features on the [Forum](https://discourse.nodered.org/)

**Comment by knolleary** [comment]
It has been a while since I looked at the Twitter API, but I think the API as it was when this node was last updated did not make  it easy to do a search against a specific user in a way that made sense for how this node is expected to work. Because you don't really want it to be searching their old tweets, you want it to pass on *new* tweets that match the search criteria. You can easily enough achieve the same by getting all of the user's tweets and then doing the filtering yourself.

**Comment by hgill** [comment]
Noted, summarizing the feature request here - [posted in forum as well](https://discourse.nodered.org/t/node-red-node-twitter-for-tweet-in-node-the-tweets-of-specific-users-mode-msg-payload-based-input-of-for-field/44455). I could devote some time to work on it, as my use case requires it, esp if I have some guidance. Anyone willing to guide me to get this done?

*Topic:* [node-red-node-twitter] For Tweet-In node, 'The Tweets of Specific Users' mode: msg.payload based input of 'for' field
*Description:* Request for Tweet-In node to have an input point for 'Tweets of Specific Users' option as well, where twitter handles can be provided to the Tweet-In node to track for new tweets. This will allow programmatic set up of the handles to monitor. It could have a refresh logic - which I think is best implemented as an Inject node injecting msg.payload every n seconds. If the payload changes, the node would get new connection with Twitter API & then cut previous connection. Similar feature currently exists for the public tweets search mode where msg.payload may be used to set the search keyword.
