### ISSUE TITLE
SQLite installed but have been deleted chatbot (RED-BOT)

### ISSUE THREAD

**Issue by FraCata00** [node-red/node-red-nodes#800]
### What are the steps to reproduce?
Try  to install sqlite from cmd and if was already installed chat-bot, this last will be delete...

### What happens?
SQLite installed but have been deleted chatbot (RED-BOT)

### Please tell us about your environment:
So when I try to install sqlite from command-line with apposit command, node-red automatically delete me a node of chat-bot
And now for me is impossible to reinstall chat-bot from command-line and from manage palette in node-red...
Sqlite now is uninstalled and chat-bot too.
This is the link to chat-bot node installation: https://flows.nodered.org/node/node-red-contrib-chatbot

- [ ] Node-RED version:
       1.3.3
- [ ] node.js version:
       v15.6.0
- [ ] npm version:
       7.11.1
- [ ] Platform/OS:
       Windows 10 64 bit
- [ ] Browser:
       Google Chrome

**Comment by hardillb** [comment]
You are going to need to provide a lot more information here (some of which should have been included in the template).

1. What exact commands did you run where?
2. Exactly which nodes are involved? Please supply the full name of the npm packages the node come from.
3. More detail about what happened?
4. What errors are shown?

**Comment by FraCata00** [comment]
so the npm packahe is: ------->  node-red-contrib-chatbot (v0.19.7)
The node that are involved are: node-red-contrib-chatbot and node-red-node-sqlite (v0.6.0)
Now if i try to reinstall chatbot whith: ------> npm install node-red-contrib-chatbot the node not install... and there are really many errors on output from cmd...

**Comment by hardillb** [comment]
OK, so what are those errors? We need to actually see them

Also you've not actually answered question about what commands you ran and where (which directory you were in) when you ran them.

**Comment by FraCata00** [comment]
![Node-red issues](https://user-images.githubusercontent.com/78490028/116996805-437d4d80-acdc-11eb-81e6-742a7a1fc77e.png)

**Comment by FraCata00** [comment]
This is the errors that's output me

**Comment by hardillb** [comment]
Please post the actual text, not screenshots, that is really hard to read, but what I can see is just warnings not errors

**Comment by FraCata00** [comment]
So okay but in node-red the chat-bot isn't  installed...
and in the cmd is output me this:

Waitng fo missing types to be registered :
-chatbot-telegram-node

**Comment by hardillb** [comment]
Right, but without seeing ALL the output from the install command we have no idea what could be happening.

**Comment by FraCata00** [comment]
So one moment

**Comment by FraCata00** [comment]
![Immagine 2021-05-04 133011](https://user-images.githubusercontent.com/78490028/116997366-fc438c80-acdc-11eb-8a96-20c41efb9391.png)

**Comment by FraCata00** [comment]
There are only the warns in command line after installation but the chat-bot node isn't installed

**Comment by hardillb** [comment]
SHOW ME THE OUTPUT

Also you STILL haven't answered the question about EXACTLY what command you ran in WHAT directory.

**Comment by hardillb** [comment]
Also Node-RED logs problems with nodes are startup, have you checked if it has a problem with any of the nodes it found?

**Comment by FraCata00** [comment]
Oh.. so now i check the logs and I try to delete any nodes thats probably can conflict with other.
The exaclty command is -----> npm install node-red-contrib-chatbot in my user's directory.

**Comment by FraCata00** [comment]
So thanks for the availability

**Comment by dceejay** [comment]
I also note you are running node15 which we don't really support. We prefer sticking to the LTS versions 12, or 14.

**Comment by FraCata00** [comment]
So I downgrade my Node version?

**Comment by dceejay** [comment]
possibly. We do often see the dev versions tend to have "features" that seem to sometimes break nodes that require building native code (like sqlite) - but given that 16 is just out you would hope they had fixed most of them by now.

**Comment by FraCata00** [comment]
Oh.. so thanks for the advice!
Now I try...

**Comment by knolleary** [comment]
To be honest, I wouldn't spend time changing your node version. That is unlikely to be related to why a node got 'uninstalled' when you installed something else.

The questions that have not yet been answered:

1. what directory exactly did you run the npm install command in? Saying ' in my user's directory' doesn't make it clear if you mean their home directory or the `.node-red` directory.

2. How did you install the nodes originally?

3. what is in the dependencies section of the file `~/.node-red/package.jsons`.

**Comment by FraCata00** [comment]
the directory is my user's directory

**Comment by knolleary** [comment]
> the directory is my user's directory

You have just repeated the same words you used before which doesn't help.

I assume you mean your user's home directory. In which case, that is the *wrong* directory to run an install in - you should be running `npm install <name-of-node>` in the `.node-red` directory. This is the directory node-red logs when it starts up. For example, for me it is:
```
    4 May 14:36:20 - [info] User directory : /Users/nol/.node-red
```

1. have you tried reinstalling the chatbot node?
2. what about the two other questions I asked?

**Comment by FraCata00** [comment]
So I try to reinstall both node (chat-bot,sqlite) and now all works great!
Thank's for the advice that you give me! :)
