### ISSUE TITLE
node-red-node-mysql - Uncaught exception error (TypeError: v.map is not a function)

### ISSUE THREAD

**Issue by m4c1n0** [node-red/node-red-nodes#802]
Hi,

after updating node-red-node-mysql to version 0.1.8 I noticed that nodered is restarting about every minute throwing the following uncaught exception (I have found the issue #763 but I feel like this is a different issue)

```
May 05 12:09:26 stp-shs Node-RED[2242]: 5 May 12:09:26 - [red] Uncaught Exception:
May 05 12:09:26 stp-shs Node-RED[2242]: 5 May 12:09:26 - TypeError: v.map is not a function
May 05 12:09:26 stp-shs Node-RED[2242]:     at /home/hmcsusr/.node-red/node_modules/node-red-node-mysql/68-mysql.js:163:75
May 05 12:09:26 stp-shs Node-RED[2242]:     at Array.map (<anonymous>)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query.<anonymous> (/home/hmcsusr/.node-red/node_modules/node-red-node-mysql/68-mysql.js:163:64)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query.<anonymous> (/home/hmcsusr/.node-red/node_modules/mysql/lib/Connection.js:526:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query._callback (/home/hmcsusr/.node-red/node_modules/mysql/lib/Connection.js:488:16)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query.Sequence.end (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query._handleFinalResultPacket (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Query.OkPacket (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/sequences/Query.js:74:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Protocol._parsePacket (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/Protocol.js:291:23)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Parser._parsePacket (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/Parser.js:433:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Parser.write (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/Parser.js:43:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Protocol.write (/home/hmcsusr/.node-red/node_modules/mysql/lib/protocol/Protocol.js:38:16)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Socket.<anonymous> (/home/hmcsusr/.node-red/node_modules/mysql/lib/Connection.js:88:28)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Socket.<anonymous> (/home/hmcsusr/.node-red/node_modules/mysql/lib/Connection.js:526:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Socket.emit (events.js:314:20)
May 05 12:09:26 stp-shs Node-RED[2242]:     at addChunk (_stream_readable.js:297:12)
May 05 12:09:26 stp-shs Node-RED[2242]:     at readableAddChunk (_stream_readable.js:272:9)
May 05 12:09:26 stp-shs Node-RED[2242]:     at Socket.Readable.push (_stream_readable.js:213:10)
May 05 12:09:26 stp-shs Node-RED[2242]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Upon further troubleshooting I tracked the issue down to a few nodes that are calling a stored procedure from the MySQL server every minute. 
The results of the stored procedure returned by the server is a single line that looks like this:
```
# SensorID, SensorNameEN, Type, SensorTimestamp, Current, Max, Min
'7', 'Exterior', 'TEMPERATURE', '2021-05-05 12:12:50', '19.1', '21.3', '8.6'
```

The stored procedure works without issues when run via MySQL Workbench and even the nodes were working up until the update of node-red-node-mysql to version 0.1.8.

Can you please help?

- [ ] Node-RED version: 1.3.4
- [ ] node.js version: v12.22.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS: Raspberry Pi 4 (2GB)
- [ ] Browser: Firefox 88.0

**Comment by JUANPAVQ** [comment]
The problem is in the mysql node v0.1.8, if you try with 0.1.7 version it works ok. I have an stored procedure like this:`CALL `OEE_PROD` ('2020-10-01','2021-05-04',false,'none');` the query its Ok in 0.1.7 version, but 0.1.8 version has problems.

This is my test flow:
`[
    {
        "id": "2c90e6ab.f63112",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "dd745132.c4f4",
        "type": "inject",
        "z": "2c90e6ab.f63112",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 180,
        "y": 100,
        "wires": [
            [
                "b94af6f6.2ca0e8"
            ]
        ]
    },
    {
        "id": "b94af6f6.2ca0e8",
        "type": "function",
        "z": "2c90e6ab.f63112",
        "name": "",
        "func": "msg.topic=\"CALL `OEE_PROD` ('2020-10-01','2021-05-04',false,'none');\";\n//msg.topic=\"SELECT * FROM `OEE` LIMIT 20;\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 330,
        "y": 100,
        "wires": [
            [
                "55e5851.a9c9ffc",
                "1298a518.7f1a43"
            ]
        ]
    },
    {
        "id": "538cb092.52b6b8",
        "type": "debug",
        "z": "2c90e6ab.f63112",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 490,
        "y": 180,
        "wires": []
    },
    {
        "id": "55e5851.a9c9ffc",
        "type": "debug",
        "z": "2c90e6ab.f63112",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 520,
        "y": 100,
        "wires": []
    },
    {
        "id": "1298a518.7f1a43",
        "type": "mysql",
        "z": "2c90e6ab.f63112",
        "mydb": "b43e9a05.954128",
        "name": "",
        "x": 320,
        "y": 220,
        "wires": [
            [
                "538cb092.52b6b8"
            ]
        ]
    },
    {
        "id": "b43e9a05.954128",
        "type": "MySQLdatabase",
        "name": "",
        "host": "192.168.1.121",
        "port": "3306",
        "db": "IOTDimatra",
        "tz": "",
        "charset": "UTF8"
    }
]`

![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/d/4/d42f0c25f4c3c5ced7b27f426eea273d6b08e422.jpeg)
![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/3/e/3e5c2023d0c8dbde4e5af1d35c45c7f31ae1e534.jpeg)
![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/b/e/be1447273828459a697b1703004e8bf28457ffc6.jpeg)

Best regards

**Comment by dceejay** [comment]
ok - I have reverted the original "fix" that was trying to help make RowPacketData types into "normal" objects. Seems like it would be safer to leave them as-is here and then let the user convert them afterwards only if necessary. v 0.1.10.
