### ISSUE TITLE
xmpp how can i send images, voices, video?

### ISSUE THREAD

**Issue by rallep71** [node-red/node-red-nodes#808]
- a feature request or suggestion for a change,

 xmpp how can i send images, voices, video?

it would be really great if this would be implemented in the xmpp node, xmpp supports this!

with telegram it works too.

is there something planned for the future?

THX

**Comment by hardillb** [comment]
As stated in the template you edited when opening this issue, questions and feature requests are handled on the forum or the Node-RED Slack instance not issues

**Comment by dceejay** [comment]
All of those are extensions to the core xmpp protocol. So there are no plans to add them unless someone offers up a pull request.
