### ISSUE TITLE
Node-red-node-email not sending attachment when msg.to is variable

### ISSUE THREAD

**Issue by thejollypop** [node-red/node-red-nodes#810]
node-red-node-email 1.12.1
Node-RED v1.3.5
Hello, Node-RED team!

**### Expected**: Send a PDF attachment to a variable-based recipient (via `msg.to `property)
**### Actual**: Message sent to the relevant `msg.to `recipient successfully, but empty, i.e. WITHOUT attachment, unless `msg.to` is hardcoded.

![image](https://user-images.githubusercontent.com/75426675/120929858-63e16300-c6f3-11eb-9880-0c3620e657b0.png)

**_Working_: Sending PDF** (`msg.to` = constant):

`[{"id":"f6f2187d.f17ca8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b90221ac.046bc","type":"inject","z":"f6f2187d.f17ca8","name":"Inject","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":280,"wires":[["e1676931.6e2968"]]},{"id":"e1676931.6e2968","type":"http request","z":"f6f2187d.f17ca8","name":"PDF","method":"GET","ret":"bin","paytoqs":"ignore","url":"http://www.orimi.com/pdf-test.pdf","tls":"","persist":false,"proxy":"","authType":"","x":130,"y":340,"wires":[["acc4eb35.0a5328"]]},{"id":"acc4eb35.0a5328","type":"file","z":"f6f2187d.f17ca8","name":"","filename":"test.pdf","appendNewline":true,"createDir":false,"overwriteFile":"true","encoding":"none","x":140,"y":380,"wires":[["68b9aa6b.4a3544"]]},{"id":"447517b4.0e2bb8","type":"e-mail","z":"f6f2187d.f17ca8","server":"smtp.zoho.com","port":"465","secure":true,"tls":true,"name":"a@mail.io","dname":"email","x":330,"y":380,"wires":[]},{"id":"68b9aa6b.4a3544","type":"change","z":"f6f2187d.f17ca8","name":"Set up the email","rules":[{"t":"set","p":"to","pt":"msg","to":"a@mail.io","tot":"str"},{"t":"set","p":"attachments","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"filename","pt":"msg","to":"Daily Report.pdf","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"Summary Report","tot":"str"},{"t":"set","p":"description","pt":"msg","to":"Please find attached your Activity Report.","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":235,"y":380,"wires":[["447517b4.0e2bb8"]],"l":false}]`

**_Not Working_Not Sending PDF** (`msg.to` = variable):

`[{"id":"f6f2187d.f17ca8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b90221ac.046bc","type":"inject","z":"f6f2187d.f17ca8","name":"Inject","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":280,"wires":[["e1676931.6e2968"]]},{"id":"e1676931.6e2968","type":"http request","z":"f6f2187d.f17ca8","name":"PDF","method":"GET","ret":"bin","paytoqs":"ignore","url":"http://www.orimi.com/pdf-test.pdf","tls":"","persist":false,"proxy":"","authType":"","x":130,"y":340,"wires":[["acc4eb35.0a5328"]]},{"id":"acc4eb35.0a5328","type":"file","z":"f6f2187d.f17ca8","name":"","filename":"test.pdf","appendNewline":true,"createDir":false,"overwriteFile":"true","encoding":"none","x":140,"y":380,"wires":[["68b9aa6b.4a3544"]]},{"id":"447517b4.0e2bb8","type":"e-mail","z":"f6f2187d.f17ca8","server":"smtp.zoho.com","port":"465","secure":true,"tls":true,"name":"","dname":"email","x":330,"y":380,"wires":[]},{"id":"68b9aa6b.4a3544","type":"change","z":"f6f2187d.f17ca8","name":"Set up the email","rules":[{"t":"set","p":"to","pt":"msg","to":"a@mail.io","tot":"str"},{"t":"set","p":"attachments","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"filename","pt":"msg","to":"Daily Report.pdf","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"Summary Report","tot":"str"},{"t":"set","p":"description","pt":"msg","to":"Please find attached your Activity Report.","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":235,"y":380,"wires":[["447517b4.0e2bb8"]],"l":false}]`

Thanks Team!

**Comment by dceejay** [comment]
I think the issue is because the http request leaves a `msg.headers` property attached - try using the change node to `delete msg.jheaders`

**Comment by thejollypop** [comment]
That worked like a charm! thanks
