### ISSUE TITLE
node-red-node-exif got an uncaught exception 

### ISSUE THREAD

**Issue by FatMatthew** [node-red/node-red-nodes#813]
I try to get EXIF imformation of an image by node-red-node-exif.
But I got a uncaught exception below:

TypeError: Cannot set property 'arc' of undefined
    at addMsgLocationDataFromExifGPSData (/data/node_modules/node-red-node-exif/94-exif.js:65:30)
    at /data/node_modules/node-red-node-exif/94-exif.js:107:41
    at /data/node_modules/exif/lib/exif/ExifImage.js:122:7
    at ExifImage.processImage (/data/node_modules/exif/lib/exif/ExifImage.js:203:7)
    at ExifImage.loadImage (/data/node_modules/exif/lib/exif/ExifImage.js:146:10)
    at Immediate._onImmediate (/data/node_modules/exif/lib/exif/ExifImage.js:117:10)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Which node are you reporting an issue on?
node-red-node-exif
### What are the steps to reproduce?
read a jpg photo binary
### What happens?
docker container stop because uncaught exception
### What do you expect to happen?
get exif information
### Please tell us about your environment:

- [ ] Node-RED version: 1.3.5
- [ ] node.js version: v10.24.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS:  Ubuntu 18.04
- [ ] Browser: FireFox 88.0.1 (16-bit)

**Comment by dceejay** [comment]
Hi - Any chance you can share the image that is causing this to fail ?

**Comment by hardillb** [comment]
I tested my PR with this:

![PXL_20210605_152827553](https://user-images.githubusercontent.com/1800845/123758855-3e411700-d8b7-11eb-9a50-cb94a9705005.jpg)

**Comment by dceejay** [comment]
yeah - fix would work - but why wasn't it getting a location lat lon before that ?

**Comment by hardillb** [comment]
There is no lat, lon attached to that image, just the arc

**Comment by dceejay** [comment]
so is there a point in adding any location info in that instance... the idea of the location property is that you can move to a payload and just send to worldmap)

**Comment by hardillb** [comment]
OK, fair point. new update pushed to PR

**Comment by dceejay** [comment]
Yup 👍

**Comment by dceejay** [comment]
Thanks Ben

**Comment by FatMatthew** [comment]
Thank you all！I updated to thenew version and It's fixed perfectly!
