### ISSUE TITLE
E-Mail Node IN Node crashes NodeRED when using msg.criteria

### ISSUE THREAD

**Issue by mickym2** [node-red/node-red-nodes#818]
### Which node are you reporting an issue on?
E-Mail Node IN

### What are the steps to reproduce?
Set the E-Mail IN Node to when triggered and set the criteria via msg.criteria

### What happens?
NodeRed crashes immediately without any log entry

### What do you expect to happen?
E-Mail In will filter mails according msg.criteria

### Please tell us about your environment:

- [ x] Node-RED version: happens with 1.2.7 and 1.3.4
- [x ] node.js version: 14.7.1 and 14.7.2
- [ x] npm version: 6.x
- [x ] Platform/OS: Linux- Raspberry and Windows 10
- [x] Browser: Chrome & Windows

**Comment by dceejay** [comment]
any more details ? - like what did you set msg.criteria to ? Is that all you had to set ? etc

**Comment by hardillb** [comment]
And what version of the email node are you using?

**Comment by mickym2** [comment]
Thanks for the quick answer to both of you.
The email-Node version is the newest: 1.12.2

So I set the email-Node in trigger mode and used an inject node and injected a msg.criteria according the examples given in :
https://github.com/mscdex/node-imap/blob/master/README.md

So I tried an example out of this as criteria examples: 
 [ ['HEADER', 'SUBJECT', 'node-imap'] ]

But I try also the simple criteria:
 [ ['ALL'] ]
['ALL' ]
'ALL'
ALL

regardless what I tries - NodeRed crashes immediately

**Comment by mickym2** [comment]
If i use any of the predefined criteria - in the node - the email-in Node works properly. So there is no general problem with this node only when I try to select emails using msg.criteria.

This is how my Inject Node looks like:
![image](https://user-images.githubusercontent.com/58858526/125943095-34395cfc-ce7a-4f57-90dd-d4a39a5ad468.png)
 and that is all what I send into the email node:
![image](https://user-images.githubusercontent.com/58858526/125942979-a0eea18d-f031-4534-a62d-a0ab165e79f6.png)

but as i said after I inject the msg.criteria - my NodeRed crashes immediately

**Comment by mickym2** [comment]
Just updated my NodeRed on Windows to version 1.3.5 - but no difference. NodeRed crahes immediately after I inject this message to the email-in node.

**Comment by dceejay** [comment]
It should just be a simple array - not a double array like you have...
(but yes - it still shouldn't crash)

**Comment by mickym2** [comment]
I used also a simple array, but no difference  - it crashes no matter what I specify. 

On the other hand - if I look to the examples (https://github.com/mscdex/node-imap/blob/master/README.md) I guess it depends on the value if there is a nested array or not:

![image](https://user-images.githubusercontent.com/58858526/125946461-df965929-45c2-43aa-9997-c71f9602a280.png)

**Comment by dceejay** [comment]
True - if I use
![image](https://user-images.githubusercontent.com/5375409/125947053-8c68089a-79be-4194-b3f6-2063179aac54.png)

it works - but again - yes - need to fix the error handling for other cases.

**Comment by mickym2** [comment]
Great!!! - So it works fine. :) Many thanks!!!! - OK you need to fix that NodeRed crashes if wrong format is used. But at least I know how it is working. Thanks again.

**Comment by dceejay** [comment]
Fixed by https://github.com/node-red/node-red-nodes/commit/761bb30ada8bffb4c37d3ec3333289732a467515
