### ISSUE TITLE
node-red-node-discovery "invalid properties" when using msg.service instead of property

### ISSUE THREAD

**Issue by dales-at-avid** [node-red/node-red-nodes#821]
### Which node are you reporting an issue on?
node-red-node-discovery  announce

### What are the steps to reproduce?
use msg.service to set the service instead of editing the properly

### What happens?
Get an "invalid properties" triangle and message.

### What do you expect to happen?
To just use the service from the msg as documented without the warning.

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.4
- [ ] node.js version: v12.22.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS: Rpi 3.  Raspbian
- [ ] Browser: Firefox 90.0.1

**Comment by hardillb** [comment]
hmm, service is marked as required in the html file (and has been for at least the last 6 years) meaning it has never been able to be set via the input message.

**Comment by dales-at-avid** [comment]
The documentation says:

The announcement can be customised by the msg if not configured in the edit panel.

    msg.service - For a full list of official service types see this list.

And in fact it *does* work that way.  The msg.service *is* used.

**Comment by hardillb** [comment]
It should just be a case of removing `required:true,` from line [92](https://github.com/node-red/node-red-nodes/blob/c1c82a623e01992e2862d68e65fcc306dd9bcdd1/io/mdns/mdns.html#L92) in the mdns.html file.

If you want to submit a PR we can look at merging it.

**Comment by dceejay** [comment]
well the validator will still fail... it needs to test for nothing as well.

**Comment by dceejay** [comment]
Published version 0.0.23
