### ISSUE TITLE
Fails to install on Windows node-red 2.x

### ISSUE THREAD

**Issue by ozdeadmeat** [node-red/node-red-nodes#827]
### What are the steps to reproduce?
Attempt to install in node-red or from the commandline. Asks for python as a dependency?

### What happens?
Application does not install

### What do you expect to happen? 
Application installs

### Please tell us about your environment:

- [ ] Node-RED version: 2.0.3
- [ ] node.js version: v16.1.0
- [ ] npm version: 7.11.2
- [ ] Platform/OS: Windows 10 Pro
- [ ] Browser: Google Chrome

**Comment by hardillb** [comment]
You need to supply a LOT more information about how you are installing Node-RED and exactly what error message you have seen.

But Python is a dependency for `npm` to install any NodeJS nodes that require building native components for the target platform. As well as Python a set of basic build tools (e.g. make and a C/C++ compiler are also required). You will need to have these installed for it to work.

**Comment by dceejay** [comment]
As covered in the forum many times you need to install the windows build tools https://www.npmjs.com/package/windows-build-tools

**Comment by ozdeadmeat** [comment]
> You need to supply a LOT more information about how you are installing Node-RED and exactly what error message you have seen.
> 
> Also this repo is for a specific group of Node-RED nodes, not Node-RED it's self.
> 
> But Python is a dependency for `npm` to install any NodeJS nodes that require building native components for the target platform. As well as Python a set of basic build tools (e.g. make and a C/C++ compiler are also required). You will need to have these installed for it to work.

Yeah this was the link that sqlite supplied for failed installs.

**Comment by hardillb** [comment]
But you left the name of the node field in the template black so we had no ready of knowing which of the many nodes you are trying to install.

As mentioned python and the ms dev tools are requirements for all nodes with native components on Windows

**Comment by ozdeadmeat** [comment]
@dceejay FYI the build tools fail to install as well, perhaps the forum post in which you speak needs to be updated?
