### ISSUE TITLE
node-red-node-pi-mcp3008 add mcp3201

### ISSUE THREAD

**Issue by mhornsby** [node-red/node-red-nodes#845]
there's support for mcp3202 can mcp3201 be added

**Comment by hardillb** [comment]
As described in the template you deleted when opening the this issue, feature requests should be made on the Discourse forum or on Slack, not in issues.

But the node-red-node-pi-mcp3008 node depends on the [mcp-spi-adc](https://www.npmjs.com/package/mcp-spi-adc) node to access the hardware, we can only support the devices it supports and it does not appear to support the mcp3201.

**Comment by fivdi** [comment]
MCP3201 support has just been added to mcp-spi-adc and is now available with mcp-spi-adc@3.2.0.

**Comment by dceejay** [comment]
Happy if someone wants to create raise and test a PR for this.

**Comment by dceejay** [comment]
@mhornsby - OK - I have pushed a potential fix/upgrade as version 0.4.0... 

NOTE I DO NOT have a 3201 so please test and feedback here if it works... or not... Thanks

**Comment by dceejay** [comment]
Thanks
