### ISSUE TITLE
node-red-node-serialport serial request  configuration problem

### ISSUE THREAD

**Issue by yfhaotian** [node-red/node-red-nodes#850]
How to configure baud rate using msg.baudrate? I've tried many times and returned a timeout error.
![image](https://user-images.githubusercontent.com/35522145/139614016-65fa00c6-d00f-4b93-a5f6-5e829bebe004.png)

a general 'how-to' type question
Node-RED version:1.3.5
node.js version:14.17.6-x64
npm version:6.14.6
Platform/OS:Windows10

**Comment by hardillb** [comment]
Looking at the code the timeout error has nothing to do with the serial port baud rate, that error is thrown after the baud rate has been updated and the `msg.payload` has been sent to the serial port.

I would suspect that what ever device you have attached doesn't expect to receive a value of `true`so is not responding to it in less than a second (as specified in the `msg.timeout`).

**Comment by yfhaotian** [comment]
If I just want to modify the baud rate and use serial input as the data input node, what should I do?

**Comment by hardillb** [comment]
Please stick to just one place to discuss this, then everybody involved sees everything. I'm going to close this issue and we will continue on the Forum [here](https://discourse.nodered.org/t/how-to-use-msg-baudrate-to-set-the-baud-rate-for-the-serial-request-in-node-red-node-serialport)
