### ISSUE TITLE
MySQL 8.0 needs new Auth mechanism

### ISSUE THREAD

**Issue by hardillb** [node-red/node-red-nodes#853]
### Which node are you reporting an issue on?
node-red-node-mysql

### What are the steps to reproduce?
Try to connect to a MySQL v8.0 server

### What happens?

https://stackoverflow.com/questions/69887565/not-able-to-connect-mysql-server-running-on-docker-with-node-red-container

"Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client"

### What do you expect to happen?

Connect and authenticate

This SO answer lays out the problem and solutions:

https://stackoverflow.com/a/56509065/504554

Workaround is to force MySQL to use old auth mechanism, solution looks to be to move to [mysql2](https://www.npmjs.com/package/mysql2) package that is fork of [mysql](https://www.npmjs.com/package/mysql) and contains the fix.

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by dceejay** [comment]
Is this a drop in and being supported ?

**Comment by hardillb** [comment]
The readme implies it's very nearly, which is arguably worse as it will no doubt need testing

**Comment by hardillb** [comment]
Last update was 4days ago

**Comment by knolleary** [comment]
Here's the docs on incompatibilities between the two modules: https://github.com/sidorares/node-mysql2/tree/master/documentation#known-incompatibilities-with-node-mysql

mysql2 certainly seems well adopted and well maintained.

**Comment by dceejay** [comment]
So only minor ones and not ones we expose directly but yes could potentially cause breakage ?

**Comment by dceejay** [comment]
@hardillb  I have published  node-red-node-mysql@next for testing
will need manual install    `cd ~/.node-red && npm install node-red-node-mysql@next`
then restart - feel free to report back to SO.

**Comment by dceejay** [comment]
now released as v1.0.0
