### ISSUE TITLE
 DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

### ISSUE THREAD

**Issue by sampushstack** [node-red/node-red-nodes#855]
### Which node are you reporting an issue on?
node-red-node-mongodb

### What are the steps to reproduce?
loading
### What happens?
deprecation warning below
 DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
### What do you expect to happen?
Is there a new version I should move to
### Please tell us about your environment:
running node-red on docker in AWS
- [ ] Node-RED version:1.2.9: Maintenance Release
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:docker container
- [ ] Browser:

**Comment by hardillb** [comment]
You've not actually said what version of the node-red-node-mongodb node you are using so it's impossible to answer your question.

Deprecated means that this method will be removed in a future release of the underlying mongodb library used by the node, it doesn't mean there is an actual problem with using it at the moment. The 3.x release of the mongodb library is continuing to get bug fix support until summer 2022 so there is no pressing need to move up to the 4.x branch just yet.
