### ISSUE TITLE
GPIO Node says N/A for all GPIOs since update

### ISSUE THREAD

**Issue by ei23fxg** [node-red/node-red-nodes#858]
### Which node are you reporting an issue on?
node-red-node-pi-gpio 

### What are the steps to reproduce?
Reinstall NodeRED like the following:
`bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --confirm-install --confirm-pi --node16 --update-nodes`
and 
`npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-pi-gpio@latest`

I have multiple Raspberry Pi's running and update them periodically via batch script. They all have the same enviroment. One of them I updated manually today (for testing), then also another one, both have the issue.

I tried Raspbian Bullseye, which doesn't has the issue.

### What happens?
GPIO Node says N/A for all GPIOs. With Python GPIOs are working fine.

### What do you expect to happen?
Can someone also reproduce it, is there some bug known?

### Please tell us about your environment:

- [x] Node-RED version: 2.1.3
- [x] node.js version: 16.13.0
- [x] npm version: 8.1.0
- [x] Platform/OS: Raspbian Buster Lite
- [x] Browser: Firefox 94

**Comment by ei23fxg** [comment]
Solved, not an issue.
Just needed to update python libs like this:
`sudo apt-get update; sudo apt-get install python-rpi.gpio python3-rpi.gpio -y`

**Comment by dceejay** [comment]
note: have added to install script to ensure it is place
