### ISSUE TITLE
Node-red crashes with MQTT Packethandler

### ISSUE THREAD

**Issue by GrafAley** [node-red/node-red-nodes#860]
### Which node are you reporting an issue on?
NodeRed/mqtt
### What are the steps to reproduce?
unknown
### What happens?
Node-red-docker start-script fails with [error] ReferenceError: err is not defined

Hi everyone,
I'm experiencing trouble with my NodeRed in docker.
Since the last update of NodeRed  (2.0.x(not sure) ->2.1.3) Node red refuses to start, instead it goes to a "bootloop", trying to restart but failing every time after just some seconds.
The log gives the following hint:

    23 Nov 12:57:40 - [red] Uncaught Exception:
    
    23 Nov 12:57:40 - [error] ReferenceError: err is not defined
    
    at MqttClient._handleConnack (/data/node_modules/mqtt/lib/client.js:920:5)
    
    at MqttClient._handlePacket (/data/node_modules/mqtt/lib/client.js:350:12)
    
    at work (/data/node_modules/mqtt/lib/client.js:292:12)
    
    at Writable.writable._write (/data/node_modules/mqtt/lib/client.js:302:5)
    
    at doWrite (/data/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    
    at writeOrBuffer (/data/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    
    at Writable.write (/data/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    
    at TLSSocket.ondata (internal/streams/readable.js:731:22)
    
    at TLSSocket.emit (events.js:400:28)
    
    at addChunk (internal/streams/readable.js:293:12)
    
    at readableAddChunk (internal/streams/readable.js:267:9)
    
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
    
    npm ERR! code ELIFECYCLE
    
    npm ERR! errno 1
    
    npm ERR! node-red-docker@2.1.3 start: node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
    
    npm ERR! Exit status 1
    
    npm ERR! Failed at the node-red-docker@2.1.3 start script.
    
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    
    npm ERR!     /data/.npm/_logs/2021-11-23T12_57_40_932Z-debug.log

I attached the mentioned logfile below.

I am running MosQTTo as a docker on the same environment, both exposed with their own IPs.
In the MosQTTo log, nodered seems to register and then unregister quite instantly:

    1637672257: New connection from 10.66.2.225:33236 on port 1883.
    
    1637672257: New connection from 10.66.2.225:33238 on port 1883.
    
    1637672257: New client connected from 10.66.2.225:33236 as Tasmota_nodered_c813f4037319ac58 (p2, c1, k60).
    
    1637672257: New client connected from 10.66.2.225:33238 as nodered_c813f4037319ac58 (p2, c1, k60).
    
    1637672260: Client nodered_c813f4037319ac58 closed its connection.
    
    1637672260: Client Tasmota_nodered_c813f4037319ac58 closed its connection.

Please tell me, if you need any further information.
If you need any debugs, logs, or else, please provide instructions how to get those, as I am not very familiar deep down technical analysis.

Thanks in advance!

Sorry for not having the flow ready, but node-red does not start.

### What do you expect to happen?
NodeRed starting, else if it's a config issue giving hint where the config issue is.

### Please tell us about your environment:

- [ ] Node-RED version: 2.1.3
- [ ] node.js version: 14.18.1
- [ ] npm version: unknown
- [ ] Platform/OS: Docker/Portainer
- [ ] Browser: Firefox 94.0.1

[2021-11-23T12_57_40_932Z-debug.log](https://github.com/node-red/node-red-nodes/files/7588211/2021-11-23T12_57_40_932Z-debug.log)

**Comment by hardillb** [comment]
The MQTT nodes are part of the core project, not the node-red-nodes project, we will move it over to the right repo later.

That stacktrace doesn't look right, the line numbers don't line up with version of the MQTT node that should be in use for version v2.1.3 of Node-RED.

Also the fact that it starts with a path in the TLS code when the log from mosquitto implies that it's not connecting to a broker on port 1883 (unless you have also enabled TLS on your broker in docker?)

Can you add the following environment variable to the Node-RED container

    NODE_RED_ENABLE_SAFE_MODE=true

This should start Node-RED but not start the flows. This should you look at your flow to see how you've configured all the MQTT broker config nodes. 

It will start the flows on the first deploy.

**Comment by GrafAley** [comment]
Hi hadillb,

thank you very much for the fast reply!

    npm ls

gives quite a list of modules.

The solution that now seemed to work is to delete the MQTT broker node and reconfigure it.
I didn't add all the MQTT nodes so far, but with the first few it does seem fine.

I've added some, one after another, always giving it some time to break.

But so far, it works fine.

Thank you very much for your help, I close this topic now.
