### ISSUE TITLE
node-red-node-pi-gpio does not work after update

### ISSUE THREAD

**Issue by Zozz** [node-red/node-red-nodes#864]
### Which node are you reporting an issue on?
node-red-node-pi-gpio
### What are the steps to reproduce?
After update to latest version (2.0.1) rpi-gpio out node does not work, it is not control the pin.
### What happens?
Voltage on the pin is not change. The status of the node is "not available" first time, then when I send 0 or 1 to the node it changes to N/A : 0 (or 1)
### What do you expect to happen?
The node controls the output pin as before.
### Please tell us about your environment:

- [ ] Node-RED version: v2.0.5
- [ ] node.js version: v12.22.7
- [ ] npm version: 6.14.15
- [ ] Platform/OS: RPi 3 / Raspbian buster
- [ ] Browser: Chrome 96

**Comment by Zozz** [comment]
OK I found the root cause: the Rpi.GPIO was not installed... after run
`sudo apt install python3-rpi.gpio`
everything works well. Was RPi.GPIO not required before?

**Comment by dceejay** [comment]
yes - and it is usually installed by default, but I guess it may not be if the device has been upgraded over time.
