### ISSUE TITLE
node-red-node-pisrf rpi-gpio not available

### ISSUE THREAD

**Issue by dingausmwald** [node-red/node-red-nodes#865]
### Which node are you reporting an issue on?
node-red-node-pisrf
### What are the steps to reproduce?
Install node, put in node-red, configure, deploy
### What happens?
See error node-red-rpi-gpio.status.not-available under node
### What do you expect to happen?
working node, ok sign or something, maybe some output from my ultrasonic sensor
### Please tell us about your environment:
raspberry pi zero, month old rasp os lite
- [ ] Node-RED version: 2.1.3
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: rasp os lite
- [ ] Browser: chrome

like in other issues there seems to be a problem with latest updates, don't know where exactly. I just can tell that the node is looking for `/usr/share/doc/python-rpi.gpio` and i don't have this. But python3-rpi.gpio. GPIOs working fine, python says 0.7.0

Updating with `sudo apt-get update; sudo apt-get install python-rpi.gpio python3-rpi.gpio -y` like stated in other issues here doesn't work as it says `Package 'python-rpi.gpio' has no installation candidate`.

**Comment by dingausmwald** [comment]
I just removed the
`        else if (!fs.existsSync("/usr/share/doc/python-rpi.gpio")) {
            RED.log.warn("rpi-srf : "+RED._("node-red:rpi-gpio.errors.libnotfound"));
            allOK = false;
        }`
part from the code and it is working, even though i have the waterproof model DYPA02YYxx, not SRF04 or SRF05 (maybe you could add this to the node description aswell). I know this removes the check if rpi.gpio is installed, but maybe you should link this to another direction since it seems that with bullseye directions have changed (not entirely sure).

**Comment by PrathameshAdinawar** [comment]
how did you solve the error i am getting the same error

**Comment by Lunapampamnoel** [comment]
Hello dingausmwald, i'm not a programmer and i use to Home Assistant. So, I have the same problem "rpi-gpio not available" in nodered. Also, you said in your previous message " I removed the line from the code file". Also, where is the code file in the folder "rpi-gpio " ? I don't see where.  Regards

**Comment by dingausmwald** [comment]
.node-red/node_modules/node-red-node-pisrf/pisrf.js
i dont know why i typed rpi-gpio

**Comment by Lunapampamnoel** [comment]
Thank you for your quick response but I don't have the same path. I have "/homeassistant/custom_components/nodered/" and after no folder named "node_modules". And in the others folders I don't see the file "pisrf.js"

**Comment by dingausmwald** [comment]
You are on a completely wrong path. It seems you are using home assistant OS. I dont think you can use your gpios on a raspberry pi with home assistant os installed.

Also, the custom component for node red is to communicate with another node red instance, to show the sensors and switches in home assistant you have created with node red. There is a node red addon that runs node red on home assistant, but still i dont think you can use the gpios here. And even if you could, you cant modify internal files in home assitant os because they get reverted after a restart. I am not quite sure but i think it is also true for the addon internal files.

**Comment by Lunapampamnoel** [comment]
yes, I have homeassistant os and I installed nodered with haos method. In fact, it's possible to communicate with the gpios in nodered through haos. But, there is a issue with raspberry 64bits to use the gpios. I think....So, thank you for your help
