### ISSUE TITLE
SNMP node fails on oid 1.3.6.1.2.1.1.1 But not fail on 1.3.6.1.2.1.1.1.0?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [node-red/node-red-nodes#868]
SNMP node fails on oid 1.3.6.1.2.1.1.1.
12/31/2021, 8:49:42 PMnode: Description
msg : string[47]
"RequestFailedError: NoSuchName: 1.3.6.1.2.1.1.1"

But works for 1.3.6.1.2.1.1.1.0.

Extract from node-red-log...
1 Jan 04:36:54 - [error] [snmp:Description] RequestFailedError: NoSuchName: 1.3.6.1.2.1.1.1

Test via CLI snmpwalk and OID does exist on node-red system, so MIB is present...
$ snmpwalk -Os -c "DD" -v 1 192.168.1.2  1.3.6.1.2.1.1.1
sysDescr.0 = STRING: Linux reserve 4.14.221 #0 Mon Feb 15 15:22:37 2021 armv5tel

Node-RED Version...
2.1.4

node.js Version...
v12.22.7 (Yes know v12 is approaching EOL)

npm Version...
6.14.15

Platform/OS...
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Browser, Firefox

CLI SNMP version... (A bit dated, but current for buster)
$ snmpd -v

NET-SNMP version:  5.7.3
Web:               http://www.net-snmp.org/
Email:             net-snmp-coders@lists.sourceforge.net

What is odd is that other OIDs work as expected for example., 1.3.6.1.2.1.1.3.0, works fine in NR.  Or even 1.3.6.1.2.1.1.1.0
12/31/2021, 8:48:31 PMnode: Message
msg : Object
object
_msgid: "f0daed2ad3d8344c"
host: "192.168.1.2"
community: "DD"
oid: "1.3.6.1.2.1.1.3.0"
payload: array[1]
0: object
oid: "1.3.6.1.2.1.1.3.0"
type: 67
value: 61487903
tstr: "TimeTicks"
_event: "node:a4281519ea4fd5

12/31/2021, 8:58:48 PMnode: Message
msg : Object
object
_msgid: "2ab15d8c47dd5703"
host: "192.168.1.2"
community: "DD"
oid: "1.3.6.1.2.1.1.1.0"
payload: array[1]
0: object
oid: "1.3.6.1.2.1.1.1.0"
type: 4
value: "Linux reserve 4.14.221 #0 Mon Feb 15 15:22:37 2021 armv5tel"
tstr: "OctetString"
_event: "node:a4281519ea4fd516"

Is not the expected behavior that ".0" is redundant for a single response?  Whereas, CLI snmpwalk does not require .0 to resolve?

**Comment by dceejay** [comment]
If you do a get rather than a walk you also get a failure
```
snmpget -v1 -Cf -c public 192.168.1.162 1.3.6.1.2.1.1.1
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: iso.3.6.1.2.1.1.1
```
so I don't think there is a problem with the node - likewise if you use the snmp walker node rather than just the snmp (get) node it does return a large array of values... 

So I don't think there is anything to fix here.

**Comment by Jibun-no-Kage** [comment]
That could be.  I have several of the devices... routers using OpenWRT firmware, I will do some more testing, just to confirm the behavior is consistent.  I did not get an snmpwalk error via the CLI on the router or on a Pi OS 11 (running NR).  The only 'error' was in the node-red node with the initial testing I did... which I illustrated above.  The tactical fix... just append .0 to the oid in the NR flow of course.  Looks like the CLI on router and Pi OS snmpwalk.... are just more forgiving.  Which is not really a good thing IMHO.

**Comment by Jibun-no-Kage** [comment]
Forgot to close... Thanks for the response.

**Comment by dceejay** [comment]
they aren't more forgiving. They are not equivalent. If you use the node-red snmp walker node then you do get a result as you do with the equivalent snmpwalk command..  Likewise if you use the simple snmp node it does a get and fails - just as the snmpget command does.
