### ISSUE TITLE
node-red-node-serialport

### ISSUE THREAD

**Issue by hkjang** [node-red/node-red-nodes#873]
Thanks for checking the issue.

### Which node are you reporting an issue on?
node-red-node-serialport 0.15.0

### What happens?
How to connect to remote rs485 serial port? If i simply write ip:port in the serialport config, can not connect.

### What do you expect to happen?
I want to connect to remote rs485 serial port using node-red-node-serialport library.

### Please tell us about your environment:

- [ ] Node-RED version: v2.1.4-1
- [ ] node.js version: 14.18.2
- [ ] npm version: 6.14.15
- [ ] Platform/OS: docker container node-red/node-red
- [ ] Browser: chrome

**Comment by knolleary** [comment]
This issue tracker is for bugs. As described in the issue template, please use the forum for general how-to questions.

This node doesn't support connecting to remote serial ports.
