### ISSUE TITLE
node-red-node-xmpp not respecting SRV record

### ISSUE THREAD

**Issue by ISharkI** [node-red/node-red-nodes#881]
### Which node are you reporting an issue on?
node-red-node-xmpp

### What are the steps to reproduce?
1. Install Node
2. Input Userdata
3. Deploy

### What happens?
The Module seems not to respect the SRV record of the Domain for xmpp-clients.

I have a domain with multiple devices. My XMPP accounts are username@exampledomain.com. The XMPP service is running on dolphin.exampledomain.com, while the main domain runs on host.exampledomain.com
I sed the needed SRV records for xmpp clients (and servers) and they are present in the DNS

```
 dig SRV _xmpp-client._tcp.exampledomain.com

; <<>> DiG 9.17.21-1-Debian <<>> SRV _xmpp-client._tcp.exampledomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18248
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_xmpp-client._tcp.exampledomain.com. IN	SRV

;; ANSWER SECTION:
_xmpp-client._tcp.exampledomain.com. 300 IN	SRV	0 5 5222 dolphin.exampledomain.com.

;; Query time: 36 msec
;; SERVER: 192.168.9.2#53(192.168.9.2) (UDP)
;; WHEN: Mon Jan 31 10:15:40 CET 2022
;; MSG SIZE  rcvd: 101
```
The XMPP host has an IP ending in .5
```
host dolphin.exampledomain.com
dolphin.exampledomain.com has address x.x.x.5
dolphin.exampledomain.com has IPv6 address x::b
```
While the main host has an IP ending in .9
```
host exampledomain.com
exampledomain.com has address x.x.x..9
```
After I deploy the flow in NodeRed it shows "error" and following is displayed in the debug log (I used an xmpp-out as example)
```

Jan 31 10:12:55 homematic daemon.err node-red[1565]: [xmpp out:35b34616.ac7bca] Unknown error: Error: connect ECONNREFUSED x.x.x.x.9:5222
Jan 31 10:12:55 homematic daemon.err node-red[1565]: [xmpp out:35b34616.ac7bca] Bad xmpp configuration; service: xmpp://exampledomain.com:5222 jid: myuser@exampledomain.com
Jan 31 10:12:55 homematic daemon.warn node-red[1565]: [xmpp out:35b34616.ac7bca] Error: connect ECONNREFUSED x.x.x.x.9:5222
Jan 31 10:12:55 homematic daemon.warn node-red[1565]: [xmpp out:35b34616.ac7bca]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

If my understanding is correct it should connect to the .5 instead of .9? Several other XMPP clients do work so the server is fine.

### What do you expect to happen?
It should connect (as other Clients do work)

### Please tell us about your environment:

- [ ] Node-RED version: 7.1.3
- [ ] node.js version: v8.11.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: RaspberryPI3, RaspberryMatic 3.37.8
- [ ] Browser: Firefox 91.5.0esr
- [ ] node-red-node-xmpp: 0.5.9

**Comment by hardillb** [comment]
Quick question, is Node-RED running in a Docker container on RaspberryMatic?

**Comment by ISharkI** [comment]
No
```
# ps -ef | grep red
 1561 root      0:00 {redmaticLoader} /bin/sh /usr/local/addons/redmatic/bin/redmaticLoader
 1565 root      1:54 node-red
 1566 root      0:00 logger -p daemon.err -t node-red
 5776 root      0:00 grep red

```

**Comment by sgofferj** [comment]
Same issue here. 
I have xmpp addresses like name@domain.tld but my XMPP server is xmpp.domain.tld with SRV records pointing to it. That doesn't work with the current NodeRed XMPP nodes because if I enter domain.tld as server, it tries to connect to my webserver and if I enter xmpp.domain.tld, my xmpp-server complains that it doesn't know that domain when a client tries to connect to it:
```
"Unknown error: StreamError: host-unknown"
"Got error on start: StreamError: host-unknown"
"XMPP Status is now: disconnecting"
```

As I understand, my setup is quite common because in general, operators like XMPP addresses like name@domain.tld as opposed to name@server.domain.tld but domain.tld usually points to a webserver, so the XMPP server would be something like xmpp.domain.tld with SRV records pointing to it.

**Comment by sgofferj** [comment]
If pulling SRV records is too complicated, an easier fix would be to separate the server address from the registration call and take the domain from the JID instead the server field. But SRV records would, of course, be best practice.

**Comment by dceejay** [comment]
Happy to look at a Pull Request if anyone wants to offer up one...

**Comment by sgofferj** [comment]
Would love to but that's way above my skills. I have an understanding of the protocols but my JS skills suck...

**Comment by dceejay** [comment]
whereas I can (on a good day) handle the JS - but obviously not getting the subtleties of the protocol....

**Comment by sgofferj** [comment]
I'll try to understand the source and do some debugging.

**Comment by sgofferj** [comment]
@dceejay 
I tried to understand how the node handles the connection.

Not sure if I got it right, but it seems, that when a domain is given in the JID, the code takes the server address from the JID.
92-xmpp.js, line 12 - 26.

In XMPP, the server is independent of the domain, a little bit like in internet mail traffic. My JID stefan@gofferje.net can be handled by a server in a completely different (internet-)domain. Where the internet mail system uses MX records, XMPP relies on either SRV records or direct specification of the server address.
The @xmpp/client package you use actually has an [@xmpp/resolve](https://github.com/xmppjs/xmpp.js/tree/2f4a6920659f19308b48ce143936e83381e3fcba/packages/resolve) to handle those things.

To fix the issue I'd see 2 possibilities:
1. Rewrite the connection part:
- Take the server address from the JID **only** when server was not specified separately.
- If the server address is specified, use the server address for connection and submit the JID as given for login.

or

2. Use @xmpp/resolve

**Comment by sgofferj** [comment]
Just noticed also that the client setup (line 48 - 53) does not specify the domain. The @xmpp/client example specifies the domain in the setup:
```javascript
const xmpp = client({
  service: "ws://localhost:5280/xmpp-websocket",
  domain: "localhost",
  resource: "example",
  username: "username",
  password: "password",
});
```

That might actually be the problem... The docs say
`domain` `<string>` Optional domain of the service, if omitted will use the hostname from service. Useful when the service domain is different than the service hostname. I would suggest either taking the domain from the JID or adding a separate configuration field.

The `resource` would actually also be useful to have. It identifies the connecting instance (e.g. "Laptop" or "NodeRED bot") which is useful as XMPP allows multiple simultaneous logins.

**Comment by dceejay** [comment]
Thanks for looking into this. So where should the resource come from ? Just another config field ? At the client level or the config node level ? What should it default to ?

**Comment by sgofferj** [comment]
I would put the resource in the config node as a separate field. It's optional so it could default to null or anything you see fit. Maybe "NodeRED"?. In practice it's really only used by a message recipient to determine who sent a message if the same JID is logged in on multiple devices. If you go into end-to-end encryption, your client would want to know which "end" it's talking too, though.

I personally use very uncreatively
stefan@gofferje.net/phone
stefan@gofferje.net/tablet
stefan@gofferje.net/laptop
stefan@gofferje.net/desktop

Many clients can/do show the resource, so it's nice to have.

**Comment by dceejay** [comment]
Hi @sgofferj  - I have pushed an update to this to npm (but not to the catalog yet)  - v0.6.0
Can you give it a try and feedback please

**Comment by sgofferj** [comment]
> Hi @sgofferj - I have pushed an update to this to npm (but not to the catalog yet) - v0.6.0 Can you give it a try and feedback please

Will do.

> PS - I see you're also having fun with TAK - did you see my tak-registration node ? (https://flows.nodered.org/node/node-red-contrib-tak-registration)

Oh, no I haven't! Indeed, I'm doing a lot of things with TAK at the moment. I have written my own CoT creating functions for all kinds of stuff. I was planning to push the code to Github but haven't had the time yet. I'll put your node to my list of things to check out.

**Comment by sgofferj** [comment]
> Hi @sgofferj - I have pushed an update to this to npm (but not to the catalog yet) - v0.6.0 Can you give it a try and feedback please

Works for me.
Server: ejabberd 22.5.0
NodeRED: 2.2.2
Tested / checked:
- Registration for domain other than server address/ip: works as expected, no errors, no warnings in server log
- Resource: 
  - submitted as configured (server debug log)
  - registered as configured (server client list)
  - appears at message recipients as configured (tested with Conversations/Android, Pidgin/Linux, Dino/Linux)

I haven't checked the code if you use XMPP/resolve or not but by configuring a specific server address, the user should be able to connect to any current XMPP server.

**Comment by dceejay** [comment]
excellent, no I just did as you suggested re extracting the domain from the JID and optionally adding the resource.
Now published to library.

**Comment by dceejay** [comment]
Ah yes the repo is currently private

**Comment by sgofferj** [comment]
> Ah yes the repo is currently private

Mmm, pity.

**Comment by dceejay** [comment]
Hi @sgofferj 

TAKreg repo now public

**Comment by sgofferj** [comment]
@dceejay Nice! Will check!
Another issue with the XMPP node, though... I tried the "in" node and while it does receive all presence notifications, nothing comes out of the message output. I have to do some more testing but at the moment, I don't know how to debug that.

**Comment by dceejay** [comment]
should be handled in 92-xmpp.js lines 478 onwards - particularly around line 532

**Comment by sgofferj** [comment]
Wilco. Just wanted to give a short heads up. Doesn't make much sense to open an issue "...does not work" without any kind of info.
