### ISSUE TITLE
Feedparser Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by brunoamaral** [node-red/node-red-nodes#884]
### Which node are you reporting an issue on?

node-red-node-feedparser

### What are the steps to reproduce?

Configure the node to fetch the following URL: https://www.clinicaltrialsregister.eu/ctr-search/rest/feed/bydates?query=multiple+sclerosis

### What happens?

The debug tab returns `Error: unable to verify the first certificate`

### What do you expect to happen?

Fetch the feed items

### Please tell us about your environment:

- [ ] Node-RED version: 2.1.4
- [ ] node.js version: v14.18.3
- [ ] npm version: 6.14.15
- [ ] Platform/OS: Docker
- [ ] Browser: Chrome / Brave

**Comment by hardillb** [comment]
This is a problem with the HTTP server providing the RSS feed.

A quick test with curl shows the same problem

```
$ curl https://www.clinicaltrialsregister.eu/ctr-search/rest/feed/bydates?query=multiple+sclerosis
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

The server probably needs configuring to include any missing intermediate certificates required to complete the certificate chain between a known root CA cert and the end server cert in it's TLS handshake.

As a work around you can export `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable, but this will completely disable all certificate checking for all parts of Node-RED not just the node-red-node-feedparser node.

**Comment by hardillb** [comment]
Actually it appears that CA cert (DigiCert TLS RSA SHA256 2020 CA1) is just not in the NodeJS CA store (or the one shipped with Ubuntu 20.04 or Fedora 35 where I tested with curl)

The list in NodeJS comes from Mozilla and is current at the time the build was made as far as I can tell. (I can't find that CA cert in their current list either https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport)

**Comment by brunoamaral** [comment]
@hardillb thank you for taking the time to clarify this. I'm using a custom version of node-red on docker, will changing the OS image be enough to resolve this on my end? https://github.com/brunoamaral/gregory/blob/main/Dockerfile

**Comment by hardillb** [comment]
No, probably not (the choices are Alpine or Debian)

The list of CA certs is baked into the NodeJS binary.

it appears it can be forced to use the OS set using the `--use-openssl-ca` cmd line option [docs](https://nodejs.org/docs/latest-v10.x/api/cli.html#cli_use_bundled_ca_use_openssl_ca) but even that wouldn't help as the required cert is not included in the Ubuntu or Fedora bundled certs (You can test on Debain with curl command I mentioned earlier, but I very much doubt it's there by default either).

Depending on how far you want to go then you should be able to download the CA and  add it to the OS/OpenSSL list of certs, then work out how to pass the option mentioned. But that is task I'm going to have to leave you to research for yourself.

**Comment by brunoamaral** [comment]
that's already a good pointer in the right direction, thank you @hardillb
