### ISSUE TITLE
Node-Reaccessibled crash with "Uncaught Exception" if the Database is not more accessible

### ISSUE THREAD

**Issue by lucagem** [node-red/node-red-nodes#885]
Using "node-red-node-mysql 1.0.0" **if the connection to the MariaDB stops to work** we get the following error and **Node-Red crash**:

Warning: got packets out of order. Expected 7 but received 1
Warning: got packets out of order. Expected 7 but received 1
17 Feb 12:54:11 - [red] Uncaught Exception:
17 Feb 12:54:11 - TypeError: Cannot read property 'release' of undefined
at /root/.node-red/node_modules/node-red-node-mysql/68-mysql.js:117:38
at /root/.node-red/node_modules/mysql2/lib/pool.js:60:18
at PoolConnection. (/root/.node-red/node_modules/mysql2/lib/connection.js:775:13)
at Object.onceWrapper (events.js:421:26)
at PoolConnection.emit (events.js:326:22)
at PoolConnection.notifyError (/root/.node-red/node_modules/mysql2/lib/connection.js:236:12)
at Socket. (/root/.node-red/node_modules/mysql2/lib/connection.js:107:12)
at Socket.emit (events.js:314:20)
at TCP. (net.js:676:12)

**This happens only if the connection was working and suddenly stops to work**.
We get this problem on a device "Siemens IOT 2050" mounting Debian OS.

17 Feb 14:43:01 - [info] Node-RED version: v2.0.6
17 Feb 14:43:01 - [info] Node.js version: v12.22.5
17 Feb 14:43:01 - [info] Linux 5.10.64 arm64 LE
17 Feb 14:43:04 - [info] Loading palette nodes
17 Feb 14:43:19 - [info] Dashboard version 2.30.0 started at /ui
17 Feb 14:43:20 - [info] Settings file : /root/.node-red/settings.js
17 Feb 14:43:20 - [info] Context store : 'default' [module=memory]
17 Feb 14:43:20 - [info] User directory : /root/.node-red
17 Feb 14:43:20 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Feb 14:43:20 - [info] Flows file : /root/.node-red/flows.json
17 Feb 14:43:20 - [info] Server now running at http://127.0.0.1:1880/
17 Feb 14:43:20 - [warn]

I know it's not the latest Node-Red version but this device it's not so easy to upgrade.
Thanks in advance for your work and your time

**Comment by hardillb** [comment]
I think I've fixed this, will let @dceejay review it, but if you are comfortable installing npm modules from git then you can try the branch in the #886  PR
