### ISSUE TITLE
snmp Nodes Version 1.0.0 stop working

### ISSUE THREAD

**Issue by mickym2** [node-red/node-red-nodes#907]
### Which node are you reporting an issue on?

snmp Nodes are not working in Version 1.0.0 - but all is fine with version 0.0.25. 

I updated the node-red-node-snmp from version 0.0.25 to 1.0.0 and none of the snmp nodes were working. All came with an error tables, multiple OIDs - with a type error: TypeError: argument must be a Number. I only triggered nodes with a boolean - but as I specified OIDs with the node, the payload should be irrelevant.

### What are the steps to reproduce?

snmp Nodes are not working

### What happens?

Type Error: argument must be a Number

### Please tell us about your environment:

- [ 2.2.2] Node-RED version:
- [14.x ] node.js version:
- [6.x ] npm version:
- [ Raspberry / bullseye] Platform/OS:
- [Edege/Chrome ] Browser:

**Comment by Steve-Mcl** [comment]
Can you please share a demo flow & I will test the upgrade process. 

This release was supposed to be a seamless upgrade but it was quite an overhaul so something could have been missed.

**Comment by mickym2** [comment]
I already converted back to version 0.0.25 - flows are nothing special: 

![image](https://user-images.githubusercontent.com/58858526/167223273-da6f661b-a359-4bbd-a906-8950f0ea72d1.png)


`[
    {
        "id": "89e1bfd7.eee8e",
        "type": "snmp table",
        "z": "99e1680f.414f18",
        "host": "192.168.178.200",
        "community": "public",
        "version": "1",
        "oids": "1.3.6.1.2.1.25.2.3",
        "timeout": 5,
        "name": "Table - Speichermedien",
        "x": 3110,
        "y": 860,
        "wires": [
            [
                "726dc35.d33293c"
            ]
        ],
        "info": "# Tabellenaufbau - Objekt\n * 1: hrStorageIndex\n * 2: OID\n * 3: hrStorageDescr\n * 4: hrStorageAllocationUnits\n * 5: hrStorageSize\n * 6: hrStorageUsed"
    },
    {
        "id": "22691b3f.aba574",
        "type": "inject",
        "z": "99e1680f.414f18",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 2830,
        "y": 860,
        "wires": [
            [
                "89e1bfd7.eee8e"
            ]
        ]
    },
    {
        "id": "726dc35.d33293c",
        "type": "debug",
        "z": "99e1680f.414f18",
        "name": "snmp table",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 3390,
        "y": 860,
        "wires": []
    },
    {
        "id": "5620f5bb.e713bc",
        "type": "snmp",
        "z": "99e1680f.414f18",
        "host": "192.168.178.200",
        "community": "public",
        "version": "1",
        "oids": "1.3.6.1.2.1.25.6.3.1.2.557",
        "timeout": 5,
        "name": "",
        "x": 3130,
        "y": 760,
        "wires": [
            [
                "200c6973.f26c46"
            ]
        ]
    },
    {
        "id": "624fc909.a8daf8",
        "type": "inject",
        "z": "99e1680f.414f18",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 2850,
        "y": 760,
        "wires": [
            [
                "5620f5bb.e713bc"
            ]
        ]
    },
    {
        "id": "200c6973.f26c46",
        "type": "debug",
        "z": "99e1680f.414f18",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 3400,
        "y": 760,
        "wires": []
    }
]`

You see everything is working fine in 0.0.25 and stopped working. You get an error message: TypeError: argument must be a Number.

**Comment by Steve-Mcl** [comment]
Thanks. I'll try to get to the bottom of this & let you know.

**Comment by DagBertelsen** [comment]
I see you have not set the SNMP version. Try setting this to v1/v2c/v3 and see if it works.

I got the same error when I upgraded and where missing the SNMP version as you have here. But when I added the correct version number it started working.

**Comment by mickym2** [comment]
The version number is set correct in version 0.0.25 in every node and is preselected - and if you look to the flow above it is set to 1 as well. If this is not taken over .

![image](https://user-images.githubusercontent.com/58858526/167256712-d1e26c64-ca73-4ba6-a937-9e91fe972d1e.png)
 and the nodes - I posted above have a version number 

[ { "id": "89e1bfd7.eee8e", "type": "snmp table", "z": "99e1680f.414f18", "host": "192.168.178.200", "community": "public", "version": "1", "oids": "1.3.6.1.2.1.25.2.3", "timeout": 5, "name": "Table - Speichermedien", "x": 3110, "y": 860, "wires": [ [ "726dc35.d33293c" ] ], "info": "# Tabellenaufbau - Objekt\n * 1: hrStorageIndex\n * 2: OID\n * 3: hrStorageDescr\n * 4: hrStorageAllocationUnits\n * 5: hrStorageSize\n * 6: hrStorageUsed" }

If this is not taken over - then this should be fixed.
