### ISSUE TITLE
node-red-node-email no longer compatible with Gmail

### ISSUE THREAD

**Issue by gkgeorgiev** [node-red/node-red-nodes#926]
Based on the Gmail documentation, as of 22.05.2022, they stop supporting less secured 3rd party apps for regular Gmail users.

### Which node are you reporting an issue on?
node-red-node-email

### What are the steps to reproduce?
1. install node-red-node-email 1.15.1
2. Configure gmail account at the email node
3. try to send an email

### What happens?
Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials g5-20020a50d5c5000000b004356c0d7436sm11008465edj.42 - gsmtp

### What do you expect to happen?
Successfully sent email

### Please tell us about your environment:

- [ ] Node-RED version: 2.2.2
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: HASSIO
- [ ] Browser: FF

**Comment by hardillb** [comment]
Have you followed the instructions in the link in the error messages? I believe App Specific passwords still work

**Comment by hardillb** [comment]
Yes, but at the bottom of that page there is a link to using an "App Password" (and generated 16 digit passcode)  that should still work. 

To be 100% sure, you have tried using that and it still doesn't work?

**Comment by dceejay** [comment]
Using App passwords still works ...  so going to close this

**Comment by Steve-Mcl** [comment]
App passwords are the way to go

Instructions here: https://discourse.nodered.org/t/gmail-email-in-node-no-longer-working-with-username-password/60683/5?u=steve-mcl

**Comment by dceejay** [comment]
Thanks @Steve-Mcl
