### ISSUE TITLE
Timeswitch reporting bizarre timestamp for next sunrise event

### ISSUE THREAD

**Issue by jdmallen** [node-red/node-red-nodes#944]
### Which node are you reporting an issue on?
node-red-node-timeswitch

### What are the steps to reproduce?
1. Insert into flow
2. Set Lat & Long for your location
3. Configure to turn ON at SUNSET and OFF at SUNRISE
4. Deploy and observe scheduled time to next execution

### What happens?
The timeswitch node says it won't execute "until 24:10." The next event (sunrise, in my case) is actually more like 8.5 hours from now. Considering this is not a standard format for any timestamp, I suspect this is more of a presentation bug than an operational one, but I have no idea.

### What do you expect to happen?
I expect it to report that it'll send "off" either in the appropriate timespan for when sunrise will actually occur for my lat/long, or "until" an actual timestamp in my local time.

[BigTimer](https://flows.nodered.org/node/node-red-contrib-bigtimer), the node-contrib that this one references in [its overview page](https://flows.nodered.org/node/node-red-node-timeswitch), reflects the correct time. Please see these comparison pictures:

![image](https://user-images.githubusercontent.com/5761601/185825074-8a5b5cbe-5cef-4e03-9f7f-1b9f63661b3e.png)
![image](https://user-images.githubusercontent.com/5761601/185825154-106de08f-a6eb-4b11-8ec9-eb9ee7f3662e.png)
![image](https://user-images.githubusercontent.com/5761601/185825293-7e8ad80c-8a86-489c-8de5-6fc6636e15c2.png)
Note the "off until 24:10" under the timeswitch.

### Please tell us about your environment:

- [x] Node-RED version: v3.0.2
- [x] node.js version: Whatever it is in the latest [`nodered/node-red`](https://hub.docker.com/r/nodered/node-red/) Docker image.
- [x] npm version: "
- [x] Platform/OS: "
- [x] Browser: "

**Comment by dceejay** [comment]
well yes definitely a presentation error at the very least... - 
would 24:10 (-> 00:10) be roughly the sunrise time in GMT rather than your local timezone ?

**Comment by dceejay** [comment]
pushed version 0.2.1

**Comment by jdmallen** [comment]
Wow, appreciate the quick work! I pulled 0.2.1 into NR and tried it again.

![image](https://user-images.githubusercontent.com/5761601/185909811-8fb4f056-6aab-4a1e-88fb-102f9e4359a7.png)


It still seems incorrect to me, using the same settings as before. We're past sunrise where I am (UTC-4), so it should be tracking the next event: sunset. However, it seems to think sunrise has not yet occurred. The current local time when I took this screenshot was about 7:20 a.m. The current status of the node should also be OFF, just like BigTimer.

![image](https://user-images.githubusercontent.com/5761601/185909511-e26b762d-45b1-4226-bf46-70739fef3166.png)

**Comment by jdmallen** [comment]
It's worth noting that I have NR set to display time in 24-hour format, so "6:29" is a.m. EDT.

**Comment by dceejay** [comment]
If you change the sunrise to be a time (eg 07:00)  - a timezone box should appear - what does that say ? (Ie is it correct or has it defaulted to GMT ?)

**Comment by jdmallen** [comment]
It was set correctly to America/New_York, though I did notice a promising clue. I set the timer to ON at 08:00 and OFF at 20:00 (8p), and here's what I got after deploying.

![image](https://user-images.githubusercontent.com/5761601/185922362-b89739cc-02ac-464e-87a0-947dcc3203b3.png)

![image](https://user-images.githubusercontent.com/5761601/185922379-b5caeba1-d1bb-4308-95d4-02e6c8d21411.png)

It looks like it might be over-correcting. I am indeed in UTC-4, so it should be subtracting 4 hours from the UTC time (12:38Z as of this comment, 8:38 here), but it's still treating the time in the dropdown as though it's UTC, not local, regardless of the timezone selected. That's fine for selecting specific times-- I can just know to select UTC-- but it doesn't work for sun events.

**Comment by dceejay** [comment]
OK - looks somewhat more broken than just displaying incorrectly then.. as the dropdown (and sunrise/sunset) should all be in local time for the user shouldn't they... (but stored internally in GMT). hmm

**Comment by jdmallen** [comment]
Thanks @dceejay. I'll see if I can get my environment set up to do Node-Red development and maybe help out in parallel (without stepping on toes, of course).

**Comment by dceejay** [comment]
Thanks - any/all help much appreciated

**Comment by jdmallen** [comment]
Happy to help!

So I did poke around at lunch. The problem is how we're interpreting "now."

![image](https://user-images.githubusercontent.com/5761601/185986638-5ac70bbc-98d1-47ec-8931-db6d71fad5e2.png)

That `Date` object is in the Offset format. It  _should_ show as either `12:49:44 GMT-0400` or `08:49:44 GMT+0000`, but not a combination of both. This is why we were seeing that excess offset of -4 hours earlier.

The reason is that we're taking the `Date.now()` epoch time and _then_ applying the timezone offset to it. The problem is that epoch time does not have timezones, and so `Date` already represents the local time when it's evaluated by the Nodejs runtime. In order for us to properly use custom timezones in this node that _differ_ from the timezone the user is currently in, we must first understand what the user's _current_ timezone is.

Let's say I want to specify that this node should send a '1' in the payload when the time 7 a.m. Pacific Standard Time is encountered. I need the code to know that the start time is -3 hours from where I am before it presents me with the "OFF until 10:00" message. Right now, it does not appear to be doing that.

Utilizing a more robust DateTime library like Moment (node_modules == ~6 MiB) or [Luxon](https://moment.github.io/luxon) (node_modules == ~4 MiB) would mitigate this pretty easily. The current library, spacetime (node_modules == ~0.5 MiB), is pretty powerful, but does not appear to supply a getter for a complete DateTime object, string, or epoch, which makes it a bit trickier to work with. However, I did see your notes in a previous PR about wanting to keep this library lightweight, so I'll play around a bit more with the code this evening and see if I can get this to play nice.

**Comment by jdmallen** [comment]
So... I fixed it. But I did a lot of other things, too. Mostly to make more use of the spacetime library (since it's there), and to make it a bit easier to read.

Before I dare make a PR, figured you might want to [take a gander](https://github.com/node-red/node-red-nodes/compare/master...jdmallen:node-red-nodes:fix-and-clean). I tested multiple scenarios, including sun events, Start + X Minutes, months or days of week disabled/enabled, sun event offsets, etc. I think it's working pretty well. Even obscure cases when the OFF time is sunset, but sunset happens to be a couple minutes before the ON time:

![image](https://user-images.githubusercontent.com/5761601/186047048-02e8484d-0857-48a7-bc6a-cde55673309c.png)

...it behaves as expected:

![image](https://user-images.githubusercontent.com/5761601/186046920-40d986fc-c687-4eb0-ad80-0e0ca681ca3f.png)

Eager to learn your thoughts.

**Comment by dceejay** [comment]
Hi - Actually it's much easier for me to test if it is a PR - so please go ahead !
Looks good to me.

**Comment by jdmallen** [comment]
Sure, I added #945. Please let me know what you'd like me to change.

**Comment by dceejay** [comment]
Much improved ! Many thanks.
