### ISSUE TITLE
node-red-node-ping in Triggered mode and Link nodes

### ISSUE THREAD

**Issue by jdotbdot** [node-red/node-red-nodes#952]
### Which node are you reporting an issue on?
Node-red-node-ping

### What are the steps to reproduce?
Place a Ping node (in Triggered mode so that it has an input as well as output) between link-in and link-out (return to calling node) nodes.
![image](https://user-images.githubusercontent.com/11013909/192631391-ce40643d-ebab-41ab-b92c-2adde53ecc53.png)

### What happens?
The link-out node throws an error: "Missing return node information".

### What do you expect to happen?
 When the Ping node is set up in Triggered mode, any additional message properties such as msg.topic, msg._linkSource which arrive at the input should pass through to the output.
### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 16.17.0
- [ ] npm version: 8.15.0
- [ ] Platform/OS: Raspberry Pi/ RPiOS Bullseye
- [ ] Browser: Firefox v105

**Comment by dceejay** [comment]
Well the node clearly specifies that the `msg.topic` will be set to the name of the host that was pinged... but yes other properties should be preserved.

**Comment by jdotbdot** [comment]
Of course. I added msg.topic when creating this report without checking the help first. 
I just wanted to highlight that msg.linkSource is not the only affected property.

**Comment by dceejay** [comment]
Fixed in version 0.3.2
