### ISSUE TITLE
Support for Matter Protocol 

### ISSUE THREAD

**Issue by Neirth** [node-red/node-red-nodes#963]
Hello!

I was thinking that a collaborative effort could be made to support the Matter protocol for the smart home. Nodered, through 3rd party Plugins, has opened this possibility to the product.

After the recent release of version 1.0 of the Matter standard, Matter becomes fully viable of being able to be integrated into this repository as an additional solution.

Personally I think that to build this plugin, you could use as a base the mechanics exposed in [https://flows.nodered.org/node/node-red-contrib-homekit-bridged](https://flows.nodered.org/node/node-red-contrib-homekit-bridged), which allows to emulate both a device (For example to create occupancy sensors by Ping to mobile devices), and to receive and send events against the devices (Essential to make an automation would be).

If I find a gap of my time, maybe I'll do a PR incorporating a version compatible with Matter and supporting the official library in Node.js [https://github.com/project-chip/matternode](https://github.com/project-chip/matternode)

**Comment by knolleary** [comment]
The best place to coordinate a community contribution for a new node is the discourse forum.

This repo holds nodes the project inherited in the early days before we supported self-publishing nodes to npm.

We do not have the bandwidth within the core maintainers to take on new nodes ourselves, unless they are ones we are actively using ourselves.

**Comment by Neirth** [comment]
Thanks for the reply @knolleary, the topic continues in [https://discourse.nodered.org/t/support-for-matter-protocol/72358](https://discourse.nodered.org/t/support-for-matter-protocol/72358)
