### ISSUE TITLE
http-response Warning: status code shouldn't be a string / express deprecated res.status("200")

### ISSUE THREAD

**Issue by carstenpi** [node-red/node-red-nodes#964]
### Which node are you reporting an issue on?
Http response
### What are the steps to reproduce?
Set a status Code like 200
### What happens?
It throws a Warning:
`express deprecated res.status("200"): use res.status(200) instead at`

The status code is stored in the flow.json file as a string.

### What do you expect to happen?
No Warning.
The status code shouldn't be a string it should be an integer.

### Please tell us about your environment:
- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 19.2.0
- [ ] npm version: 9.1.3
- [ ] Platform/OS: Linux 5.15.80-sunxi
- [ ] Browser:

**Comment by hardillb** [comment]
The http-in/http-out nodes are core nodes and in the https://github.com/node-red/node-red repository

Duplicate https://github.com/node-red/node-red/issues/3893

Fixed in https://github.com/node-red/node-red/issues/3894

It will be included in the next release
