### ISSUE TITLE
SNMP node - entering data in ‘timeout’ works backwards

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-nodes#970]
<!--

### Which node are you reporting an issue on?
Node-red-node-snmp

### What are the steps to reproduce?
1 - add an snap node to a tab
2 - click on the 'timeout' option
3 - put your cursor before the 5 and type a number (say 2)

 
### What happens?
The number you enter is in the wrong place
![snmpbug](https://user-images.githubusercontent.com/11473405/212311361-c9734178-548e-47b4-aa52-af457cc909c2.gif)

### What do you expect to happen?
instead of seeing 25, the result is 52. If you now put the cursor after the 2 and enter 4, instead of 524 you get 452

### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 18.12.1
- [ ] npm version: 8.19.2
- [ ] Platform/OS: macOS/Ventura
- [ ] Browser: Safari - Note it also fails in Chrome but works correctly in FireFox

**Comment by knolleary** [comment]
For some reason, that input has `direction: rtl` set. Presumably that was done to get the numbers to appear on the right-hand edge... but was never tested with > 1 digit.

https://github.com/node-red/node-red-nodes/blob/9bae313b722147b00480ce2e26ed0aab357b836b/io/snmp/snmp.html#L68

**Comment by dceejay** [comment]
Fixed in v1.0.6

**Comment by juggledad** [comment]
Wow, that took less time to fix than it took me to write up (grin)
