### ISSUE TITLE
node-red timeswitch  time format, and crazy time format

### ISSUE THREAD

**Issue by AndKe** [node-red/node-red-nodes#971]
![Screenshot from 2023-01-17 22-05-43](https://user-images.githubusercontent.com/1468842/213013973-a974842f-fcdf-45df-85e7-80ea5e636b42.png)

### Which node are you reporting an issue on?
node-red timeswitch 

### What are the steps to reproduce?
install - in Europe, or any other place with normal 24h time.

### What happens?
the reported set time is incorrect, and in am/pm mess-units.

### What do you expect to happen?
Expected to see set time - in a format according to system settings.

### Please tell us about your environment:

Being on UTC+1 now, it may be that the status text is displaying UTC. - so this *may* be a visual bug only, but does not look reliable.

- [ ] Node-RED version:3.0.2
- [ ] node.js version:  don't know
- [ ] npm version: ?
- [ ] Platform/OS: Rpi / Lunux
- [ ] Browser: n/a

**Comment by dceejay** [comment]
Indeed it is showing it in UTC - we can certainly change it to 24 hr clock and to the timezone the user selects. Not sure if this is better than UTC but  🤷

**Comment by dceejay** [comment]
Fixed and published as version 1.0.0
