### ISSUE TITLE
Irrelevant credential errors in node-red-node-email

### ISSUE THREAD

**Issue by erunaheru** [node-red/node-red-nodes#989]
### Which node are you reporting an issue on?
Outbound email node

### What are the steps to reproduce?
Create an email node that does not have a username or password

### What happens?
After each deploy, debug log fills with "No e-mail userid set" and "No e-mail password set" errors, one of each for each node. The nodes otherwise function properly.

### What do you expect to happen?
No error messages.

### Please tell us about your environment:

- Node-RED version: 3.0.2
- node.js version: 16.16.0
- npm version: 8.11.0
- Platform/OS: Official Docker on Ubuntu 20.04 host
- Browser: Brave

**Comment by SynoUser-NL** [comment]
Hi,
Can confirm this, with node.js version 18.12. 
Pleas consider adding Authentication: none as an option.
Thank you.
DenW

**Comment by dceejay** [comment]
So this is only a problem if you have an email server that doesn't need authentication ? Seems odd to ever allow that ?

**Comment by SynoUser-NL** [comment]
Well.. i've set up an internal email relay that only responds to emails sent from adresses in a defined domain, only from within the local network, and then sends\forwards the email to an external (authenticated) email server.
This is working perfectly for a great number of devices\applications, none of which have any problem sending mail to a network-internal unauthenticated email server\relay. And this has been working perfectly for Node-RED flow mails as well..

While I do agree that an email server should normally be configured with authentication, there are some (a few) use cases where this is simply not necessary. And as far as I know it is not a requirement (as defined in RfC's, but correct me if i'm wrong on that..).

So I'm kindly requesting to please enable this option, you'll have my eternal undying gratitude.. 👍 🥇 :)

Thank you! DenW

**Comment by erunaheru** [comment]
I have a similar set up, the mail server accepts email only from the internal Docker network but otherwise does not have any authentication.

**Comment by excessnet** [comment]
same here, anti-spam servers use no authentications for internal relay. Was working fine before this update.

**Comment by dceejay** [comment]
OK - will add a NONE option

**Comment by excessnet** [comment]
> OK - will add a NONE option

Thanks a lot !

**Comment by SynoUser-NL** [comment]
Thank you! As said before: extremely appreciated!

DenW

**Comment by erunaheru** [comment]
Works great, thank you!
