### ISSUE TITLE
node-red suncalc - issue when daytime hours traverse midnight UTC

### ISSUE THREAD

**Issue by pmscientist** [node-red/node-red-nodes#99]
The node-red-node-suncalc module doesn't handle daytime hours that traverse midnight UTC correctly. For example, if daylight start time is 13:00 UTC and end time is 02:00 UTC (US/Mountain time), and the suncalc is given a current time of  23:00 UTC (16:00 local), the module reports that it's night.

I've modified my local version of 79-suncalc.js to use millis since 1/1/1970 instead of minutes. If this method of calculating e1 and e2 is of interest, I'm happy to submit a pull request and patch.

var nowMillis = Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),now.getUTCHours(),now.getUTCMinutes());
var startMillis = Date.UTC(times[node.start].getUTCFullYear(),times[node.start].getUTCMonth(),times[node.start].getUTCDate(),times[node.start].getUTCHours(),times[node.start].getUTCMinutes());
var endMillis = Date.UTC(times[node.end].getUTCFullYear(),times[node.end].getUTCMonth(),times[node.end].getUTCDate(),times[node.end].getUTCHours(),times[node.end].getUTCMinutes());
var e1 = nowMillis - startMillis;
var e2 = nowMillis - endMillis;

**Comment by dceejay** [comment]
Hi thanks for spotting this. To raise a PR we would need a signed CLA (as per the contribution guidelines)... but I'm happy to apply this fix manually if you don't mind. ?

**Comment by dceejay** [comment]
Applied by hand - Closed by Commit 7307891aeeb9fbcaa62399f00efe1d16cf25b90c

**Comment by pmscientist** [comment]
Sorry for the delayed response. I agree, the manual fix was the best choice. No sense in dealing with the CLA for this. Thank you for fixing it.
