### ISSUE TITLE
How is 1.3.6.1.2.1.1.3... "Error: argument is not a valid OID string"

### ISSUE THREAD

**Issue by Jibun-no-Kage** [node-red/node-red-nodes#993]
How is 1.3.6.1.2.1.1.3... "Error: argument is not a valid OID string"  I am using the SNMP (get) node in Node Red, and I get the error?  Sorry but it is not making any sense.  I enter the OID in the OID box of the node.

**Comment by dceejay** [comment]
for general how-to questions we prefer people to use the only discourse forum as then the question will be seen by the widest possible audience including many who may use the node day to day.

**Comment by Jibun-no-Kage** [comment]
Not a how to question.   The OID is valid, but it is rejected.... but if .0 appended then and only then accepted?  That is NOT how the various CLI SNMP tools accept such and OID.  So is it a code design issue?  Appending .0 should not be required.  If the NR node is wrapper, then the wrapped component could be at issue.  But if your code is doing something to break a valid OID, that should be discussed here, IMHO.

**Comment by Jibun-no-Kage** [comment]
You details are a bit help.  The interesting thing is... net-snmp, i.e. snmpwalk does in fact accept the above OID as valid.  I have tested it explicitly.  For example...

\#  snmpwalk -v 1 -c DD 192.168.1.252 1.3.6.1.2.1.1.3
iso.3.6.1.2.1.1.3.0 = Timeticks: (404901445) 46 days, 20:43:34.45

Whereas...

\#  snmpwalk -v 1 -c DD 192.168.1.252 1.3.6.1.2.1.1.3.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (404905056) 46 days, 20:44:10.56

So why the net-snmp library fails to accept the first example is a mystery.  The value returned is not a tree, or group object returned, as some SNMP get query OIDs return.  In fact using the subtree node, the .0 is not required.  Per the way I read the SNMP standard, .0 is only required if you want the explicit first element of a dataset returned, say an array of items turned, such as....

\# snmpwalk -v 1 -c DD 192.168.1.250 1.3.6.1.2.1.2.2.1.6
iso.3.6.1.2.1.2.2.1.6.1 = ""
iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 00 01 36 1F E4 59
iso.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 00 01 36 1F E4 5B
iso.3.6.1.2.1.2.2.1.6.4 = Hex-STRING: 00 01 36 1F E4 5F
iso.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 00 01 36 1F E4 59
iso.3.6.1.2.1.2.2.1.6.6 = Hex-STRING: 00 01 36 1F E4 69
iso.3.6.1.2.1.2.2.1.6.7 = Hex-STRING: 00 01 36 1F E4 59
iso.3.6.1.2.1.2.2.1.6.8 = ""
iso.3.6.1.2.1.2.2.1.6.9 = ""

Or...

\# snmpwalk -v 1 -c DD 192.168.1.250 1.3.6.1.2.1.2.2.1.6.0
[No Result]
\# snmpwalk -v 1 -c DD 192.168.1.250 1.3.6.1.2.1.2.2.1.6.1
iso.3.6.1.2.1.2.2.1.6.1 = ""
\# snmpwalk -v 1 -c DD 192.168.1.250 1.3.6.1.2.1.2.2.1.6.2
iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 00 01 36 1F E4 59

From the CLI of net-snmp, snmpwalk and snmpget are identical for the above results.  Really interesting inconsistent handling of OIDs that are not index specific,, i.e. .0,, .1, etc.

**Comment by Jibun-no-Kage** [comment]
Closing since the real issue appears to be with core code, not the NR node wrapper.
